### ISSUE TITLE
Unable to resolve a dependency

### ISSUE THREAD

**Issue by jsumners** [pnpm/pnpm#1024]
### Code to reproduce the issue:

1. Clone https://github.com/jsumners/nixconfig
2. `pnpm install`
3. `node test/envLoader.test.js`

### Expected behavior:

Test suite succeeds.

### Actual behavior:

```
Error: Cannot find module 'own-or'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/private/tmp/01/nixconfig/node_modules/.registry.npmjs.org/own-or-env/1.0.0/node_modules/own-or-env/own-or-env.js:1:13)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
```

### Additional information:

Looking in `~/.pnpm-store/2/registry.npmjs.org` I can see the `own-or` module as installed.

 - `node -v` prints: v8.9.4
 - Windows, OS X, or Linux?: macOS

**Comment by zkochan** [comment]
It is a bug in `own-or-env`. It uses `own-or` but it has not `own-or` in its dependencies
https://github.com/isaacs/own-or-env/blob/master/package.json

**Comment by jsumners** [comment]
https://github.com/isaacs/own-or-env/pull/2
