### ISSUE TITLE
can't install haul via pnpm (Cannot find module 'babel-polyfill')

### ISSUE THREAD

**Issue by tachtevrenidis** [pnpm/pnpm#1165]
I am cross-posting this as I don't know if this is a haul issue or a pnpm issue.

https://github.com/callstack/haul/issues/432

### pnpm version: 
1.43.1

### Code to reproduce the issue:

* mkdir test-dir
* pnpm install haul --save-dev
* node node_modules/haul/bin/cli.js

pnpm install completes successfully but the haul bundler CLI fails when invoked.

### Expected behavior:

Executing the same repro steps but using 'npm' instead of 'pnpm' works as expected.

### Actual behavior:

```
node node_modules/haul/bin/cli.js 
module.js:538
    throw err;
    ^

Error: Cannot find module 'babel-polyfill'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/user/Development/pnpm-test/node_modules/.registry.npmjs.org/haul/1.0.0-rc.0/node_modules/haul/src/cli.js:10:1)
    at Module._compile (module.js:635:30)
    at Module._extensions..js (module.js:646:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/user/Development/pnpm-test/node_modules/.registry.npmjs.org/babel-register/6.26.0/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
```

### Additional information:

 - node 8.9.3
 - OS X

**Comment by zkochan** [comment]
Weird because it fails on missing `babel-polyfill` but this package is not in subdependencies. So it would fail with flat node_modules as well. Are you sure that haul is the only dependency in your project?

When I added babel-polyfill, another error was thrown on `pnpx haul`: 

```
/home/zkochan/src/test/test-dir/node_modules/.registry.npmjs.org/haul/1.0.0-rc.0/node_modules/haul/src/cliEntry.js:7
import type { Command } from './types';
^^^^^^

SyntaxError: Unexpected token import
    at new Script (vm.js:51:7)
    at createScript (vm.js:136:10)
    at Object.runInThisContext (vm.js:197:10)
    at Module._compile (module.js:613:28)
    at Module._extensions..js (module.js:660:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/zkochan/src/test/test-dir/node_modules/.registry.npmjs.org/babel-register/6.26.0/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)

```

**Comment by tachtevrenidis** [comment]
yeap tried that. Since this error is not thrown when installing with npm, I figured it must be something in how it is installed via pnpm.

**Comment by tachtevrenidis** [comment]
also my repro steps start out with an empty folder (not even a package.json file in there). So there can't be any other deps?

**Comment by zkochan** [comment]
@tachtevrenidis seems like it has been fixed by @chaseholland in https://github.com/callstack/haul/pull/443
