### ISSUE TITLE
Doesn't support webpack-blocks 

### ISSUE THREAD

**Issue by zaaack** [pnpm/pnpm#1191]
webpack-blocks requires installing dependences under `<project root>/node_modules/@webpack_blocks/typescript`, but pnpm would install it to `<project root>/node_modules/webpack_blocks/node_modules/@webpack_blocks/typescript`

```js

$ pnpm start

> counter-example@1.0.0 start /Users/z/Projects/Node/Hydux/hydux-pixi/examples/compare
> cross-env NODE_ENV=development webpack-dev-server --progress --config webpack.config.js

Error: Cannot find module '@webpack-blocks/typescript'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/z/Projects/Node/Hydux/hydux-pixi/examples/compare/webpack.config.js:7:20)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at requireConfig (/Users/z/Projects/Node/Hydux/hydux-pixi/examples/compare/node_modules/.registry.npm.taobao.org/webpack/3.12.0/node_modules/webpack/bin/convert-argv.js:97:18)
    at /Users/z/Projects/Node/Hydux/hydux-pixi/examples/compare/node_modules/.registry.npm.taobao.org/webpack/3.12.0/node_modules/webpack/bin/convert-argv.js:104:17
    at Array.forEach (native)
    at module.exports (/Users/z/Projects/Node/Hydux/hydux-pixi/examples/compare/node_modules/.registry.npm.taobao.org/webpack/3.12.0/node_modules/webpack/bin/convert-argv.js:102:15)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! counter-example@1.0.0 start: `cross-env NODE_ENV=development webpack-dev-server --progress --config webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the counter-example@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/z/.npm/_logs/2018-05-28T02_31_02_877Z-debug.log
```

**Comment by zkochan** [comment]
@zaaack if this is still an issue with the latest pnpm, could you please create a sample repository and steps to reproduce the issue? I tried to reproduce it with `webpack-blocks` and `@webpack-blocks/typescript` but it did not fail

**Comment by zaaack** [comment]
I tried with latest webpack-blocks，looks it's fixed by webpack，perhaps.


But then I hit new issue，type error from typescript because duplicate packages in node_modules/.registry.npm.taobao.org/xxxx

**Comment by zkochan** [comment]
If it still doesn't work, use [node-linker=hoisted](https://pnpm.io/npmrc#node-linker)
