### ISSUE TITLE
pnpm fails to install hoodie npm module

### ISSUE THREAD

**Issue by indiescripter** [pnpm/pnpm#1249]
### Code to reproduce the issue:

```
mkdir hoodie-app
cd hoodie-app
pnpm init -y
pnpm install --save hoodie
```

### Expected behavior:
I came across the [hoodie open source project](http://hood.ie) that I was interested in trying out and thought:

> ok, instead of using [their quickstart instructions verbatim with npm](http://docs.hood.ie/en/latest/guides/quickstart.html), I'll give it a spin with `pnpm`.

Unfortunately the experience was unsatisfying with the attempt to install the `hoodie` dependency resulting in an error.

Repeating exactly the same steps above with `npm` instead of `pnpm` works as expected.

### Actual behavior:
Per console log copied underneath:

```
Packages: +672
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Resolving: total 672, reused 672, downloaded 0, done

registry.npmjs.org/hoodie/28.2.6         | postinstall$ node ./bin/setup.js
registry.npmjs.org/hoodie/28.2.6         | postinstall:     at tryModuleLoad (module.js:505:12)
registry.npmjs.org/hoodie/28.2.6         | postinstall:     at Function.Module._load (module.js:497:3)
registry.npmjs.org/hoodie/28.2.6         | postinstall: Exited with 1
 ERROR  hoodie@28.2.6 postinstall: `node ./bin/setup.js`
Exit status 1
at Error: hoodie                                                                                     
at <anonymous>    …node_modules/npm-lifecycle/index.js:304  var er = new Error('Exit status ' + code)
at emitTwo        events.js:126                                                                      
at emit           events.js:214                                                                      
at <anonymous>    …e_modules/npm-lifecycle/lib/spawn.js:55  cooked.emit('close', code, signal)       
at emitTwo        events.js:126                                                                      
at emit           events.js:214                                                                      
at maybeClose     internal/child_process.js:925                                                      
at on             internal/child_process.js:346                                                      
at emitOne        events.js:116                                                                      
at emit           events.js:211
```

### Additional information:

 - `node -v` prints: v8.11.3
 - Windows, OS X, or Linux?: Linux

**Comment by zkochan** [comment]
The issue is here:

https://github.com/hoodiehq/hoodie/blob/10a32ccea297dfb42fc8043206b3d3e0f25cba7b/bin/setup.js#L11

the real location of hoodie, when installed with pnpm, is not in `node_modules/hoodie` but in `node_modules/.registry.npmjs.org/hoodie/28.2.6/node_modules/hoodie`.

([here's](https://medium.com/pnpm/flat-node-modules-is-not-the-only-way-d2e40f7296a3) some more details about this node_modules structure)

It is easy to fix this issue in hoodie. They need to use `process.env.INIT_CWD` instead of `path.resolve('..', '..') `

**Comment by indiescripter** [comment]
Thanks @zkochan  for looking into this so quickly.

I understand why "why pnpm’s strictness is a good thing" and, with your explanation, why this is happening and how it's an easy fix for the `hoodie` developers.

Just by way of "package manager user experience feedback" though, which I hope you will take as constructive, I would like to offer these thoughts:

A first time user who finds a module that installs with `npm` and subsequently tries to give `pnpm` a go only to find that the module does not install may possibly conclude that `pnpm` is flakey and simply move on without looking into the issue any further, let alone go to the trouble of submitting an issue like I did.

I hope you appreciate that *works with npm* but *does not work with pnpm* is not exactly ideal given the ubiquity of npm as the defacto package manager for Node.js. 

Unfortunately I cannot see an easy way out of this dilemma short of pnpm becoming so popular that package developers test installation of their package with both `pnpm` and `npm` (and `yarn` for that matter). Nevertheless, I'm happy to open an issue over on [hoodie](https://github.com/hoodiehq/hoodie) to try and have this rectified on their end.

Done, the hoodie pnpm issue is [here](https://github.com/hoodiehq/hoodie/issues/858).
