### ISSUE TITLE
Not working with electron-webpack

### ISSUE THREAD

**Issue by deadcoder0904** [pnpm/pnpm#1257]
I tried [electron-webpack](https://github.com/electron-userland/electron-webpack) installation with `pnpm` by both normal install & the `shamefully-flatten` way but none of it is working. Its some weird error with `webpack-dev-server`.

```js
> electron-webpack-quick-start@0.0.0 dev /Desktop/end-of-life
> electron-webpack dev

{ Error: spawn /Desktop/end-of-life/node_modules/.bin/webpack-dev-server ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
From previous event:
    at /Desktop/end-of-life/node_modules/.registry.npmjs.org/graceful-fs/4.1.11/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:185:5)
From previous event:
    at startRenderer (/Desktop/end-of-life/node_modules/.registry.npmjs.org/electron-webpack/2.1.2/node_modules/electron-webpack/out/dev/WebpackDevServerManager.js:149:17)
    at /Desktop/end-of-life/node_modules/.registry.npmjs.org/electron-webpack/2.1.2/node_modules/electron-webpack/src/dev/dev-runner.ts:43:7
    at Generator.next (<anonymous>)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at DevRunner.start (/Desktop/end-of-life/node_modules/.registry.npmjs.org/electron-webpack/2.1.2/node_modules/electron-webpack/src/dev/dev-runner.ts:32:14)
    at /Desktop/end-of-life/node_modules/.registry.npmjs.org/electron-webpack/2.1.2/node_modules/electron-webpack/src/dev/dev-runner.ts:142:19
    at Generator.next (<anonymous>)
From previous event:
    at main (/Desktop/end-of-life/node_modules/.registry.npmjs.org/electron-webpack/2.1.2/node_modules/electron-webpack/out/dev/dev-runner.js:132:18)
    at Object.<anonymous> (/Desktop/end-of-life/node_modules/.registry.npmjs.org/electron-webpack/2.1.2/node_modules/electron-webpack/src/dev/dev-runner.ts:145:1)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at runInDevMode (/Desktop/end-of-life/node_modules/.registry.npmjs.org/electron-webpack/2.1.2/node_modules/electron-webpack/out/cli.js:46:3)
    at Object._yargs.default.command.command.command.command.command.argv [as handler] (/Desktop/end-of-life/node_modules/.registry.npmjs.org/electron-webpack/2.1.2/node_modules/electron-webpack/out/cli.js:22:440)
    at Object.runCommand (/Desktop/end-of-life/node_modules/.registry.npmjs.org/yargs/11.1.0/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/Desktop/end-of-life/node_modules/.registry.npmjs.org/yargs/11.1.0/node_modules/yargs/yargs.js:1046:30)
    at Object.get [as argv] (/Desktop/end-of-life/node_modules/.registry.npmjs.org/yargs/11.1.0/node_modules/yargs/yargs.js:989:21)
    at Object.<anonymous> (/Desktop/end-of-life/node_modules/.registry.npmjs.org/electron-webpack/2.1.2/node_modules/electron-webpack/out/cli.js:22:455)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall:
   'spawn /Desktop/end-of-life/node_modules/.bin/webpack-dev-server',
  path:
   '/Desktop/end-of-life/node_modules/.bin/webpack-dev-server',
  spawnargs:
   [ '--color',
     '--env.autoClean=false',
     '--config',
     '/Desktop/end-of-life/node_modules/.registry.npmjs.org/electron-webpack/2.1.2/node_modules/electron-webpack/webpack.renderer.config.js' ] }
```

**Comment by zkochan** [comment]
issue number 1: something tries to run webpack-dev-server in `node_modules/.bin/webpack-dev-server` but webpack-dev-server is not a direct dependency of the package, so it cannot be linked in `node_modules/.bin`. @etamponi this seems like a bug in `--shamefully-flatten`. bins shouls also be flattened.

after installing webpack-dev-server as a dev dependency, it failed on another issue: ` Error: Cannot find module '@babel/preset-env'`

Seems like another flat node_modules issue.

But if you install webpack-dev-server as a dev dependency and reinstall dependencies with `--shamefull-flatten` then it works

**Comment by etamponi** [comment]
`--shamefully-flatten` already flattens bins.

Perhaps this has to do with `devDependencies`. Can you give me the exact steps to reproduce the issue?

**Comment by zkochan** [comment]
steps:

```
mkdir my-project && cd my-project
curl -fsSL https://github.com/electron-userland/electron-webpack-quick-start/archive/master.tar.gz | tar -xz --strip-components 1
pnpm i
pnpm run dev
```

**Comment by etamponi** [comment]
Ok, I can reproduce. It's strange that the bin is not added. I think I even have a test for this. I'll try to look into it!

**Comment by etamponi** [comment]
Interesting: running `pnpm install another-package --shamefully-flatten` added all the missing bins!

**Comment by etamponi** [comment]
Ok, this is a regression.

If you run

```
pnpm install --shamefully-flatten
```

twice, the bins get installed correctly. But if you run it just one time, they don't get installed.

**Comment by zkochan** [comment]
The fix to the shamefully-flatten issue published in v2.10.5

**Comment by saltyshiomix** [comment]
Since `pnpm@4`, `--shamefully-flatten` option is renamed to `--shamefully-hoist`:

```zsh
$ pnpm install --shamefully-hoist
```

And this should be worked 👍

**Comment by zkochan** [comment]
If nothing works, use [node-linker=hoisted](https://pnpm.io/npmrc#node-linker)
