### ISSUE TITLE
ERROR: Cannot find module 'request' when using package azure-event-hubs

### ISSUE THREAD

**Issue by vdurante** [pnpm/pnpm#1258]
I am attempting to use pnpm (2.9.0) for the first time in a project that uses the package `azure-event-hubs`.

If I install packages using `pnpm i --shamefully-flatten --force` it works perfectly.

```
module.js:549
    throw err;
    ^

Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Repos\NMind\Transporting\import-from-datastore\node_modules\.registry.npmjs.org\ms-rest-azure\2.5.7\node_modules\ms-rest-azure\lib\credentials\msiVmTokenCredentials.js:12:17)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

**Comment by zkochan** [comment]
It is a bug in `ms-rest-azure`. It uses request

https://github.com/Azure/azure-sdk-for-node/blob/d82264c00bf00447547ba452495a56bda3400ff9/runtime/ms-rest-azure/lib/credentials/msiVmTokenCredentials.js#L12

But doesn't have it in the `package.json` as a dependency

https://github.com/Azure/azure-sdk-for-node/blob/d82264c00bf00447547ba452495a56bda3400ff9/runtime/ms-rest-azure/package.json

**Comment by vdurante** [comment]
@zkochan Thank you for the info. I will let them know
