### ISSUE TITLE
pnpm doesn't work with create-react-app/react-scripts-ts

### ISSUE THREAD

**Issue by flaviut** [pnpm/pnpm#1261]
### pnpm version:
2.10.4

### Code to reproduce the issue:

```console
$ pnpm install create-react-app
$ node ./node_modules/create-react-app/createReactApp.js foo --scripts-version=react-scripts-ts
$ cd foo
$ rm -rf node_modules
$ pnpm install
$ npm start
```

### Expected behavior:

With yarn
```
Compiled successfully!

You can now view foo in the browser.

  Local:            http://localhost:3000/
  On Your Network:  http://10.7.1.146:3000/

Note that the development build is not optimized.
To create a production build, use yarn build.
```

### Actual behavior:
```
> foo@0.1.0 start /home/user/dev/foo
> react-scripts-ts start

internal/modules/cjs/loader.js:596
    throw err;
    ^

Error: Cannot find module 'enhanced-resolve/lib/createInnerCallback'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/user/dev/foo/node_modules/.registry.npmjs.org/tsconfig-paths-webpack-plugin/2.0.0/node_modules/tsconfig-paths-webpack-plugin/lib/plugin.js:8:29)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/user/dev/foo/node_modules/.registry.npmjs.org/tsconfig-paths-webpack-plugin/2.0.0/node_modules/tsconfig-paths-webpack-plugin/index.js:1:76)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! foo@0.1.0 start: `react-scripts-ts start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the foo@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/etc/.npm/_logs/2018-07-06T01_44_17_848Z-debug.log
```

Log file: https://gist.github.com/flaviut/ed389c2bb74d77817bb62223d93905ad

### Additional information:

 - `node -v` prints: `v10.5.0`
 - Windows, OS X, or Linux?: `Linux andromeda 4.17.3-1-ARCH #1 SMP PREEMPT Tue Jun 26 04:42:36 UTC 2018 x86_64 GNU/Linux`

**Comment by zkochan** [comment]
Try remove node_modules and run `pnpm install --shamefully-flatten`

**Comment by flaviut** [comment]
Yup, that works great! I read a little more around the internet, and went ahead and followed this procedure:

1. `pnpm install enhanced-resolve` (with `-D` depending on the package)
2. examine the next error and see which package is missing
3. goto 1 but use the different package

After this, I no longer needed `--shamefully-flatten`

**Comment by cesasol** [comment]
I don't think this could by a resolved issue, but a really cleaver way to work arround the big issue of resolving node modules.

So i created a script and then uploaded as a gist to share. Maybe this could go to the recipes page on the docs.
https://gist.github.com/cesasol/d57731cd767c47eb414a6b0a94714269

**Comment by cie** [comment]
> we can add it as one of the solutions [here](https://pnpm.js.org/docs/en/faq.html#pnpm-does-not-work-with-your-project-here)

Yes, @zkochan please do add it there, this has just helped me. I'm using pnpm with rush.js, so I cannot --shamefully-flatten.

**Comment by baeharam** [comment]
@zkochan Page is broken.

**Comment by zkochan** [comment]
fixed the link
