### ISSUE TITLE
pnpm start fails for angular app

### ISSUE THREAD

**Issue by snowe2010** [pnpm/pnpm#1262]
### pnpm version:
2.9.0

### Code to reproduce the issue:

Not actually a frontend dev, just sick of npm as a backend dev. Not sure what the issue is, but it appears that a module isn't linked properly. 

### Expected behavior:

for the app to start. 

### Actual behavior:

```
~/Documents/dev/code/app develop* 1m 30s
❯ npm start //happens with pnpm start as well

> app@0.0.0 start /Users/tylerthrailkill/Documents/dev/code/app
> ng serve --port=9004 --base-href=/ --environment=local

** NG Live Development Server is listening on localhost:9004, open your browser on http://localhost:9004/ **
Date: 2018-07-06T19:44:50.243Z
Hash: cb805befaa298f025da0
Time: 13993ms
chunk {inline} inline.bundle.js (inline) 3.85 kB [entry] [rendered]
chunk {main} main.bundle.js (main) 3.6 kB [initial] [rendered]
chunk {polyfills} polyfills.bundle.js (polyfills) 289 bytes [initial] [rendered]
chunk {scripts} scripts.bundle.js (scripts) 1.14 MB [initial] [rendered]
chunk {styles} styles.bundle.js (styles) 679 bytes [initial] [rendered]
chunk {vendor} vendor.bundle.js (vendor) 862 kB [initial] [rendered]

ERROR in multi ./node_modules/.registry.npmjs.org/webpack-dev-server/2.11.2/webpack@3.11.0/node_modules/webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts
Module not found: Error: Can't resolve '@ngtools/webpack' in '/Users/tylerthrailkill/Documents/dev/code/app'
ERROR in multi ./src/polyfills.ts
Module not found: Error: Can't resolve '@ngtools/webpack' in '/Users/tylerthrailkill/Documents/dev/code/app'
ERROR in multi ./src/assets/scss/styles.scss ./node_modules/primeng/resources/primeng.min.css ./node_modules/quill/dist/quill.snow.css
Module not found: Error: Can't resolve 'raw-loader' in '/Users/tylerthrailkill/Documents/dev/code/app'
ERROR in multi ./src/assets/scss/styles.scss ./node_modules/primeng/resources/primeng.min.css ./node_modules/quill/dist/quill.snow.css
Module not found: Error: Can't resolve 'raw-loader' in '/Users/tylerthrailkill/Documents/dev/code/app'
ERROR in multi ./src/assets/scss/styles.scss ./node_modules/primeng/resources/primeng.min.css ./node_modules/quill/dist/quill.snow.css
Module not found: Error: Can't resolve 'style-loader' in '/Users/tylerthrailkill/Documents/dev/code/app'
ERROR in node_modules/@types/uuid/interfaces.d.ts(1,23): error TS2688: Cannot find type definition file for 'node'.
node_modules/@types/uuid/interfaces.d.ts(4,48): error TS2304: Cannot find name 'Buffer'.
node_modules/apollo-angular-link-http/HttpLink.d.ts(1,23): error TS2688: Cannot find type definition file for 'zen-observable'.
node_modules/apollo-angular-link-http/HttpLink.d.ts(3,85): error TS2307: Cannot find module 'apollo-link'.
node_modules/apollo-angular/Apollo.d.ts(2,29): error TS2307: Cannot find module 'apollo-link'.
node_modules/apollo-cache-inmemory/lib/fragmentMatcher.d.ts(1,25): error TS2307: Cannot find module 'apollo-utilities'.
node_modules/apollo-cache-inmemory/lib/inMemoryCache.d.ts(2,60): error TS2307: Cannot find module 'apollo-cache'.
node_modules/apollo-cache-inmemory/lib/readFromStore.d.ts(1,25): error TS2307: Cannot find module 'apollo-utilities'.
node_modules/apollo-cache-inmemory/lib/readFromStore.d.ts(2,23): error TS2307: Cannot find module 'apollo-cache'.
node_modules/apollo-cache-inmemory/lib/types.d.ts(2,33): error TS2307: Cannot find module 'graphql-anywhere'.
node_modules/apollo-cache-inmemory/lib/types.d.ts(3,29): error TS2307: Cannot find module 'apollo-cache'.
node_modules/apollo-cache-inmemory/lib/types.d.ts(4,37): error TS2307: Cannot find module 'apollo-utilities'.
node_modules/apollo-cache-inmemory/lib/writeToStore.d.ts(2,33): error TS2307: Cannot find module 'graphql-anywhere'.
node_modules/apollo-cache-inmemory/lib/writeToStore.d.ts(3,29): error TS2307: Cannot find module 'apollo-utilities'.
node_modules/apollo-client/ApolloClient.d.ts(1,57): error TS2307: Cannot find module 'apollo-link'.
node_modules/apollo-client/ApolloClient.d.ts(3,40): error TS2307: Cannot find module 'apollo-cache'.
node_modules/apollo-client/core/QueryManager.d.ts(1,41): error TS2307: Cannot find module 'apollo-link'.
node_modules/apollo-client/core/QueryManager.d.ts(3,23): error TS2307: Cannot find module 'apollo-cache'.
node_modules/apollo-client/core/types.d.ts(4,29): error TS2307: Cannot find module 'apollo-link'.
node_modules/apollo-client/core/watchQueryOptions.d.ts(2,29): error TS2307: Cannot find module 'apollo-link'.
node_modules/apollo-client/core/watchQueryOptions.d.ts(3,27): error TS2307: Cannot find module 'apollo-cache'.
node_modules/apollo-client/data/store.d.ts(2,40): error TS2307: Cannot find module 'apollo-cache'.
node_modules/apollo-client/util/Observable.d.ts(1,23): error TS2688: Cannot find type definition file for 'zen-observable'.
node_modules/apollo-client/util/Observable.d.ts(2,46): error TS2307: Cannot find module 'apollo-link'.
node_modules/apollo-client/util/Observable.d.ts(3,36): error TS2503: Cannot find namespace 'ZenObservable'.
node_modules/apollo-client/util/Observable.d.ts(4,35): error TS2503: Cannot find namespace 'ZenObservable'.
node_modules/apollo-link-error/lib/index.d.ts(1,23): error TS2688: Cannot find type definition file for 'zen-observable'.
node_modules/apollo-link-error/lib/index.d.ts(2,51): error TS2307: Cannot find module 'apollo-link'.
src/app/core/modules/graphql/graphql.module.ts(8,28): error TS2307: Cannot find module 'apollo-link'.

ERROR in   Error: Child compilation failed:
  Entry module not found: Error: Can't resolve 'raw-loader' in '/Users/tylerthrailkill/Documents/dev/code/app':
  Error: Can't resolve 'raw-loader' in '/Users/tylerthrailkill/Documents/dev/code/app'

  - compiler.js:76
    [app]/[webpack@3.11.0]/[html-webpack-plugin]/lib/compiler.js:76:16

  - Compiler.js:300 compile
    [app]/[webpack@3.11.0]/[webpack]/lib/Compiler.js:300:11

  - Compiler.js:510 applyPluginsAsync.err
    [app]/[webpack@3.11.0]/[webpack]/lib/Compiler.js:510:14

  - Tapable.js:202 next
    [app]/[0.2.8]/[tapable]/lib/Tapable.js:202:11

  - CachePlugin.js:78 Compiler.<anonymous>
    [app]/[webpack@3.11.0]/[webpack]/lib/CachePlugin.js:78:5

  - Tapable.js:206 Compiler.applyPluginsAsyncSeries
    [app]/[0.2.8]/[tapable]/lib/Tapable.js:206:13

  - Compiler.js:507 compilation.seal.err
    [app]/[webpack@3.11.0]/[webpack]/lib/Compiler.js:507:11

  - Tapable.js:195 Compilation.applyPluginsAsyncSeries
    [app]/[0.2.8]/[tapable]/lib/Tapable.js:195:46

  - Compilation.js:677 applyPluginsAsync.err
    [app]/[webpack@3.11.0]/[webpack]/lib/Compilation.js:677:19

  - Tapable.js:195 Compilation.applyPluginsAsyncSeries
    [app]/[0.2.8]/[tapable]/lib/Tapable.js:195:46

  - Compilation.js:668 applyPluginsAsync.err
    [app]/[webpack@3.11.0]/[webpack]/lib/Compilation.js:668:11

  - Tapable.js:195 Compilation.applyPluginsAsyncSeries
    [app]/[0.2.8]/[tapable]/lib/Tapable.js:195:46

  - Compilation.js:663 applyPluginsAsync.err
    [app]/[webpack@3.11.0]/[webpack]/lib/Compilation.js:663:10

  - Tapable.js:195 Compilation.applyPluginsAsyncSeries
    [app]/[0.2.8]/[tapable]/lib/Tapable.js:195:46

  - Compilation.js:659 applyPluginsAsyncSeries
    [app]/[webpack@3.11.0]/[webpack]/lib/Compilation.js:659:9

  - Tapable.js:195 Compilation.applyPluginsAsyncSeries
    [app]/[0.2.8]/[tapable]/lib/Tapable.js:195:46
```
### Additional information:

 - `node -v` prints:
```bash
❯ node -v
v9.6.1
```
 - Windows, OS X, or Linux?:
`macOS Sierra 10.12.6 (16G1212)`

**Comment by zkochan** [comment]
Try to remove node_modules and run pnpm install --shamefully-flatten

**Comment by snowe2010** [comment]
still failing :/

```

❯ npm start

> project@0.0.0 start /Users/tylerthrailkill/Documents/dev/code/frontend/project
> ng serve --port=9004 --base-href=/ --environment=local

** NG Live Development Server is listening on localhost:9004, open your browser on http://localhost:9004/ **
Date: 2018-07-09T15:55:31.474Z
Hash: 58f09da3b62498ff51a3
Time: 19413ms
chunk {inline} inline.bundle.js (inline) 3.85 kB [entry] [rendered]
chunk {main} main.bundle.js (main) 3.88 kB [initial] [rendered]
chunk {polyfills} polyfills.bundle.js (polyfills) 577 bytes [initial] [rendered]
chunk {scripts} scripts.bundle.js (scripts) 1.14 MB [initial] [rendered]
chunk {styles} styles.bundle.js (styles) 2 MB [initial] [rendered]
chunk {vendor} vendor.bundle.js (vendor) 862 kB [initial] [rendered]

ERROR in node_modules/@types/graphql/subscription/subscribe.d.ts(17,12): error TS2304: Cannot find name 'AsyncIterator'.
node_modules/@types/graphql/subscription/subscribe.d.ts(29,12): error TS2304: Cannot find name 'AsyncIterable'.
node_modules/apollo-cache-inmemory/lib/inMemoryCache.d.ts(25,35): error TS2314: Generic type 'Query<TVariables>' requires 1 type argument(s).
node_modules/apollo-cache-inmemory/lib/inMemoryCache.d.ts(26,41): error TS2314: Generic type 'Fragment<TVariables>' requires 1 type argument(s).
node_modules/apollo-cache-inmemory/lib/inMemoryCache.d.ts(27,25): error TS2314: Generic type 'WriteQueryOptions<TData, TVariables>' requires 2 type argument(s).
node_modules/apollo-cache-inmemory/lib/inMemoryCache.d.ts(28,28): error TS2314: Generic type 'WriteFragmentOptions<TData, TVariables>' requires 2 type argument(s).
node_modules/apollo-client/ApolloClient.d.ts(24,22): error TS2420: Class 'ApolloClient<TCacheShape>' incorrectly implements interface 'DataProxy'.
  Property 'writeData' is missing in type 'ApolloClient<TCacheShape>'.
node_modules/apollo-client/ApolloClient.d.ts(41,27): error TS2314: Generic type 'Query<TVariables>' requires 1 type argument(s).
node_modules/apollo-client/ApolloClient.d.ts(42,30): error TS2314: Generic type 'Fragment<TVariables>' requires 1 type argument(s).
node_modules/apollo-client/ApolloClient.d.ts(43,25): error TS2314: Generic type 'WriteQueryOptions<TData, TVariables>' requires 2 type argument(s).
node_modules/apollo-client/ApolloClient.d.ts(44,28): error TS2314: Generic type 'WriteFragmentOptions<TData, TVariables>' requires 2 type argument(s).
src/app/shared/graphql/applicant-demographics.graphql.ts(1,8): error TS1192: Module '"/Users/tylerthrailkill/Documents/dev/code/frontend/project/node_modules/@types/graphql/index"' has no default export.
src/app/shared/graphql/applicant-groups-credit-reference-numbers.ts(1,8): error TS1192: Module '"/Users/tylerthrailkill/Documents/dev/code/frontend/project/node_modules/@types/graphql/index"' has no default export.
src/app/shared/graphql/conditions.graphql.ts(1,8): error TS1192: Module '"/Users/tylerthrailkill/Documents/dev/code/frontend/project/node_modules/@types/graphql/index"' has no default export.
src/app/shared/graphql/credit-reports.graphql.ts(1,8): error TS1192: Module '"/Users/tylerthrailkill/Documents/dev/code/frontend/project/node_modules/@types/graphql/index"' has no default export.
src/app/shared/graphql/current-product.graphql.ts(1,8): error TS1192: Module '"/Users/tylerthrailkill/Documents/dev/code/frontend/project/node_modules/@types/graphql/index"' has no default export.
src/app/shared/graphql/decisions.graphql.ts(1,8): error TS1192: Module '"/Users/tylerthrailkill/Documents/dev/code/frontend/project/node_modules/@types/graphql/index"' has no default export.
src/app/shared/graphql/document-types.graphql.ts(1,8): error TS1192: Module '"/Users/tylerthrailkill/Documents/dev/code/frontend/project/node_modules/@types/graphql/index"' has no default export.
src/app/shared/graphql/document.graphql.ts(1,8): error TS1192: Module '"/Users/tylerthrailkill/Documents/dev/code/frontend/project/node_modules/@types/graphql/index"' has no default export.
src/app/shared/graphql/documents.graphql.ts(1,8): error TS1192: Module '"/Users/tylerthrailkill/Documents/dev/code/frontend/project/node_modules/@types/graphql/index"' has no default export.
src/app/shared/graphql/fnm-product-identifier.graphql.ts(1,8): error TS1192: Module '"/Users/tylerthrailkill/Documents/dev/code/frontend/project/node_modules/@types/graphql/index"' has no default export.
src/app/shared/graphql/ida.graphql.ts(1,8): error TS1192: Module '"/Users/tylerthrailkill/Documents/dev/code/frontend/project/node_modules/@types/graphql/index"' has no default export.
src/app/shared/graphql/income-timeline.graphql.ts(1,8): error TS1192: Module '"/Users/tylerthrailkill/Documents/dev/code/frontend/project/node_modules/@types/graphql/index"' has no default export.
src/app/shared/graphql/loan-applicant-status.graphql.ts(1,8): error TS1192: Module '"/Users/tylerthrailkill/Documents/dev/code/frontend/project/node_modules/@types/graphql/index"' has no default export.
src/app/shared/graphql/loan-data.graphql.ts(1,8): error TS1192: Module '"/Users/tylerthrailkill/Documents/dev/code/frontend/project/node_modules/@types/graphql/index"' has no default export.
src/app/shared/graphql/loan-file.graphql.ts(1,8): error TS1192: Module '"/Users/tylerthrailkill/Documents/dev/code/frontend/project/node_modules/@types/graphql/index"' has no default export.
src/app/shared/graphql/loan-number.graphql.ts(1,8): error TS1192: Module '"/Users/tylerthrailkill/Documents/dev/code/frontend/project/node_modules/@types/graphql/index"' has no default export.
src/app/shared/graphql/loan-summary.graphql.ts(1,8): error TS1192: Module '"/Users/tylerthrailkill/Documents/dev/code/frontend/project/node_modules/@types/graphql/index"' has no default export.
src/app/shared/graphql/loan-transaction-summary.graphql.ts(1,8): error TS1192: Module '"/Users/tylerthrailkill/Documents/dev/code/frontend/project/node_modules/@types/graphql/index"' has no default export.
src/app/shared/graphql/loan-transaction.graphql.ts(1,8): error TS1192: Module '"/Users/tylerthrailkill/Documents/dev/code/frontend/project/node_modules/@types/graphql/index"' has no default export.
src/app/shared/graphql/prequal-letter.graphql.ts(1,8): error TS1192: Module '"/Users/tylerthrailkill/Documents/dev/code/frontend/project/node_modules/@types/graphql/index"' has no default export.
src/app/shared/graphql/product-search.graphql.ts(1,8): error TS1192: Module '"/Users/tylerthrailkill/Documents/dev/code/frontend/project/node_modules/@types/graphql/index"' has no default export.
src/app/shared/graphql/selected-product.graphql.ts(1,8): error TS1192: Module '"/Users/tylerthrailkill/Documents/dev/code/frontend/project/node_modules/@types/graphql/index"' has no default export.
src/app/shared/services/borrower.service.ts(246,35): error TS2345: Argument of type '{ query: ApplicantGroupNode; variables: { loanTransactionId: string; loanId: string; }; }' is not assignable to parameter of type 'WatchQueryOptions & TypedVariables<{ loanTransactionId: string; loanId: string; }>'.
  Type '{ query: ApplicantGroupNode; variables: { loanTransactionId: string; loanId: string; }; }' is not assignable to type 'WatchQueryOptions'.
    Types of property 'query' are incompatible.
      Type 'ApplicantGroupNode' is not assignable to type 'DocumentNode'.
        Property 'kind' is missing in type 'ApplicantGroupNode'.


webpack: Failed to compile.
```

**Comment by mgtest42** [comment]
What do you think, problems with angular-pnpm related more to pnpm or angular-cli?
"pnpm install --shamefully-flatten" works (partially), but why this flag only required by angular?
I'm quite long using pnpm, an only now faced such problems. Sometimes there were issues, but nothing so global.

But there is another problem. I don't know, does anyone using angular and it's cli. So, I'll describe a little bit for verbose.
There's short how-to about adding global styles/scripts: https://medium.com/@davembush/adding-css-and-javascript-to-an-angular-cli-project-2b843a8283f3
It works with npm.
With pnpm, it doesn't produce any errors, but added styles/scripts don't appear in the final build. I have no idea why.

**Comment by nguyenxndaidev** [comment]
I have error when start angular 6 after trying to switch from npm (6.9.0) to pnpm (4.1.4) today:
nodejs v10.16.3
@angular/compiler-cli 8.2.11
```
> ng "serve" "-c" "local"

Object prototype may only be an Object or null: undefined
TypeError: Object prototype may only be an Object or null: undefined
    at setPrototypeOf (<anonymous>)
    at Object.__extends (C:\myproject\node_modules\.pnpm\registry.npmjs.org\tslib\1.10.0\node_modules\tslib\tslib.js:65:9)
    at C:\myproject\node_modules\.pnpm\registry.npmjs.org\@angular\compiler-cli\8.2.11_edfeddfbad03900b377e8d2372f0d6e2\node_modules\@angular\compiler-cli\src\ngtsc\indexer\src\template.js:115:17
    at C:\myproject\node_modules\.pnpm\registry.npmjs.org\@angular\compiler-cli\8.2.11_edfeddfbad03900b377e8d2372f0d6e2\node_modules\@angular\compiler-cli\src\ngtsc\indexer\src\template.js:314:6
    at C:\myproject\node_modules\.pnpm\registry.npmjs.org\@angular\compiler-cli\8.2.11_edfeddfbad03900b377e8d2372f0d6e2\node_modules\@angular\compiler-cli\src\ngtsc\indexer\src\template.js:3:17
    at Object.<anonymous> (C:\myproject\node_modules\.pnpm\registry.npmjs.org\@angular\compiler-cli\8.2.11_edfeddfbad03900b377e8d2372f0d6e2\node_modules\@angular\compiler-cli\src\ngtsc\indexer\src\template.js:9:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at C:\myproject\node_modules\.pnpm\registry.npmjs.org\@angular\compiler-cli\8.2.11_edfeddfbad03900b377e8d2372f0d6e2\node_modules\@angular\compiler-cli\src\ngtsc\indexer\src\transform.js:20:22
    at C:\myproject\node_modules\.pnpm\registry.npmjs.org\@angular\compiler-cli\8.2.11_edfeddfbad03900b377e8d2372f0d6e2\node_modules\@angular\compiler-cli\src\ngtsc\indexer\src\transform.js:10:17
    at Object.<anonymous> (C:\myproject\node_modules\.pnpm\registry.npmjs.org\@angular\compiler-cli\8.2.11_edfeddfbad03900b377e8d2372f0d6e2\node_modules\@angular\compiler-cli\src\ngtsc\indexer\src\transform.js:16:3)
```

**Comment by zkochan** [comment]
Unfortunately, both Angular and Vue still work only with
shamefully-hoist=true. You can set this config in the root `. npmrc` of
your projclect.

Nguyen <notifications@github.com> ezt írta (időpont: 2019. okt. 21., H
13:24):

**Comment by zkochan** [comment]
Seems like the latest Angular works.

If there'll be issues, we are now able to hoist selected dependencies instead of hoisting all. Just add something like this to your `.npmrc`:

```
public-hoist-pattern[]=*angular*
```

This will make pnpm hoist any packages that have `angular` in the name. This is a better approach than hoisting everything with `shamefully-hoist=true`.
