### ISSUE TITLE
Cannot read property 'fetchingRawManifest' of undefined

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#1273]
```
ERROR  ENOENT: no such file or directory, open '/app/.pnpm-store/2/registry.npmjs.org/nopt/3.0.6/package/package.json'
Error: ENOENT: no such file or directory, open '/app/.pnpm-store/2/registry.npmjs.org/proto-list/1.2.4/package/package.json'
TypeError: Cannot read property 'fetchingRawManifest' of undefined
    at fetchingFiles.promise.then (/usr/lib/node_modules/pnpm/lib/node_modules/@pnpm/package-requester/lib/packageRequester.js:206:41)
    at <anonymous>
TypeError: Cannot read property 'fetchingRawManifest' of undefined
    at fetchingFiles.promise.then (/usr/lib/node_modules/pnpm/lib/node_modules/@pnpm/package-requester/lib/packageRequester.js:206:41)
    at <anonymous>
```

### Additional information:

 - `node -v` prints: 8.4.0
 - Windows, OS X, or Linux?: Linux RHEL

**Comment by zkochan** [comment]
I don't know what is the issue yet but this was the last significant change in that area: https://github.com/pnpm/package-requester/pull/25
