### ISSUE TITLE
` ERROR  Cannot read property 'algorithm' of undefined`

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#1324]
```
 ERROR  Cannot read property 'algorithm' of undefined
at parse      …-package/node_modules/ssri/index.js:128  } else if (sri.algorithm && sri.digest) {           
at checkData  …-package/node_modules/ssri/index.js:218  sri = parse(sri, opts)                              
at data       …k-package/node_modules/dint/index.js:65  .then(data => ssri.checkData(data, fstat.integrity))
Resolving: total 11767, reused 10649, downloaded 1117
Downloading registry.npmjs.org/flow-bin/0.46.0: 2.51 MB/6.36 MB
TypeError: Cannot read property 'algorithm' of undefined
    at parse (/home/webdev/.nvm/versions/node/v8.10.0/lib/node_modules/pnpm/lib/node_modules/@pnpm/check-package/node_modules/ssri/index.js:128:18)
    at Object.checkData (/home/webdev/.nvm/versions/node/v8.10.0/lib/node_modules/pnpm/lib/node_modules/@pnpm/check-package/node_modules/ssri/index.js:218:9)
    at fs.readFile.then.data (/home/webdev/.nvm/versions/node/v8.10.0/lib/node_modules/pnpm/lib/node_modules/@pnpm/check-package/node_modules/dint/index.js:65:26)
    at <anonymous>
TypeError: Cannot read property 'algorithm' of undefined
    at parse (/home/webdev/.nvm/versions/node/v8.10.0/lib/node_modules/pnpm/lib/node_modules/@pnpm/check-package/node_modules/ssri/index.js:128:18)
    at Object.checkData (/home/webdev/.nvm/versions/node/v8.10.0/lib/node_modules/pnpm/lib/node_modules/@pnpm/check-package/node_modules/ssri/index.js:218:9)
    at fs.readFile.then.data (/home/webdev/.nvm/versions/node/v8.10.0/lib/node_modules/pnpm/lib/node_modules/@pnpm/check-package/node_modules/dint/index.js:65:26)
    at <anonymous>

```

### Additional information:

 - `node -v` prints: 8.10.0
 - Windows, OS X, or Linux?: Ubuntu 16.04

**Comment by zkochan** [comment]
:ship: 2.13.5
