### ISSUE TITLE
pnpm install with dataframe-js dependency generates an invalid node_modules structure which fails at runtime

### ISSUE THREAD

**Issue by adamhonen** [pnpm/pnpm#1435]
### Code to reproduce the issue:

1.  Create the following package.json:
```
{
  "name": "test-proj",
  "version": "1.0.0",
  "private": true,
  "dependencies": {
    "dataframe-js": "^1.3.2"
  }
}
```
 
2. run `pnpm install`
3. run node
4. enter the following code: `require('dataframe-js');`

### Expected behavior:
This is the output I get when using npm instead of pnpm (step 2 above):
```
> require('dataframe-js');
{ __esModule: true,
  DataFrame:
   { [Function: DataFrame]
     defaultModules: [ [Function: Stat], [Function: Matrix], [Object] ],
     sql: { [Function: SQL] tables: {} } },
  Row: [Function: Row],
  Errors:
   { __esModule: true,
     FileNotFoundError: [Function: FileNotFoundError],
     MixedTypeError: [Function: MixedTypeError],
     NoSuchColumnError: [Function: NoSuchColumnError],
     WrongSchemaError: [Function: WrongSchemaError],
     ArgumentTypeError: [Function: ArgumentTypeError],
     SQLParseError: [Function: SQLParseError],
     TableAlreadyExistsError: [Function: TableAlreadyExistsError],
     WrongTableNameError: [Function: WrongTableNameError] },
  default:
   { [Function: DataFrame]
     defaultModules: [ [Function: Stat], [Function: Matrix], [Object] ],
     sql: { [Function: SQL] tables: {} } } }
```

### Actual behavior:
```
> require('dataframe-js');
Error: Cannot find module 'babel-runtime/core-js/array/from'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/mnt/c/dev/projects/test-proj/node_modules/.registry.npmjs.org/dataframe-js/1.3.2/node_modules/dataframe-js/lib/dataframe.js:5:13)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
```
### Additional information:

 - `node -v` prints: v8.3.0
 - Windows, OS X, or Linux?: Windows 10, using the Linux subsystem
 - npm version: 6.4.1

**Comment by KSXGitHub** [comment]
I guess you need to use `--shamefully-flatten` flag.

**Comment by zkochan** [comment]
or install `babel-runtime` as a dependency

The issue is that `dataframe-js` requires `babel-runtime` but `babel-runtime` is not in prod dependencies of `dataframe-js`, so seems like a bug in `dataframe-js`.

It works with flat node_modules because babel-runtime is a dependency of babel-polyfill which is a prod dependency, so it is hoisted to the top of node_modules

**Comment by adamhonen** [comment]
> 
> 
> ...or install `babel-runtime` as a dependency
> 
> The issue is that `dataframe-js` requires `babel-runtime` but `babel-runtime` is not in prod dependencies of `dataframe-js`, so seems like a bug in `dataframe-js`.
> 
> It works with flat node_modules because babel-runtime is a dependency of babel-polyfill which is a prod dependency, so it is hoisted to the top of node_modules

Right....
I now see the dataframe-js project have this issue: https://github.com/Gmousse/dataframe-js/issues/63

**Comment by adamhonen** [comment]
@zkochan as this seems to be a bug in dataframe-js, is it OK, if I close this issue?
I'm not sure what you usually do with such cases...

Personally I ended up adding the babel-runtime dependency in my module to overcome this, which worked just fine.
