### ISSUE TITLE
Script logging cuts off lines

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#1609]
Note that the line for the error is trimmed, and I cannot see the name of the missing module.

```
.../patched/next-react-router prepublish$ npm run build
│ > @vjpr/next-react-router@1.1.1 build xxx/packages/public/patched/next-react-router
│ > babel src -d dist
│ { Error: [BABEL] xxx/packages/public/patched/next-react-router/src/IsomorphicRouter.js: Cannot find module '@babel/helper-c
│     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
│     at Function.Module._load (internal/modules/cjs/loader.js:529:25)
│     at Module.require (internal/modules/cjs/loader.js:659:17)
│     at require (internal/modules/cjs/helpers.js:22:18)
│     at _helperCreateClassFeaturesPlugin (xxx/node_modules/.registry.npmjs.org/@babel/plugin-proposal-class-properties/7.2.3
│     at _default (xxx/node_modules/.registry.npmjs.org/@babel/plugin-proposal-class-properties/7.2.3/node_modules/@babel/plu
│     at xxx/node_modules/.registry.npmjs.org/@babel/helper-plugin-utils/7.0.0/node_modules/@babel/helper-plugin-utils/lib/in
│     at loadDescriptor (xxx/node_modules/.registry.npmjs.org/@babel/core/7.1.2/node_modules/@babel/core/lib/config/full.js:1
│     at cachedFunction (xxx/node_modules/.registry.npmjs.org/@babel/core/7.1.2/node_modules/@babel/core/lib/config/caching.j
│     at loadPluginDescriptor (xxx/node_modules/.registry.npmjs.org/@babel/core/7.1.2/node_modules/@babel/core/lib/config/ful
│ npm ERR! code ELIFECYCLE
│ npm ERR! errno 1
│ npm ERR! @vjpr/next-react-router@1.1.1 build: `babel src -d dist`
│ npm ERR! Exit status 1
│ npm ERR!
│ npm ERR! Failed at the @vjpr/next-react-router@1.1.1 build script.
│ npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
│ npm ERR! A complete log of this run can be found in:
│ npm ERR!     /Users/Vaughan/.npm/_logs/2019-01-18T13_58_11_312Z-debug.log
└─ Failed in 601ms
 ERROR  @vjpr/next-react-router@1.1.1 prepublish: `npm run build`
Exit status 1
```

### Additional information:

 - `node -v` prints: 11
 - Windows, OS X, or Linux?: macOS

**Comment by vjpr** [comment]
Just want to bump this, its a pretty frustrating bug. 

Workaround is to inspect the `pnpm-debug.log` or run with `--reporter ndjson`.

**Comment by panoply** [comment]
Bumping this. Current log options are exceptionally limiting. I'm using pnpm on a monorepo that recursively runs rollup scripts from within packages. Logging is cut off, lacks colours and is generally just terrible.

**Comment by zkochan** [comment]
Use the `stream=true` option since pnpm v5.1.0
