### ISSUE TITLE
pnpm completely broken - global.Observable

### ISSUE THREAD

**Issue by reneroth** [pnpm/pnpm#1658]
### pnpm version:

most recent available via `npm i -g pnpm`, unable to check, running on node v11.3.0

### Code to reproduce the issue:

`pnpm --version` or any other command

### Expected behavior:

output the version or execute any other command

### Actual behavior:

throwing error

### Additional information:

```
Users/reneroth/.nvm/versions/node/v11.3.0/pnpm-global/1/node_modules/.registry.npmjs.org/any-observable/0.3.0/node_modules/any-observable/register.js:29
		throw new Error('Cannot find any-observable implementation nor' +
		^

Error: Cannot find any-observable implementation nor global.Observable. You must install polyfill or call require("any-observable/register") with your preferred implementation, e.g. require("any-observable/register")('rxjs') on application load prior to any require("any-observable").
    at loadImplementation (/Users/reneroth/.nvm/versions/node/v11.3.0/pnpm-global/1/node_modules/.registry.npmjs.org/any-observable/0.3.0/node_modules/any-observable/register.js:29:9)
    at /Users/reneroth/.nvm/versions/node/v11.3.0/pnpm-global/1/node_modules/.registry.npmjs.org/any-observable/0.3.0/node_modules/any-observable/loader.js:30:18
    at Object.<anonymous> (/Users/reneroth/.nvm/versions/node/v11.3.0/pnpm-global/1/node_modules/.registry.npmjs.org/any-observable/0.3.0/node_modules/any-observable/index.js:2:39)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:22:18)

```

**Comment by reneroth** [comment]
Fixed it by completely `rm -rf`ing my global npm packages.
