### ISSUE TITLE
Global install .cmd stub paths

### ISSUE THREAD

**Issue by Js-Brecht** [pnpm/pnpm#1846]
### pnpm version: 
3.3.4

### Code to reproduce the issue:
Install any global package using pnpm
`D:\> pnpm --global install typescript`

Try to run installed bin files
`D:\> tsc`

### Expected behavior:
tsc should run using the bin installed in the global directory

### Actual behavior:
Error: Cannot find module 'C:\Program Files\nodejs\D:\nvm\v10.13.0\pnpm-global\2\node_modules\jshint\bin\jshint'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)

### Additional information:
I am using NVM for windows
I have nvm running off of a secondary drive, where I keep my source.
NVM uses a symlink in "C:\Program Files" to point to the currently selected version
```
C:\Program Files\nodejs -> D:\nvm\v10.13.0
```
I have pnpm-prefix set in userconfig .npmrc
```
D:\npm config list
...
pnpm-prefix = "C:\\Program Files\\nodejs"
...
```
Setting the prefix for npm was unnecessary, because npm uses "C:\Program Files\nodejs"as its global directory by default.
```
D:\> npm --version
6.4.1

D:\> npm config list -l
...
prefix = "C:\\Program Files\\nodejs"
...
```
npm runs without issue.  pnpm finds the global directory, no problem.  Installs, no problem.  However, the .cmd stubs created look like this
```
@IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.exe"  "%~dp0\D:\nvm\v10.13.0\pnpm-global\2\node_modules\typescript\bin\tsc" %*
) ELSE (
  @SETLOCAL
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  node  "%~dp0\D:\nvm\v10.13.0\pnpm-global\2\node_modules\typescript\bin\tsc" %*
)
```

Where it actually executes the bin file, it looks like to me that it is adding the resolved pnpm-prefix to the beginning of its location in the pnpm-global store, but because that occurs after "%~dp0", it winds up with the prefix in there twice.

 - `node -v` prints: v10.13.0
 - Windows, OS X, or Linux?: Windows 10

**Comment by zkochan** [comment]
I guess we should resolve the command shim to its real location before getting the relative path to the src file

https://github.com/pnpm/cmd-shim/blob/58f02f9e49ec2b2ecdad2ae5a2562b36b9b354d3/index.js#L245

**Comment by Js-Brecht** [comment]
So just out of curiosity, why is the path not resolved before it gets to cmd-shim?  Is it because of how the store operates?  Seems to be a deviation from how npm operates, so I assume it's intentional.

**Comment by altaywtf** [comment]
I can't reproduce this on current pnpm (Windows 11, Node 24.21.0).

With the pnpm 11.27.1 shim writer (`@pnpm/bins.cmd-shim`), a `.cmd` shim on `C:` whose target is on another drive (`subst Q:`) now gets the absolute target (`"Q:\pnpm-global\tool.js"`) and runs. Removing the `path.isAbsolute(target)` guard in `pnpm11/bins/cmd-shim/src/index.ts` reproduces exactly the error reported here (`Cannot find module 'C:\...\bin\Q:\pnpm-global\tool.js'`), so the guard is what fixed it. pnpm 12 has the same guard in `pnpm/crates/cmd-shim/src/shim.rs`; I checked that one by reading the code, not by running a global install.

Unless someone can still reproduce it on 11.27.1 or 12.6.0, I think this can be closed.

Written by an agent (Claude Code, Opus 5.5).
