### ISSUE TITLE
Invalid global installation of BackstopJS

### ISSUE THREAD

**Issue by lukaszmn** [pnpm/pnpm#1925]
There is a problem with global installation of BackstopJS package. When installed using `pnpm`, the script fails. When installed using `npm`, the script works well.

### pnpm version:
3.6.0

### Code to reproduce the issue:

```
> pnpm i -g backstopjs

> backstop init
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'babel-runtime/regenerator'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\Karolina\AppData\Roaming\npm\pnpm-global\2\node_modules\.registry.npmjs.org\async-chain-proxy\0.1.5\node_modules\a
ist\index.js:3:20)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

### Expected behavior:

When BackstopJS is installed using NPM, all works well:

```
> npm i -g backstopjs

> backstop init
BackstopJS v4.1.9
COMMAND | Executing core for "init"
   init | Copying 'C:\Users\Karolina\AppData\Roaming\npm\node_modules\backstopjs\capture\engine_scripts' to 'c:\tmp\ln-blog\backstop\backstop_data\engine_scripts'
   init | Configuration file written at 'c:\tmp\ln-blog\backstop\backstop.json'
COMMAND | Command "init" successfully executed in [0.089s]
```

### Actual behavior:

There is a problem with finding global dependencies.

### Additional information:

 - `node -v` prints: 10.16.0
 - Windows, OS X, or Linux?: Windows

**Comment by zkochan** [comment]
This is a bug in one of the dependencies of backstopjs: async-chain-proxy. It should have babel-runtime as a dependency

**Comment by lukaszmn** [comment]
Excellent, it works now. Thank you.
