### ISSUE TITLE
typorm do not find `ormconfig.json` when it placed on root dir on monorepo

### ISSUE THREAD

**Issue by hemedani** [pnpm/pnpm#1929]
### pnpm version:
```
 [I] ➜ pnpm -v
3.6.0
```
### Code to reproduce the issue:
```javascript
import { createConnection } from "typeorm";
  createConnection();
```
the actual file address on [git repo](https://github.com/hemedani/sefood-tracing-pnpm) is this : `./packages/sefood-tracing-bc/src/index.ts`

the issue is it as say on console :
```console
> sefood-tracing-bc@1.0.0 start /Users/syd/work/sefood/sefoodTracing/packages/sefood-tracing-bc
> ts-node-dev --respawn src/index.ts

Using ts-node version 8.3.0, typescript version 3.5.3
(node:29025) UnhandledPromiseRejectionWarning: Error: No connection options were found in any of configurations file.
    at ConnectionOptionsReader.<anonymous> (/Users/syd/work/sefood/sefoodTracing/node_modules/.registry.npmjs.org/typeorm/0.2.18/src/connection/ConnectionOptionsReader.ts:41:19)
    at step (/Users/syd/work/sefood/sefoodTracing/node_modules/.registry.npmjs.org/tslib/1.10.0/node_modules/tslib/tslib.js:136:27)
    at Object.next (/Users/syd/work/sefood/sefoodTracing/node_modules/.registry.npmjs.org/tslib/1.10.0/node_modules/tslib/tslib.js:117:57)
    at fulfilled (/Users/syd/work/sefood/sefoodTracing/node_modules/.registry.npmjs.org/tslib/1.10.0/node_modules/tslib/tslib.js:107:62)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
(node:29025) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:29025) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

but when `ormconfig.json` placed on the `./packages/sefood-tracing-bc/src` everything is fine,
in yarn workspaces we can place `ormconfig.json` on the root directory

### Expected behavior:
detect `ormconfig.json` on the root directory
### Additional information:
I create a [github repo](https://github.com/hemedani/sefood-tracing-pnpm) to see the error in action

 - `node -v` prints: `v8.11.2`
 - Windows, OS X, or Linux?: `OS X`

**Comment by BlackDark** [comment]
Still applies. Working with nestjs.

Installing with yarn -> works and ormconfig.json is found and used. Installed via pnpm not found anymore.

**Comment by zkochan** [comment]
In worst case scenario, you may use the [node-linker=hoisted](https://pnpm.io/npmrc#node-linker) setting
