### ISSUE TITLE
Dynamic loading of dependencies causes "Error: Cannot find module"

### ISSUE THREAD

**Issue by iampeterbanjo** [pnpm/pnpm#1963]
I am migrating an existing yarn workspace to pnpm. I'm using a nodejs framework (Hapi) and in some cases module names can be passed as arguments and loaded later as plugins into the framework. This doesn't work with pnpm. I'm finding that I have to require the plugins at the top level and pass them down or else I get `Error: Cannot find module '@hapi/good-squeeze'`. This is the [source code](https://github.com/hapijs/good/blob/e94aefff880b25e69cad6f699c7f5d5fbf529ab3/lib/monitor.js#L100) of one the dynamic module loaders. You can see it just takes a string or a function - if it's a string it requires it - that doesn't work. Do you have any suggestions about how to go work around or fix this?

See #1355

### Code to reproduce the issue: 
git clone git@github.com:iampeterbanjo/iampeterbanjo.com-pnpm.git
cd iampeterbanjo.com-pnpm
pnpm m i
pnpm run dry-run

### Actual behavior: 
{ Error: Cannot find module '@hapi/good-squeeze'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)

### Additional information:

 - `node -v` prints: v10.14.2
 - Windows, OS X, or Linux?: Linux

**Comment by zkochan** [comment]
I am getting a different error:

```
> site@1.0.0 start /home/zoltan/src/sandbox/iampeterbanjo.com-pnpm
> node ./packages/server/start.js

/home/zoltan/src/sandbox/iampeterbanjo.com-pnpm/node_modules/.registry.npmjs.org/lyricist/2.2.2/node_modules/lyricist/lib/index.js:6
    if (!accessToken) throw new Error('No access token provided to lyricist!');
                      ^

Error: No access token provided to lyricist!
    at new Lyricist (/home/zoltan/src/sandbox/iampeterbanjo.com-pnpm/node_modules/.registry.npmjs.org/lyricist/2.2.2/node_modules/lyricist/lib/index.js:6:29)
    at Object.<anonymous> (/home/zoltan/src/sandbox/iampeterbanjo.com-pnpm/packages/server/utils/clientel.js:33:18)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/zoltan/src/sandbox/iampeterbanjo.com-pnpm/packages/server/utils/index.js:1:80)
```

**Comment by zkochan** [comment]
This is the same as #1791

I submitted a workaround for you https://github.com/iampeterbanjo/iampeterbanjo.com-pnpm/pull/1

**Comment by zkochan** [comment]
I think the right way would be to fix it on the `@hapi/good` side. They should load plugins via:

```js
let Ctor = isFn ? spec.module : require(require.resolve(spec.module, {paths: [require.main.filename]}));
```

**Comment by iampeterbanjo** [comment]
Wow! Thanks, you're awesome - I didn't expect a solution and a PR so quickly! I'll let the maintainers know.

**Comment by zkochan** [comment]
no problem

I opened a PR at `@hapi/good`: https://github.com/hapijs/good/pull/623

**Comment by iampeterbanjo** [comment]
hmm... the pnpmfile.js change doesn't work but adding `@hapi/good-squeeze`, `@hapi/good-console` it to the root package does. what i did was clean node_modules, run `pnpm m i`, and try and start again.

**Comment by zkochan** [comment]
oh, sorry, forgot to mention. After any changes in the pnpmfile.js, you should run `pnpm m up --depth 999`

**Comment by iampeterbanjo** [comment]
Yup that works
