### ISSUE TITLE
symlinks not correct inside docker

### ISSUE THREAD

**Issue by iampeterbanjo** [pnpm/pnpm#1968]
### Code to reproduce the issue:
```
git clone git@github.com:iampeterbanjo/iampeterbanjo.com-pnpm.git
cd iampeterbanjo.com-pnpm
make build
make run
make logs
```

### Expected behavior:
docker image starts without package errors
### Actual behavior:
```
> site@1.0.0 start /usr/src/app
> node ./packages/server/start.js

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '@hapi/glue'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/src/app/packages/server/api.js:1:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
 WARN  Unsupported engine: wanted: {"node":"10.14.2"} (current: {"node":"v10.16.3","pnpm":"3.7.3"})
 ERROR  Command failed with exit code 1.
```

### Additional information:

If I connect to the docker shell (`make exec`) and I manually run `pnpm install; pnpm start` the image runs as expected (there is a separate problem with environmental variables but that's on me). I've tried adding `--unsafe-perm` as #1069 suggests and that hasn't worked.

This is the directory structure in docker.

```
node@c59409c1fe6e:/usr/src/app$ ls -la
total 296
drwxr-xr-x  1 node node   4096 Aug 19 04:51 .
drwxr-xr-x  1 root root   4096 Aug 19 04:50 ..
-rw-rw-r--  1 node node    232 Apr 13 05:49 .editorconfig
-rw-rw-r--  1 node node   1044 Jul 25 06:07 .envrc
-rw-rw-r--  1 node node     37 Apr  6 13:40 .eslintignore
-rw-rw-r--  1 node node    139 Jul 23 04:30 .eslintrc.json
-rw-rw-r--  1 node node     71 Jul 23 04:30 .labrc.js
-rw-rw-r--  1 node node     25 Aug 17 19:29 .npmrc
-rw-rw-r--  1 node node      9 Apr 13 05:49 .prettierignore
-rw-rw-r--  1 node node    863 Aug 18 21:09 Makefile
-rw-rw-r--  1 node node    774 Jul 23 04:30 README.md
-rw-rw-r--  1 node node    170 Aug 13 06:01 jsconfig.json
drwxr-xr-x  1 node node   4096 Aug 19 04:51 node_modules
-rw-rw-r--  1 node node   1633 Aug 17 19:54 package.json
drwxrwxr-x 11 node node   4096 Aug  6 06:07 packages
-rw-rw-r--  1 node node 225383 Aug 17 19:48 pnpm-lock.yaml
-rw-rw-r--  1 node node    119 Aug 17 19:29 pnpm-workspace.yaml
-rw-rw-r--  1 node node    321 Aug 17 19:29 pnpmfile.js
-rw-rw-r--  1 node node    108 Apr 12 06:14 prettier.config.js
```

I checked the contents of the `node_modules` and I'm not able to follow any of the symlinks e.g. `cd packages/server/node_modules/@hapi/catbox` returns `bash: cd: catbox: No such file or directory`. This is not just the case for @hapi - its true for any of the modules e.g. `bash: cd: acorn: No such file or directory` etc

```
node@c59409c1fe6e:/usr/src/app$ ls -la packages/server/node_modules/@hapi
total 56
drwxrwxr-x 2 node node 4096 Aug 18 20:32 .
drwxrwxr-x 4 node node 4096 Aug 18 20:32 ..
lrwxrwxrwx 1 node node   86 Aug 18 20:32 catbox -> ../../../../node_modules/.localhost+4873/@hapi/catbox/10.2.2/node_modules/@hapi/catbox
lrwxrwxrwx 1 node node   81 Aug 18 20:32 code -> ../../../../node_modules/.localhost+4873/@hapi/code/5.3.1/node_modules/@hapi/code
lrwxrwxrwx 1 node node   81 Aug 18 20:32 glue -> ../../../../node_modules/.localhost+4873/@hapi/glue/6.1.1/node_modules/@hapi/glue
lrwxrwxrwx 1 node node  114 Aug 18 20:32 good -> ../../../../node_modules/.localhost+4873/@hapi/good/8.2.1_51fe610a0a17b7d438e0f3777b08d9bf/node_modules/@hapi/good
```

 - `node -v` prints: 10.16.3
 - Windows, OS X, or Linux?: Linux

**Comment by iampeterbanjo** [comment]
The issue appears to have been my Dockerfile. The ordering of copying the packages and installing with pnpm :P

**Comment by abetoots** [comment]
@iampeterbanjo How did you solve this? What should be the correct order?

**Comment by rstuven** [comment]
Install external dependencies first, copy the rest of the source and then install again to create symlinks:

```docker
COPY package.json pnpm-lock.yaml ./

RUN pnpm install

COPY . .

RUN pnpm install
```

**Comment by jeanhdev** [comment]
Anybody found a way?

**Comment by RexSkz** [comment]
Symlinks won't work after changing their location (even if by changing their parent folder). So we should first copy the dependency files (`package.json` & `pnpm-lock.yaml`) to image, then run `pnpm i`. The `Dockerfile` should be like:

```dockerfile
COPY package.json ./
COPY pnpm-lock.yaml ./
# ...and other files that are necessary

RUN pnpm i
```

**Comment by lihongxiangfrontend** [comment]
add  node-linker=hoisted in .npmrc, but. not a good method

**Comment by gabrielDonnantuoni** [comment]
Unfortunately adding `node-linker=hoisted` still creates symlinks to packages of the workspace. It would be great if that just worked.

> Hey @RexSkz, thanks for the reply. I've tried this and it works fine in that use-case, but when using packages from `workspace:*` I can't sort it out, got any suggestions?

- My use case: 
Create a Docker image of an app under the `apps` folder that depends on some workspace packages on that are under the `packages` folder. All the packages are named like `@myorg/package-name` and built with tsc. I'm also using turbo repo to prune the workspace to only the dependencies that I need to build my target app.

- How I made it work:
I had to add this to steps to my Dockerfile

```
# First remove the symlinks inside  ${PROJECT_DIR}/node_modules/@myorg
RUN find ${PROJECT_DIR}/node_modules/@myorg -type l -exec rm -rf {} \;
# For each PACKAGE_DIR inside the packages directory, copy the package.json and the dist folder to ${PROJECT_DIR}/node_modules/@myorg/${PACKAGE_DIR}
RUN find packages -maxdepth 1 -mindepth 1 -type d -exec sh -c 'PACKAGE_DIR=$(basename {}); mkdir -p ./${PROJECT_DIR}/node_modules/@myorg/${PACKAGE_DIR}; cp {}/package.json ./${PROJECT_DIR}/node_modules/@myorg/${PACKAGE_DIR}; cp -r {}/dist ./${PROJECT_DIR}/node_modules/@myorg/${PACKAGE_DIR}/dist' \;
```
