### ISSUE TITLE
workspaces make require.resolve fail

### ISSUE THREAD

**Issue by wmertens** [pnpm/pnpm#1993]
### Expected behavior:

```bash
$ mkdir -p foo; cd foo; pnpm i jest-cli nps-utils; node -e 'console.log(require("nps-utils").getBin("jest-cli","jest"))'; cd -
Packages: +496
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Resolving: total 496, reused 496, downloaded 0, done

dependencies:
+ jest-cli 24.9.0
+ nps-utils 1.7.0
node_modules/.registry.npmjs.org/jest-cli/24.9.0/node_modules/jest-cli/bin/jest.js
```

### Actual behavior:

I would expect this to work the same way in a workspace package:

```bash
$ mkdir -p foo/sub; echo "packages: ['**']" > foo/pnpm-workspace.yaml; cd foo/sub; pnpm i jest-cli nps-utils; node -e 'console.log(require("nps-utils").getBin("jest-cli","jest"))'; cd -
Scope: current workspace package
..                                       | +496 +++++++++++++++++++++++++++++++++++++++++++++
..                                       | Resolving: total 496, reused 496, downloaded 0, don..                                       | Resolving: total 496, reused 496, downloaded 0, done

dependencies:
+ jest-cli 24.9.0
+ nps-utils 1.7.0

../node_modules/.registry.npmjs.org/fsevents/1.2.9/node_modules/fsevents: Running install script, done in 1s
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'jest-cli/package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.resolve (internal/modules/cjs/helpers.js:33:19)
    at Object.getBin (/Users/wmertens/foo/node_modules/.registry.npmjs.org/nps-utils/1.7.0/node_modules/nps-utils/dist/index.js:410:29)
```

The `getBin` call runs `require.resolve('jest-cli/package.json')`, which fails in the context of a workspace directory

### Additional information:

 - `node -v` prints: v10.16.0
 - Windows, OS X, or Linux?: OS X

**Comment by wmertens** [comment]
Is there anything I could do to make this issue better for you?

**Comment by zkochan** [comment]
I did not look into it yet but I think the issue might be something similar to https://github.com/pnpm/pnpm/issues/1791

**Comment by wmertens** [comment]
I agree, closing in favor of that one
