### ISSUE TITLE
pnpm fails to download packages when cashing the pnpm-store folder

### ISSUE THREAD

**Issue by ahmedkotb** [pnpm/pnpm#1999]
### Code to reproduce the issue:

we cache the pnpm-store folder in our CI builds then run pnpm update so that pnpm tries to reuse most of the packages and  downloads the delta.

however pnpm fails to download some packages ... that doesn't happen if we don't use the cache or if we disabled store integrity check

### Expected behavior: 
packages gets downloaded correctly

### Actual behavior:

```
FetchError: request to https://pkgs.dev.azure.com/msazure/_packaging/test-repo/npm/registry/abab/-/abab-2.0.0.tgz failed, reason: getaddrinfo ENOTFOUND pkgs.dev.azure.com pkgs.dev.azure.com:443
    at ClientRequest.<anonymous> (/home/vsts/.rush/node-v10.16.3/pnpm-3.7.5/node_modules/pnpm/lib/node_modules/node-fetch-unix/lib/index.js:1445:11)
    at ClientRequest.emit (events.js:198:13)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:203:15)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
FetchError: request to https://pkgs.dev.azure.com/msazure/_packaging/test-repo/npm/registry/minipass/-/minipass-2.4.0.tgz failed, reason: getaddrinfo ENOTFOUND pkgs.dev.azure.com pkgs.dev.azure.com:443
    at ClientRequest.<anonymous> (/home/vsts/.rush/node-v10.16.3/pnpm-3.7.5/node_modules/pnpm/lib/node_modules/node-fetch-unix/lib/index.js:1445:11)
    at ClientRequest.emit (events.js:198:13)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:203:15)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

### Additional information:

 - `node -v` prints: 10.16.3
 - Windows, OS X, or Linux?: Ubuntu 16.04

**Comment by zkochan** [comment]
This targets a part of pnpm that no longer exists, so closing.

Reported against pnpm 3.7 and the old per-package store layout. The store is content-addressable now and the integrity check it describes no longer exists.

If you still hit this on the latest pnpm, please comment with a reproduction and we will reopen.

---
Written by an agent (Claude Code, claude-opus-5).
