### ISSUE TITLE
@pnpm/cli-utils is unable to resolve pnpm's package.json when using self-installer

### ISSUE THREAD

**Issue by josephschmitt** [pnpm/pnpm#2273]
I've done some investigation into the issue, and I think it stems from this change: https://github.com/pnpm/pnpm/commit/70b5c50b6218521604099a138ad9c48615788611#diff-d1b685eea7a01a36d55534bf94486fceL5

Now instead of trying to read a package.json from a relative location, it's trying to resolve the `pnpm` package and read that package.json. The problem with this is in our projects we use the self-installer to save pnpm into our own specific cache, and so it never gets installed into the node_modules folder it's being run in. This breaks the resolution of `require.resolve(pnpm)`.

### Code to reproduce the issue:
Using the self-installer, install pnpm somewhere
Try getting the pnpm version from `pnpm.js`: `node path/to/lib/bin/pnpm.js -v`

### Expected behavior:
`node path/to/lib/bin/pnpm.js -v` Outputs the pnpm version

### Actual behavior:
Outputs the following stack trace:

```
(node:98772) UnhandledPromiseRejectionWarning: Error: Cannot find module 'pnpm/package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.resolve (internal/modules/cjs/helpers.js:33:19)
    at Object.<anonymous> (/Users/josephschmitt/development/uc-frontend/.pnpm/4.5.0/lib/node_modules/@pnpm/cli-utils/lib/pnpmPkgJson.js:4:43)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
```

### Additional information:
- Any NodeJS
- macOS 10.15.x

**Comment by zkochan** [comment]
As far as I know, Node.js allows to get the entry module path. We could use that to find the package manager manifest.

**Comment by josephschmitt** [comment]
> As far as I know, Node.js allows to get the entry module path. We could use that to find the package manager manifest.

The module in this case would be `@pnpm/cli` wouldn't it? So the version being returned would be for that package instead of `pnpm` as a whole?

**Comment by zkochan** [comment]
no, it would be the bin.js in pnpm

**Comment by josephschmitt** [comment]
@zkochan Hmm, tried installing 4.9.x to try out this fix but now getting a different error:

```
(node:6271) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/Users/josephschmitt/development/uc-frontend/.pnpm/4.9.1/lib/package.json'
    at Object.openSync (fs.js:457:3)
    at Object.readFileSync (fs.js:359:35)
    at AsyncFunction.module.exports.sync (/Users/josephschmitt/development/uc-frontend/.pnpm/4.9.1/lib/node_modules/load-json-file/index.js:19:55)
    at Object.<anonymous> (/Users/josephschmitt/development/uc-frontend/.pnpm/4.9.1/lib/node_modules/@pnpm/cli-utils/lib/pnpmPkgJson.js:5:30)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
```

Let me know if you want me to open a new issue.

**Comment by zkochan** [comment]
ok, created https://github.com/pnpm/pnpm/issues/2324

**Comment by zkochan** [comment]
> Try getting the pnpm version from `pnpm.js: node path/to/lib/bin/pnpm.js -v`

@josephschmitt you should try to run the bin file at `path/to/bin/pnpm.js -v`

**Comment by josephschmitt** [comment]
@zkochan 
```
~> node /Users/josephschmitt/development/uc-frontend/.pnpm/4.9.2/lib/bin/pnpm.js -v
(node:13383) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/Users/josephschmitt/development/uc-frontend/.pnpm/4.9.2/lib/package.json'
    at Object.openSync (fs.js:440:3)
    at Object.readFileSync (fs.js:342:35)
    at AsyncFunction.module.exports.sync (/Users/josephschmitt/development/uc-frontend/.pnpm/4.9.2/lib/node_modules/load-json-file/index.js:19:55)
    at Object.<anonymous> (/Users/josephschmitt/development/uc-frontend/.pnpm/4.9.2/lib/node_modules/@pnpm/cli-utils/lib/pnpmPkgJson.js:5:30)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
```

**Comment by zkochan** [comment]
you should try `node /Users/josephschmitt/development/uc-frontend/.pnpm/4.9.2/bin/pnpm.js -v`

**Comment by josephschmitt** [comment]
@zkochan I just tried with `4.9.3` and it's working even without the new path. I tried the non-lib path in `4.9.2` and it did not work. Thanks for the fix!

**Comment by josephschmitt** [comment]
Is the non-lib path the new preferred entrypoint to the cli?

**Comment by zkochan** [comment]
yes, it is. But if the old path works as well, I don't care. I assume if  you use the old path and run `-v` it will print `0.0.0`

**Comment by josephschmitt** [comment]
@zkochan yup, exactly. Updated to use the new path and everything's working great. Thanks again! You're the best.
