### ISSUE TITLE
Linking doesn't work anymore

### ISSUE THREAD

**Issue by RoelVB** [pnpm/pnpm#2276]
Linking doesn't seem to work anymore. It did work with PNPM 3.x.
I did recreate the node-modules directories after upgrading to 4.x.

### Code to reproduce the issue:

```
cd foo
pnpm link
cd ../bar
pnpm link foo
```

### Expected behavior:

It should link `foo` to `bar` instead of throwing an error.

### Actual behavior:

Receiving the following error:
```json
{
  "0 debug pnpm:scope": {
    "selected": 1
  },
  "1 debug pnpm": {
    "isCaseSensitive": false,
    "store": "C:\\Users\\RoelVB\\.pnpm-store\\2"
  },
  "2 error pnpm": {
    "message": {
      "code": "ERR_PNPM_UNEXPECTED_VIRTUAL_STORE",
      "expected": "C:\\Users\\RoelVB\\Documents\\Development\\foo\\node_modules\\.pnpm",
      "actual": "C:\\Users\\RoelVB\\AppData\\Roaming\\npm\\pnpm-global\\node_modules\\foo\\node_modules\\.pnpm",
      "modulesDir": "C:\\Users\\RoelVB\\Documents\\Development\\foo\\node_modules"
    },
    "err": {
      "name": "Error",
      "message": "Unexpected virtual store location",
      "code": "ERR_PNPM_UNEXPECTED_VIRTUAL_STORE",
      "stack": "Error: Unexpected virtual store location\n    at Object.checkCompatibility [as default] (C:\\Users\\RoelVB\\AppData\\Roaming\\npm\\pnpm-global\\3\\node_modules\\.pnpm\\registry.npmjs.org\\pnpm\\4.7.2\\node_modules\\pnpm\\lib\\node_modules\\@pnpm\\get-context\\lib\\checkCompatibility\\index.js:21:15)\n    at Promise.all.projects.map (C:\\Users\\RoelVB\\AppData\\Roaming\\npm\\pnpm-global\\3\\node_modules\\.pnpm\\registry.npmjs.org\\pnpm\\4.7.2\\node_modules\\pnpm\\lib\\node_modules\\@pnpm\\get-context\\lib\\index.js:137:41)\n    at Array.map (<anonymous>)\n    at validateNodeModules (C:\\Users\\RoelVB\\AppData\\Roaming\\npm\\pnpm-global\\3\\node_modules\\.pnpm\\registry.npmjs.org\\pnpm\\4.7.2\\node_modules\\pnpm\\lib\\node_modules\\@pnpm\\get-context\\lib\\index.js:135:32)\n    at Object.getContext [as default] (C:\\Users\\RoelVB\\AppData\\Roaming\\npm\\pnpm-global\\3\\node_modules\\.pnpm\\registry.npmjs.org\\pnpm\\4.7.2\\node_modules\\pnpm\\lib\\node_modules\\@pnpm\\get-context\\lib\\index.js:20:15)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
    }
  }
}
```

### Additional information:

 - `node -v` prints: v10.16.3
 - Windows, OS X, or Linux?: Windows

**Comment by yaodingyd** [comment]
Does this https://github.com/pnpm/pnpm/commit/66cdabac65942923fc206c9c65934f1fff9a2edc fixed your issue?

**Comment by RoelVB** [comment]
Just upgraded from 4.x to 5.15.1
Linking is working fine now!
