### ISSUE TITLE
Fail when /usr/local/lib/node_modules is a symlink

### ISSUE THREAD

**Issue by hyuzea** [pnpm/pnpm#2282]
### Code to reproduce the issue:
```pnpm -v```

### Actual behavior:
```
(node:9853) UnhandledPromiseRejectionWarning: Error: Cannot find module 'pnpm/package.json'
Require stack:
- /media/xubuncup/ntfsd/.linux-fs/usr~local~lib~node_modules/pnpm/lib/node_modules/@pnpm/cli-utils/lib/pnpmPkgJson.js
- /media/xubuncup/ntfsd/.linux-fs/usr~local~lib~node_modules/pnpm/lib/node_modules/@pnpm/cli-utils/lib/getConfig.js
- /media/xubuncup/ntfsd/.linux-fs/usr~local~lib~node_modules/pnpm/lib/node_modules/@pnpm/cli-utils/lib/index.js
- /media/xubuncup/ntfsd/.linux-fs/usr~local~lib~node_modules/pnpm/lib/bin/pnpm.js
- /media/xubuncup/ntfsd/.linux-fs/usr~local~lib~node_modules/pnpm/bin/pnpm.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.resolve (internal/modules/cjs/helpers.js:78:19)
    at Object.<anonymous> (/media/xubuncup/ntfsd/.linux-fs/usr~local~lib~node_modules/pnpm/lib/node_modules/@pnpm/cli-utils/lib/pnpmPkgJson.js:4:43)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/media/xubuncup/ntfsd/.linux-fs/usr~local~lib~node_modules/pnpm/lib/node_modules/@pnpm/cli-utils/lib/getConfig.js:4:23)
(node:9853) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9853) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
### Additional information:
 - This happen when using direktori `/usr/local/lib/node_modules` as symlink to `/media/xubuncup/ntfsd/.linux-fs/usr~local~lib~node_modules/`. If not using symlink it seem working fine
 - `node -v` prints: v13.7.0
 - Ubuntu 18.04

**Comment by zackkrida** [comment]
Same issue on macos 10.15.2 with node `v12.14.1`. Node is installed via volta fyi `/Users/zack/.volta/bin/node`

```
❯ pnpm -v
(node:47189) UnhandledPromiseRejectionWarning: Error: Cannot find module 'pnpm/package.json'
Require stack:
- /Users/zack/.volta/tools/image/packages/pnpm/4.8.0/lib/node_modules/@pnpm/cli-utils/lib/pnpmPkgJson.js
- /Users/zack/.volta/tools/image/packages/pnpm/4.8.0/lib/node_modules/@pnpm/cli-utils/lib/getConfig.js
- /Users/zack/.volta/tools/image/packages/pnpm/4.8.0/lib/node_modules/@pnpm/cli-utils/lib/index.js
- /Users/zack/.volta/tools/image/packages/pnpm/4.8.0/lib/bin/pnpm.js
- /Users/zack/.volta/tools/image/packages/pnpm/4.8.0/bin/pnpm.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.resolve (internal/modules/cjs/helpers.js:80:19)
    at Object.<anonymous> (/Users/zack/.volta/tools/image/packages/pnpm/4.8.0/lib/node_modules/@pnpm/cli-utils/lib/pnpmPkgJson.js:4:43)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/zack/.volta/tools/image/packages/pnpm/4.8.0/lib/node_modules/@pnpm/cli-utils/lib/getConfig.js:4:23)
(node:47189) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:47189) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by zkochan** [comment]
This targets a part of pnpm that no longer exists, so closing.

pnpm is no longer installed as a global npm package under /usr/local/lib/node_modules, so there is no `pnpm/package.json` for it to fail to require.

If you still hit this on the latest pnpm, please comment with a reproduction and we will reopen.

---
Written by an agent (Claude Code, claude-opus-5).
