### ISSUE TITLE
pnpm install breaks in a directory with special characters

### ISSUE THREAD

**Issue by evandrojr** [pnpm/pnpm#2291]
### Code to reproduce the issue:

[gdes_anonimizador (cópia).zip](https://github.com/pnpm/pnpm/files/4117237/gdes_anonimizador.copia.zip)

The same problem happens with NPM

### Expected behavior:

Install the dependencies

### Actual behavior:

Installation breaks

### Additional information:

 - node -v 11.1.0

 - Linux Ubuntu

```

pnpm install
Lockfile is up-to-date, resolution step is skipped
Packages: +102
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Resolving: total 102, reused 102, downloaded 0, done
node_modules/.pnpm/registry.npmjs.org/@ronomon/utimes/2.3.1/node_modules/@ronomon/utimes: Running install script, failed in 843ms
.../2.3.1/node_modules/@ronomon/utimes install$ node-gyp rebuild
│ gyp info it worked if it ends with ok
│ gyp info using node-gyp@6.1.0
│ gyp info using node@11.1.0 | linux | x64
│ gyp info find Python using Python version 3.6.9 found at "/usr/bin/python3"
│ gyp info spawn /usr/bin/python3
│ gyp info spawn args [ '/home/93274300500/.nvm/versions/node/v11.1.0/lib/node_modules/pnpm/lib/node_modules/node-gyp/gyp/gyp_main.py',
│ gyp info spawn args   'binding.gyp',
│ gyp info spawn args   '-f',
│ gyp info spawn args   'make',
│ gyp info spawn args   '-I',
│ gyp info spawn args   '/home/93274300500/lab/gdes_anonimizador (cópia)/node_modules/.pnpm/registry.npmjs.org/@ronomon/utimes/2.3.1/node_mo
│ gyp info spawn args   '-I',
│ gyp info spawn args   '/home/93274300500/.nvm/versions/node/v11.1.0/lib/node_modules/pnpm/lib/node_modules/node-gyp/addon.gypi',
│ gyp info spawn args   '-I',
│ gyp info spawn args   '/home/93274300500/.cache/node-gyp/11.1.0/include/node/common.gypi',
│ gyp info spawn args   '-Dlibrary=shared_library',
│ gyp info spawn args   '-Dvisibility=default',
│ gyp info spawn args   '-Dnode_root_dir=/home/93274300500/.cache/node-gyp/11.1.0',
│ gyp info spawn args   '-Dnode_gyp_dir=/home/93274300500/.nvm/versions/node/v11.1.0/lib/node_modules/pnpm/lib/node_modules/node-gyp',
│ gyp info spawn args   '-Dnode_lib_file=/home/93274300500/.cache/node-gyp/11.1.0/<(target_arch)/node.lib',
│ gyp info spawn args   '-Dmodule_root_dir=/home/93274300500/lab/gdes_anonimizador (cópia)/node_modules/.pnpm/registry.npmjs.org/@ronomon/ut
│ gyp info spawn args   '-Dnode_engine=v8',
│ gyp info spawn args   '--depth=.',
│ gyp info spawn args   '--no-parallel',
│ gyp info spawn args   '--generator-output',
│ gyp info spawn args   'build',
│ gyp info spawn args   '-Goutput_dir=.' ]
│ gyp info spawn make
│ gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
│ make: Entering directory '/home/93274300500/lab/gdes_anonimizador (cópia)/node_modules/.pnpm/registry.npmjs.org/@ronomon/utimes/2.3.1/node
│   CXX(target) Release/obj.target/binding/binding.o
│ ../binding.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE utimes(Nan::NAN_METHOD_ARGS_TYPE)’:
│ ../binding.cc:151:46: warning: ‘uint32_t v8::Value::Uint32Value() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
│    const uint8_t flags = info[1]->Uint32Value();
│                                               ^
│ In file included from /home/93274300500/.cache/node-gyp/11.1.0/include/node/v8.h:26:0,
│                  from /home/93274300500/.cache/node-gyp/11.1.0/include/node/node.h:63,
│                  from ../../../../../../../nan/2.14.0/node_modules/nan/nan.h:54,
│                  from ../binding.cc:1:
│ /home/93274300500/.cache/node-gyp/11.1.0/include/node/v8.h:2571:47: note: declared here
│    V8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
│                                                ^
│ /home/93274300500/.cache/node-gyp/11.1.0/include/node/v8config.h:326:3: note: in definition of macro ‘V8_DEPRECATED’
│    declarator __attribute__((deprecated(message)))
│    ^~~~~~~~~~
│ ../binding.cc:152:48: warning: ‘int64_t v8::Value::IntegerValue() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
│    const uint64_t btime = info[2]->IntegerValue();
│                                                 ^
│ In file included from /home/93274300500/.cache/node-gyp/11.1.0/include/node/v8.h:26:0,
│                  from /home/93274300500/.cache/node-gyp/11.1.0/include/node/node.h:63,
│                  from ../../../../../../../nan/2.14.0/node_modules/nan/nan.h:54,
│                  from ../binding.cc:1:
│ /home/93274300500/.cache/node-gyp/11.1.0/include/node/v8.h:2570:46: note: declared here
│    V8_DEPRECATED("Use maybe version", int64_t IntegerValue() const);
│                                               ^
│ /home/93274300500/.cache/node-gyp/11.1.0/include/node/v8config.h:326:3: note: in definition of macro ‘V8_DEPRECATED’
│    declarator __attribute__((deprecated(message)))
│    ^~~~~~~~~~
│ ../binding.cc:153:48: warning: ‘int64_t v8::Value::IntegerValue() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
│    const uint64_t mtime = info[3]->IntegerValue();
│                                                 ^
│ In file included from /home/93274300500/.cache/node-gyp/11.1.0/include/node/v8.h:26:0,
│                  from /home/93274300500/.cache/node-gyp/11.1.0/include/node/node.h:63,
│                  from ../../../../../../../nan/2.14.0/node_modules/nan/nan.h:54,
│                  from ../binding.cc:1:
│ /home/93274300500/.cache/node-gyp/11.1.0/include/node/v8.h:2570:46: note: declared here
│    V8_DEPRECATED("Use maybe version", int64_t IntegerValue() const);
│                                               ^
│ /home/93274300500/.cache/node-gyp/11.1.0/include/node/v8config.h:326:3: note: in definition of macro ‘V8_DEPRECATED’
│    declarator __attribute__((deprecated(message)))
│    ^~~~~~~~~~
│ ../binding.cc:154:48: warning: ‘int64_t v8::Value::IntegerValue() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
│    const uint64_t atime = info[4]->IntegerValue();
│                                                 ^
│ In file included from /home/93274300500/.cache/node-gyp/11.1.0/include/node/v8.h:26:0,
│                  from /home/93274300500/.cache/node-gyp/11.1.0/include/node/node.h:63,
│                  from ../../../../../../../nan/2.14.0/node_modules/nan/nan.h:54,
│                  from ../binding.cc:1:
│ /home/93274300500/.cache/node-gyp/11.1.0/include/node/v8.h:2570:46: note: declared here
│    V8_DEPRECATED("Use maybe version", int64_t IntegerValue() const);
│                                               ^
│ /home/93274300500/.cache/node-gyp/11.1.0/include/node/v8config.h:326:3: note: in definition of macro ‘V8_DEPRECATED’
│    declarator __attribute__((deprecated(message)))
│    ^~~~~~~~~~
│   SOLINK_MODULE(target) Release/obj.target/binding.node
│   COPY Release/binding.node
│   COPY /home/93274300500/lab/gdes_anonimizador (cópia)/node_modules/.pnpm/registry.npmjs.org/@ronomon/utimes/2.3.1/node_modules/@ronomon/u
│ /bin/sh: 1: Syntax error: "(" unexpected
│ make: *** [/home/93274300500/lab/gdes_anonimizador (cópia)/node_modules/.pnpm/registry.npmjs.org/@ronomon/utimes/2.3.1/node_modules/@ronom
│ copy.target.mk:8: recipe for target '/home/93274300500/lab/gdes_anonimizador (cópia)/node_modules/.pnpm/registry.npmjs.org/@ronomon/utimes
│ make: Leaving directory '/home/93274300500/lab/gdes_anonimizador (cópia)/node_modules/.pnpm/registry.npmjs.org/@ronomon/utimes/2.3.1/node_
│ gyp ERR! build error 
│ gyp ERR! stack Error: `make` failed with exit code: 2
│ gyp ERR! stack     at ChildProcess.onExit (/home/93274300500/.nvm/versions/node/v11.1.0/lib/node_modules/pnpm/lib/node_modules/node-gyp/li
│ gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
│ gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
│ gyp ERR! System Linux 4.15.0-72-generic
│ gyp ERR! command "/home/93274300500/.nvm/versions/node/v11.1.0/bin/node" "/home/93274300500/.nvm/versions/node/v11.1.0/lib/node_modules/pn
│ gyp ERR! cwd /home/93274300500/lab/gdes_anonimizador (cópia)/node_modules/.pnpm/registry.npmjs.org/@ronomon/utimes/2.3.1/node_modules/@ron
│ gyp ERR! node -v v11.1.0
│ gyp ERR! node-gyp -v v6.1.0
│ gyp ERR! not ok 
└─ Failed in 843ms
 ERROR  Command failed with exit code 1.

```

**Comment by mcmxcdev** [comment]
Why do you think that this is related to special characters? If I rename the folder from `gdes_anonimizador (cópia)` to `gdes_anonimizador`, it still fails.

The failure is due to `node-gyp rebuild` if you ask me. 

node -v v16.17.1
node-gyp -v v9.2.0

**Comment by zkochan** [comment]
This no longer reproduces on current pnpm, so closing.

Verified on pnpm 12.5.1 in a directory named "spec (cópia) & ç": install and `pnpm run` both work.

If you still hit this on the latest pnpm, please comment with a reproduction and we will reopen.

---
Written by an agent (Claude Code, claude-opus-5).
