### ISSUE TITLE
Installation to non-standard path doesn't work

### ISSUE THREAD

**Issue by yannayl** [pnpm/pnpm#2302]
### pnpm version:
4.8.0

### Code to reproduce the issue:
```bash
## on ubuntu 18.04
mkdir /tmp/something
mkdir /tmp/somethig_bin
curl -L https://unpkg.com/@pnpm/self-installer | PNPM_DEST=/tmp/something PNPM_BIN_DEST=/tmp/somethig_bin node
/tmp/somethig_bin/pnpm -v
```
output:
```
(node:12036) UnhandledPromiseRejectionWarning: Error: Cannot find module 'pnpm/package.json'
Require stack:
- /tmp/something/lib/node_modules/@pnpm/cli-utils/lib/pnpmPkgJson.js
- /tmp/something/lib/node_modules/@pnpm/cli-utils/lib/getConfig.js
- /tmp/something/lib/node_modules/@pnpm/cli-utils/lib/index.js
- /tmp/something/lib/bin/pnpm.js
- /tmp/something/bin/pnpm.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:17)
    at Function.resolve (internal/modules/cjs/helpers.js:78:19)
    at Object.<anonymous> (/tmp/something/lib/node_modules/@pnpm/cli-utils/lib/pnpmPkgJson.js:4:43)
    at Module._compile (internal/modules/cjs/loader.js:1139:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1159:10)
    at Module.load (internal/modules/cjs/loader.js:988:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/tmp/something/lib/node_modules/@pnpm/cli-utils/lib/getConfig.js:4:23)
(node:12036) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:12036) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Expected behavior:
_pnpm_ installs successfully

### Actual behavior:
_pnpm_ cli is broken. `@pnpm/cli-utils` assumes the _pnpm_ package is in the `require.resolve` default paths and since this assumption does not hold, the resolution fails.

### Additional information:
node version: v13.5.0
Ubuntu 18.04

**Comment by zkochan** [comment]
Related https://github.com/pnpm/pnpm/issues/2273
