### ISSUE TITLE
pnpm does not install devDependencies before executing prepare script

### ISSUE THREAD

**Issue by yannayl** [pnpm/pnpm#2348]
pnpm fails to install devDependencies and execute `prepare` script when installing a dependency.
I have created a [repro repository](/yannayl/pnpm_prepare.git) which uses `rollup` in the prepare script to create a bundled version.
Adding this repository as  a dependency fails.

### pnpm version:
4.9.3

### Code to reproduce the issue:
The following commands fail:
```bash
cd $(mktemp -d)
pnpm init -y
pnpm add git+https://github.com/yannayl/pnpm_prepare.git
```

Whereas the `npm` equivalent works:
```bash
cd $(mktemp -d)
npm init -y
npm add git+https://github.com/yannayl/pnpm_prepare.git
```

pnpm-debug.log:
```
{
  "0 debug pnpm:scope": {
    "selected": 1
  },
  "1 debug pnpm": {
    "isCaseSensitive": true,
    "store": "/home/yannayl/.pnpm-store/2"
  },
  "2 debug pnpm:package-manifest": {
    "initial": {
      "name": "tmp.MAehyzdFi2",
      "version": "1.0.0",
      "description": "",
      "main": "index.js",
      "scripts": {
        "test": "echo \"Error: no test specified\" && exit 1"
      },
      "keywords": [],
      "author": "",
      "license": "ISC"
    },
    "prefix": "/tmp/tmp.MAehyzdFi2"
  },
  "3 debug pnpm:stage": {
    "prefix": "/tmp/tmp.MAehyzdFi2",
    "stage": "resolution_started"
  },
  "4 debug pnpm:_dependency_resolved": {
    "resolution": "github.com/yannayl/pnpm_prepare/22ae5f1f17c18f826f69c9e8de0b39d8c0841948",
    "wanted": {
      "rawSpec": "git+https://github.com/yannayl/pnpm_prepare.git"
    }
  },
  "5 debug pnpm:progress": {
    "packageId": "github.com/yannayl/pnpm_prepare/22ae5f1f17c18f826f69c9e8de0b39d8c0841948",
    "requester": "/tmp/tmp.MAehyzdFi2",
    "status": "resolved"
  },
  "6 debug pnpm:progress": {
    "packageId": "github.com/yannayl/pnpm_prepare/22ae5f1f17c18f826f69c9e8de0b39d8c0841948",
    "requester": "/tmp/tmp.MAehyzdFi2",
    "status": "found_in_store"
  },
  "7 debug pnpm:stage": {
    "prefix": "/tmp/tmp.MAehyzdFi2",
    "stage": "resolution_done"
  },
  "8 debug pnpm:package-manifest": {
    "prefix": "/tmp/tmp.MAehyzdFi2",
    "updated": {
      "name": "tmp.MAehyzdFi2",
      "version": "1.0.0",
      "description": "",
      "main": "index.js",
      "scripts": {
        "test": "echo \"Error: no test specified\" && exit 1"
      },
      "keywords": [],
      "author": "",
      "license": "ISC",
      "dependencies": {
        "pnpm_prepare": "github:yannayl/pnpm_prepare"
      }
    }
  },
  "9 debug pnpm:stats": {
    "prefix": "/tmp/tmp.MAehyzdFi2",
    "removed": 0
  },
  "10 debug pnpm:stage": {
    "prefix": "/tmp/tmp.MAehyzdFi2",
    "stage": "importing_started"
  },
  "11 debug pnpm:stats": {
    "added": 1,
    "prefix": "/tmp/tmp.MAehyzdFi2"
  },
  "12 debug pnpm:importing": {
    "from": "/home/yannayl/.pnpm-store/2/github.com/yannayl/pnpm_prepare/22ae5f1f17c18f826f69c9e8de0b39d8c0841948/node_modules/pnpm_prepare",
    "to": "/tmp/tmp.MAehyzdFi2/node_modules/.pnpm/github.com/yannayl/pnpm_prepare/22ae5f1f17c18f826f69c9e8de0b39d8c0841948/node_modules/pnpm_prepare",
    "method": "clone"
  },
  "13 debug pnpm:importing": {
    "from": "/home/yannayl/.pnpm-store/2/github.com/yannayl/pnpm_prepare/22ae5f1f17c18f826f69c9e8de0b39d8c0841948/node_modules/pnpm_prepare",
    "to": "/tmp/tmp.MAehyzdFi2/node_modules/.pnpm/github.com/yannayl/pnpm_prepare/22ae5f1f17c18f826f69c9e8de0b39d8c0841948/node_modules/pnpm_prepare",
    "method": "hardlink"
  },
  "14 debug pnpm:stage": {
    "prefix": "/tmp/tmp.MAehyzdFi2",
    "stage": "importing_done"
  },
  "15 debug pnpm:link": {
    "target": "/tmp/tmp.MAehyzdFi2/node_modules/.pnpm/github.com/yannayl/pnpm_prepare/22ae5f1f17c18f826f69c9e8de0b39d8c0841948/node_modules/pnpm_prepare",
    "link": "/tmp/tmp.MAehyzdFi2/node_modules/pnpm_prepare"
  },
  "16 debug pnpm:root": {
    "added": {
      "dependencyType": "prod",
      "id": "github.com/yannayl/pnpm_prepare/22ae5f1f17c18f826f69c9e8de0b39d8c0841948",
      "name": "pnpm_prepare",
      "realName": "pnpm_prepare",
      "version": "1.0.0"
    },
    "prefix": "/tmp/tmp.MAehyzdFi2"
  },
  "17 debug pnpm:lifecycle": {
    "depPath": "github.com/yannayl/pnpm_prepare/22ae5f1f17c18f826f69c9e8de0b39d8c0841948",
    "optional": false,
    "script": "rollup -c",
    "stage": "prepare",
    "wd": "/tmp/tmp.MAehyzdFi2/node_modules/.pnpm/github.com/yannayl/pnpm_prepare/22ae5f1f17c18f826f69c9e8de0b39d8c0841948/node_modules/pnpm_prepare"
  },
  "18 debug pnpm:lifecycle": {
    "depPath": "github.com/yannayl/pnpm_prepare/22ae5f1f17c18f826f69c9e8de0b39d8c0841948",
    "line": "sh: 1: rollup: not found",
    "stage": "prepare",
    "stdio": "stderr",
    "wd": "/tmp/tmp.MAehyzdFi2/node_modules/.pnpm/github.com/yannayl/pnpm_prepare/22ae5f1f17c18f826f69c9e8de0b39d8c0841948/node_modules/pnpm_prepare"
  },
  "19 error pnpm": {
    "message": {
      "code": "ELIFECYCLE",
      "errno": "ENOENT",
      "syscall": "spawn",
      "file": "sh",
      "pkgid": "pnpm_prepare@1.0.0",
      "stage": "prepare",
      "script": "rollup -c",
      "pkgname": "pnpm_prepare"
    },
    "err": {
      "name": "Error",
      "message": "pnpm_prepare@1.0.0 prepare: `rollup -c`\nspawn ENOENT",
      "code": "ELIFECYCLE",
      "stack": "Error: pnpm_prepare@1.0.0 prepare: `rollup -c`\nspawn ENOENT\n    at ChildProcess.<anonymous> (/home/yannayl/.node_modules/pnpm/lib/node_modules/@zkochan/npm-lifecycle/lib/spawn.js:48:18)\n    at ChildProcess.emit (events.js:321:20)\n    at maybeClose (internal/child_process.js:1026:16)\n    at Socket.<anonymous> (internal/child_process.js:441:11)\n    at Socket.emit (events.js:321:20)\n    at Pipe.<anonymous> (net.js:668:12)"
    }
  }
}
```

### Expected behavior:
Installation succeeds.
Specifically, the devDependencies of the installed package (rollup) are installed and then the prepare script executes.

### Actual behavior:
Installation fails.

### Additional information:
See npm-scripts documentation: https://docs.npmjs.com/misc/scripts#prepublish-and-prepare

 - `node -v` prints:
v13.7.0
 - Windows, OS X, or Linux?:
Ubuntu 18.04

**Comment by zkochan** [comment]
There's already an issue for this: #855

**Comment by yannayl** [comment]
Sorry, missed it. Closing
