### ISSUE TITLE
Facing a problem while developing nativescript app 

### ISSUE THREAD

**Issue by yus-ham** [pnpm/pnpm#2350]
Sample apps: https://market.nativescript.org/?tab=samples&framework=all_frameworks&category=all_samples

 ### pnpm version:
4.9.3

### Code to reproduce the issue:
`pnpm i -f --shamefully-hoist`
```
 WARN  using --force I sure hope you know what you are doing
Lockfile is up-to-date, resolution step is skipped
Packages: +659
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Resolving: total 659, reused 659, downloaded 0, done
node_modules/.pnpm/registry.npmjs.org/ejs/2.7.4/node_modules/ejs: Running postinstall script, done in 59s
node_modules/.pnpm/registry.npmjs.org/@nativescript/core/6.3.1/node_modules/@nativescript/core: Running postinstall script, done in 60s
node_modules/.pnpm/registry.npmjs.org/fsevents/1.2.11/node_modules/fsevents: Running install script, done in 1m
node_modules/.pnpm/registry.npmjs.org/kinvey-nativescript-sdk/4.2.5_tns-core-modules@6.3.1/node_modules/kinvey-nativescript-sdk: Running postinstall script, done in 225ms
node_modules/.pnpm/registry.npmjs.org/nativescript-dev-webpack/1.4.0/node_modules/nativescript-dev-webpack: Running postinstall script, done in 268ms
```
installation success while next run `tns run android`
```
Searching for devices...
Your application will be deployed only on the device specified by the provided index or identifier.
Preparing project...
/media/xubuncup/ntfsd/cup/www/nodejs/tns/js-carousel/node_modules/webpack-cli/bin/cli.js:244
				throw err;
				^

TypeError: Cannot set property 'dynamicImport' of undefined
    at injectDynamicImport (/media/xubuncup/ntfsd/cup/www/nodejs/tns/js-carousel/node_modules/acorn-dynamic-import/lib/inject.js:29:31)
    at Object.<anonymous> (/media/xubuncup/ntfsd/cup/www/nodejs/tns/js-carousel/node_modules/acorn-dynamic-import/lib/index.js:17:46)
    at Module._compile (/media/xubuncup/ntfsd/cup/www/nodejs/tns/js-carousel/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (/media/xubuncup/ntfsd/cup/www/nodejs/tns/js-carousel/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/media/xubuncup/ntfsd/cup/www/nodejs/tns/js-carousel/node_modules/webpack/lib/Parser.js:9:15)
    at Module._compile (/media/xubuncup/ntfsd/cup/www/nodejs/tns/js-carousel/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (/media/xubuncup/ntfsd/cup/www/nodejs/tns/js-carousel/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/media/xubuncup/ntfsd/cup/www/nodejs/tns/js-carousel/node_modules/webpack/lib/JavascriptModulesPlugin.js:7:16)
    at Module._compile (/media/xubuncup/ntfsd/cup/www/nodejs/tns/js-carousel/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (/media/xubuncup/ntfsd/cup/www/nodejs/tns/js-carousel/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/media/xubuncup/ntfsd/cup/www/nodejs/tns/js-carousel/node_modules/webpack/lib/WebpackOptionsApply.js:9:33)
    at Module._compile (/media/xubuncup/ntfsd/cup/www/nodejs/tns/js-carousel/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (/media/xubuncup/ntfsd/cup/www/nodejs/tns/js-carousel/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/media/xubuncup/ntfsd/cup/www/nodejs/tns/js-carousel/node_modules/webpack/lib/webpack.js:10:29)
Executing webpack failed with exit code 1.
```
### Additional information:
 - no error with `npm install` 
 - `node -v` prints: v13.7.0
 - OS: ubuntu 18.04
 - The result package `acorn` (in folder `.pnpm/registry.npmjs.org/acorn`) has two version :
    - 5.7.3 required by webpack | acorn-dynamyc-import
    - 6.4.0 required by webpack-bundle-analyzer
 - webpack or acorn-dynamyc-import seem resolves acorn to version 6.4.0 ( node_modules/acorn symlinked to .pnpm/registry.npmjs.org/acorn/6.4.0/node_modules/acorn ).
- My temporary solution is to ` rm node_modules/acorn && ln -s .pnpm/registry.npmjs.org/acorn/5.7.3/node_modules/acorn node_modules/acorn` after installation or use `npm install` instead.

**Comment by zkochan** [comment]
Use [node-linker=hoisted](https://pnpm.io/npmrc#node-linker) if nothing else helps.
