### ISSUE TITLE
pnpm 4.9.3 stops silently in iterm2 with quite narrow width

### ISSUE THREAD

**Issue by freewind** [pnpm/pnpm#2353]
### pnpm version:

pnpm 4.9.3

### Code to reproduce the issue:

open iterm2, adjust the width to be very narrow, e.g. less than 200px or smaller, then run pnpm:

```
/Users/peng.li/workspace/uc-frontend/.pnpm/4.9.3/bin/pnpm.js -h
```

or any other commands other than `-v`

```
/Users/peng.li/workspace/uc-frontend/.pnpm/4.9.3/bin/pnpm.js i
```

### Expected behavior:

pnpm prints help or print output of that command

### Actual behavior:

Outputs nothing and does nothing, stops silently.

### Additional information:

 - `node -v` prints: `v12.12.0`
 - Windows, OS X, or Linux?: OS X

I actually found the problem. I edited `.pnpm/4.9.3/lib/bin/pnpm.js`, added a line to print the thrown errors in `runPnpm`:

```
async function runPnpm() {
    const errorHandler = (await Promise.resolve().then(() => require('../err'))).default;
    try {
        const main = (await Promise.resolve().then(() => require('../main'))).default;
        await main(argv);
    }
    catch (err) {
        console.log(err);  // !!!! added this line to print error to console
        errorHandler(err);
    }
}

```

And the error is:

```
$/Users/peng.li/workspace/uc-frontend/.pnpm/4.9.3/bin/pnpm.js i
Error: Column width must be greater than 0.
    at calculateCellHeight (/Users/peng.li/workspace/uc-frontend/.pnpm/4.9.3/lib/node_modules/table/dist/calculateCellHeight.js:30:11)
    at /Users/peng.li/workspace/uc-frontend/.pnpm/4.9.3/lib/node_modules/table/dist/calculateRowHeightIndex.js:39:66
    at Array.forEach (<anonymous>)
    at /Users/peng.li/workspace/uc-frontend/.pnpm/4.9.3/lib/node_modules/table/dist/calculateRowHeightIndex.js:30:11
    at Array.forEach (<anonymous>)
    at calculateRowHeightIndex (/Users/peng.li/workspace/uc-frontend/.pnpm/4.9.3/lib/node_modules/table/dist/calculateRowHeightIndex.js:28:8)
    at Object.table (/Users/peng.li/workspace/uc-frontend/.pnpm/4.9.3/lib/node_modules/table/dist/table.js:100:63)
    at renderDescriptionList (/Users/peng.li/workspace/uc-frontend/.pnpm/4.9.3/lib/node_modules/render-help/lib/index.js:38:30)
    at renderHelp (/Users/peng.li/workspace/uc-frontend/.pnpm/4.9.3/lib/node_modules/render-help/lib/index.js:68:49)
    at Object.help (/Users/peng.li/workspace/uc-frontend/.pnpm/4.9.3/lib/node_modules/@pnpm/plugin-commands-listing/lib/list.js:30:12)
```

Seems like the iterm2 window is too narrow that makes internal table calculation break, and the error is caught silently.

![image](https://user-images.githubusercontent.com/333781/74135945-33d19f00-4c28-11ea-97fb-cb1843234a8b.png)

(my monitor resolution is 1680x1050)

**Comment by zkochan** [comment]
fixed in 4.10.0-1
