### ISSUE TITLE
`string.prototype.padstart` missing

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#2460]
```
Error: Cannot find module 'string.prototype.padstart'
Require stack:
- /Users/Vaughan/dev-live/pnpm/packages/default-reporter/lib/reporterForClient.js
- /Users/Vaughan/dev-live/pnpm/packages/default-reporter/lib/index.js
- /Users/Vaughan/dev-live/pnpm/packages/pnpm/lib/reporter/index.js
- /Users/Vaughan/dev-live/pnpm/packages/pnpm/lib/main.js
- /Users/Vaughan/dev-live/pnpm/packages/pnpm/lib/bin/pnpm.js
- /Users/Vaughan/dev-live/pnpm/packages/pnpm/bin/pnpm.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:17)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/Vaughan/dev-live/pnpm/packages/default-reporter/lib/reporterForClient.js:13:18)
    at Module._compile (internal/modules/cjs/loader.js:1139:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1159:10)
    at Module.load (internal/modules/cjs/loader.js:988:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1028:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/Vaughan/dev-live/pnpm/packages/default-reporter/lib/reporterForClient.js',
    '/Users/Vaughan/dev-live/pnpm/packages/default-reporter/lib/index.js',
    '/Users/Vaughan/dev-live/pnpm/packages/pnpm/lib/reporter/index.js',
    '/Users/Vaughan/dev-live/pnpm/packages/pnpm/lib/main.js',
    '/Users/Vaughan/dev-live/pnpm/packages/pnpm/lib/bin/pnpm.js',
    '/Users/Vaughan/dev-live/pnpm/packages/pnpm/bin/pnpm.js'
  ]
}
```

**Comment by vjpr** [comment]
I think this is because `default-reporter/lib` was not being cleaned.

**Comment by zkochan** [comment]
Have you tried with a clean repo? Try to clean it with `git clean -fdx` and then reinstall the deps

**Comment by vjpr** [comment]
Thanks that was the command I was looking for.
