### ISSUE TITLE
Cannot use pnpm@alpha (v5)

### ISSUE THREAD

**Issue by rfestag** [pnpm/pnpm#2539]
I haven't been able to get the v5 alpha to work at all. Commands that pass through to npm seem to work (like `pnpm init`), but commands that are handled by pnpm (run, add, etc) have failed for me, always giving me the same error regarding no valid main export for the `uuid` dependency. I have to run `npx pnpm@4.14.2 i -g pnpm` to get back to a working install of pnpm.  Below is a simple example of trying to install `react` into a clean project.

### pnpm version:
5.0.0-alpha.5

### Code to reproduce the issue:

```bash
pnpm i -g pnpm@alpha
mkdir test
cd test
pnpm init -y
pnpm add react
```

### Expected behavior:

pnpm v5 will install the `react` library

### Actual behavior:

_Note: I placed my actual home directory with [homedir] below_

```
Error: No valid exports main found for '[homedir]/.nvm/versions/node/v13.6.0/pnpm-global/3/node_modules/.pnpm/registry.npmjs.org/pnpm/5.0.0-alpha.5/node_modules/pnpm/lib/node_modules/uuid'
    at resolveExportsTarget (internal/modules/cjs/loader.js:625:9)
    at applyExports (internal/modules/cjs/loader.js:502:14)
    at resolveExports (internal/modules/cjs/loader.js:551:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:657:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:960:27)
    at Function.Module._load (internal/modules/cjs/loader.js:855:27)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> ([homedir]/.nvm/versions/node/v13.6.0/pnpm-global/3/node_modules/.pnpm/registry.npmjs.org/pnpm/5.0.0-alpha.5/node_modules/pnpm/lib/node_modules/@pnpm/server/lib/connectStoreController.js:6:14)
    at Module._compile (internal/modules/cjs/loader.js:1144:30) {
  code: 'MODULE_NOT_FOUND'
}

```
### Additional information:

 - `node -v` prints: 13.6.0
 - Windows, OS X, or Linux?: Linux

**Comment by zkochan** [comment]
Seems like an issue with Node.js.

I reproduced it with 13.6.0 but it works fine with 13.14

I'd recommend to update Node.js

**Comment by rfestag** [comment]
Good to know, that worked. Thanks! I also confirmed that works in 13.7.0, so it looks like I just happened to be using the last version that didn't work =P
