### ISSUE TITLE
PNPM Broken Systemwide

### ISSUE THREAD

**Issue by dresch86** [pnpm/pnpm#2600]
### Code to reproduce the issue:
Try running pnpm i -g pnpm or any pnpm command fails with the below....
```
Error: Package exports for 'C:\Users\Me\AppData\Roaming\npm\node_modules\pnpm\lib\node_modules\uuid' do not define a valid '.' target
    at resolveExportsTarget (internal/modules/cjs/loader.js:545:13)
    at applyExports (internal/modules/cjs/loader.js:459:14)
    at resolveExports (internal/modules/cjs/loader.js:508:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:577:20)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:879:27)
    at Function.Module._load (internal/modules/cjs/loader.js:785:27)
    at Module.require (internal/modules/cjs/loader.js:956:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\Me\AppData\Roaming\npm\node_modules\pnpm\lib\node_modules\@pnpm\server\lib\connectStoreController.js:6:14)
    at Module._compile (internal/modules/cjs/loader.js:1063:30) {
  code: 'MODULE_NOT_FOUND'
}
```

### Expected behavior:
Command should update PNPM or install package

### Actual behavior:
MODULE_NOT_FOUND error

### Additional information:

 - `node -v` prints: v13.1.0
 - **Windows**, OS X, or Linux?:

I tried uninstalling and then reinstalling PNPM but I still have the same problem.

**Comment by zkochan** [comment]
We should add a meaningful error but this Node version is pretty old and we don't support it.

You may update to the latest minor of v13 or to v14

v10 is also supported since v10.13

**Comment by dresch86** [comment]
@zkochan Thanks! I updated to 14 and everything seems to work now.
