### ISSUE TITLE
pnpm & npm different install behavior behind corporate proxy

### ISSUE THREAD

**Issue by the-constant** [pnpm/pnpm#2650]
### pnpm version:
5.2.3

### Code to reproduce the issue:

 - package.json:

`{
    "dependencies": {
        "webpack": "^4.43.0"
    }
}`

 - ~/.npmrc:

`strict-ssl=false`
`registry=http://registry.npmjs.org/`
`proxy=http://<user>:<password>@proxy.company.com:<port>/`
`https_proxy=http://<user>:<password>@proxy.company.com:<port>/`
`config=proxy`

 - command:

`pnpm install webpack`

### Expected behavior:

`pnpm install webpack` installs the webpack package to a monorepo root's `node_modules` folder.

### Actual behavior:

`pnpm install webpack` fails to find `.tgz` in https://registry.npmjs.org/ with the following error:

WARN GET https://registry.npmjs.org/webpack/-/webpack-4.43.0.tgz error (ENOTFOUND). Will Retry in 10 seconds. 2 retries left.

Continued automated retries fail to find the package.

`npm install webpack` installs the package successfully.

_(It looks like pnpm is not using the config in ~/.npmrc)_

### Additional information:

 - `node -v` prints:  v12.16.1
 - Windows, OS X, or Linux?:  Windows

**Comment by zkochan** [comment]
Try to change the `https_proxy` setting to `https-proxy`

**Comment by the-constant** [comment]
Just tried with `https-proxy` and I'm still facing the same issue. Using `npm install webpack` is working fine just now, but `pnpm install webpack` yields the `ENOTFOUND` error again.

**Comment by zkochan** [comment]
Do you have a `pnpm-lock.yaml` present?

**Comment by zkochan** [comment]
I think I have found the issue. I will fix it.

**Comment by the-constant** [comment]
Awesome, thank you! Appreciate the quick turnaround :)

**Comment by zkochan** [comment]
:ship: 5.2.6

**Comment by the-constant** [comment]
@zkochan after downloading 5.2.6 and running pnpm recursive install, I still have the same error message.

This time however, a node_modules folder is made in both the workspace's root and the workspace-a. The workspace-a node_modules contains the actual modules, while there is almost nothing in root's node_modules (which is to be expected since package.json in it does not specify dependencies).

Is this expected?

**Comment by zkochan** [comment]
Do you still have the https-proxy setting or have you changed it back to https_proxy? pnpm currently reads the `https-proxy`. (Seems like npm as well, I checked)

If yes, maybe pnpm fails to read the global config. Try to set those configs in the `.npmrc` file in the root of your workspace

**Comment by the-constant** [comment]
@zkochan yes, I am still using https-proxy. I will try the global .npmrc config in the root of my workspace and let you know how it goes

**Comment by the-constant** [comment]
@zkochan just added the global config and still the same behavior. Seems like it's not using my proxy settings specified in ~/.npmrc. I can try adding it to the .npmrc in the root of the workspace?

**Comment by zkochan** [comment]
if it is a workspace, then try to add `.npmrc` in the same dir where `pnpm-workspace.yaml` is.

**Comment by the-constant** [comment]
@zkochan `.npmrc` in the same directory as `pnpm-workspace.yaml` did not work.

My directory structure:

```
foo/
  pnpm-workspace.yaml
  babel.config.js
  .npmrc
  package.json
  package-lock.json

  bar/
    workspace-a/
      src/
      dist/
      package.json
      package-lock.json
      webpack.common.js
      webpack.dev.js
      webpack.prod.js

    workspace-b/
      src/
      package.json
```

**Comment by the-constant** [comment]
@zkochan so my registry in `.npmrc` is `http://registry.npmjs.org` but the error message from pnpm is `http**s**://registry.npmjs.org`. The error message suggests that pnpm is definitely not using the `.npmrc` file in either `~/.npmrc` or `workspace-root/.npmrc`.

**Comment by the-constant** [comment]
Confirming that **the HTTP_PROXY and HTTPS_PROXY environment variables work**! So the .npmrc files didn't work.

**Comment by zkochan** [comment]
I did some refactoring. Try pnpm v5.2.7

**Comment by aks314** [comment]
Hi, this still seems to be an issue for me.

**pnpm version:**
5.5.13

**Code to reproduce the issue:**

- ~/.npmrc:

```
proxy=http://user%40domain.net:password%40123@proxy.company.com:<port>/
https-proxy=http://user%40domain.net:password%40123@proxy.company.com:<port>/
HTTP_PROXY=http://user%40domain.net:password%40123@proxy.company.com:<port>/
HTTPS_PROXY=http://user%40domain.net:password%40123@proxy.company.com:<port>/
http_proxy=http://user%40domain.net:password%40123@proxy.company.com:<port>/
https_proxy=http://user%40domain.net:password%40123@proxy.company.com:<port>/

```

- command:

`pnpm install gulp`

**Expected behavior:**
pnpm should install gulp and all dependencies

**Actual behavior:**
pnpm install gulp fails with the following error:

` ERROR  GET https://registry.npmjs.org/gulp: Proxy Authentication Required - 407`

All the while npm work without any issue.
It looks like pnpm is not using the config in ~/.npmrc. 
The official PNPM docs say to use environment variables, on using them I still get the same error. Sometimes with different flags the error changes to ENOTFOUND. (Note - I've also tried by encoding @ as %40  in environment variables and changing the case of variable names, no luck)
Hoping that we can use the npmrc config values for pnpm as well. Please confirm if that is not possible/not a priority.


Additional information:

node -v : v10.22.0
npm -v : 6.14.6
Windows 10



**pnpm Debug log:**

`{
  "0 debug pnpm:scope": {
    "selected": 1
  },
  "1 debug pnpm:package-manifest": {
    "initial": {},
    "prefix": "C:\\Users\\username\\AppData\\Roaming\\npm\\pnpm-global\\4"
  },
  "2 debug pnpm:context": {
    "currentLockfileExists": false,
    "storeDir": "C:\\pnpm\\.pnpm-store\\v3",
    "virtualStoreDir": "C:\\Users\\username\\AppData\\Roaming\\npm\\pnpm-global\\4\\node_modules\\.pnpm"
  },
  "3 debug pnpm:stage": {
    "prefix": "C:\\Users\\username\\AppData\\Roaming\\npm\\pnpm-global\\4",
    "stage": "resolution_started"
  },
  "4 error pnpm": {
    "message": {
      "code": "ERR_PNPM_FETCH_407",
      "request": {
        "url": "https://registry.npmjs.org/gulp"
      },
      "response": {
        "size": 0,
        "timeout": 0
      },
      "pkgName": "gulp",
      "pkgsStack": []
    },
    "err": {
      "name": "Error",
      "message": "GET https://registry.npmjs.org/gulp: Proxy Authentication Required - 407",
      "code": "ERR_PNPM_FETCH_407",
      "stack": "Error: GET https://registry.npmjs.org/gulp: Proxy Authentication Required - 407\n    at fromRegistry (C:\\npm\\node_modules\\pnpm\\lib\\node_modules\\@pnpm\\npm-resolver\\lib\\fetch.js:29:15)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
    }
  }
}`

**Comment by nathanhruby** [comment]
I tried to run `pnpm audit` from version 5.7.0 through mitmproxy to take a look at the payload for #2848 and ran into this same issue.  No combination of `https-proxy` in .npmrc or the env vars seem to have any effect 

I did double check with curl to make sure the proxy is working, and it is.

**Comment by SomebodyOdd** [comment]
I have same issue with 6.0.2 version, fresh install.
Command _pnpm config get_ correctly shows me configuration with my proxy and https_proxy (tried https-proxy too), but it looks to me that parameter is ignored or applied partially (because I get 407 Proxy Authentication Required error, but I still get my proxy account banned after some amount of tries, so it possibly at least sends username to a proxy).

npm with that same config works, even with just proxy setting.

This issue is marked with 5.2 milestone, but it's 6.0 already and it seems not fixed. Any news/updates/complications with this? @zkochan

**Comment by SomebodyOdd** [comment]
Okay, I got it solved for me, but it's not exactly convinient thing and, IMO, requires a fix.

I had special characters in my password that needed to be url encoded in .npmrc file. So my proxy string looked something like this 
proxy='http://myusername:AwesomePassword12%21%2A_%23%26%3F@proxy:8080'
Which, when url decoded should mean this password

AwesomePassword12!*_#&?

But it looks like this url encoding doesn't work right with specifically pnpm. NPM didn't have any problems with that and worked fine with same config and url encoded password for months for me.

I hope this info helps with solving this bug, having special characters in my password is something that I'd like to continue doing =)

**Comment by mubaidr** [comment]
This issue still persists fpr me. I am able to use `npm` but `pnpm` fails to connect with same config. 

My config details:

```bash
$ fnm --version
fnm 1.37.1

$ node -v
v22.9.0

$ npm -v
10.8.3

$ pnpm -v
9.11.0

$ pnpm config list
registry=https://registry.npmjs.org/
user-agent=pnpm/9.11.0 npm/? node/v22.9.0 win32 x64

$ npm config list
; node bin location = C:\Users\usr\AppData\Local\fnm_multishells\24140_1727068008437\node.exe
; node version = v22.9.0
; npm local prefix = C:\Users\usr
; npm version = 10.8.3
; cwd = C:\Users\usr\AppData\Local\Programs\Git
; HOME = C:\Users\usr
; Run `npm config ls -l` to show all defaults.
```

My proxy details: 

![Capture](https://github.com/user-attachments/assets/828e37b2-2f34-40aa-b73d-7fb60d2091a8)

```bash
$ pnpm i
WARN  GET https://registry.npmjs.org/tslib/-/tslib-2.4.1.tgz error (ERR_PNPM_FETCH_407). Will retry in 10 seconds. 2 retries left.
```

I am happy to provide more info if required.
