### ISSUE TITLE
run --silent doesn't work

### ISSUE THREAD

**Issue by leandro-manifesto** [pnpm/pnpm#2660]
So I'm trying pnpm out and found out that the `silent` flag simply doesn't work.
I found some issues claiming that similar problems have been fixed way back in the 4.x version but it seems not to be the case.

### Code to reproduce the issue

Minimal source code: https://gist.github.com/leandro-manifesto/fd13d6391976df550d6ce572526b1868

Commands:
```
$ pnpm install
$ pnpm run --silent lint
```

### Expected behavior:
```
/path/to/my-package/index.js
  1:1  error  Unexpected console statement  no-console

✖ 1 problem (1 error, 0 warnings)
```

### Actual behavior:
```

> my-package@0.0.0 lint /path/to/my-package
> eslint --ext .js .


/path/to/my-package/index.js
  1:1  error  Unexpected console statement  no-console

✖ 1 problem (1 error, 0 warnings)

my-package@0.0.0 lint: `eslint --ext .js .`
Exit status 1

Error: my-package@0.0.0 lint: `eslint --ext .js .`
Exit status 1
    at EventEmitter.<anonymous> (/path/to/.nvm/versions/node/v12.16.3/pnpm-global/3/node_modules/.pnpm/registry.npmjs.org/pnpm/5.2.6/node_modules/pnpm/lib/node_modules/@zkochan/npm-lifecycle/index.js:307:16)
    at EventEmitter.emit (events.js:310:20)
    at ChildProcess.<anonymous> (/path/to/.nvm/versions/node/v12.16.3/pnpm-global/3/node_modules/.pnpm/registry.npmjs.org/pnpm/5.2.6/node_modules/pnpm/lib/node_modules/@zkochan/npm-lifecycle/lib/spawn.js:55:14)
    at ChildProcess.emit (events.js:310:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

```

### Additional information:
- Ubuntu 18.04.4 LTS (on WSL, Windows 10 18363.900)
- nvm 0.34.0
- node 12.16.3
- npm 6.14.4
- pnpm 5.2.6 (installed globally with npm)

**Comment by zkochan** [comment]
You want to pass `--silent` to eslint?

In that case you should run `pnpm run lint -- --silent`

**Comment by leandro-manifesto** [comment]
Nope, I want to suppress pnpm's call line and error so that only the command's (`eslint` in this case) output is presented on the console.

**Comment by cyrus-za** [comment]
For anyone stumbling on this old issue (like I just did before checking the docs) the below is probably what @leandro-manifesto was looking for
<img width="999" alt="image" src="https://user-images.githubusercontent.com/1845861/122374920-0e168180-cf63-11eb-8d63-e35119ccb407.png">
