### ISSUE TITLE
Broken lockfile: no entry for ... with disabled lockfile option

### ISSUE THREAD

**Issue by ghost** [pnpm/pnpm#2677]
### pnpm version

5.3.0

### Code to reproduce the issue:

- Disable lockfile via `npm config set lockfile false`
- Run `pnpm install --no-optional` etc as usual
- Call `pnpm prune --prod`

### Expected behavior:

It should prune successfully, without errors about lockfile (which is turned off)

### Actual behavior:

It throws an error and prints:

```
ERROR Broken lockfile: no entry for '...' in pnpm-lock.yaml
```

### Additional information:

 - `node -v` prints: v12.18.0
 - Windows, OS X, or Linux?: Linux\OSX

**Comment by zkochan** [comment]
I couldn't reproduce this. Provide a repro repo, if possible

**Comment by ghaiklor-wix** [comment]
@zkochan it happens randomly, but for some revisions it is indeed reproducible. I'm not sure I'll be able to reproduce this in open repository 🤔 

Conditions are too flaky and I couldn't debug anything useful. I tried to grep debug logs, but `pnpm prune --prod --loglevel debug` prints nothing.

**Comment by zkochan** [comment]
try `pnpm prune --prod --reporter ndjson`.

Also, when pnpm fails, it writes the logs to `node_modules/.pnpm-debug.log`

**Comment by ghaiklor-wix** [comment]
Ok, I'll try `ndjson` with `.pnpm-debug.log` and report back to you. Hope it will help to debug. It is late for today, so I'll be back tomorrow only.

**Comment by ghaiklor-wix** [comment]
Here is what I've found when tried with `ndjson`:

```
{"time":1594370818187,"hostname":"serverless-build-server-796fd49c4b-x57pz","pid":596,"level":"error","name":"pnpm","message":{"code":"ERR_PNPM_LOCKFILE_MISSING_DEPENDENCY","hint":"This issue is probably caused by a badly resolved merge conflict.\nTo fix the lockfile, run 'pnpm install --no-frozen-lockfile'."},"err":{"name":"Error","message":"Broken lockfile: no entry for 'repo.dev.wixpress.com/dtrace-provider/0.8.8' in pnpm-lock.yaml","code":"ERR_PNPM_LOCKFILE_MISSING_DEPENDENCY","stack":"Error: Broken lockfile: no entry for 'repo.dev.wixpress.com/dtrace-provider/0.8.8' in pnpm-lock.yaml\n    at pkgAllDeps (/usr/local/lib/node_modules/pnpm/lib/node_modules/@pnpm/filter-lockfile/lib/filterLockfileByImporters.js:34:19)\n    at pkgAllDeps (/usr/local/lib/node_modules/pnpm/lib/node_modules/@pnpm/filter-lockfile/lib/filterLockfileByImporters.js:30:9)\n    at pkgAllDeps (/usr/local/lib/node_modules/pnpm/lib/node_modules/@pnpm/filter-lockfile/lib/filterLockfileByImporters.js:30:9)\n    at pkgAllDeps (/usr/local/lib/node_modules/pnpm/lib/node_modules/@pnpm/filter-lockfile/lib/filterLockfileByImporters.js:30:9)\n    at Object.filterByImporters [as filterLockfileByImporters] (/usr/local/lib/node_modules/pnpm/lib/node_modules/@pnpm/filter-lockfile/lib/filterLockfileByImporters.js:12:9)\n    at Object.linkPackages [as default] (/usr/local/lib/node_modules/pnpm/lib/node_modules/supi/lib/install/link.js:105:50)\n    at async installInContext (/usr/local/lib/node_modules/pnpm/lib/node_modules/supi/lib/install/index.js:495:20)\n    at async _install (/usr/local/lib/node_modules/pnpm/lib/node_modules/supi/lib/install/index.js:292:24)\n    at async Object.mutateModules (/usr/local/lib/node_modules/pnpm/lib/node_modules/supi/lib/install/index.js:67:20)"}}
```

**Comment by ghaiklor-wix** [comment]
Welp, I think I found a possible culprit.
At first, everything is ok, debug logs has a lot of `progress` and `dependency_resolved` statuses. Nothing suspicious.

But then, it starts printing out:

```
"3753 debug pnpm:skipped-optional-dependency": {
    "details": "Error: No package.json (or package.yaml, or package.json5) was found in ".../dtrace-provider/0.8.8".,
    "package": {
      "name": "dtrace-provider",
      "pref": ".../dtrace-provider/0.8.8",
      "version": ".../dtrace-provider/0.8.8"
    },
```

And the similar ones... Afterwards, it prints `resolution_done` and starts printing out that those optional dependencies that were errored before are not able to find in lockfile (I have disabled lockfile):

```
Cannot find resolution of .../dtrace-provider/0.8.8 in lockfile
Cannot find resolution of .../uglify-js/3.10.0 in lockfile
...
```

Next step is `pnpm prune --prod` which is going smooth with a lot of `removal` steps until this is happening and exits:

```
"5450 debug pnpm:stage": {
    "prefix": "...",
    "stage": "importing_started"
  },
  "5451 error pnpm": {
    "message": {
      "code": "ERR_PNPM_LOCKFILE_MISSING_DEPENDENCY",
      "hint": "This issue is probably caused by a badly resolved merge conflict.\nTo fix the lockfile, run 'pnpm install --no-frozen-lockfile'."
    },
    "err": {
      "name": "Error",
      "message": "Broken lockfile: no entry for '.../dtrace-provider/0.8.8' in pnpm-lock.yaml",
      "code": "ERR_PNPM_LOCKFILE_MISSING_DEPENDENCY",
      "stack": "Error: Broken lockfile: no entry for '.../dtrace-provider/0.8.8' in pnpm-lock.yaml\n    at pkgAllDeps (/usr/local/lib/node_modules/pnpm/lib/node_modules/@pnp
m/filter-lockfile/lib/filterLockfileByImporters.js:34:19)\n    at pkgAllDeps (/usr/local/lib/node_modules/pnpm/lib/node_modules/@pnpm/filter-lockfile/lib/filterLockfileByImporters.js:30:9)\n
   at pkgAllDeps (/usr/local/lib/node_modules/pnpm/lib/node_modules/@pnpm/filter-lockfile/lib/filterLockfileByImporters.js:30:9)\n    at pkgAllDeps (/usr/local/lib/node_modules/pnpm/lib/node_
modules/@pnpm/filter-lockfile/lib/filterLockfileByImporters.js:30:9)\n    at Object.filterByImporters [as filterLockfileByImporters] (/usr/local/lib/node_modules/pnpm/lib/node_modules/@pnpm/f
ilter-lockfile/lib/filterLockfileByImporters.js:12:9)\n    at Object.linkPackages [as default] (/usr/local/lib/node_modules/pnpm/lib/node_modules/supi/lib/install/link.js:105:50)\n    at asyn
c installInContext (/usr/local/lib/node_modules/pnpm/lib/node_modules/supi/lib/install/index.js:495:20)\n    at async _install (/usr/local/lib/node_modules/pnpm/lib/node_modules/supi/lib/inst
all/index.js:292:24)\n    at async Object.mutateModules (/usr/local/lib/node_modules/pnpm/lib/node_modules/supi/lib/install/index.js:67:20)"
    }
```

Sorry for such a way of showing logs, but it reproduces only in Kubernetes pod without persisten volume, so it is really hard to get a whole file from there.

**Comment by ghaiklor-wix** [comment]
It helps me to reproduce the issue locally. It is happening when I'm installing dependencies with `--no-optional` flag.

**Comment by zkochan** [comment]
Try to run `pnpm install --prod --no-optional` instead of prune. It will do basically the same.

**Comment by ghaiklor-wix** [comment]
@zkochan Got it, thanks! The issue resolved from my side then, not sure if you want to take it as a bug :)

**Comment by zkochan** [comment]
So `pnpm install --prod --no-optional` works?

We can fix the prune command

**Comment by ghaiklor-wix** [comment]
Yes, while `pnpm prune --prod` fails, `pnpm install --prod --no-optional` just emits warnings, but does not fail the process.

**Comment by zkochan** [comment]
What are the warnings that you get?

**Comment by ghaiklor-wix** [comment]
```
Failed to find ".../source-map/0.6.1" in lockfile during hoisting. Next aliases will not be hoisted: source-map
...
```

**Comment by zkochan** [comment]
I don't understand where this `.../` comes from. Do you have an entry with the `.../source-map/0.6.1` in your `node_modules/.pnpm/lock.yaml`?

**Comment by ghaiklor-wix** [comment]
Ah, no, it has nothing to do with that. I just omit a registry for simplicity :)

**Comment by yanickrochon** [comment]
Just got this. I have no idea what it means.

```
 ERR_PNPM_ERR_PNPM_LOCKFILE_MISSING_DEPENDENCY  The lockfile is broken! Resolution step will be performed to fix it.
```

But no step is "performed to fix it". All it does is try to download a dev package and fails because the dev package is one that is local and not published.

**Comment by EfeDurmaz16** [comment]
@zkochan, I checked this during the oldest-priority-1 triage using rebuilt v11.27.0 and v12.5.1 CLIs from main commit `1be9010902aeaa5aa4b7376fd745e8f848eb48c9` on macOS arm64.

With lockfiles disabled and a fixture containing an incompatible optional dependency, I ran `pnpm install`, `pnpm install --no-optional`, then `pnpm prune --prod`. Prune exited 0 in both versions. In v11 it still printed the broken-lockfile warning and re-resolved successfully. A second v11 probe where the optional package later returned 404 also exited 0.

This did not reproduce the original fatal failure, but it does not establish that every case in this thread is fixed, especially the later unpublished local-dependency report. Would a current minimal reproducer be the useful next step here?

Written by an agent (Codex, GPT-6).
