### ISSUE TITLE
"pnpm add" cannot handle empty tags

### ISSUE THREAD

**Issue by diachedelic** [pnpm/pnpm#2737]
pnpm version: 5.4.8

### Code to reproduce the issue:

```pnpm add sharp@```

debug log: https://gist.github.com/diachedelic/82865a049353f492c3c4cf96cd0747a0

#### Stack trace
```
TypeError: Cannot read property '/sharp/0.25.4' of undefined
    at /Users/me/.nvm/versions/node/v14.4.0/lib/node_modules/pnpm/lib/node_modules/supi/lib/install/link.js:177:64
    at async Promise.all (index 80)
    at async Object.linkPackages [as default] (/Users/me/.nvm/versions/node/v14.4.0/lib/node_modules/pnpm/lib/node_modules/supi/lib/install/link.js:162:5)
    at async installInContext (/Users/me/.nvm/versions/node/v14.4.0/lib/node_modules/pnpm/lib/node_modules/supi/lib/install/index.js:502:20)
    at async _install (/Users/me/.nvm/versions/node/v14.4.0/lib/node_modules/pnpm/lib/node_modules/supi/lib/install/index.js:292:24)
    at async Object.mutateModules (/Users/me/.nvm/versions/node/v14.4.0/lib/node_modules/pnpm/lib/node_modules/supi/lib/install/index.js:67:20)
    at async Object.handler [as default] (/Users/me/.nvm/versions/node/v14.4.0/lib/node_modules/pnpm/lib/node_modules/@pnpm/plugin-commands-installation/lib/installDeps.js:122:35)
    at async Timeout._onTimeout (/Users/me/.nvm/versions/node/v14.4.0/lib/node_modules/pnpm/lib/main.js:198:30)
```

### Expected behavior:
An empty tag should be ignored, as does yarn and npm. This is so you can do stuff like `pnpm add "$PKG_NAME"@"$PKG_TAG"` and not worry about the empty variable.

### Actual behavior:
A fatal error occurs.

### Additional information:

 - `node -v` prints: v14.4.0
 - Windows, OS X, or Linux?: MacOS 10.15.6

**Comment by diachedelic** [comment]
My workaround is to specify the `latest` tag if not set, like `pnpm add "${PKG_NAME}@${PKG_TAG:-latest}"`
