### ISSUE TITLE
pnpm stopped working after upgrading

### ISSUE THREAD

**Issue by aminya** [pnpm/pnpm#2800]
I installed new pnpm, and suddenly it does not work anymore
```ps1
❯ pnpm -v
internal/modules/cjs/loader.js:1083
  throw err;
  ^

Error: Cannot find module 'C:\Users\aminy\AppData\Roaming\npm\pnpm-global\4\node_modules\pnpm\bin\pnpm.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1080:15)
    at Function.Module._load (internal/modules/cjs/loader.js:923:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```
Now returning back to 5.5.2 does not solve the issue!
```ps1
❯ npm install -g pnpm@5.5.2
C:\Users\aminy\AppData\Roaming\npm\pnpm -> C:\Users\aminy\AppData\Roaming\npm\node_modules\pnpm\bin\pnpm.js
C:\Users\aminy\AppData\Roaming\npm\pnpx -> C:\Users\aminy\AppData\Roaming\npm\node_modules\pnpm\bin\pnpx.js
+ pnpm@5.5.2
updated 1 package in 3.64s

❯ pnpm -v
internal/modules/cjs/loader.js:1083
  throw err;
  ^

Error: Cannot find module 'C:\Users\aminy\AppData\Roaming\npm\pnpm-global\4\node_modules\pnpm\bin\pnpm.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1080:15)
    at Function.Module._load (internal/modules/cjs/loader.js:923:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

```

### pnpm version:
5.5.3

### Code to reproduce the issue:
```
pnpm i -g pnpm
```

### Expected behavior:
Upgrade

### Actual behavior:
pnpm stops working

### Additional information:

 - `node -v` prints: 14.8
 - Windows, OS X, or Linux?: Win10

**Comment by aminya** [comment]
When I try to find all the `pnpm` things that are on my path, this shows up:
```
❯ whichall pnpm
C:\Program Files\nodejs\pnpm
C:\Program Files\nodejs\pnpm.cmd
C:\Users\aminy\AppData\Roaming\npm\pnpm
C:\Users\aminy\AppData\Roaming\npm\pnpm.cmd
```

After ` npm uninstall -g pnpm`
it becomes:
```
❯ whichall pnpm
C:\Program Files\nodejs\pnpm
C:\Program Files\nodejs\pnpm.cmd
```

I am not sure what this nodejs folder comes from!

**Comment by zkochan** [comment]
Seems like we need to update https://github.com/pnpm/pnpm/tree/master/packages/global-bin-dir

if it finds an exec directory that has `pnpm` and it has no write access to that directory, then `pnpm i -g pnpm` should fail

**Comment by aminya** [comment]
I think it should never write to nodejs folder. You may add a check for that. If that happens manual deletion is needed. `npm uninstall` can't delete that.

**Comment by zenmumbler** [comment]
Just to add, updated pnpm to 5.5.10 which now fails on `pnpm root -g` returning

```
 ERROR  Couldn't find a suitable global executables directory.
There should be a node, nodejs, npm, or pnpm directory in the "PATH" environment variable
```

Downgrading back to pnpm@5.5.2 restores functionality, in my case it returns:
`/usr/local/Cellar/node/14.9.0/pnpm-global/4/node_modules`

Which may or may not be correct as I use `npm` to install global modules, mostly because pnpm's global installations would be wiped on every time I upgrade node (which is quite often, using brew)

`npm root -g` returns `/usr/local/lib/node_modules` which is also where pnpm is installed

**Comment by zkochan** [comment]
This targets a part of pnpm that no longer exists, so closing.

The AppData\Roaming\npm\pnpm-global layout that broke here no longer exists. pnpm installs standalone under PNPM_HOME.

If you still hit this on the latest pnpm, please comment with a reproduction and we will reopen.

---
Written by an agent (Claude Code, claude-opus-5).
