### ISSUE TITLE
The "from" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by wighawag** [pnpm/pnpm#2847]
### pnpm version:
latest using (docker image: znck/pnpm:latest)

### Code to reproduce the issue:

docker-compose.yml
```
version: '3.7'
services:
  app:
    image: znck/pnpm:latest
    command: sh -c 'pnpm install --store=node_modules/.pnpm-store'
    working_dir: /workspace
    volumes:
      - './:/workspace'
```

and I get the following pnpm-debug.log
```
{
  "0 debug pnpm:scope": {
    "selected": 5,
    "total": 5,
    "workspacePrefix": "/workspace"
  },
  "1 debug pnpm": {
    "isCaseSensitive": true,
    "store": "/workspace/node_modules/.pnpm-store/2"
  },
  "2 error pnpm": {
    "message": {
      "code": "ERR_INVALID_ARG_TYPE"
    },
    "err": {
      "name": "TypeError",
      "message": "The \"from\" argument must be of type string. Received undefined",
      "code": "ERR_INVALID_ARG_TYPE",
      "stack": "TypeError [ERR_INVALID_ARG_TYPE]: The \"from\" argument must be of type string. Received undefined\n    at validateString (internal/validators.js:118:11)\n    at Object.relative (path.js:1053:5)\n    at Object.checkCompatibility [as default] (/usr/local/lib/node_modules/pnpm/lib/node_modules/@pnpm/get-context/lib/checkCompatibility/index.js:13:14)\n    at /usr/local/lib/node_modules/pnpm/lib/node_modules/@pnpm/get-context/lib/index.js:137:41\n    at Array.map (<anonymous>)\n    at validateNodeModules (/usr/local/lib/node_modules/pnpm/lib/node_modules/@pnpm/get-context/lib/index.js:135:32)\n    at Object.getContext [as default] (/usr/local/lib/node_modules/pnpm/lib/node_modules/@pnpm/get-context/lib/index.js:20:15)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async Object.mutateModules (/usr/local/lib/node_modules/pnpm/lib/node_modules/supi/lib/install/index.js:63:17)\n    at async Object.recursive [as default] (/usr/local/lib/node_modules/pnpm/lib/node_modules/@pnpm/plugin-commands-installation/lib/recursive.js:174:29)"
    }
  }
}
```

### Expected behavior:
works fine

### Actual behavior:
I get the following error
```
 ERROR  The "from" argument must be of type string. Received undefined
at validateString             internal/validators.js:118
at relative                   path.js:1053
at checkCompatibility [as d…  ../usr/local/lib/node_modules/pnpm/lib/node_modules/@pnpm/get-context/lib/checkCompatibility/index.js:13     if (path.relative(module…
at at /usr/local/lib/node_m…  pnpm/get-context/lib/index.js:137
at map
at validateNodeModules        ../usr/local/lib/node_modules/pnpm/lib/node_modules/@pnpm/get-context/lib/index.js:135                       await Promise.all(projec…
at getContext [as default]    ../usr/local/lib/node_modules/pnpm/lib/node_modules/@pnpm/get-context/lib/index.js:20                        await validateNodeModule…
at processTicksAndRejections  internal/process/task_queues.js:97
at mutateModules              ../usr/local/lib/node_modules/pnpm/lib/node_modules/supi/lib/install/index.js:63                             const ctx = await get_co…
at recursive [as default]     ../usr/local/lib/node_modules/pnpm/lib/node_modules/@pnpm/plugin-commands-installation/lib/recursive.js:174  const mutatedPkgs = awai…

```

**Comment by wighawag** [comment]
never mind it was because of existing node_modules and the use of volume
