### ISSUE TITLE
Can't install pnpm using standalone script

### ISSUE THREAD

**Issue by mhmdanas** [pnpm/pnpm#2857]
### pnpm version:
Can't install so can't answer.

### Code to reproduce the issue:
Try installation using standalone script (see https://pnpm.js.org/en/installation).

### Expected behavior:
pnpm should be installed successfully.

### Actual behavior:
I get this output:
```
[stdin]:15911
},{}],122:[function(require,module,exports){
^

SyntaxError: Unexpected token '}'
    at new Script (vm.js:88:7)
    at createScript (vm.js:261:10)
    at Object.runInThisContext (vm.js:309:10)
    at Object.<anonymous> ([stdin]-wrapper:10:26)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at evalScript (internal/process/execution.js:94:25)
    at internal/main/eval_stdin.js:29:5
    at Socket.<anonymous> (internal/process/execution.js:207:5)
    at Socket.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12)
```

### Additional information:

 - `node -v` prints: `v12.18.3`
 - Windows, OS X, or Linux?: macOS 10.15.6

I don't know if this is the correct repo to open this issue in. Please move it to the correct repo if that is not the case.

**Comment by mcmxcdev** [comment]
Cannot reproduce this. Standalone script instructions can be found on https://pnpm.io/installation#using-a-standalone-script now

**Comment by mhmdanas** [comment]
I install pnpm through my package manager now, and nobody else is able to reproduce this, so I'm closing the issue.
