### ISSUE TITLE
 .npmrc option to copy dependencies instead of using symlink

### ISSUE THREAD

**Issue by aminya** [pnpm/pnpm#2883]
I use a Node project that builds native modules in a certain way, and so I need to copy the dependencies like npm.

Could you add an option for this? I don't want to switch to npm just for one package that needs this in our organization. 

Another example is Parcel bundler that does not work with pnpm because of symlinks:

https://github.com/parcel-bundler/parcel/pull/4920
https://github.com/parcel-bundler/parcel/pull/4939

### Code to reproduce the issue:
https://github.com/atom-ide-community/terminal

```
> pnpm install
```

atom package manager (apm):
```
> apm rebuild
Rebuilding modules failed
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'C:\Users\aminy\Documents\GitHub\JavaScript\prebuild-install@5.3.5\node_modules\prebuild-install\bin.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
Error in sitecustomize; set PYTHONVERBOSE for traceback:
OSError: [WinError 1392] The file or directory is corrupted and unreadable: 'C:\\Users\\aminy\\AppData\\Local\\emsdk\\python\\3.7.4-pywin32_64bit\\lib\\site-packages\\Pythonwin'
Error in usercustomize; set PYTHONVERBOSE for traceback:
OSError: [WinError 1392] The file or directory is corrupted and unreadable: 'C:\\Users\\aminy\\AppData\\Local\\emsdk\\python\\3.7.4-pywin32_64bit\\lib\\site-packages\\Pythonwin'
Traceback (most recent call last):
  File "C:\Users\aminy\AppData\Local\atom\app-1.51.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 47, in <module>
    import gyp
  File "C:\Users\aminy\AppData\Local\atom\app-1.51.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 9, in <module>
    import copy
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\copy.py", line 60, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1252, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1368, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1408, in _fill_cache
OSError: [WinError 1392] The file or directory is corrupted and unreadable: 'C:\\Users\\aminy\\AppData\\Local\\emsdk\\python\\3.7.4-pywin32_64bit\\lib\\site-packages\\Pythonwin'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\aminy\AppData\Local\atom\app-1.51.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.19041
gyp ERR! command "C:\\Users\\aminy\\AppData\\Local\\atom\\app-1.51.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\aminy\\AppData\\Local\\atom\\app-1.51.0\\resources\\app\\apm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\aminy\Documents\GitHub\JavaScript\terminal\node_modules\.pnpm\node-pty-prebuilt-multiarch@0.9.0\node_modules\node-pty-prebuilt-multiarch
gyp ERR! node -v v10.20.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty-prebuilt-multiarch@0.9.0 install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-pty-prebuilt-multiarch@0.9.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\aminy\.atom\.apm\_logs\2020-09-22T08_29_46_563Z-debug.log
```

### Expected behavior:

Install like npm so the native modules built using apm can resolve its dependencies.

### Actual behavior:

Creates symlinks

### Additional information:

 - `node -v` prints: v12.18.1
 - Windows, OS X, or Linux?: Win 10

**Comment by zkochan** [comment]
There is no config to avoid symlinks. There is no way to avoid symlinks. You either use a flat node_modules (like npm and yarn 1), or override Node's resolution algorithm, like Yarn 2 Plug'n'Play. We might support plug'n'play one day but not flat node_modules.

package-import-method is for setting how files are added to the modules directory from the content-addressable store.

**Comment by aminya** [comment]
I see. So, could you add an option for this? I don't want to switch to npm just for one package that needs this in our organization. 

Another example is Parcel bundler that does not work with pnpm because of symlinks:

https://github.com/parcel-bundler/parcel/pull/4920
https://github.com/parcel-bundler/parcel/pull/4939

**Comment by codejamninja** [comment]
Some other examples of projects that need this include typegraphql-prisma and expo.

https://github.com/MichalLytek/type-graphql/issues/710#issuecomment-698600017

**Comment by zkochan** [comment]
Experimental pnp support added via a separate CLI tool that generates a `.pnp.js` file from a pnpm lockfile and node_modules: https://github.com/pnpm/pnpm/tree/master/packages/lockfile-to-pnp

Try to use it on projects that don't work with symlinks.

**Comment by aminya** [comment]
So, should we start Node with this script instead?

**Comment by zkochan** [comment]
Yes, for instance, `node --require ./.pnp.js index.js`

**Comment by aminya** [comment]
This is an issue with many packages that use `postinstall` including those who use `prebuild-install`. I tried to install [`@arkweid/lefthook`](https://github.com/evilmartians/lefthook/blob/master/docs/node.md), but it failed with the following error

```js
❯ pnpm i --save-dev @arkweid/lefthook
Packages: +1 -141
+--------------------------------------------------------------------------------------------------------------------------------
node_modules/.pnpm/@arkweid+lefthook@0.7.4/node_modules/@arkweid/lefthook: Running postinstall script, failed in 69ms
.../node_modules/@arkweid/lefthook postinstall$ node postinstall.js
│ node:events:342
│       throw er; // Unhandled 'error' event
│       ^
│ Error: spawn C:\Users\aminy\Documents\GitHub\Dream\dream\node_modules\.pnpm\@arkweid+lefthook@0.7.4\node_modules\@arkweid\lefth
│     at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
│     at onErrorNT (node:internal/child_process:480:16)
│     at processTicksAndRejections (node:internal/process/task_queues:83:21)
│ Emitted 'error' event on ChildProcess instance at:
│     at Process.ChildProcess._handle.onexit (node:internal/child_process:288:12)
│     at onErrorNT (node:internal/child_process:480:16)
│     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
│   errno: -4058,
│   code: 'ENOENT',
│   syscall: 'spawn C:\\Users\\aminy\\Documents\\GitHub\\Dream\\dream\\node_modules\\.pnpm\\@arkweid+lefthook@0.7.4\\node_modules
│   path: 'C:\\Users\\aminy\\Documents\\GitHub\\Dream\\dream\\node_modules\\.pnpm\\@arkweid+lefthook@0.7.4\\node_modules\\@arkwei
│   spawnargs: [ 'install', '-f' ]
│ }
└─ Failed in 69ms
 ERROR  Command failed with exit code 1.
Progress: resolved 22, reused 22, downloaded 0, added 0
```

The `postinstall` script itself is very simple. Not sure why `pnpm` fails to run it.

**Comment by zkochan** [comment]
This is implemented in current pnpm, so closing.

`nodeLinker: hoisted` builds a flat node_modules of real directories with no symlinks, and `packageImportMethod: copy` forces copies instead of links.

If you still hit this on the latest pnpm, please comment with a reproduction and we will reopen.

---
Written by an agent (Claude Code, claude-opus-5).
