### ISSUE TITLE
Next.js + dgraph-js-http@20.07.2 doesn’t work with pnpm

### ISSUE THREAD

**Issue by octrhiumlofera** [pnpm/pnpm#2973]
#### pages/dgraph.js
```javascript
const dgraph = require("dgraph-js-http");

const clientStub = new dgraph.DgraphClientStub();
const dgraphClient = new dgraph.DgraphClient(clientStub);

const dropAll = async () => {
  await dgraphClient.alter({ dropAll: true });
}
```

#### pages/index.js
```javascript
import dropAll from './dgraph'

const Page = () => {
  return <button onClick = {dropAll}>Test</button>
}

export default Page;
```

#### next.config.js
```javascript
const withTM = require('next-transpile-modules')(['dgraph-js-http']);

module.exports = withTM();
```

#### package.json
```json
{
  "dependencies": {
    "dgraph-js-http": "^20.7.2",
    "next": "^10.0.1",
    "next-transpile-modules": "^4.1.0",
    "react": "^17.0.1",
    "react-dom": "^17.0.1"
  },
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  }
}
```

#### Command:
```bash
$ pnpm run dev
```

**Note:** Deploying a Dgraph database isn’t needed, but recommended. Check out [the download page + quick guide](https://dgraph.io/downloads).

### Expected behavior:

The app should be able to render the page and interact with the database without any issue.

### Actual behavior:

This comes out after accessing `http://localhost:3000/` on the browser:
```
internal/fs/utils.js:308
    throw err;
    ^

Error: ENOENT: no such file or directory, lstat 'C:\zz\next\ab\url'
    at realpathSync (fs.js:1728:7)
    at handleExternals (C:\zz\next\ab\node_modules\.pnpm\next@10.0.1_react-dom@17.0.1+react@17.0.1\node_modules\next\dist\build\webpack-config.js:68:21)
    at webpackConfig.externals (C:\zz\next\ab\node_modules\.pnpm\next@10.0.1_react-dom@17.0.1+react@17.0.1\node_modules\next\dist\build\webpack-config.js:80:136)
    at C:\zz\next\ab\node_modules\.pnpm\next-transpile-modules@4.1.0\node_modules\next-transpile-modules\src\next-transpile-modules.js:88:56
    at handleExternals (C:\zz\next\ab\node_modules\.pnpm\webpack@4.44.1\node_modules\webpack\lib\ExternalModuleFactoryPlugin.js:78:17)
    at next (C:\zz\next\ab\node_modules\.pnpm\webpack@4.44.1\node_modules\webpack\lib\ExternalModuleFactoryPlugin.js:66:9)
    at handleExternals (C:\zz\next\ab\node_modules\.pnpm\webpack@4.44.1\node_modules\webpack\lib\ExternalModuleFactoryPlugin.js:71:7)
    at C:\zz\next\ab\node_modules\.pnpm\webpack@4.44.1\node_modules\webpack\lib\ExternalModuleFactoryPlugin.js:101:5
    at C:\zz\next\ab\node_modules\.pnpm\webpack@4.44.1\node_modules\webpack\lib\NormalModuleFactory.js:400:5
    at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (C:\zz\next\ab\node_modules\.pnpm\tapable@1.1.3\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1) {
  errno: -4058,
  syscall: 'lstat',
  code: 'ENOENT',
  path: 'C:\\zz\\next\\ab\\url'
}
 ERROR  Command failed with exit code 1.
```

### Additional information:

 - `node -v` prints: `v14.15.0`
 - Windows, macOS, or Linux?: **Windows 10 x64 (Build 19042.572)**
 - The reason `next-transpile-modules` is being used is the fact that `dgraph-js-http@20.07.2` uses ES6 export, unlike the previous version `v20.07.1` which uses CommonJS require.
 - Installing modules with npm handles this issue properly.

**Comment by octrhiumlofera** [comment]
It has been solved by Dgraph team with the next update `dgraph-js-http@20.07.3`. I’m still curious about the compatibility between `next-transpile-modules` and `pnpm` because I haven’t yet seen them working together properly. Nothing to be worried, hopefully.
