### ISSUE TITLE
Stream Premature close - pnpm install

### ISSUE THREAD

**Issue by losintikfos** [pnpm/pnpm#3007]
### Expected behavior:

When I attempt `pnpm install` I expect to see package.json dependencies installed without any error.

### Actual behavior:

Unfortunately install is generating this error:

```bash
Progress: resolved 19, reused 0, downloaded 0, added 0
Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
    at Source.onclose (internal/streams/end-of-stream.js:80:38)
    at Source.emit (events.js:315:20)
    at Extract.destroy (/opt/node-v13.13.0-linux-x64/lib/node_modules/pnpm/dist/pnpm.js:66127:20)
    at Source.destroy (/opt/node-v13.13.0-linux-x64/lib/node_modules/pnpm/dist/pnpm.js:65983:18)
    at Object.destroyer (internal/streams/destroy.js:140:59)
    at Source.<anonymous> (internal/streams/pipeline.js:65:19)
    at Source.<anonymous> (internal/util.js:392:14)
    at Source.onend (internal/streams/end-of-stream.js:70:49)
    at Source.emit (events.js:327:22)
```

### Additional information:

 - `node -v` prints: v13.13.0
 - Windows, macOS, or Linux?: x86_64 GNU/Linux

**Comment by zkochan** [comment]
do you have the repository available publicly? to reproduce the issue

**Comment by losintikfos** [comment]
Yes it is a github [repository](https://github.com/dangvanthanh/vue-shopping-cart)

**Comment by zkochan** [comment]
anyway, if I understand correctly from the chatroom, this is not an issue with Node.js 14, so I think we can close this issue.

**Comment by creepinson** [comment]
I'm having this same issue with the same line numbers - was there a solution that was found?

**Comment by aesyondu** [comment]
Can confirm, updating node from 13.14.0 to 14.15.4 fixes the error.

**Comment by Kujo-Jotaro-AAAAA** [comment]
node: 17.0.1
pnpm: 6.24.0

Premature close

> Progress: resolved 18, reused 0, downloaded 0, added 0
Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
    at Source.onclose (internal/streams/end-of-stream.js:105:38)
    at Source.emit (events.js:315:20)
    at Extract.destroy (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:68128:22)
    at Source.destroy (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:67984:20)
    at Object.destroyer (internal/streams/destroy.js:166:59)
    at internal/streams/pipeline.js:58:19
    at internal/util.js:392:14
    at Source.<anonymous> (internal/streams/pipeline.js:84:7)
    at Source.<anonymous> (internal/util.js:392:14)
    at Source.onend (internal/streams/end-of-stream.js:95:49)
Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
    at Source.onclose (internal/streams/end-of-stream.js:105:38)
    at Source.emit (events.js:315:20)
    at Extract.destroy (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:68128:22)
    at Source.destroy (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:67984:20)
    at Object.destroyer (internal/streams/destroy.js:166:59)
    at internal/streams/pipeline.js:58:19
    at internal/util.js:392:14
    at Source.<anonymous> (internal/streams/pipeline.js:84:7)
    at Source.<anonymous> (internal/util.js:392:14)
    at Source.onend (internal/streams/end-of-stream.js:95:49)
Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
    at Source.onclose (internal/streams/end-of-stream.js:105:38)
    at Source.emit (events.js:315:20)
    at Extract.destroy (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:68128:22)
    at Source.destroy (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:67984:20)
    at Object.destroyer (internal/streams/destroy.js:166:59)
    at internal/streams/pipeline.js:58:19
    at internal/util.js:392:14
    at Source.<anonymous> (internal/streams/pipeline.js:84:7)
    at Source.<anonymous> (internal/util.js:392:14)
    at Source.onend (internal/streams/end-of-stream.js:95:49)
