### ISSUE TITLE
Broken lockfile error occurs when attempting to upgrade globally installed package

### ISSUE THREAD

**Issue by achou11** [pnpm/pnpm#3046]
### Code to reproduce the issue:

Run `pnpm i -g DEPENDENCY_NAME` (in this case I'm trying to update the globally installed `netlify-cli` to `2.69.11`)

Relevant output of `node_modules/.pnpm-debug.log`:

```
  "5534 error pnpm": {
    "message": {
      "code": "ERR_PNPM_LOCKFILE_MISSING_DEPENDENCY",
      "hint": "This issue is probably caused by a badly resolved merge conflict.\nTo fix the lockfile, run 'pnpm install --no-frozen-lockfile'."
    },
    "err": {
      "name": "Error",
      "message": "Broken lockfile: no entry for '/@babel/core/7.12.9_supports-color@7.2.0' in pnpm-lock.yaml",
      "code": "ERR_PNPM_LOCKFILE_MISSING_DEPENDENCY",
      "stack": "Error: Broken lockfile: no entry for '/@babel/core/7.12.9_supports-color@7.2.0' in pnpm-lock.yaml\n    at pkgAllDeps (/Users/andrewchou/.npm-global/pnpm-global/4/node_modules/.pnpm/pnpm@5.14.1/node_modules/pnpm/dist/pnpm.js:73615:15)\n    at pkgAllDeps (/Users/andrewchou/.npm-global/pnpm-global/4/node_modules/.pnpm/pnpm@5.14.1/node_modules/pnpm/dist/pnpm.js:73611:7)\n    at pkgAllDeps (/Users/andrewchou/.npm-global/pnpm-global/4/node_modules/.pnpm/pnpm@5.14.1/node_modules/pnpm/dist/pnpm.js:73611:7)\n    at pkgAllDeps (/Users/andrewchou/.npm-global/pnpm-global/4/node_modules/.pnpm/pnpm@5.14.1/node_modules/pnpm/dist/pnpm.js:73611:7)\n    at pkgAllDeps (/Users/andrewchou/.npm-global/pnpm-global/4/node_modules/.pnpm/pnpm@5.14.1/node_modules/pnpm/dist/pnpm.js:73611:7)\n    at Object.filterByImporters [as filterLockfileByImporters] (/Users/andrewchou/.npm-global/pnpm-global/4/node_modules/.pnpm/pnpm@5.14.1/node_modules/pnpm/dist/pnpm.js:73593:7)\n    at Object.linkPackages [as default] (/Users/andrewchou/.npm-global/pnpm-global/4/node_modules/.pnpm/pnpm@5.14.1/node_modules/pnpm/dist/pnpm.js:94266:50)\n    at async installInContext (/Users/andrewchou/.npm-global/pnpm-global/4/node_modules/.pnpm/pnpm@5.14.1/node_modules/pnpm/dist/pnpm.js:94983:22)\n    at async _install (/Users/andrewchou/.npm-global/pnpm-global/4/node_modules/.pnpm/pnpm@5.14.1/node_modules/pnpm/dist/pnpm.js:94804:23)\n    at async Object.mutateModules (/Users/andrewchou/.npm-global/pnpm-global/4/node_modules/.pnpm/pnpm@5.14.1/node_modules/pnpm/dist/pnpm.js:94600:20)"
    }
  }
  ```

### Expected behavior:

Should update the globally installed package version without any errors

### Actual behavior:

Attempts to install the upgraded dependency but then halts with the following error output:

```
 ERROR  Broken lockfile: no entry for '/@babel/core/7.12.9_supports-color@7.2.0' in pnpm-lock.yaml
This issue is probably caused by a badly resolved merge conflict.
To fix the lockfile, run 'pnpm install --no-frozen-lockfile'.
```

Not really sure how to apply the suggested fix in the context of a globally installed package but maybe that's all I need? Found https://github.com/pnpm/pnpm/issues/2677 but didn't see an actionable potential fix based on its discussion.

### Additional information:

 - `node -v` prints: `v15.5.0`
 - Windows, macOS, or Linux?: macOS (Catalina 10.15.7)

**Comment by achou11** [comment]
Looks like the issue was fixed on Netlify's end with release of [v2.70.0](https://github.com/netlify/cli/releases/tag/v2.70.0)

Feel free to close this!

**Comment by zkochan** [comment]
Such error should never happen on globally installed packages. To autofix the broken global lockfile, this command can be used: `pnpm install --no-frozen-lockfile`

**Comment by zkochan** [comment]
This no longer reproduces on current pnpm, so closing.

Verified on pnpm 12.5.1: installing a global package and then installing a newer version of it upgrades cleanly, with no lockfile error.

If you still hit this on the latest pnpm, please comment with a reproduction and we will reopen.

---
Written by an agent (Claude Code, claude-opus-5).
