### ISSUE TITLE
P'n'P doesn't work with electron

### ISSUE THREAD

**Issue by lenchvolodymyr** [pnpm/pnpm#3108]
### pnpm version:
5.15.2

### Code to reproduce the issue:

Install electron:

```
pnpm i electron
```

index.js:
```
require('./.pnp.js').setup();
const electron = require('electron');

electron.app.on('ready', () => {
	new electron.BrowserWindow();
})
```

.npmrc
```
node-linker=pnp
symlink=false
```

Run electron:
```
./node_modules/.bin/electron index.js
```

### Expected behavior:

Electron window is opened

### Actual behavior:
App threw an error during load
TypeError: Cannot read property 'on' of undefined
    at Object.<anonymous> (/electron_pnpm/index.js:5:14)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at loadApplicationPackage (/electron_pnpm/node_modules/.pnpm/electron@11.2.1/node_modules/electron/dist/resources/default_app.asar/main.js:110:16)
    at Object.<anonymous> (/electron_pnpm/node_modules/.pnpm/electron@11.2.1/node_modules/electron/dist/resources/default_app.asar/main.js:222:9)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)

### Additional information:

And similar situation with "electron-rebuild":

env NODE_OPTIONS="--require=./.pnp.js" ./node_modules/.bin/electron-rebuild
An unhandled error occurred inside electron-rebuild
Unable to find electron's version number, either install it or specify an explicit version

 - `node -v` prints: v12.0.0
 - Windows, macOS, or Linux?: Ubuntu 20.04

**Comment by mubaidr** [comment]
Add `shamefully-hoist = true` to your `,npmrc` config and then re-install dependencies.

**Comment by zkochan** [comment]
Closing for lack of a reproduction on a supported version.

Reported against pnpm 5.15 and the `.pnp.js` loader of the time. Electron's own bundling is what has to support Plug'n'Play; nothing here is actionable in pnpm without a current reproduction.

If you still hit this on the latest pnpm, please comment with a reproduction and we will reopen.

---
Written by an agent (Claude Code, claude-opus-5).
