### ISSUE TITLE
Command "store status" fails

### ISSUE THREAD

**Issue by Camo30** [pnpm/pnpm#3185]
As mentioned in issue #609 I get the following error while trying to execute `pnpm store status`:

``` 
ERROR  EMFILE: too many open files, open 'C:\Dev\nxdemo\node_modules\.pnpm\autoprefixer@10.2.1_postcss@8.2.4\node_modules\autoprefixer\lib\hacks\grid-template-areas.js'
at 1_postcss
internal/fs/utils.js:307
    throw err;
    ^

Error: EMFILE: too many open files, open 'node_modules/.pnpm-debug.log'
    at Object.openSync (fs.js:476:3)
    at Object.writeFileSync (fs.js:1467:35)
    at process.<anonymous> (C:\Users\sta\AppData\Roaming\npm\pnpm-global\4\node_modules\.pnpm\pnpm@5.17.3\node_modules\pnpm\dist\pnpm.js:122644:10)
    at process.emit (events.js:315:20)
    at processEmit (C:\Users\sta\AppData\Roaming\npm\pnpm-global\4\node_modules\.pnpm\pnpm@5.17.3\node_modules\pnpm\dist\pnpm.js:11186:37)
    at processEmit [as emit] (C:\Users\sta\AppData\Roaming\npm\pnpm-global\4\node_modules\.pnpm\pnpm@5.17.3\node_modules\pnpm\dist\node_modules\signal-exit\index.js:155:35)
    at process.exit (internal/process/per_thread.js:169:15)
    at Timeout._onTimeout (C:\Users\sta\AppData\Roaming\npm\pnpm-global\4\node_modules\.pnpm\pnpm@5.17.3\node_modules\pnpm\dist\pnpm.js:11052:30)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) {
  errno: -4066,
  syscall: 'open',
  code: 'EMFILE',
  path: 'node_modules/.pnpm-debug.log'
}
```

### Code to reproduce the issue:

No code available. If needed I could maybe provide a sample project to get it reproducable.

Unfortunately the file node_modules/.pnpm-debug.log is fully empty.

### Expected behavior:

Should execute the command successfully and show some status information of the store.

### Actual behavior:

Fails while executing the command and prints the error listed above.

### Additional information:

 - `node -v` prints: 14.15.4
 - Windows, macOS, or Linux?: Windows

**Comment by gunters63** [comment]
I have exact the same problem on windows. Node version exactly the same.
node_modules/.pnpm-debug.log is also empty for me.

Interestingly, the output is different if I execute it in a command prompt in my project directory or if I execute it from VsCode built-in terminal.

Inside the command prompt it throws always exactly at the same file.
Inside VsCode terminal it sometimes varies. That makes sense because the number of available file handles in VsCode varies over time because so much stuff is going on in the background processes of VsCode.

I will try with different Node versions, probably it is a node problem.

**Comment by gunters63** [comment]
Tried it with Node 15.10.0 now, same result. The stack trace:

````
D:\proj\AtlasCopco\EnsoUi>pnpm store status
 ERROR  EMFILE: too many open files, open 'D:\proj\AtlasCopco\EnsoUi\node_modules\.pnpm\tsconfig-paths@3.9.0\node_modules\tsconfig-paths\lib\tsconfig-loader.js'
at pnpm\tsconfig-paths
node:internal/fs/utils:323
    throw err;
    ^

Error: EMFILE: too many open files, open 'node_modules/.pnpm-debug.log'
    at Object.openSync (node:fs:497:3)
    at Object.writeFileSync (node:fs:1521:35)
    at process.<anonymous> (C:\Users\retnu\AppData\Roaming\nvm\v15.10.0\node_modules\pnpm\dist\pnpm.js:122742:10)
    at process.emit (node:events:378:20)
    at processEmit (C:\Users\retnu\AppData\Roaming\nvm\v15.10.0\node_modules\pnpm\dist\pnpm.js:11186:37)
    at processEmit [as emit] (C:\Users\retnu\AppData\Roaming\nvm\v15.10.0\node_modules\pnpm\dist\node_modules\signal-exit\index.js:155:35)
    at process.exit (node:internal/process/per_thread:181:15)
    at Timeout._onTimeout (C:\Users\retnu\AppData\Roaming\nvm\v15.10.0\node_modules\pnpm\dist\pnpm.js:11052:30)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7) {
  errno: -4066,
  syscall: 'open',
  code: 'EMFILE',
  path: 'node_modules/.pnpm-debug.log'
}
````

**Comment by gunters63** [comment]
I am pretty sure I found the culprit:

In [index.ts](https://github.com/pnpm/pnpm/blob/main/packages/plugin-commands-store/src/storeStatus/index.ts) we have:

````
  const modified = await pFilter(pkgs, async ({ integrity, pkgPath, depPath, name }) => {
    const pkgIndexFilePath = integrity
      ? getFilePathInCafs(cafsDir, integrity, 'index')
      : path.join(storeDir, pkgPath, 'integrity.json')
    const { files } = await loadJsonFile<PackageFilesIndex>(pkgIndexFilePath)
    return (await dint.check(path.join(virtualStoreDir, dp.depPathToFilename(depPath, opts.dir), 'node_modules', name), files)) === false
  })
````

The [pFilter](https://github.com/sindresorhus/p-filter )package concurrently executes the passed filterer. The problem is that it defaults to an infinite number to concurrently executing promises which leads to too many open file handles while the filter is running (seems to be 500 with Node on windows.

The solution is to append an options object to the pFilter call like `, {concurrency: 8}`. After I patch this locally the command runs without problems.

I played around with concurrency 100, 16, 8 and even 1 and didn't see much change.

**Comment by Camo30** [comment]
@gunters63 Thanks for digging into this. I can confirm that the solution with `, {concurrency: 8}` for pFilter works.

**Comment by zkochan** [comment]
:ship: 5.18.3

**Comment by gunters63** [comment]
Can confirm emfile error is fixed :)
