### ISSUE TITLE
Completions do not install

### ISSUE THREAD

**Issue by esdmr** [pnpm/pnpm#3221]
### Code to reproduce the issue:
```sh
pnpm install-completion
# Select any shell
```

### Expected behavior:
After selecting shell, it should correctly print prompts and wait for user input.

### Actual behavior:
All user inputs happen at once and completions are not installed.

```
✔ Which Shell do you use ? · fish
Very well, we will install using undefined
? Which path then ? Must be absolute. ‣ ? We will install completion to ~/.config/fish/config.fish, is it ok ? (y/$HOME/.local/share/npm/lib/node_modules/pnpm/dist/pnpm.js:8450
      throw new Error("options.location is required");
            ^

Error: options.location is required
    at Object.install ($HOME/.local/share/npm/lib/node_modules/pnpm/dist/pnpm.js:8450:13)
    at install ($HOME/.local/share/npm/lib/node_modules/pnpm/dist/pnpm.js:8557:21)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async $HOME/.local/share/npm/lib/node_modules/pnpm/dist/pnpm.js:123194:7
```

### Additional information:

 - `node -v` prints: v15.10.0
 - Windows, macOS, or Linux?: Linux (Ubuntu 20.04.02)
 - Shell: Fish
 - NPM Prefix: `$HOME/.local/share/npm`

**Comment by esdmr** [comment]
I've filed a PR fixing this at <https://github.com/pnpm/tabtab/pull/6>

**Comment by zkochan** [comment]
:ship: 5.18.4
