### ISSUE TITLE
ERR_STREAM_PREMATURE_CLOSE on 6.0.0-rc.1

### ISSUE THREAD

**Issue by wighawag** [pnpm/pnpm#3311]
### Code to reproduce the issue:

repo :  https://github.com/wighawag/issue-prettier-pnpm

command:

`pnpm i`

error :

```
Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
    at Source.onclose (internal/streams/end-of-stream.js:105:38)
    at Source.emit (events.js:315:20)
    at Extract.destroy (D:\scoop\wighawag\persist\nvm\nodejs\v14.0.0\node_modules\pnpm\dist\pnpm.cjs:82859:20)
    at Source.destroy (D:\scoop\wighawag\persist\nvm\nodejs\v14.0.0\node_modules\pnpm\dist\pnpm.cjs:82715:18)
    at Object.destroyer (internal/streams/destroy.js:166:59)
    at internal/streams/pipeline.js:58:19
    at internal/util.js:392:14
    at Source.<anonymous> (internal/streams/pipeline.js:84:7)
    at Source.<anonymous> (internal/util.js:392:14)
    at Source.onend (internal/streams/end-of-stream.js:95:49)
```

full output was :

```
Scope: all 3 workspace projects
 WARN  eslint-plugin-svelte3@3.1.2 requires a peer of svelte@^3.2.0 but none was installed.
 WARN  @typescript-eslint/eslint-plugin > @typescript-eslint/experimental-utils > @typescript-eslint/typescript-estree: tsutils@3.21.0 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none was installed.
 WARN  prettier-plugin-svelte@2.2.0 requires a peer of svelte@^3.2.0 but none was installed.
main                                     |  WARN  @sveltejs/kit > @sveltejs/vite-plugin-svelte: @rollup/pluginutils@4.1.0 requires a peer of rollup@^1.20.0||^2.0.0 but none was installed.
Packages: +382
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: C:\Users\wighawag\.pnpm-store\v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 383, reused 382, downloaded 0, added 18
Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
    at Source.onclose (internal/streams/end-of-stream.js:105:38)
    at Source.emit (events.js:315:20)
    at Extract.destroy (D:\scoop\wighawag\persist\nvm\nodejs\v14.0.0\node_modules\pnpm\dist\pnpm.cjs:82859:20)
    at Source.destroy (D:\scoop\wighawag\persist\nvm\nodejs\v14.0.0\node_modules\pnpm\dist\pnpm.cjs:82715:18)
    at Object.destroyer (internal/streams/destroy.js:166:59)
    at internal/streams/pipeline.js:58:19
    at internal/util.js:392:14
    at Source.<anonymous> (internal/streams/pipeline.js:84:7)
    at Source.<anonymous> (internal/util.js:392:14)
    at Source.onend (internal/streams/end-of-stream.js:95:49)
```

**Comment by wighawag** [comment]
Seems the same issue as : https://github.com/pnpm/pnpm/issues/3007

**Comment by zkochan** [comment]
Have you tried to update Node.js?

**Comment by wighawag** [comment]
Ha, yes did not realise I was on 14.0.0 (use nvm and though nvm install 14) would give me the latest. Thanks for looking into it
