### ISSUE TITLE
tslib module No match

### ISSUE THREAD

**Issue by pincman** [pnpm/pnpm#3342]
### Code to reproduce the issue:

```json
{
  "0 debug pnpm:scope": {
    "selected": 1
  },
  "1 error pnpm": {
    "errno": 1,
    "code": "ELIFECYCLE",
    "pkgid": "myweb@0.0.0",
    "stage": "dev",
    "script": "node ./build/theme/compile.js && vite",
    "pkgname": "myweb",
    "err": {
      "name": "Error",
      "message": "myweb@0.0.0 dev: `node ./build/theme/compile.js && vite`\nExit status 1",
      "code": "ELIFECYCLE",
      "stack": "Error: myweb@0.0.0 dev: `node ./build/theme/compile.js && vite`\nExit status 1\n    at EventEmitter.<anonymous> (/usr/local/pnpm-global/5/node_modules/.pnpm/pnpm@6.0.1/node_modules/pnpm/dist/pnpm.cjs:103104:18)\n    at EventEmitter.emit (events.js:315:20)\n    at ChildProcess.<anonymous> (/usr/local/pnpm-global/5/node_modules/.pnpm/pnpm@6.0.1/node_modules/pnpm/dist/pnpm.cjs:88678:16)\n    at ChildProcess.emit (events.js:315:20)\n    at maybeClose (internal/child_process.js:1048:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)"
    }
  }
}
```

### Expected behavior:
`pnpm i`  then run `vite dev`
```shell
 > node_modules/.pnpm/@antv+algorithm@0.1.8-beta.5/node_modules/@antv/algorithm/es/dijkstra.js:1:9: error: No matching export in "node_modules/.pnpm/tslib@1.14.1/node_modules/tslib/tslib.es6.js" for import "__spreadArray"
    1 │ import { __spreadArray } from "tslib";
      ╵          ~~~~~~~~~~~~~

 > node_modules/.pnpm/@antv+algorithm@0.1.8-beta.5/node_modules/@antv/algorithm/es/gaddi.js:3:9: error: No matching export in "node_modules/.pnpm/tslib@1.14.1/node_modules/tslib/tslib.es6.js" for import "__spreadArray"
    3 │ import { __spreadArray } from "tslib";
      ╵          ~~~~~~~~~~~~~

error when starting dev server:
Error: Build failed with 2 errors:
node_modules/.pnpm/@antv+algorithm@0.1.8-beta.5/node_modules/@antv/algorithm/es/dijkstra.js:1:9: error: No matching export in "node_modules/.pnpm/tslib@1.14.1/node_modules/tslib/tslib.es6.js" for import "__spreadArray"
node_modules/.pnpm/@antv+algorithm@0.1.8-beta.5/node_modules/@antv/algorithm/es/gaddi.js:3:9: error: No matching export in "node_modules/.pnpm/tslib@1.14.1/node_modules/tslib/tslib.es6.js" for import "__spreadArray"
    at failureErrorWithLog (/Users/nangongmo/Code/myweb/node_modules/.pnpm/esbuild@0.9.7/node_modules/esbuild/lib/main.js:1224:15)
    at buildResponseToResult (/Users/nangongmo/Code/myweb/node_modules/.pnpm/esbuild@0.9.7/node_modules/esbuild/lib/main.js:936:32)
    at /Users/nangongmo/Code/myweb/node_modules/.pnpm/esbuild@0.9.7/node_modules/esbuild/lib/main.js:1035:20
    at /Users/nangongmo/Code/myweb/node_modules/.pnpm/esbuild@0.9.7/node_modules/esbuild/lib/main.js:568:9
    at handleIncomingPacket (/Users/nangongmo/Code/myweb/node_modules/.pnpm/esbuild@0.9.7/node_modules/esbuild/lib/main.js:657:9)
    at Socket.readFromStdout (/Users/nangongmo/Code/myweb/node_modules/.pnpm/esbuild@0.9.7/node_modules/esbuild/lib/main.js:535:7)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:284:9)
    at Socket.Readable.push (_stream_readable.js:223:10)
 ERROR  Command failed with exit code 1.
```

### Actual behavior:
`yarn` and `yarn dev`  every thing is work fine

### Additional information:

 - `node -v` prints: v14.15.0
 - Windows, macOS, or Linux?: macOS

**Comment by Jungzl** [comment]
put this in your package.json
`  "resolutions": {
    "tslib": "^2.3.0"
  },`

**Comment by jpbourgeon** [comment]
@Jungzl  your suggestion didn't work for me
I also tried `public-hoist-pattern[]=tslib` without success

**Comment by Ivkaa** [comment]
same issue here, even showing in this starter template: https://github.com/thiswallz/rollup-react-starter-lib-ts/

**Comment by YizYah** [comment]
I managed to resolve the problem by installing `tslib` directly:
```
pnpm i tslib -w -D
```

**Comment by zkochan** [comment]
Closing for lack of a reproduction on a supported version.

A tslib resolution failure in a Vite project on pnpm 6.0.1, with no reproduction.

If you still hit this on the latest pnpm, please comment with a reproduction and we will reopen.

---
Written by an agent (Claude Code, claude-opus-5).
