### ISSUE TITLE
"EMFILE: too many open files" error at end of PNPM install in large monorepo

### ISSUE THREAD

**Issue by D4N14L** [pnpm/pnpm#3378]
### Expected behavior:
Successful install

### Actual behavior:
Unable to retrieve the log file due to it failing during write. Here is the output after running postinstall hooks in dependencies:
```
.../.pnpm/ws@0.4.32/node_modules/ws install: Done
.../node_modules/puppeteer install: Chromium downloaded to D:\dbs\el\odw\common\temp\node_modules\.pnpm\puppeteer@2.1.1\node_modules\puppeteer\.local-chromium\win64-722234
.../node_modules/puppeteer install: Done

Cannot link binary 'jest' of 'jest-cli' to 'D:\dbs\el\odw\common\temp\node_modules\.pnpm\@microsoft+gulp-core-build@3.17.12\node_modules\@microsoft\gulp-core-build\node_modules\.bin': binary of 'jest' is already linked

ERROR EMFILE: too many open files, open '<path to monorepo project>\package.json'

internal/fs/utils.js:269
    throw err;
    ^

Error: EMFILE: too many open files, open 'node_modules/.pnpm-debug.log'
    at Object.openSync (fs.js:462:3)
    at Object.writeFileSync (fs.js:1384:35)
    at process.<anonymous> (C:\Users\CBA-0421_123153\.rush\node-v12.21.0\pnpm-6.0.2\node_modules\pnpm\dist\pnpm.cjs:123320:10)
    at process.emit (events.js:326:22)
    at processEmit [as emit] (C:\Users\CBA-0421_123153\.rush\node-v12.21.0\pnpm-6.0.2\node_modules\pnpm\dist\pnpm.cjs:11973:37)
    at p
rocess.exit (internal/process/per_thread.js:168:15)
    at Timeout._onTimeout (C:\Users\CBA-0421_123153\.rush\node-v12.21.0\pnpm-6.0.2\node_modules\pnpm\dist\pnpm.cjs:11839:30)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) {
  errno: -4066,
  syscall: 'open',
  code: 'EMFILE',
  path: 'node_modules/.pnpm-debug.log'
}


The command failed:

 D:\dbs\el\odw\common\temp\pnpm-local\node_modules\.bin\pnpm install --store D:\dbs\Cx\odw\rush-temp\pnpm-store --frozen-lockfile --recursive --link-workspace-packages false

ERROR: Error: The command failed with exit code 1
```

### Additional information:

 - `node -v` prints: 12.22.1
 - Windows, macOS, or Linux?: Windows

**Comment by D4N14L** [comment]
@zkochan This bug is blocking our upgrade from PNPM 5 -> 6 :(

**Comment by zkochan** [comment]
In pnpm v6 we removed graceful-fs from our dependencies, which handles these issues. We could probably limit the number of concurrent package.json file reads.

**Comment by zkochan** [comment]
@D4N14L check if pnpm@6.1.0-202104230041 solves the issue

**Comment by D4N14L** [comment]
Just as an update, I'm still (occasionally) seeing this:

```
ERROR  EMFILE: too many open files, open '<PathToRushRepo>\common\temp\pnpm-store\v3\files\bd\a16d8758a075d2fafd8e106bc638b511f54e44aeae8fb46fb292ed397e8f7b23b780309c36d5569f3a81ed0bdaa15ea91451ca5fba9249a16e133c338233a3'
 ```

So it does still seem like this is an issue, but now it's in a different part of the code.

**Comment by zkochan** [comment]
:ship: 6.2.4

**Comment by D4N14L** [comment]
Unfortunately this seems to have come back, this time complaining about too many open files when attempting to open the log, resulting in the log not getting generated in the node_modules dir:

```console
 ERROR  EMFILE: too many open files, scandir '/home/daniel/workspace/my-rush-repo/common/temp/node_modules'

internal/fs/utils.js:269
    throw err;
    ^

Error: EMFILE: too many open files, open 'node_modules/.pnpm-debug.log'
    at Object.openSync (fs.js:462:3)
    at Object.writeFileSync (fs.js:1384:35)
    at process.<anonymous> (/home/daniel/.rush/node-v12.22.2/pnpm-6.10.3/node_modules/pnpm/dist/pnpm.cjs:124819:12)
    at process.emit (events.js:326:22)
    at processEmit [as emit] (/home/daniel/.rush/node-v12.22.2/pnpm-6.10.3/node_modules/pnpm/dist/pnpm.cjs:12200:39)
    at process.exit (internal/process/per_thread.js:168:15)
    at Timeout._onTimeout (/home/daniel/.rush/node-v12.22.2/pnpm-6.10.3/node_modules/pnpm/dist/pnpm.cjs:12062:32)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) {
  errno: -24,
  syscall: 'open',
  code: 'EMFILE',
  path: 'node_modules/.pnpm-debug.log'
}
```

**Comment by zkochan** [comment]
I don't understand how this could happen because `@pnpm/file-reporter` uses `graceful-fs`.

**Comment by D4N14L** [comment]
Yes, I opened up `pnpm.cjs` to the specified line and it does look like it should be using `graceful-fs`. Looking around the file though, it looks like the install failed earlier with a non-zero exit code and thus reaches this failure when attempting to write the debug log. At the end of the console output, I get this error (without a callstack):
` ERROR  EMFILE: too many open files, scandir '/home/daniel/workspace/odsp-web/common/temp/node_modules'`

**Comment by D4N14L** [comment]
Ah sorry, it must be the same error... I piped the verbose output to a file and this was at the end of the install:
```js
{"time":1626728365871,"hostname":"DESKTOP-O4I5B9G","pid":4896,"level":"error","name":"pnpm","errno":-24,"code":"EMFILE","syscall":"scandir","path":"/home/daniel/workspace/my-rush-repo/common/temp/node_modules","err":{"name":"Error","message":"EMFILE: too many open files, scandir '/home/daniel/workspace/my-rush-repo/common/temp/node_modules'","code":"EMFILE","stack":"Error: EMFILE: too many open files, scandir '/home/daniel/workspace/my-rush-repo/common/temp/node_modules'"}}
```

**Comment by zkochan** [comment]
I have reproduced it while running pnpm in a docker container.

**Comment by D4N14L** [comment]
@zkochan that actually sounds about right, I was encountering this error when using WSL 2 which is apparently based on Docker.

**Comment by zkochan** [comment]
:ship: 6.12.0-0
