### ISSUE TITLE
[DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed.

### ISSUE THREAD

**Issue by Jack-Works** [pnpm/pnpm#3379]
### Node: 16.0.0

```
pnpm i
Scope: all 9 workspace projects
(node:9460) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
Lockfile is up-to-date, resolution step is skipped
Already up-to-date
```

**Comment by vladmandic** [comment]
with a trace:

```log
node --trace-deprecation ./pnpm.cjs update
(node:615263) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
    at emitRecursiveRmdirWarning (node:internal/fs/utils:784:13)
    at Object.rmdir (node:internal/fs/promises:521:5)
    at module2.exports (/home/vlado/.nvm/versions/node/v16.0.0/pnpm-global/5/node_modules/.pnpm/pnpm@6.0.2/node_modules/pnpm/dist/pnpm.cjs:61606:16)
    at safeRmdir (/home/vlado/.nvm/versions/node/v16.0.0/pnpm-global/5/node_modules/.pnpm/pnpm@6.0.2/node_modules/pnpm/dist/pnpm.cjs:66834:13)
    at canLinkToSubdir (/home/vlado/.nvm/versions/node/v16.0.0/pnpm-global/5/node_modules/.pnpm/pnpm@6.0.2/node_modules/pnpm/dist/pnpm.cjs:66828:13)
    at async storePathRelativeToHome (/home/vlado/.nvm/versions/node/v16.0.0/pnpm-global/5/node_modules/.pnpm/pnpm@6.0.2/node_modules/pnpm/dist/pnpm.cjs:66799:9)
    at async default_1 (/home/vlado/.nvm/versions/node/v16.0.0/pnpm-global/5/node_modules/.pnpm/pnpm@6.0.2/node_modules/pnpm/dist/pnpm.cjs:66785:14)
    at async createOrConnectStoreController (/home/vlado/.nvm/versions/node/v16.0.0/pnpm-global/5/node_modules/.pnpm/pnpm@6.0.2/node_modules/pnpm/dist/pnpm.cjs:85951:22)
    at async handler (/home/vlado/.nvm/versions/node/v16.0.0/pnpm-global/5/node_modules/.pnpm/pnpm@6.0.2/node_modules/pnpm/dist/pnpm.cjs:114361:19)
    at async Timeout._onTimeout (/home/vlado/.nvm/versions/node/v16.0.0/pnpm-global/5/node_modules/.pnpm/pnpm@6.0.2/node_modules/pnpm/dist/pnpm.cjs:123639:22)
```

seems that issue is at `Object.rmdir (node:internal/fs/promises:521:5)`, not `pnpm` itself

**Comment by thynson** [comment]
> seems that issue is at Object.rmdir (node:internal/fs/promises:521:5), not pnpm itself 
Calling `rmdir` of `fs/promises` with `recursive` is also deprecated in v16, they just share one deprecation warning.

**Comment by vladmandic** [comment]
true, `pnpm` should be switched to use `rm` instead of `rmdir`

**Comment by thynson** [comment]
Just check the doc, and found node v12 did not have `fsPromises.rm` yet. So this issue will be a bit more complicated.

**Comment by vladmandic** [comment]
that is not a huge problem, just checking for `undefined` in `if` statement.  

but i did a quick scan and don't see a single explicit call to `fs.rmdir` from `pnpm`.  
looking at compiled `pnpm.cjs`, it seems that call comes from `rimraf`, so it should be fixed upstream.

**Comment by zkochan** [comment]
It can be fixed here: https://github.com/zkochan/packages/blob/main/rimraf/index.js

**Comment by vladmandic** [comment]
@zkochan yes, exactly. will you create an update and publish it as you're the package maintainer?

**Comment by zkochan** [comment]
I will
