### ISSUE TITLE
TypeError: Invalid comparator: ^

### ISSUE THREAD

**Issue by benmccann** [pnpm/pnpm#3495]
### pnpm version: all versions

My CI logs show I'm on 6.6.2:

> npm install -g pnpm
/opt/hostedtoolcache/node/12.22.1/x64/bin/pnpm -> /opt/hostedtoolcache/node/12.22.1/x64/lib/node_modules/pnpm/bin/pnpm.cjs
/opt/hostedtoolcache/node/12.22.1/x64/bin/pnpx -> /opt/hostedtoolcache/node/12.22.1/x64/lib/node_modules/pnpm/bin/pnpx.cjs
>+ pnpm@6.6.2
added 1 package in 0.676s

### Code to reproduce the issue:

We experienced a breakage when putting `workspace:^` as the version for `devDependencies` or `peerDependencies`

https://github.com/sveltejs/kit/pull/1620 and https://github.com/sveltejs/kit/pull/1434 both broke for us as a result

### Expected behavior:

`workspace:^` should work as described in https://pnpm.io/workspaces#publishing-workspace-packages

### Actual behavior:

https://github.com/sveltejs/kit/runs/2722521240

```
🦋  error TypeError: Invalid comparator: ^
🦋  error     at Comparator.parse (/home/runner/work/kit/kit/node_modules/.pnpm/semver@5.7.1/node_modules/semver/semver.js:754:11)
🦋  error     at new Comparator (/home/runner/work/kit/kit/node_modules/.pnpm/semver@5.7.1/node_modules/semver/semver.js:737:8)
🦋  error     at Range.<anonymous> (/home/runner/work/kit/kit/node_modules/.pnpm/semver@5.7.1/node_modules/semver/semver.js:925:12)
🦋  error     at Array.map (<anonymous>)
🦋  error     at Range.parseRange (/home/runner/work/kit/kit/node_modules/.pnpm/semver@5.7.1/node_modules/semver/semver.js:924:13)
🦋  error     at Range.<anonymous> (/home/runner/work/kit/kit/node_modules/.pnpm/semver@5.7.1/node_modules/semver/semver.js:867:17)
🦋  error     at Array.map (<anonymous>)
🦋  error     at new Range (/home/runner/work/kit/kit/node_modules/.pnpm/semver@5.7.1/node_modules/semver/semver.js:866:40)
🦋  error     at versionPackage (/home/runner/work/kit/kit/node_modules/.pnpm/@changesets+apply-release-plan@5.0.0/node_modules/@changesets/apply-release-plan/dist/apply-release-plan.cjs.dev.js:160:9)
🦋  error     at /home/runner/work/kit/kit/node_modules/.pnpm/@changesets+apply-release-plan@5.0.0/node_modules/@changesets/apply-release-plan/dist/apply-release-plan.cjs.dev.js:312:12
```

### Additional information:

 - `node -v` prints: 12.22.1
 - Windows, macOS, or Linux?: Linux

**Comment by zkochan** [comment]
This is an issue with changesets. Changesets currently only support workspace ranges (e.g. `workspace:^1.2.3`)

**Comment by mcmxcdev** [comment]
Unfortunately still an issue with changesets, open issue to track: https://github.com/changesets/changesets/issues/598

There's also a workaround listed.

**Comment by zkochan** [comment]
Closing for lack of a reproduction on a supported version.

A semver parsing error from pnpm 6.6 in 2021, with no reproduction on a supported version.

If you still hit this on the latest pnpm, please comment with a reproduction and we will reopen.

---
Written by an agent (Claude Code, claude-opus-5).
