### ISSUE TITLE
Error: Cannot find module

### ISSUE THREAD

**Issue by SilverFox008** [pnpm/pnpm#3524]
### Code to reproduce the issue:

Copying items to other drive letters will cause some problems

Run pnpm install on disk D, and then copy the project to Disk C for execution

```
const express = require('express')
```

### Expected behavior:
Project running successfully

### Actual behavior:
Error: Cannot find module 'express'
```
PS C:\test\pnpm> node index.js
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'express'
Require stack:
- C:\test\pnpm\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\test\pnpm\index.js:5:17)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'C:\\test\\pnpm\\index.js' ]
}
```

 - `node -v` prints: 12.22.1
 - Windows, macOS, or Linux?: Windows10

**Comment by zkochan** [comment]
On Windows, pnpm uses junctions to link dependencies in node_modules. Unlike symlinks, junctions specify absolute path, not relative path, so when the location of the project changes, the links are broken. See https://github.com/pnpm/pnpm/discussions/3516
