### ISSUE TITLE
Jest require path is strange within monorepo

### ISSUE THREAD

**Issue by evantahler** [pnpm/pnpm#3582]
The version of jest installed by `pnpm` is having some problems requiring the proper files.   

Testing with the version of jest installed by pnpm:

```
➜  ui-components git:(jest-update) ✗ ./node_modules/.bin/jest --version
27.0.6
➜  ui-components git:(jest-update) ✗ ./node_modules/.bin/jest
 FAIL  __tests__/test.tsx
  ● Test suite failed to run

    ReferenceError: global is not defined

      at Object.<anonymous> (../../node_modules/.pnpm/graceful-fs@4.2.6/node_modules/graceful-fs/graceful-fs.js:92:1)
      at Object.<anonymous> (../../node_modules/.pnpm/expect@27.0.6/node_modules/expect/build/toThrowMatchers.js:10:24)
      at Object.<anonymous> (../../node_modules/.pnpm/expect@27.0.6/node_modules/expect/build/index.js:35:48)
      at TestScheduler.scheduleTests (../../node_modules/.pnpm/@jest+core@27.0.6/node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (../../node_modules/.pnpm/@jest+core@27.0.6/node_modules/@jest/core/build/runJest.js:387:19)
      at _run10000 (../../node_modules/.pnpm/@jest+core@27.0.6/node_modules/@jest/core/build/cli/index.js:408:7)
      at runCLI (../../node_modules/.pnpm/@jest+core@27.0.6/node_modules/@jest/core/build/cli/index.js:261:3)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.342 s, estimated 3 s
Ran all test suites.
```

However, using a globally installed version of jest works just fine:

```
➜  ui-components git:(jest-update) ✗ npm install -g jest

added 328 packages, and audited 329 packages in 6s

24 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
➜  ui-components git:(jest-update) ✗ jest --version
27.0.6
➜  ui-components git:(jest-update) ✗ jest
 PASS  __tests__/test.tsx
  ✓ has correct welcome text (28 ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        2.414 s
Ran all test suites.
```

What's really interesting is that if we run jest without using the pnpm symlink, it also works OK:

```
➜  ui-components git:(jest-update) ✗ ls -la ./node_modules/jest
lrwxr-xr-x  1 evan  staff  57 Jul  6 10:56 ./node_modules/jest -> ../../../node_modules/.pnpm/jest@27.0.6/node_modules/jest
➜  ui-components git:(jest-update) ✗ ../../node_modules/.pnpm/jest@27.0.6/node_modules/jest/bin/jest.js
 PASS  __tests__/test.tsx
  ✓ has correct welcome text (28 ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        2.392 s, estimated 3 s
Ran all test suites.
```

### Code to reproduce the issue:

The `@grouparoo/ui-components` package here: https://github.com/grouparoo/grouparoo/tree/main/ui/ui-components

### Expected behavior:

Jest works and can require all of it's files

### Actual behavior:

`ReferenceError: global is not defined`

### Additional information:

 - `node -v` prints: v15.14.0
 - Windows, macOS, or Linux?: OSX and Ubuntu (you can see CI here -> https://app.circleci.com/pipelines/github/grouparoo/grouparoo/9896/workflows/bb5e8f77-5920-4910-81bf-a2ff00f09d11/jobs/207008)

**Comment by evantahler** [comment]
Closing!

This problem was created by having 2 versions of jest installed in the same monorepo.  Matching jest versions in all sub-packages fixed this problem.
