### ISSUE TITLE
Running `pnpm install` in a workspace fails if `public-hoist-pattern` has changed

### ISSUE THREAD

**Issue by denenr** [pnpm/pnpm#3600]
### Code to reproduce the issue:

Run this bash script in an empty directory:

```bash

# Set up a default pnpm workspace
touch pnpm-workspace.yaml

# Create a package with at least one dependency, else installation will be skipped (depends on itself, but could depend on any package)
mkdir pkg
printf '%s' '{"name":"pkg","version":"0.1.0","private":true,"dependencies":{"pkg":"workspace:*"}}' > pkg/package.json

# Run initial pnpm install
pnpm install

# Run pnpm install again (generates node_modules/.modules.yaml)
pnpm install

# Change public-hoist-pattern
printf '%s' 'public-hoist-pattern[]=' > .npmrc

# Attempt to update the installation
pnpm install
```

`node_modules/.pnpm-debug.log`:
```json
{
  "0 debug pnpm:scope": {
    "selected": 1,
    "total": 1,
    "workspacePrefix": "<omitted>"
  },
  "1 error pnpm": {
    "code": "ERR_PNPM_PUBLIC_HOIST_PATTERN_DIFF",
    "err": {
      "name": "Error",
      "message": "This modules directory was created using a different public-hoist-pattern value. Run \"pnpm install\" to recreate the modules directory.",
      "code": "ERR_PNPM_PUBLIC_HOIST_PATTERN_DIFF",
      "stack": "Error: This modules directory was created using a different public-hoist-pattern value. Run \"pnpm install\" to recreate the modules directory.\n    at validateModules (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:92342:15)\n    at Object.getContext [as default] (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:92255:34)\n    at async Object.mutateModules (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:114767:19)\n    at async Object.recursive [as default] (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:117322:29)\n    at async Object.handler [as default] (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:117619:11)\n    at async /usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:126856:20\n    at async run (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:126831:34)\n    at async runPnpm (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:127041:5)\n    at async /usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:127033:7"
    }
  }
}
```

### Expected behavior:

`pnpm install` should update `public-hoist-pattern` and hoist/unhoist packages as specified.

### Actual behavior:

An error message is returned prompting the user to run `pnpm install` again.

Also, the first two installs should be identical because nothing changes, but only the second one generates `node_modules/.modules.yaml`. This extra state could potentially cause obscure errors, and definitely confused my initial attempts at minimal reproduction.

### Additional information:

 - `node -v` prints: 16.5.0
 - Tested on Windows and Linux through WSL

**Comment by xuchaobei** [comment]
Any updates?

**Comment by a2k42** [comment]
It appears that `pnpm deploy` has the same problem:

```bash
$ pnpm --filter nuxt-app deploy ../deploy
ERR_PNPM_PUBLIC_HOIST_PATTERN_DIFF  This modules directory was created using a different public-hoist-pattern value. Run "pnpm install" to recreate the modules directory.
```

In this case, it is not clear what directory is being referred to as the deploy target doesn't have a `node_modules` folder due to the error.

**Comment by s-herbert** [comment]
same issue, would be nice if solution was implemented.

**Comment by 8bu** [comment]
any solution for this issue?

**Comment by max13fr** [comment]
The current solution is to drop node_modules in the same directory as your pnpm-workspace.yaml file.

Then `pnpm install` should works again

**Comment by Heartnett** [comment]
> The current solution is to drop the node_modules directory (that lives in the same directory of your pnpm-workspace.yaml file).
> 
> Then `pnpm install` should work again

Your solution did not work, for me at least.

**Comment by zkochan** [comment]
This no longer reproduces on current pnpm, so closing.

Verified on pnpm 12.5.1: adding a publicHoistPattern to an existing workspace and reinstalling succeeds.

If you still hit this on the latest pnpm, please comment with a reproduction and we will reopen.

---
Written by an agent (Claude Code, claude-opus-5).
