### ISSUE TITLE
pnpm is currently broken in the official node docker containers

### ISSUE THREAD

**Issue by wzrdtales** [pnpm/pnpm#3625]
### pnpm version:

6.10.3

### Code to reproduce the issue:

pnpm i msgpack

### Expected behavior:

works

### Actual behavior:

```
Packages: +2
++
node_modules/.pnpm/msgpack@1.0.3/node_modules/msgpack: Running install script, failed in 205ms
.../msgpack@1.0.3/node_modules/msgpack install$ node-gyp rebuild
│ gyp info it worked if it ends with ok
│ gyp info using node-gyp@8.1.0
│ gyp info using node@14.17.1 | linux | x64
│ gyp ERR! find Python 
│ gyp ERR! find Python Python is not set from command line or npm configuration
│ gyp ERR! find Python Python is not set from environment variable PYTHON
│ gyp ERR! find Python checking if "python3" can be used
│ gyp ERR! find Python - executable path is "/usr/bin/python3"
│ gyp ERR! find Python - version is "3.5.3"
│ gyp ERR! find Python - version is 3.5.3 - should be >=3.6.0
│ gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
│ gyp ERR! find Python checking if "python" can be used
│ gyp ERR! find Python - executable path is "/usr/bin/python"
│ gyp ERR! find Python - version is "2.7.13"
│ gyp ERR! find Python - version is 2.7.13 - should be >=3.6.0
│ gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
│ gyp ERR! find Python 
│ gyp ERR! find Python **********************************************************
│ gyp ERR! find Python You need to install the latest version of Python.
│ gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
│ gyp ERR! find Python you can try one of the following options:
│ gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
│ gyp ERR! find Python   (accepted by both node-gyp and npm)
│ gyp ERR! find Python - Set the environment variable PYTHON
│ gyp ERR! find Python - Set the npm configuration variable python:
│ gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
│ gyp ERR! find Python For more information consult the documentation at:
│ gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
│ gyp ERR! find Python **********************************************************
│ gyp ERR! find Python 
│ gyp ERR! configure error 
│ gyp ERR! stack Error: Could not find any Python installation to use
│ gyp ERR! stack     at PythonFinder.fail (/usr/local/lib/node_modules/pnpm/dist/node_modules/node-gyp/lib/find-python.js:330:47)
│ gyp ERR! stack     at PythonFinder.runChecks (/usr/local/lib/node_modules/pnpm/dist/node_modules/node-gyp/lib/find-python.js:159:21)
│ gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/pnpm/dist/node_modules/node-gyp/lib/find-python.js:266:16)
│ gyp ERR! stack     at PythonFinder.execFileCallback (/usr/local/lib/node_modules/pnpm/dist/node_modules/node-gyp/lib/find-python.js:297:7)
│ gyp ERR! stack     at ChildProcess.exithandler (child_process.js:310:7)
│ gyp ERR! stack     at ChildProcess.emit (events.js:375:28)
│ gyp ERR! stack     at maybeClose (internal/child_process.js:1055:16)
│ gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
│ gyp ERR! System Linux 5.12.14-arch1-1
│ gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/pnpm/dist/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
│ gyp ERR! cwd /node_modules/.pnpm/msgpack@1.0.3/node_modules/msgpack
│ gyp ERR! node -v v14.17.1
│ gyp ERR! node-gyp -v v8.1.0
│ gyp ERR! not ok 
└─ Failed in 206ms
Progress: resolved 2, reused 2, downloaded 0, added 0, done
```

### Additional information:

root@ddcd8f034ed9:/# node -v
v14.17.1

in a docker container, linux

when I run `npm i msgpack` in the same container everything works perfect.

This is using the official node docker container node:14

**Comment by wzrdtales** [comment]
this seems to be a misbehavior of pnpm in general

```
│ gyp ERR! stack Error: Could not find any Python installation to use
│ gyp ERR! stack     at PythonFinder.fail (/usr/local/lib/node_modules/pnpm/dist/node_modules/node-gyp/lib/find-python.js:330:47)
│ gyp ERR! stack     at PythonFinder.runChecks (/usr/local/lib/node_modules/pnpm/dist/node_modules/node-gyp/lib/find-python.js:159:21)
│ gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/pnpm/dist/node_modules/node-gyp/lib/find-python.js:266:16)
│ gyp ERR! stack     at PythonFinder.execFileCallback (/usr/local/lib/node_modules/pnpm/dist/node_modules/node-gyp/lib/find-python.js:297:7)
```

this script seems to be of pnpm itself. however this is nothing pnpm should ever get involved with.

**Comment by wzrdtales** [comment]
seems like this is node-gyp, which pnpm has picked a bit too early. the ecosystem hasn't reacted properly yet, so the official node docker container is not up to date enough.

**Comment by wzrdtales** [comment]
https://github.com/nodejs/node-gyp/issues/2392

**Comment by zkochan** [comment]
This no longer reproduces on current pnpm, so closing.

Verified on pnpm 12: a native package builds with node-gyp inside the official node image, and better-sqlite3 builds to completion on pnpm 12.5.1.

If you still hit this on the latest pnpm, please comment with a reproduction and we will reopen.

---
Written by an agent (Claude Code, claude-opus-5).
