### ISSUE TITLE
pnpm and Angular (ngcc) do not play well together

### ISSUE THREAD

**Issue by athoma13** [pnpm/pnpm#3686]
### Code to reproduce the issue:
unzip [my-app.zip](https://github.com/pnpm/pnpm/files/7011209/my-app.zip)
pnpm i
ng serve

### Expected behavior: 
Should not have any errors when you open the browser window

### Actual behavior: 
ERROR TypeError: Cannot read property 'bindingStartIndex' of null
    at Module.ɵɵelementStart (core.js:14847)
    at AppComponent_Template (app.component.html:1)
    at executeTemplate (core.js:9598)
    at renderView (core.js:9402)
    at renderComponent (core.js:10682)
    at renderChildComponents (core.js:9267)
    at renderView (core.js:9427)
    at ComponentFactory$1.create (core.js:25169)
    at ApplicationRef.bootstrap (core.js:29671)
    at core.js:29363

### Workaround:
restart ng serve **OR** use npm (yikes!)

### Additional information:
 - `node -v` prints: 14.17.5
 - Linux - Ubuntu 21.04
 - `npm -v` prints: 7.20.6

### Notes
* I absolute love pnpm, and believe that ngcc is likely the culprit in all this, as this is obviously a state issue (building twice fixed all issues).
* This is hugely annoying in a 
CI build as you require building twice for a successful build
* This behaviour also manifests itself (on a different project) as a 'Does not have 'ɵmod' property' error see [here](https://stackoverflow.com/questions/68827779/does-not-have-%C9%B5mod-property-errors) the workarounds mentioned fixes the issue.
* This behaviour can also cause the following (on a different project)
`An error occurred during the build:
Error: Tried to overwrite .../node_modules/.pnpm/@angular+material@12.2.1_a1ce8319c77965cf9aafd2eaeb70daa7/node_modules/@angular/animations/animations.d.ts.__ivy_ngcc_bak with an ngcc back up file, which is disallowed.
    at NewEntryPointFileWriter.InPlaceFileWriter.writeFileAndBackup (.../node_modules/.pnpm/@angular+compiler-cli@12.2.1_24e73589fa2ce0fc98fea59db79eca5d/node_modules/@angular/compiler-cli/ngcc/src/writing/in_place_file_writer.js:58:27)
    at NewEntryPointFileWriter.writeFile (.../node_modules/.pnpm/@angular+compiler-cli@12.2.1_24e73589fa2ce0fc98fea59db79eca5d/node_modules/@angular/compiler-cli/ngcc/src/writing/new_entry_point_file_writer.js:128:53)
    at .../node_modules/.pnpm/@angular+compiler-cli@12.2.1_24e73589fa2ce0fc98fea59db79eca5d/node_modules/@angular/compiler-cli/ngcc/src/writing/new_entry_point_file_writer.js:47:69
    at Array.forEach (<anonymous>)
    at NewEntryPointFileWriter.writeBundle (.../node_modules/.pnpm/@angular+compiler-cli@12.2.1_24e73589fa2ce0fc98fea59db79eca5d/node_modules/@angular/compiler-cli/ngcc/src/writing/new_entry_point_file_writer.js:47:30)
    at writeBundle (.../node_modules/.pnpm/@angular+compiler-cli@12.2.1_24e73589fa2ce0fc98fea59db79eca5d/node_modules/@angular/compiler-cli/ngcc/src/execution/create_compile_function.js:58:36)
    at .../node_modules/.pnpm/@angular+compiler-cli@12.2.1_24e73589fa2ce0fc98fea59db79eca5d/node_modules/@angular/compiler-cli/ngcc/src/execution/create_compile_function.js:65:25
    at SingleProcessExecutorSync.SingleProcessorExecutorBase.doExecute (.../node_modules/.pnpm/@angular+compiler-cli@12.2.1_24e73589fa2ce0fc98fea59db79eca5d/node_modules/@angular/compiler-cli/ngcc/src/execution/single_process_executor.js:36:17)
    at .../node_modules/.pnpm/@angular+compiler-cli@12.2.1_24e73589fa2ce0fc98fea59db79eca5d/node_modules/@angular/compiler-cli/ngcc/src/execution/single_process_executor.js:57:59
    at SyncLocker.lock (.../node_modules/.pnpm/@angular+compiler-cli@12.2.1_24e73589fa2ce0fc98fea59db79eca5d/node_modules/@angular/compiler-cli/ngcc/src/locking/sync_locker.js:34:24)
    at SingleProcessExecutorSync.execute (.../node_modules/.pnpm/@angular+compiler-cli@12.2.1_24e73589fa2ce0fc98fea59db79eca5d/node_modules/@angular/compiler-cli/ngcc/src/execution/single_process_executor.js:57:27)
    at Object.mainNgcc (.../node_modules/.pnpm/@angular+compiler-cli@12.2.1_24e73589fa2ce0fc98fea59db79eca5d/node_modules/@angular/compiler-cli/ngcc/src/main.js:74:25)
    at Object.process (.../node_modules/.pnpm/@angular+compiler-cli@12.2.1_24e73589fa2ce0fc98fea59db79eca5d/node_modules/@angular/compiler-cli/ngcc/index.js:29:23)
    at NgccProcessor.processModule (.../node_modules/.pnpm/@ngtools+webpack@12.2.1_69a9b0994bc968351bdb9888c8040475/node_modules/@ngtools/webpack/src/ngcc_processor.js:175:16)
    at .../node_modules/.pnpm/@ngtools+webpack@12.2.1_69a9b0994bc968351bdb9888c8040475/node_modules/@ngtools/webpack/src/ivy/host.js:146:18
    at .../node_modules/.pnpm/@ngtools+webpack@12.2.1_69a9b0994bc968351bdb9888c8040475/node_modules/@ngtools/webpack/src/ivy/host.js:76:24
An unhandled exception occurred: Tried to overwrite .../node_modules/.pnpm/@angular+material@12.2.1_a1ce8319c77965cf9aafd2eaeb70daa7/node_modules/@angular/animations/animations.d.ts.__ivy_ngcc_bak with an ngcc back up file, which is disallowed.`

**Comment by tripodsgames** [comment]
Temporary fix:
Add a `postinstall` to the `package.json` with the command:
ng build

![image](https://user-images.githubusercontent.com/11417768/130234966-3ba61bff-7976-4661-b78a-a663933388ce.png)

**Comment by begandroide** [comment]
Hi! I'm also facing the same issue with `MatTooltipModule`, i used workaround showd with postinstall and works fine. But i has a question: this workaround could has a problem? 

Regards, and thank by advanced

**Comment by stanciupaul** [comment]
Hi. Any update on this?

**Comment by DzmVasileusky** [comment]
@stanciupaul try adding `node-linker=hoisted` to `.npmrc`
