### ISSUE TITLE
EPERM: operation not permitted, chmod

### ISSUE THREAD

**Issue by hronro** [pnpm/pnpm#3699]
### Code to reproduce the issue:

```
 ERROR  EPERM: operation not permitted, chmod '/Users/hronro/Projects/my-project/node_modules/.pnpm/rimraf@3.0.2/node_modules/rimraf/bin.js'
at pnpm/rimraf
```

### Additional information:

 - `node -v` prints: v16.6.2
 - Windows, macOS, or Linux?: macOS

**Comment by HenrijsS** [comment]
Same here:
` EPERM  EPERM: operation not permitted, chmod '/Users/henry/Documents/_DEV/_WEB/_Sites/my-project/node_modules/.pnpm/typescript@4.4.2/node_modules/typescript/bin/tsc'

pnpm@6.14.7
node@14.17.0
macOS@11.5.2

**Comment by m1heng** [comment]
Had same issue, but worked after deleted all content-addressable store.
Btw I don't know if its relevant that I am using M1 mac.

**Comment by hronro** [comment]
@m1heng Same on Intel mac

**Comment by m1heng** [comment]
And also I have two repo using different npm registry, but using the same store.
I think it is possible to find a reproduce way.

**Comment by keyding** [comment]
I have the same problem:

`EPERM: operation not permitted, chmod '/Users/xxxx/.pnpm-store/v3/tmp/_npx/93724/5/node_modules/.pnpm/registry.npmmirror.com+typescript@3.9.10/node_modules/typescript/bin/tsc'`

pnpm@6.23.2
node@14.17.2
macOS@12

**Comment by zkochan** [comment]
What command were you running?

**Comment by OysterD3** [comment]
> What command were you running?

I got this whenever I run `pnpm i`

**Comment by zkochan** [comment]
I can't find any code that runs chmod on those files. The exec files get the executable permission when they get unpacked to the global content-addressable store. After that, they are not modified, just hard links are created that point to them.

Maybe if you download the repo, compile it and run install via `node <path to repo>/packages/pnpm/lib/pnpm.js install`, you'll get a stack trace to the place where it happens.

**Comment by hronro** [comment]
@zkochan 
I fixed this by deleting the whole pnpm global cache directory.
I guess there are some files with incorrect permissions in the global cache directory.

**Comment by zkochan** [comment]
This may be related: https://github.com/pnpm/pnpm/issues/2343#issuecomment-893486787

>I had an issue where mkdirp@1.0.4/node_modules/mkdirp/bin/cmd.js ended up with root:wheel ownership. That caused me to get ERROR  EPERM: operation not permitted, chmod '/path/to/my/project/node_modules/mkdirp/bin/cmd.js' when attempting to pnpm install. Running rm -rf node_modules in my project and reinstalling the package didn't fix it nor did trying to pnpm install mkdirp in a new/empty test project, but rm -rf node_modules && rm -rf $HOME/.pnpm-store and then reinstalling did fix it. So my guess is some files in that package had gotten corrupted in the store somehow.

**Comment by m1heng** [comment]
Just a guess.
Since permissions are shared between original file and its hard links, what if packages' install scripts (or pnpm did, or other tools) changed its file's permission in behave of current user in certain repo, and this will leads to an error when another user is trying to install packages in another repo with same dependency.

**Comment by zkochan** [comment]
It might be possible. Can we make the store readonly?

**Comment by zkochan** [comment]
Looks like on Linux a hard link is created even if the user has no permissions to the file.

All these errors happened with bin files, which are read only here:

https://github.com/pnpm/cmd-shim/blob/51909b72a85ba5c5ed796eafed570a6beb4fa520/src/index.ts#L265

So I think that is the only place where the exception may happen. But I would expect a `EACCES: permission denied, open` error, not a `chmod` error. I don't see any code that runs chmod on those files.

**Comment by andyg0808** [comment]
Is it possible that
https://github.com/pnpm/pnpm/blob/1a3126e0bc754679232dea8ee29ed966be455f81/packages/cafs/src/index.ts#L64 
is setting the permissions to be user-writable (`755` to be precise) on the files in the CAFS as they get written in?

**Comment by caoxiemeihao** [comment]
After i deleted the `/Users/${user}/.pnpm-store` directory, re-run `pnpm i` in my project and it worked.  
May be this command really needs. #2343

**Comment by wflixu** [comment]
I have same question
![image](https://user-images.githubusercontent.com/37231473/186611060-0dfd0287-e304-4ab4-b92f-8c11be08e4d7.png)

**Comment by shaodahong** [comment]
I use `sudo pnpm install` resolve it

**Comment by milliephanillie** [comment]
> deleting the whole pnpm global cache directory.

ok but how did you do that?

**Comment by mrsaleh** [comment]
Even with an administrator commandline on windows I get the same error. I got the same error on several projects , and I couldn't resolve it , so sadly I had to get back to the old npm. 
Windows 10
Nodejs v18.15.0
Nextjs

**Comment by DreamEcho100** [comment]
> After i deleted the `/Users/${user}/.pnpm-store` directory, re-run `pnpm i` in my project and it worked. May be this command really needs. #2343

For me in windows, I had to remove the `pnpm` folder on the `%USERPROFILE%\AppData\Local` path

**Comment by DavidVaness** [comment]
just ran into this issue today

**Comment by ArianHamdi** [comment]
I received this error message today. In my case I reinstalled windows os and it shows this error when running pnpm install on the drive where the pnpm store was created in the previous OS (it works fine in adminstrator mode without any errors). After removing .pnpm-store it was fixed.

**Comment by yairEO** [comment]
Hi, I get this error: `operation not permitted, lstat 'C:\Users\foo'` 

But my current *Windows* user is another name (both are admin-level users)

I've just installed `pnpm` on my current Windows user.

**Comment by jennysol** [comment]
I have the same problem too:

EPERM: operation not permitted, chmod '/Users/xxxx/.pnpm-store/v3/tmp/_npx/93724/5/node_modules/.pnpm/registry.npmmirror.com+typescript@3.9.10/node_modules/typescript/bin/tsc'

pnpm@6.23.2
node@14.17.2
macOS@12

**Comment by Elvincth** [comment]
fixed this problem after running `pnpm store prune` See: https://pnpm.io/cli/store

**Comment by Elvincth** [comment]
fixed this problem after running `pnpm store prune` See: https://pnpm.io/cli/store

**Comment by HironTez** [comment]
Downgrading to pnpm 7 fixed it for me `npm i -g pnpm@7`.
Looks like pnpm 8 is so fast that Windows unlocks files after using them slower than pnpm tries to use them again.

**Comment by wclr** [comment]
In window (10/11) this happened to me all the time (on versions pnpm version and the latest) when installing from terminal with user priveleges:

> ERR_PNPM_READ_FROM_STORE  Error: EPERM: operation not permitted, stat 'D:\.pnpm-store\v3\files\ed\031fa33842bec21fff8d9d80b45d66c569b5eea6f74b3357efae80f4c19893bf62a5b8099339373e6cdc04e03243866e6c5e9ca983aa5914edae9c4cb4e583'

Usually I used terminal with admin privileges as it doesn't give me the error.

Finally, `pnpm store prune` **didn't** help, but manually removed `.pnpm-store\v3\files\` dir, fixed this.

**Comment by KanishkKhurana** [comment]
> @zkochan I fixed this by deleting the whole pnpm global cache directory. I guess there are some files with incorrect permissions in the global cache directory.

what is the command to do this ?

**Comment by vatoer** [comment]
gor error when build 

`pnpm build`

```
glob error [Error: EPERM: operation not permitted, scandir 'C:\Users\admin\Application Data'] {
  errno: -4048,
  code: 'EPERM',
  syscall: 'scandir',
  path: 'C:\\Users\\admin\\Application Data'
}
Failed to compile.
```

`pnpm dev` doing just fine

pnpm version 8.9
windows 11

any idea?

**Comment by codenoid** [comment]
bruh, this should be unix based only problem

```
scoop install pnpm
pnpm i <something>
EPERM  EPERM: operation not permitted, rename
```

**Comment by codenoid** [comment]
this is kinda weird, why would pnpm need an admin permission?

### Solution

if you are on unix, you need to `sudo` the pnpm / vscode where you run the pnpm
if you are on windows, you need to "Run as Administrator" the vscode or the terminal you are using

**Comment by wclr** [comment]
> if you are on unix, you need to `sudo` the pnpm / vscode where you run the pnpm
> if you are on windows, you need to "Run as Administrator" the vscode or the terminal you are using

Running vscode under Admin will [make updates disabled](https://code.visualstudio.com/docs/setup/windows#_user-setup-versus-system-setup), and in some cases admin prevs do not save from the problem discussed.

**Comment by Bosphoramus** [comment]
Fixed it on Linux deleting this folder: `~/.local/share/pnpm/store/v3/files`

```bash
rm -r ~/.local/share/pnpm/store/v3/files
```

**Comment by GodfreyGuo** [comment]
> gor error when build
> 
> `pnpm build`
> 
> ```
> glob error [Error: EPERM: operation not permitted, scandir 'C:\Users\admin\Application Data'] {
>   errno: -4048,
>   code: 'EPERM',
>   syscall: 'scandir',
>   path: 'C:\\Users\\admin\\Application Data'
> }
> Failed to compile.
> ```
> 
> `pnpm dev` doing just fine
> 
> pnpm version 8.9 windows 11
> 
> any idea?

i got the same issue....

**Comment by yanalshoubaki** [comment]
> ```shell
> rm -r ~/.local/share/pnpm/store/v3/files
> ```

This command fixed my issue on Ubuntu, thanks @Bosphoramus

**Comment by LayZeeDK** [comment]
I have had a similar issue because of:
- Wrong pnpm version
- `pnpm install` first run from the host OS (Windows) then from a Linux dev container

Solution
- Update/downgrade pnpm to the expected version
- Delete `node_modules` and rerun `pnpm install` from the expected OS and environment

**Comment by jamesbuch** [comment]
> Fixed it on Linux deleting this folder: `~/.local/share/pnpm/store/v3/files`
> 
> rm -r ~/.local/share/pnpm/store/v3/files

Fixed for me, thank you!

**Comment by aghArdeshir** [comment]
I created this minimal reproduction repo: https://github.com/aghArdeshir/pnpm-chmod-issue-3699

If you follow README.md you should be able to reproduce this, and this is the stack trace I am getting: 
```
pnpm: EPERM: operation not permitted, chmod '.../pnpm-chmod-issue-3699/package-b/node_modules/package-a/bin/something'
    at async chmod (node:internal/fs/promises:1079:10)
    at async linkBin (/home/myusername/.cache/node/corepack/v1/pnpm/9.15.4/dist/pnpm.cjs:103822:9)
    at async pReflect (/home/myusername/.cache/node/corepack/v1/pnpm/9.15.4/dist/pnpm.cjs:103042:23)
    at async Promise.all (index 0)
    at async _linkBins (/home/myusername/.cache/node/corepack/v1/pnpm/9.15.4/dist/pnpm.cjs:103711:23)
    at async /home/myusername/.cache/node/corepack/v1/pnpm/9.15.4/dist/pnpm.cjs:185332:30
    at async Promise.all (index 0)
    at async _installInContext (/home/myusername/.cache/node/corepack/v1/pnpm/9.15.4/dist/pnpm.cjs:185322:9)
    at async installInContext (/home/myusername/.cache/node/corepack/v1/pnpm/9.15.4/dist/pnpm.cjs:185568:16)
    at async _install (/home/myusername/.cache/node/corepack/v1/pnpm/9.15.4/dist/pnpm.cjs:185021:25)

```

In the end its coming from this file in pnpm: `pkg-manager/link-bins/src/index.ts` which calls `fixBin` from this package: https://www.npmjs.com/package/bin-links which tries to chmod on filesystem: https://github.com/npm/bin-links/blob/main/lib/fix-bin.js#L38

No amount of removing caches and stores work for me. I'm getting this error in a CI environment wherein my docker image, the user is `node` but some of the workspace packages are owned by user `root`. I get this error even if my file already has required permission `-rwxrwxrwx`

**Comment by felipecrs** [comment]
In my case, pnpm@11.0.9 is trying to `chmod` a file that already has executable permission:

```bash
docker run --rm -i --user root node:lts bash -ex <<EOF
  # 1. Install pnpm
  npm install -g pnpm@11.0.9

  # 2. Create the root-owned dependency
  mkdir -p /opt/root-dep
  cd /opt/root-dep

  # Create a package.json with a "bin" entry
  echo '{"name": "root-dep", "version": "1.0.0", "bin": {"my-cli": "./cli.js"}}' > package.json
  echo -e '#!/usr/bin/env node\nconsole.log("works");' > cli.js

  # Ensure the file is executable already
  chmod +x cli.js
  ./cli.js

  # 3. Create a consumer project owned by a non-root user
  mkdir -p /home/node/app
  chown -R node:node /home/node/app

  # 4. Attempt to link as the non-root user
  cd /home/node/app
  su node -c "pnpm init"
  su node -c "pnpm link /opt/root-dep"
EOF
```

Logs:

```
+ npm install -g pnpm@11.0.9
+ mkdir -p /opt/root-dep
+ cd /opt/root-dep
+ echo '{"name": "root-dep", "version": "1.0.0", "bin": {"my-cli": "./cli.js"}}'
+ echo -e '#!/usr/bin/env node\nconsole.log("works");'
+ chmod +x cli.js
+ ./cli.js
works
+ mkdir -p /home/node/app
+ chown -R node:node /home/node/app
+ cd /home/node/app
+ su node -c 'pnpm init'
+ su node -c 'pnpm link /opt/root-dep'
[EPERM] EPERM: operation not permitted, chmod '/opt/root-dep/cli.js'

pnpm: EPERM: operation not permitted, chmod '/opt/root-dep/cli.js'
    at async chmod (node:internal/fs/promises:1092:10)
    at async linkBin (file:///home/node/.local/share/pnpm/store/v11/links/@/pnpm/11.1.0/33deae4d52acca73efc17ce122dda7d57192e77f814ebb31c67b2e74411d6252/node_modules/pnpm/dist/pnpm.mjs:76662:5)
    at async Promise.allSettled (index 0)
    at async _linkBins (file:///home/node/.local/share/pnpm/store/v11/links/@/pnpm/11.1.0/33deae4d52acca73efc17ce122dda7d57192e77f814ebb31c67b2e74411d6252/node_modules/pnpm/dist/pnpm.mjs:76501:19)
    at async file:///home/node/.local/share/pnpm/store/v11/links/@/pnpm/11.1.0/33deae4d52acca73efc17ce122dda7d57192e77f814ebb31c67b2e74411d6252/node_modules/pnpm/dist/pnpm.mjs:159891:32
    at async Promise.all (index 0)
    at async _installInContext (file:///home/node/.local/share/pnpm/store/v11/links/@/pnpm/11.1.0/33deae4d52acca73efc17ce122dda7d57192e77f814ebb31c67b2e74411d6252/node_modules/pnpm/dist/pnpm.mjs:159873:11)
    at async installInContext (file:///home/node/.local/share/pnpm/store/v11/links/@/pnpm/11.1.0/33deae4d52acca73efc17ce122dda7d57192e77f814ebb31c67b2e74411d6252/node_modules/pnpm/dist/pnpm.mjs:160090:16)
    at async _install (file:///home/node/.local/share/pnpm/store/v11/links/@/pnpm/11.1.0/33deae4d52acca73efc17ce122dda7d57192e77f814ebb31c67b2e74411d6252/node_modules/pnpm/dist/pnpm.mjs:159042:21)
    at async mutateModules (file:///home/node/.local/share/pnpm/store/v11/links/@/pnpm/11.1.0/33deae4d52acca73efc17ce122dda7d57192e77f814ebb31c67b2e74411d6252/node_modules/pnpm/dist/pnpm.mjs:158773:19)
```

**Comment by jclaveau** [comment]
I have the exact same bug as @aghArdeshir. I preinstall packages in a CI env with but the consumer can change the container user to avoid bind-mounts volume permission issues.

This forces a `sudo chmod` on the consumer side

**Comment by felipecrs** [comment]
My potential fix on npm bin-links has been merged and released.

https://github.com/npm/bin-links/pull/171

Now pnpm needs to update it to the latest version.

**Comment by altaywtf** [comment]
[PR 15281](https://github.com/pnpm/pnpm/pull/15281) fixes bin permission handling in TypeScript v11 and Rust v12. Already executable targets skip chmod, avoiding permission errors on files owned by another user. TypeScript already tolerated those errors for executable LF files; the fix also removes the redundant permission changes.

Regression tests cover both stacks. CI is green, CodeRabbit has approved, and the PR is ready for maintainer review.

---
Written by an agent (Codex, GPT-6).
