### ISSUE TITLE
EPERM: operation not permitted, rename

### ISSUE THREAD

**Issue by davidabap** [pnpm/pnpm#3884]
### pnpm version:
6.17.2
### Code to reproduce the issue:
We use mono repo to manage our application(config pnpm inside Rush) and we got this EPERM issue after we upgrade pnpm from v5 to v6. Issue only happend in `windows OS` and it will randomly failed different app in each build. But after I delete the `.pnpm-store` and revert back to pnpm `v5`, then everything working fine.

### Expected behavior:
pnpm runs without errors during `rush update` & `rush build`

### Actual behavior:
Error will raised in `rush build`
```
[exec] Error: EPERM: operation not permitted, rename 'C:\z_dv\cd-2105.1\hybris\bin\modules\personalization-search\personalizationsearchsmartedit\apps\personalizationsearchsmarteditContainer\node_modules\.cache\rollup-plugin-typescript2/rpt2_291fccd8a4439113868df196851ea0e00ed4a0e7/code/cache_' -> 'C:\z_dv\cd-2105.1\hybris\bin\modules\personalization-search\personalizationsearchsmartedit\apps\personalizationsearchsmarteditContainer\node_modules\.cache\rollup-plugin-typescript2/rpt2_291fccd8a4439113868df196851ea0e00ed4a0e7/code/cache'
[exec] at Object.renameSync (node:fs:977:3)
[exec] at RollingCache.roll (C:\z_dv\cd-2105.1\hybris\bin\modules\smartedit\smartedittools\common\temp\node_modules\.pnpm\rollup-plugin-typescript2@0.27.1_rollup@2.17.0+typescript@3.9.3\node_modules\rollup-plugin-typescript2\dist\rollup-plugin-typescript2.cjs.js:24004:12)
[exec] at TsCache.done (C:\z_dv\cd-2105.1\hybris\bin\modules\smartedit\smartedittools\common\temp\node_modules\.pnpm\rollup-plugin-typescript2@0.27.1_rollup@2.17.0+typescript@3.9.3\node_modules\rollup-plugin-typescript2\dist\rollup-plugin-typescript2.cjs.js:24846:24)
[exec] at Object._ongenerate (C:\z_dv\cd-2105.1\hybris\bin\modules\smartedit\smartedittools\common\temp\node_modules\.pnpm\rollup-plugin-typescript2@0.27.1_rollup@2.17.0+typescript@3.9.3\node_modules\rollup-plugin-typescript2\dist\rollup-plugin-typescript2.cjs.js:29120:21)
[exec] at Object.generateBundle (C:\z_dv\cd-2105.1\hybris\bin\modules\smartedit\smartedittools\common\temp\node_modules\.pnpm\rollup-plugin-typescript2@0.27.1_rollup@2.17.0+typescript@3.9.3\node_modules\rollup-plugin-typescript2\dist\rollup-plugin-typescript2.cjs.js:29098:18)
[exec] at C:\z_dv\cd-2105.1\hybris\bin\modules\smartedit\smartedittools\common\temp\node_modules\.pnpm\rollup@2.17.0\node_modules\rollup\dist\shared\rollup.js:18130:25 {
[exec] errno: -4048,
[exec] syscall: 'rename',
[exec] code: 'PLUGIN_ERROR',
[exec] path: 'C:\\z_dv\\cd-2105.1\\hybris\\bin\\modules\\personalization-search\\personalizationsearchsmartedit\\apps\\personalizationsearchsmarteditContainer\\node_modules\\.cache\\rollup-plugin-typescript2/rpt2_291fccd8a4439113868df196851ea0e00ed4a0e7/code/cache_',
[exec] dest: 'C:\\z_dv\\cd-2105.1\\hybris\\bin\\modules\\personalization-search\\personalizationsearchsmartedit\\apps\\personalizationsearchsmarteditContainer\\node_modules\\.cache\\rollup-plugin-typescript2/rpt2_291fccd8a4439113868df196851ea0e00ed4a0e7/code/cache',
[exec] pluginCode: 'EPERM',
[exec] plugin: 'rpt2',
[exec] hook: 'generateBundle'
[exec] }
```

### Additional information:
I'm not sure whether it's an pnpm issue or rush issue since it happend in the phase 'rush build', but the issue is gone when I revert pnpm to v5, so seem like it's a pnpm regression.

 - `node -v` prints: v16.6.0
 -  Rush version 5.50.0
 - Windows, macOS, or Linux?: Windows 10 Enterprise

**Comment by zkochan** [comment]
These files from the error stack don't look like files created by pnpm

**Comment by zkochan** [comment]
Closing for lack of a reproduction on a supported version.

An EPERM on rename inside the pnpm 6 store on Windows, through Rush. That store layout is gone and there is no current reproduction.

If you still hit this on the latest pnpm, please comment with a reproduction and we will reopen.

---
Written by an agent (Claude Code, claude-opus-5).
