### ISSUE TITLE
run script pnpm -r exec -- pnpm i throw error

### ISSUE THREAD

**Issue by linkscope** [pnpm/pnpm#3973]
When I run 'pnpm -r exec --pnpm i' trying to install dependencies for all workspaces on vite 2.7.0-beta.1, I get an error every once in a while that there is no package.json file in one package, and when I run it again I get the same error from other packages. Is it my wrong use or a bug?

### Code to reproduce the issue:

```
{
  "0 debug pnpm:scope": {
    "selected": 83,
    "total": 83,
    "workspacePrefix": "/Users/linkscope/Documents/Source/vite"
  },
  "1 info pnpm": {
    "err": {
      "name": "Error",
      "message": "Command failed with exit code 1: /Users/linkscope/.nvm/versions/node/v17.0.0/bin/pnpm i",
      "stack": "Error: Command failed with exit code 1: /Users/linkscope/.nvm/versions/node/v17.0.0/bin/pnpm i\n    at makeError (/Users/linkscope/.nvm/versions/node/v17.0.0/lib/node_modules/pnpm/dist/pnpm.cjs:49414:17)\n    at handlePromise (/Users/linkscope/.nvm/versions/node/v17.0.0/lib/node_modules/pnpm/dist/pnpm.cjs:49985:33)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async /Users/linkscope/.nvm/versions/node/v17.0.0/lib/node_modules/pnpm/dist/pnpm.cjs:129973:13"
    }
  },
  "2 error pnpm": {
    "shortMessage": "Command failed with exit code 1: /Users/linkscope/.nvm/versions/node/v17.0.0/bin/pnpm i",
    "command": "/Users/linkscope/.nvm/versions/node/v17.0.0/bin/pnpm i",
    "escapedCommand": "\"/Users/linkscope/.nvm/versions/node/v17.0.0/bin/pnpm\" i",
    "exitCode": 1,
    "failed": true,
    "timedOut": false,
    "isCanceled": false,
    "killed": false,
    "code": "ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL",
    "prefix": "/Users/linkscope/Documents/Source/vite/packages/playground",
    "err": {
      "name": "pnpm",
      "message": "Command failed with exit code 1: /Users/linkscope/.nvm/versions/node/v17.0.0/bin/pnpm i",
      "code": "ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL",
      "stack": "Error: Command failed with exit code 1: /Users/linkscope/.nvm/versions/node/v17.0.0/bin/pnpm i\n    at makeError (/Users/linkscope/.nvm/versions/node/v17.0.0/lib/node_modules/pnpm/dist/pnpm.cjs:49414:17)\n    at handlePromise (/Users/linkscope/.nvm/versions/node/v17.0.0/lib/node_modules/pnpm/dist/pnpm.cjs:49985:33)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async /Users/linkscope/.nvm/versions/node/v17.0.0/lib/node_modules/pnpm/dist/pnpm.cjs:129973:13"
    }
  }
}
```

### Additional information:

 - `node -v` prints: 17.0.0
 - Windows, macOS, or Linux?: macOS

**Comment by zkochan** [comment]
Why don't you just run `pnpm install`? `pnpm install` when executed in a workspace installs all the dependencies of all projects.

**Comment by linkscope** [comment]
> Why don't you just run `pnpm install`? `pnpm install`, when executed in a workspace, installs all the dependencies of all projects.

Later I knew it could be executed in this way, but when I started using it, I saw the command similar to Lerna's shell executing script at first sight. Theoretically, this command can execute any shell script, and it is feasible for me to install it by using this command. In fact, I could have installed it with this command, but it would have required several errors and re-execution.By the way, does this command have an option to execute in a separate package? I just saw some packages filtered out.

**Comment by zkochan** [comment]
This no longer reproduces on current pnpm, so closing.

Verified on pnpm 12.5.1: `pnpm -r exec pnpm install` completes across every workspace project with no missing-package.json error.

If you still hit this on the latest pnpm, please comment with a reproduction and we will reopen.

---
Written by an agent (Claude Code, claude-opus-5).
