### ISSUE TITLE
Unhelpful error when a postinstall script fails due to a lack of Node.js

### ISSUE THREAD

**Issue by illright** [pnpm/pnpm#4022]
### pnpm version: 6.22.2

Let me first describe how this issue came about. I was setting up my development environment on Arch WSL and forgot to install Node.js. I tried running `pnpm install` in one of my projects that had a transitive dependency on `esbuild` and was faced with an error and no indication as to what went wrong. Eventually, I diagnosed the issue with `pnpm install --reporter ndjson`. I'd like the errors from `postinstall` scripts to come through to the terminal to allow for further diagnosis.

### Code to reproduce the issue:
This only happens if Node.js is not installed on the machine and `pnpm` is installed standalone.  
In an empty directory, run `pnpm add -D esbuild`.

### Expected behavior:
An error from a postinstall script is displayed that could lead to diagnosing the lack of Node.js.

### Actual behavior:
No indication as to what went wrong. The following output to the terminal:
```
Packages: +2
++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /home/illright/.pnpm-store/v3
  Virtual store is at:             node_modules/.pnpm
node_modules/.pnpm/esbuild@0.13.15/node_modules/esbuild: Running postinstall script...
 ELIFECYCLE  Command failed.
```

The last two log entries when running `pnpm add -D esbuild --reporter ndjson`:
```json
{"time":1637475520161,"hostname":"illaptop-win","pid":1307,"level":"debug","name":"pnpm:lifecycle","depPath":"/esbuild/0.13.15","line":"sh: line 1: node: command not found","stage":"postinstall","stdio":"stderr","wd":"/home/illright/work/test/node_modules/.pnpm/esbuild@0.13.15/node_modules/esbuild"}
{"time":1637475520173,"hostname":"illaptop-win","pid":1307,"level":"error","name":"pnpm","code":"ELIFECYCLE","errno":"ENOENT","syscall":"spawn","file":"sh","pkgid":"esbuild@0.13.15","stage":"postinstall","script":"node install.js","pkgname":"esbuild","name":"pnpm","err":{"name":"pnpm","message":"esbuild@0.13.15 postinstall: `node install.js`\nspawn ENOENT","code":"ELIFECYCLE","stack":"pnpm: esbuild@0.13.15 postinstall: `node install.js`\nspawn ENOENT\n    at ChildProcess.<anonymous> (/snapshot/dist/pnpm.cjs)\n    at ChildProcess.emit (events.js:376:20)\n    at maybeClose (internal/child_process.js:1055:16)\n    at Socket.<anonymous> (internal/child_process.js:441:11)\n    at Socket.emit (events.js:376:20)\n    at Pipe.<anonymous> (net.js:673:12)"}}
```

### Additional information:

 - `node -v` prints: nothing, there's no Node
 - Windows, macOS, or Linux?: Arch Linux WSL on Windows 11

**Comment by havenchyk** [comment]
Happened to me as well on WSL, node 16.17.0, pnpm 7.9.4

postinstall just failed with no additional info

**Comment by zkochan** [comment]
This no longer reproduces on current pnpm, so closing.

A failing dependency build now prints the script's own stdout and stderr, so a missing interpreter shows as "node: command not found", followed by ERR_PNPM_EXECUTOR_LIFECYCLE_SCRIPT_FAILED naming the package and script.

If you still hit this on the latest pnpm, please comment with a reproduction and we will reopen.

---
Written by an agent (Claude Code, claude-opus-5).
