### ISSUE TITLE
Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by qiYuei** [pnpm/pnpm#4129]
### Code to reproduce the issue:

``` pnpm publish ```

### Expected behavior:
Was expecting a successful installation
### Actual behavior:
throw Error:
Cannot read property 'replace' of undefined

### Additional information:

 - `node -v` prints: v14.16.1
 - Windows, macOS, or Linux?: windows

 .pnpm-debug.log
 ```json
  "1 error pnpm": {
    "err": {
      "name": "pnpm",
      "message": "Cannot read property 'replace' of undefined",
      "stack": "pnpm: Cannot read property 'replace' of undefined\n    at Object.handler (D:\\node\\node_global\\node_modules\\pnpm\\dist\\pnpm.cjs:129422:44)\n    at async Object.handler [as publish] (D:\\node\\node_global\\node_modules\\pnpm\\dist\\pnpm.cjs:129299:27)\n    at async D:\\node\\node_global\\node_modules\\pnpm\\dist\\pnpm.cjs:134203:20\n    at async run (D:\\node\\node_global\\node_modules\\pnpm\\dist\\pnpm.cjs:134177:34)\n    at async runPnpm (D:\\node\\node_global\\node_modules\\pnpm\\dist\\pnpm.cjs:134389:5)\n    at async D:\\node\\node_global\\node_modules\\pnpm\\dist\\pnpm.cjs:134381:7"
    }
  }
```

**Comment by fireairforce** [comment]
Can you provided a small demo for it ?

**Comment by tian0o0** [comment]
I meet the same problem, is there any resolutions?

**Comment by see** [comment]
same issue

**Comment by HeatherFlux** [comment]
I'm also dealing with this issue.

**Comment by zkochan** [comment]
Looks like the initial issue was caused by running `pnpm publish` on a package that has no name. As of now, pnpm prints an error in this case: Cannot read properties of undefined (reading 'replace')

If you have these error, add steps to reproduce.

**Comment by HeatherFlux** [comment]
Hmm interesting I run publish regularly but all my packages have names.

**Comment by tastypackets** [comment]
This still comes up as a top result on Google, so wanted to update the issue on 1 edge case I ran into.

I had PnP mode enabled and there was a custom eslint rule created inside a package in a monorepo and then installed using local path. Adding a console log to pnpm during install to log out data of the package showed the first value in data array was undefined when trying to install the eslint rule.

The wasy fix was moving the eslint rule out of the other monorepo package and into a monorepo package and installing it with `workspace:*`. If anyone else runs into this an easy way to sort out what package it fails on is adding a console log right above the line where pnpm errors.

Example:

.npmrc
```
node-linker=pnp
symlink=false
```

Repo
```
- packages
  - a
    - src
      - custom-eslint-rule
    - package.json <- eslint rule was installed here using file:src/custom-eslint-rules
  - b
```

The fix:
```
- packages
  - a
    - custom-eslint-rule
    - package.json <- eslint rule is installed here using "package-a-custom-eslint-rule": "workspace:*"
  - b
  - eslint-configs
    - package-a-custom-eslint-rule
```

**Comment by saewitz** [comment]
For us we had `version` as a number instead of a string, and changing `"version": "0.1",` to `"version": "0.1",` improves it

**Comment by saewitz** [comment]
For us we had `version` as a number instead of a string, and changing `"version": "0.1",` to `"version": "0.1",` improves it

**Comment by maddrag0n** [comment]
experiencing a similar issue

## steps to reproduce

1. create folder 'pnpm-test'
2. `corepack enable pnpm` (node 22.15.0 in my case)
3. `pnpm init`
4. `mkdir packages/my-package && cd packages/my-package && pnpm init && cd ../..`
5. create pnpm-workspace.yaml with `packages:\n- 'packages/*'`
6. `pnpm add -D prettier`

when I remove the packages key and value(s) it works

```yaml
# pnpm-workspace.yaml
packages:
  - 'packages/*'
```

**Comment by zkochan** [comment]
This targets a part of pnpm that no longer exists, so closing.

A JavaScript TypeError from the pnpm 6 publish path. pnpm 12's publish is native code and reports errors with an ERR_PNPM_ code.

If you still hit this on the latest pnpm, please comment with a reproduction and we will reopen.

---
Written by an agent (Claude Code, claude-opus-5).
