### ISSUE TITLE
6.24.0 Invalid range; version range does not intersect: >=16.0.0 <16.0.0

### ISSUE THREAD

**Issue by roykho** [pnpm/pnpm#4134]
### pnpm version:
6.24.0

### Code to reproduce the issue:
When running `pnpm install` I am seeing the following error in `.pnpm-debug.log`. My node version is 16.13.1.

```
    "err": {
      "name": "pnpm",
      "message": "Invalid range; version range does not intersect: >=16.0.0 <16.0.0",
      "stack": "pnpm: Invalid range; version range does not intersect: >=16.0.0 <16.0.0\n    at new SingleRange (/Users/user/.nvm/versions/node/v16.13.1/lib/node_modules/pnpm/dist/pnpm.cjs:113535:17)\n    at SingleRange.intersect (/Users/user/.nvm/versions/node/v16.13.1/lib/node_modules/pnpm/dist/pnpm.cjs:113565:20)\n    at /Users/user/.nvm/versions/node/v16.13.1/lib/node_modules/pnpm/dist/pnpm.cjs:113753:116\n    at Array.map (<anonymous>)\n    at /Users/user/.nvm/versions/node/v16.13.1/lib/node_modules/pnpm/dist/pnpm.cjs:113753:81\n    at Array.map (<anonymous>)\n    at MultiRange.intersect (/Users/user/.nvm/versions/node/v16.13.1/lib/node_modules/pnpm/dist/pnpm.cjs:113753:44)\n    at /Users/user/.nvm/versions/node/v16.13.1/lib/node_modules/pnpm/dist/pnpm.cjs:113790:151\n    at Array.reduce (<anonymous>)\n    at intersect (/Users/user/.nvm/versions/node/v16.13.1/lib/node_modules/pnpm/dist/pnpm.cjs:113790:102)"
    }
```

If I downgrade to pnpm version 6.20.4, everything works.

### Expected behavior:
For pnpm install to work without errors.

### Actual behavior:
Install is halted when encountered error.

### Additional information:

 - `node -v` prints: 16.13.1
 - Windows, macOS, or Linux?: macOS

**Comment by zkochan** [comment]
What package has such a peer dependency? `>=16.0.0 <16.0.0 ` seems like an invalid range

**Comment by roykho** [comment]
I am trying to hunt that down now.

**Comment by zkochan** [comment]
I'll fix it today

**Comment by roykho** [comment]
Thanks for the prompt fix!
