### ISSUE TITLE
fix:  ERR_PNPM_CANNOT_RESOLVE_WORKSPACE_PROTOCOL for scoped peerDependency

### ISSUE THREAD

**Issue by jjangga0214** [pnpm/pnpm#4164]
### pnpm version: 

6.24.3

### Code to reproduce the issue:

Reproduction steps are here. The repo I mentioned is very simple.
```sh
$ git clone git@github.com:jjangga0214/node-configs.git

$ git reset --hard 666a9a5

$ pnpm install

$ cd packages/eslint-config

$ pnpm publish
 ERR_PNPM_CANNOT_RESOLVE_WORKSPACE_PROTOCOL  Cannot resolve workspace protocol of dependency "@jjangga0214/prettier-config" because this dependency is not installed. Try running "pnpm install"
```

```jsonc
{
  "0 debug pnpm:scope": {
    "selected": 6,
    "total": 6,
    "workspacePrefix": "/Users/ocean/main/node-configs"
  },
  "1 error pnpm": {
    "code": "ERR_PNPM_CANNOT_RESOLVE_WORKSPACE_PROTOCOL",
    "err": {
      "name": "pnpm",
      "message": "Cannot resolve workspace protocol of dependency \"@jjangga0214/prettier-config\" because this dependency is not installed. Try running \"pnpm install\".",
      "code": "ERR_PNPM_CANNOT_RESOLVE_WORKSPACE_PROTOCOL",
      "stack": "pnpm: Cannot resolve workspace protocol of dependency \"@jjangga0214/prettier-config\" because this dependency is not installed. Try running \"pnpm install\".\n    at makePublishDependency (/opt/homebrew/Cellar/pnpm/6.24.2/libexec/lib/node_modules/pnpm/dist/pnpm.cjs:178311:17)\n    at async /opt/homebrew/Cellar/pnpm/6.24.2/libexec/lib/node_modules/pnpm/dist/pnpm.cjs:178299:9\n    at async Promise.all (index 0)\n    at async makePublishDependencies (/opt/homebrew/Cellar/pnpm/6.24.2/libexec/lib/node_modules/pnpm/dist/pnpm.cjs:178297:60)\n    at async makePublishManifest (/opt/homebrew/Cellar/pnpm/6.24.2/libexec/lib/node_modules/pnpm/dist/pnpm.cjs:178277:22)\n    at async packPkg (/opt/homebrew/Cellar/pnpm/6.24.2/libexec/lib/node_modules/pnpm/dist/pnpm.cjs:178900:35)\n    at async Object.handler (/opt/homebrew/Cellar/pnpm/6.24.2/libexec/lib/node_modules/pnpm/dist/pnpm.cjs:178873:7)\n    at async handler (/opt/homebrew/Cellar/pnpm/6.24.2/libexec/lib/node_modules/pnpm/dist/pnpm.cjs:178740:27)\n    at async default_1 (/opt/homebrew/Cellar/pnpm/6.24.2/libexec/lib/node_modules/pnpm/dist/pnpm.cjs:178450:35)\n    at async Object.handler [as publish] (/opt/homebrew/Cellar/pnpm/6.24.2/libexec/lib/node_modules/pnpm/dist/pnpm.cjs:178705:9)"
    }
  }
}
```

### Expected behavior: 

It should just work.

### Actual behavior: 

It does not.

### Additional information:

 - `node -v` prints: v16.13.1
 - Windows, macOS, or Linux?: macOS

**Comment by meteorlxy** [comment]
Same here. Any updates?

**Comment by jjangga0214** [comment]
@meteorlxy 
I published every package without `workspace:` protocol.
After the first publish, I then applied `workspace:` protocol.
Finally I became able to publish with `workspace:` protocol from the second

**Comment by jjangga0214** [comment]
>Workaround:
I published every package without workspace: protocol.
After the first publish, I then applied workspace: protocol.
Finally, I became able to publish with workspace: protocol from the second publish.

>I think it's better for workspace: to work from the first publish.

It turned out that already published(not the first publish) packages also experience this issue.

For example, [this workflow](https://github.com/jjangga0214/haetae/runs/7938742871?check_suite_focus=true)'s error is the screenshot below.

<img width="1119" alt="스크린샷 2022-08-21 오후 10 05 00" src="https://user-images.githubusercontent.com/28584151/185792309-209fd828-b9a6-4d39-b88f-8ae77061d011.png">

**Comment by jjangga0214** [comment]
> Workaround:
    I published every package without workspace: protocol.
    After the first publish, I then applied workspace: protocol.
    Finally, I became able to publish with workspace: protocol from the second publish.
> 
>    I think it's better for workspace: to work from the first publish.
> 
> It turned out published(not the first publish) packages also experience this issue.
> 
> For example, [this workflow](https://github.com/jjangga0214/haetae/runs/7938742871?check_suite_focus=true)'s error is the screenshot below.

I solved this issue by duplicating  peerDependencies to devDependencies.

**package.json (before)**

```json
{
  "name": "@haetae/cli",
  "peerDependencies": {
    "@haetae/core": "workspace:~"
  },
  "devDependencies": {}
}
```

**package.json (after)**

```json
{
  "name": "@haetae/cli",
  "peerDependencies": {
    "@haetae/core": "workspace:~"
  },
  "devDependencies": {
    "@haetae/core": "workspace:~",
  }
}
```

**Comment by raulfdm** [comment]
Just want to point out that I was having the same problem while publishing and I fix it by adding a version to my package (which was undefined)

**Comment by baptisteArno** [comment]
> Just want to point out that I was having the same problem while publishing and I fix it by adding a version to my package (which was undefined)

THIS! Thank you 🙏

**Comment by Andarist** [comment]
One extra way to end up with this problem is to combine a workspace protocol and `publishConfig.directory`. The dependency is being searched in the `node_modules` of the `publishConfig.directory` but unless you symlink it manually or something then the `node_modules` in there don't exist at all and it fails

**Comment by volkandkaya** [comment]
> Just want to point out that I was having the same problem while publishing and I fix it by adding a version to my package (which was undefined)

Thanks, I wonder if this should be in workspace docs or as a eslint rule.

**Comment by FredrikAugust** [comment]
Just ran into this again, and it was fixed by setting a version. Perhaps it would be possible to check for this and warn the user?

**Comment by raulfdm** [comment]
@zkochan maybe a fix for v10? 😅

**Comment by kitsunekyo** [comment]
@FredrikAugust maybe a stupid question, but do you mean setting a `version` in the `package.json` of the package you're trying import as workspace, or pinning the version number in the `package.json` of the importing project, when referencing the package via `workspace:^1` or something?

**Comment by FredrikAugust** [comment]
@kitsunekyo Wish I could tell you, but I don't remember, sadly. I think _maybe_ it was something with setting a version in the package.json you're importing.

**Comment by rccyx** [comment]
hmm, solved by having a versioned fallback for workspace packages
```json
  "devDependencies": {
    "@rep/env": "workspace:^0.0.1",
    "@rep/eslint-config": "workspace:^0.0.1",
    "@rep/prettier-config": "workspace:^0.0.1",
    "@rep/rollup-config": "workspace:^0.0.1",
    "@rep/tsconfig": "workspace:^0.0.1",
    "@rep/vitest-config": "workspace:^0.0.1",
    "rollup": "catalog:",
    "typescript": "catalog:",
    "vitest": "catalog:",
    "zod": "catalog:"
  },
```
instead of `workspace:*`

**Comment by mattmink** [comment]
For anyone using Changsets to manage versions and releases, I solved this by adding a version to internal private packages and then adding those packages to the `ignore` array in my config.

**.changeset/config.json**

```json
{
  "$schema": "https://unpkg.com/@changesets/config@3.1.3/schema.json",
  "ignore": ["@repo/eslint-config", "@repo/typescript-config"]
}
```

**Comment by olllayor** [comment]
I am taking this issue.

The remaining gap after pnpm/pnpm#15349 is the misleading `ERR_PNPM_CANNOT_RESOLVE_WORKSPACE_PROTOCOL` message: when a workspace dependency (including a scoped `peerDependencies` entry using `workspace:`) is found but its `package.json` has no `version`, pnpm still says the dependency is not installed and tells people to run `pnpm install`. Several reports in this thread were fixed by adding a missing `version` field.

Plan:
1. Report a missing `version` (or `name`) field on the dependency instead of "not installed".
2. Keep name-only workspace packages in the publish lookup so that case is reachable.
3. Cover scoped `workspace:` peerDependencies in tests on both pnpm v11 and v12.

I will open a PR that addresses this part of the issue.

---
Written by an agent (MiMo, mimo-v2.5-pro).

**Comment by olllayor** [comment]
Opened [pnpm/pnpm#15444](https://github.com/pnpm/pnpm/pull/15444) for this.

It covers the remaining gap after pnpm/pnpm#15349: when a workspace dependency (including a scoped `peerDependencies` entry using `workspace:`) is found but its `package.json` has no `version`, pnpm now says so instead of claiming the dependency is not installed. Name-only workspace packages stay in the publish lookup so that case is reachable.

This is a partial fix. Other workarounds in this thread, such as `publishConfig.directory`, are not covered yet.

---
Written by an agent (MiMo, mimo-v2.5-pro).
