### ISSUE TITLE
Filter "..." does not work in package.json scripts

### ISSUE THREAD

**Issue by crimx** [pnpm/pnpm#4176]
### Code to reproduce the issue:

package.json
```json
{
  "scripts": {
    "test-all": "pnpm test --filter ..."
  }
}
```

Run `pnpm test-all` at project root.

### Expected behavior:

Run the `test` script of each package.

### Actual behavior:

Terminal error:

```
Unsupported package selector: {"exclude":false,"excludeSelf":false,"includeDependencies":true,"includeDependents":false,"followProdDepsOnly":false}
```

`.pnpm-debug.log`

```json
{
  "0 debug pnpm:scope": {
    "selected": 1,
    "workspacePrefix": "/Users/xxx/Desktop/ttx"
  },
  "1 error pnpm": {
    "errno": 1,
    "code": "ELIFECYCLE",
    "pkgid": "ttx@1.0.0",
    "stage": "test-all",
    "script": "pnpm test --filter ...",
    "pkgname": "ttx",
    "err": {
      "name": "pnpm",
      "message": "ttx@1.0.0 test-all: `pnpm test --filter ...`\nExit status 1",
      "code": "ELIFECYCLE",
      "stack": "pnpm: ttx@1.0.0 test-all: `pnpm test --filter ...`\nExit status 1\n    at EventEmitter.<anonymous> (/Users/xxx/.nvm/versions/node/v16.13.0/lib/node_modules/pnpm/dist/pnpm.cjs:103873:20)\n    at EventEmitter.emit (node:events:390:28)\n    at ChildProcess.<anonymous> (/Users/xxx/.nvm/versions/node/v16.13.0/lib/node_modules/pnpm/dist/pnpm.cjs:91802:18)\n    at ChildProcess.emit (node:events:390:28)\n    at maybeClose (node:internal/child_process:1064:16)\n    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)"
    }
  }
}
```

### Additional information:

Running `pnpm test --filter ...` directly is working as expected.

 - `node -v` prints: v16.13.0
 - Windows, macOS, or Linux?: macOS

**Comment by fireairforce** [comment]
`--filter` doesn't support single `...`, maybe you can use `pnpm test --filter *` instead?

**Comment by crimx** [comment]
> `--filter` doesn't support single `...`, maybe you can use `pnpm test --filter *` instead?

Looks like `pnpm test --filter *` builds dependencies first as expected. Or should I be explicit with `pnpm test --filter *...`?

And also but why running `pnpm test --filter ...` directly works?

**Comment by m1heng** [comment]
Does `pnpm run xxx -r` is what you what? 
https://pnpm.io/cli/run#--recursive--r

**Comment by crimx** [comment]
> Does `pnpm run xxx -r` is what you what? 
> https://pnpm.io/cli/run#--recursive--r

Is it guaranteed that the commands in dependencies run first?

**Comment by zkochan** [comment]
Dependencies always run first unless you use `--no-sort`

**Comment by crimx** [comment]
> Dependencies always run first unless you use `--no-sort`

I see. Thanks for all of your help! I've got what I needed☺️. I'll leave this issue open  because `pnpm xxx --filter ...` works when running directly. If the team think it's too trivial please just close it.

**Comment by zkochan** [comment]
This no longer reproduces on current pnpm, so closing.

Verified on pnpm 12.5.1: `--filter "..."` inside a package.json script no longer fails with "Unsupported package selector". Use `pnpm -r run <script>` to run a script in every project.

If you still hit this on the latest pnpm, please comment with a reproduction and we will reopen.

---
Written by an agent (Claude Code, claude-opus-5).
