### ISSUE TITLE
pnpm install bug on certainly formed git+ssh repository URLs

### ISSUE THREAD

**Issue by albertdb** [pnpm/pnpm#419]
I'm seeing that pnpm finally supports git+ssh, but there is a parsing bug on certainly formed repository URLs. The test case is simple:

`git+ssh://git@gitlab.domain.tld:/myproject/myrepo.git#master`
does work,
while
`git+ssh://git@gitlab.domain.tld:myproject/myrepo.git#master`
does not, throwing the following error:
`ssh: Could not resolve hostname gitlab.domain.tld:myproject: Name or service not known`

`myproject` seems to be interpreted as a host port instead of what it really is.

By default, self-hosted GitLab gives the second format, so it would be really useful to support it.

Thank you very much!

**Comment by zkochan** [comment]
is this like a private gitlab instance? `gitlab.domain.tld`

because I tried a similar URL pointing to gitlab.com and it worked

**Comment by albertdb** [comment]
@zkochan Yes, it is.

**Comment by zkochan** [comment]
does it work with npm? (I don't mean we won't fix it if does not work there but it'll help to narrow down where is the issue happening)

**Comment by albertdb** [comment]
@zkochan Yes, it works. The only thing that doesn't work is what I explained. Just in case it makes a difference: I'm talking about a dependency, so the URL is in package.json file.

**Comment by zkochan** [comment]
Can you please look into the end of the pnpm-debug.log file and post the exact place where the error happens. In case it does not contain any private info you can just post the whole log file.

**Comment by albertdb** [comment]
Here it is:

```
---
  0 debug pnpm:mkdirp: "/root/theProject/mycomponent/node_modules/.store"
  1 debug pnpm:install: "installing coffee-script@1.10.0"
  2 debug pnpm:install: "installing level@^1.4.0"
  3 debug pnpm:install: "installing lodash@^3.10.1"
  4 debug pnpm:install: "installing q@^1.4.1"
  5 debug pnpm:install: "installing mymodule@git+ssh://git@gitlab.domain.tld:myproject/myrepo.git#master"
  6 debug pnpm:install: "installing traverse@^0.6.6"
  7 debug pnpm:install: "installing zmq@2.13.0"
  8 debug pnpm:install: "installing chalk@^1.1.1"
  9 debug pnpm:install: "installing coffee-coverage@1.0.1"
  10 debug pnpm:install: "installing coffeelint@^1.12.1"
  11 debug pnpm:install: "installing istanbul@0.4.2"
  12 debug pnpm:install: "installing mocha@^2.2.4"
  13 debug pnpm:install: "installing should@^6.0.1"
  14 debug pnpm:install: "installing tcp-port-used@0.1.2"
  15 progress coffee-script@1.10.0: "resolving"
  16 verbose request: "uri https://registry.npmjs.org/coffee-script"
  17 verbose request: "no auth needed"
  18 info attempt: "registry request try #1 at 12:19:51"
  19 verbose request id: "374143efd47d9213"
  20 http request: "GET https://registry.npmjs.org/coffee-script"
  21 progress level@^1.4.0: "resolving"
  22 verbose request: "uri https://registry.npmjs.org/level"
  23 verbose request: "no auth needed"
  24 info attempt: "registry request try #1 at 12:19:51"
  25 http request: "GET https://registry.npmjs.org/level"
  26 progress lodash@^3.10.1: "resolving"
  27 verbose request: "uri https://registry.npmjs.org/lodash"
  28 verbose request: "no auth needed"
  29 info attempt: "registry request try #1 at 12:19:51"
  30 http request: "GET https://registry.npmjs.org/lodash"
  31 progress q@^1.4.1: "resolving"
  32 verbose request: "uri https://registry.npmjs.org/q"
  33 verbose request: "no auth needed"
  34 info attempt: "registry request try #1 at 12:19:51"
  35 http request: "GET https://registry.npmjs.org/q"
  36 progress mymodule@git+ssh://git@gitlab.domain.tld:myproject/myrepo.git#master: "resolved [object Object]"
  37 debug pnpm:mkdirp: "/root/theProject/mycomponent/node_modules"
  38 progress traverse@^0.6.6: "resolving"
  39 verbose request: "uri https://registry.npmjs.org/traverse"
  40 verbose request: "no auth needed"
  41 info attempt: "registry request try #1 at 12:19:51"
  42 http request: "GET https://registry.npmjs.org/traverse"
  43 progress zmq@2.13.0: "resolving"
  44 verbose request: "uri https://registry.npmjs.org/zmq"
  45 verbose request: "no auth needed"
  46 info attempt: "registry request try #1 at 12:19:51"
  47 http request: "GET https://registry.npmjs.org/zmq"
  48 progress chalk@^1.1.1: "resolving"
  49 verbose request: "uri https://registry.npmjs.org/chalk"
  50 verbose request: "no auth needed"
  51 info attempt: "registry request try #1 at 12:19:51"
  52 http request: "GET https://registry.npmjs.org/chalk"
  53 progress coffee-coverage@1.0.1: "resolving"
  54 verbose request: "uri https://registry.npmjs.org/coffee-coverage"
  55 verbose request: "no auth needed"
  56 info attempt: "registry request try #1 at 12:19:51"
  57 http request: "GET https://registry.npmjs.org/coffee-coverage"
  58 progress coffeelint@^1.12.1: "resolving"
  59 verbose request: "uri https://registry.npmjs.org/coffeelint"
  60 verbose request: "no auth needed"
  61 info attempt: "registry request try #1 at 12:19:51"
  62 http request: "GET https://registry.npmjs.org/coffeelint"
  63 progress istanbul@0.4.2: "resolving"
  64 verbose request: "uri https://registry.npmjs.org/istanbul"
  65 verbose request: "no auth needed"
  66 info attempt: "registry request try #1 at 12:19:51"
  67 http request: "GET https://registry.npmjs.org/istanbul"
  68 progress mocha@^2.2.4: "resolving"
  69 verbose request: "uri https://registry.npmjs.org/mocha"
  70 verbose request: "no auth needed"
  71 info attempt: "registry request try #1 at 12:19:51"
  72 http request: "GET https://registry.npmjs.org/mocha"
  73 progress should@^6.0.1: "resolving"
  74 verbose request: "uri https://registry.npmjs.org/should"
  75 verbose request: "no auth needed"
  76 info attempt: "registry request try #1 at 12:19:51"
  77 http request: "GET https://registry.npmjs.org/should"
  78 progress tcp-port-used@0.1.2: "resolving"
  79 verbose request: "uri https://registry.npmjs.org/tcp-port-used"
  80 verbose request: "no auth needed"
  81 info attempt: "registry request try #1 at 12:19:51"
  82 http request: "GET https://registry.npmjs.org/tcp-port-used"
  83 progress mymodule@git+ssh://git@gitlab.domain.tld:myproject/myrepo.git#master: "download-queued"
  84 debug pnpm:git: "cloning git repository from ssh://git@gitlab.domain.tld:myproject/myrepo.git"
  85 debug pnpm:git: "executing git with args clone,-b,master,ssh://git@gitlab.domain.tld:myproject/myrepo.git,/root/theProject/mycomponent/node_modules/.store/ssh:++git@gitlab.domain.tld:myproject+myrepo.git#master/_,--single-branch"
  86 debug pnpm:git: "failed to clone repository from ssh://git@gitlab.domain.tld:myproject/myrepo.git"
  87 progress mymodule@git+ssh://git@gitlab.domain.tld:myproject/myrepo.git#master: "error Error: failed to clone repository from ssh://git@gitlab.domain.tld:myproject/myrepo.git\n        Cloning into '/root/theProject/mycomponent/node_modules/.store/ssh:++git@gitlab.domain.tld:myproject+myrepo.git#master/_'...\nssh: Could not resolve hostname gitlab.domain.tld:myproject: Name or service not known\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n\nError: failed to clone repository from ssh://git@gitlab.domain.tld:myproject/myrepo.git\n        Cloning into '/root/theProject/mycomponent/node_modules/.store/ssh:++git@gitlab.domain.tld:myproject+myrepo.git#master/_'...\nssh: Could not resolve hostname gitlab.domain.tld:myproject: Name or service not known\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n\n    at errorHandler (/usr/lib/node_modules/pnpm/lib/resolve/git.js:50:20)\n    at ChildProcess.<anonymous> (/usr/lib/node_modules/pnpm/lib/resolve/git.js:47:43)\n    at emitTwo (events.js:87:13)\n    at ChildProcess.emit (events.js:172:7)\n    at maybeClose (internal/child_process.js:818:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)"
  88 error : "Error: failed to clone repository from ssh://git@gitlab.domain.tld:myproject/myrepo.git\n        Cloning into '/root/theProject/mycomponent/node_modules/.store/ssh:++git@gitlab.domain.tld:myproject+myrepo.git#master/_'...\nssh: Could not resolve hostname gitlab.domain.tld:myproject: Name or service not known\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n\nError: failed to clone repository from ssh://git@gitlab.domain.tld:myproject/myrepo.git\n        Cloning into '/root/theProject/mycomponent/node_modules/.store/ssh:++git@gitlab.domain.tld:myproject+myrepo.git#master/_'...\nssh: Could not resolve hostname gitlab.domain.tld:myproject: Name or service not known\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n\n    at errorHandler (/usr/lib/node_modules/pnpm/lib/resolve/git.js:50:20)\n    at ChildProcess.<anonymous> (/usr/lib/node_modules/pnpm/lib/resolve/git.js:47:43)\n    at emitTwo (events.js:87:13)\n    at ChildProcess.emit (events.js:172:7)\n    at maybeClose (internal/child_process.js:818:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)"
```

**Comment by albertdb** [comment]
Could you please fix this issue? The only thing needed is checking if there is a colon followed by letters instead of numbers (indication host port) in the URL and adding a `/` in that case (`gitlab.domain.tld:myproject` resulting in `gitlab.domain.tld:/myproject`).

Thank you!

**Comment by zkochan** [comment]
Here we normalize the repo URL: https://github.com/pnpm/pnpm/blob/master/src/resolve/git.ts#L76-L80

The fix might have to be done in this package: https://github.com/zkochan/hosted-git-info

I might be able to fix it tonight, if someone would like to work on the fix, please leave a notice

**Comment by zkochan** [comment]
landed in [v0.55.3](https://github.com/pnpm/pnpm/releases/tag/v0.55.3)

**Comment by albertdb** [comment]
@zkochan Part of the problem is solved, but now I get the following error:

```
# pnpm install
  mymodule git+ssh://git@gitlab.domain.tld:myproject/myrepo.git#master ERROR ✗ 
ERROR Command failed: git ls-remote --refs ssh://git@gitlab.domain.tld/:myproject/myrepo.git master
GitLab: The project you were looking for could not be found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

The only way it would work is if the issued command was:
`git ls-remote --refs sh://git@gitlab.domain.tld:/myproject/myrepo.git master`

Please note that `/` should be after `:`, not before.

I would greatly appreciate if you could fix it.

Thanks!

**Comment by zkochan** [comment]
Without colons it should work as well, I believe
`ssh://git@gitlab.domain.tld/myproject/myrepo.git`

**Comment by albertdb** [comment]
@zkochan Let me confirm that tomorrow morning.

**Comment by zkochan** [comment]
Probably it will work, see: http://stackoverflow.com/questions/5279624/whats-the-purpose-of-the-colon-in-this-git-repository-url

**Comment by albertdb** [comment]
@zkochan I've just checked it and it does not work. Only `:/` works.

**Comment by zkochan** [comment]
[parse-url](https://github.com/IonicaBizau/parse-url) seems to be the only npm package that can correctly parse your type of ssh URLs.

https://runkit.com/58a20862fe14c40014e86901/58acc41dce91f10014a9ca96

I'll probably fix this tommorow

**Comment by zkochan** [comment]
will the ssh work if the port will be specified - `:22/`?

**Comment by albertdb** [comment]
@zkochan Yes it does (the `git ls-remote --refs` command)

**Comment by zkochan** [comment]
Landed in [v0.57.0](https://github.com/pnpm/pnpm/releases/tag/v0.57.0)

**Comment by albertdb** [comment]
Works great! Thank you very much!

**Comment by zkochan** [comment]
You're welcome

**Comment by zwif** [comment]
This Issue is quite hold, but I'm experiencing an Issue heavily related:

*(Notice the different chars after `*.server`)*
1. `pnpm install git+ssh://git@private.gitlab.server/something/repo` (works)
2. `pnpm install git+ssh://git@private.gitlab.server:/something/repo` (works)
3. `pnpm install git+ssh://git@private.gitlab.server:something/repo` (works **not**)

Whereas (3) also [works with standard npm](https://docs.npmjs.com/files/package.json#git-urls-as-dependencies). 

Encountered this, since we have (3) in some `package.json` files which formerly were handled via npm (and everything worked as expected) but encountered `Invalid URL: git+ssh://[...]` Error with `pnpm`.


Imo `pnpm` should handle all the git url forms that `npm` handles...

**Comment by zkochan** [comment]
You should create a new issue then. Nobody is looking at closed issues.
