### ISSUE TITLE
pnpm install-completion failed

### ISSUE THREAD

**Issue by zhengcan** [pnpm/pnpm#4208]
### pnpm version:

6.25.0

### Code to reproduce the issue:

```
curl -fsSL https://get.pnpm.io/install.sh | sh -
source ~/.zshrc
pnpm install-completion
```

### Expected behavior:

pnpm install completion success

### Actual behavior:

```
➜  ~ pnpm install-completion
✔ Which Shell do you use ? · zsh
✔ We will install completion to ~/.zshrc, is it ok ? (y/N) · true
ERROR: Error: File '/**/dist/scripts/zsh.sh' was not included into executable at compilation stage. Please recompile adding it as asset or script.
    at error_ENOENT (pkg/prelude/bootstrap.js:556:19)
    at readFileFromSnapshot (pkg/prelude/bootstrap.js:948:29)
    at readFile (pkg/prelude/bootstrap.js:1019:5)
    at internal/util.js:308:30
    at new Promise (<anonymous>)
    at readFile (internal/util.js:307:12)
    at writeToCompletionScript (/snapshot/dist/pnpm.cjs)
    at Object.install (/snapshot/dist/pnpm.cjs)
    at install (/snapshot/dist/pnpm.cjs)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  errno: -2,
  code: 'ENOENT',
  path: '/snapshot/dist/scripts/zsh.sh',
  pkg: true
}
=> Tabtab line already exists in ~/.zshrc file
=> Tabtab line already exists in ~/.config/tabtab/zsh/__tabtab.zsh file

    => Tabtab source line added to ~/.zshrc for pnpm package.

    Make sure to reload your SHELL.
```

### Additional information:

macOS Intel & M1 had the same issue.

**Comment by xiamu33** [comment]
I got the same issue with same step.

macOS(M1) 12.1
node v16.13.2
pnpm 6.27.2
