### ISSUE TITLE
tests fails with Error: Error: connect ECONNREFUSED 127.0.0.1:80

### ISSUE THREAD

**Issue by hypervisorfdi** [pnpm/pnpm#4235]
```
FAIL feature libs/feature/src/lib/table/table.component.spec.ts (24.531 s)
  ● Console
    console.error
      Error: Error: connect ECONNREFUSED 127.0.0.1:80
          at Object.dispatchError (/export/app/gitlab-runner/root/ui/project/node_modules/.pnpm/jsdom@16.7.0/node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js:63:19)
          at Request.<anonymous> (/export/app/gitlab-runner/root/ui/project/node_modules/.pnpm/jsdom@16.7.0/node_modules/jsdom/lib/jsdom/living/xhr/XMLHttpRequest-impl.js:655:18)
          at Request.emit (events.js:412:35)
          at ClientRequest.<anonymous> (/export/app/gitlab-runner/root/ui/project/node_modules/.pnpm/jsdom@16.7.0/node_modules/jsdom/lib/jsdom/living/helpers/http-request.js:121:14)
          at ClientRequest.emit (events.js:400:28)
          at Socket.socketErrorListener (_http_client.js:475:9)
          at Socket.emit (events.js:400:28)
          at emitErrorNT (internal/streams/destroy.js:106:8)
          at emitErrorCloseNT (internal/streams/destroy.js:74:3)
          at processTicksAndRejections (internal/process/task_queues.js:82:21) undefined
```

### pnpm version:
6.26.1

### Expected behavior:
tests run normally
### Actual behavior:
tests failing
### Additional information:

 - `node -v` prints: v12.22.7
 - Linux

**Comment by zkochan** [comment]
What makes you think that this is related to pnpm?

**Comment by hypervisorfdi** [comment]
so running with NPM all tests works, without touching the code

**Comment by hypervisorfdi** [comment]
Thanks, that helped
