### ISSUE TITLE
pnpm fails when trying to install prod-only dependencies with node-linker=hoisted

### ISSUE THREAD

**Issue by PabloSzx** [pnpm/pnpm#4261]
### pnpm version: 6.27.1

As mentioned in the reproduction repo:

Install all dependencies:

```
pnpm i
```

```
Lockfile is up-to-date, resolution step is skipped
Packages: +4
++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /home/pablosz/.pnpm-store/v3
  Virtual store is at:             node_modules/.pnpm
node_modules/@prisma/client: Running postinstall script, done in 497ms
node_modules/@prisma/engines: Running postinstall script, done in 278ms
node_modules/prisma: Running preinstall script, done in 28ms
node_modules/prisma: Running install script, done in 24ms
Progress: resolved 0, reused 4, downloaded 0, added 4, done
```

Then install only prod dependencies:

```
pnpm i --prod
```

```
Lockfile is up-to-date, resolution step is skipped
 ERROR  Cannot read properties of undefined (reading 'name')
```

### Code to reproduce the issue:

https://github.com/PabloSzx/pnpm-hoisted-prod-only-bug

### Expected behavior:

To work

### Actual behavior:

crashes

### Additional information:

 - `node -v` prints: 16.13.2
 - Windows, macOS, or Linux?: Linux

**Comment by divmgl** [comment]
I can confirm that this is still happening. 

Here's the error stack:

```
  "4694 error pnpm": {
    "err": {
      "name": "pnpm",
      "message": "Cannot read properties of undefined (reading 'name')",
      "stack": "pnpm: Cannot read properties of undefined (reading 'name')\n    at exports2.default (code:87241:24)\n    at /opt/homebrew/Cellar/node/17.4.0/pnpm-global/5/node_modules/.pnpm/pnpm@6.29.1/node_modules/pnpm/dist/pnpm.cjs:114804:71\n    at Array.map (<anonymous>)\n    at toTree (/opt/homebrew/Cellar/node/17.4.0/pnpm-global/5/node_modules/.pnpm/pnpm@6.29.1/node_modules/pnpm/dist/pnpm.cjs:114781:43)\n    at /opt/homebrew/Cellar/node/17.4.0/pnpm-global/5/node_modules/.pnpm/pnpm@6.29.1/node_modules/pnpm/dist/pnpm.cjs:114817:31\n    at Array.map (<anonymous>)\n    at toTree (/opt/homebrew/Cellar/node/17.4.0/pnpm-global/5/node_modules/.pnpm/pnpm@6.29.1/node_modules/pnpm/dist/pnpm.cjs:114781:43)\n    at /opt/homebrew/Cellar/node/17.4.0/pnpm-global/5/node_modules/.pnpm/pnpm@6.29.1/node_modules/pnpm/dist/pnpm.cjs:114817:31\n    at Array.map (<anonymous>)\n    at toTree (/opt/homebrew/Cellar/node/17.4.0/pnpm-global/5/node_modules/.pnpm/pnpm@6.29.1/node_modules/pnpm/dist/pnpm.cjs:114781:43)"
    }
  }
}
```

**Comment by garth** [comment]
Same issue, only happens with `--prod` when using the .npmrc below. Tested on macos and linux (docker) with same result.

```json
  "5 error pnpm": {
    "err": {
      "name": "pnpm",
      "message": "Cannot read properties of undefined (reading 'name')",
      "stack": "pnpm: Cannot read properties of undefined (reading 'name')\n    at exports2.default (/Users/garth/.volta/tools/image/packages/pnpm/lib/node_modules/pnpm/dist/pnpm.cjs:87275:24)\n    at /Users/garth/.volta/tools/image/packages/pnpm/lib/node_modules/pnpm/dist/pnpm.cjs:114870:71\n    at Array.map (<anonymous>)\n    at toTree (/Users/garth/.volta/tools/image/packages/pnpm/lib/node_modules/pnpm/dist/pnpm.cjs:114847:43)\n    at /Users/garth/.volta/tools/image/packages/pnpm/lib/node_modules/pnpm/dist/pnpm.cjs:114883:31\n    at Array.map (<anonymous>)\n    at toTree (/Users/garth/.volta/tools/image/packages/pnpm/lib/node_modules/pnpm/dist/pnpm.cjs:114847:43)\n    at hoistByLockfile (/Users/garth/.volta/tools/image/packages/pnpm/lib/node_modules/pnpm/dist/pnpm.cjs:114820:23)\n    at _lockfileToHoistedDepGraph (/Users/garth/.volta/tools/image/packages/pnpm/lib/node_modules/pnpm/dist/pnpm.cjs:114950:45)\n    at lockfileToHoistedDepGraph (/Users/garth/.volta/tools/image/packages/pnpm/lib/node_modules/pnpm/dist/pnpm.cjs:114944:18)"
    }
  }
```

my .npmrc:

```
shamefully-hoist=true
node-linker=hoisted     # removing this line seems to fix
package-import-method=copy
```

**Comment by hinell** [comment]
Werildly, I got this:

```rust
 ERR_PNPM_META_FETCH_FAIL  GET https://registry.npmjs.org/pnpm: Value of "this" must be of type URLSearchParams
 WARN  GET https://registry.npmjs.org/@typescript-eslint%2Fparser error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/@typescript-eslint%2Feslint-plugin error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/eslint error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/typescript error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
```

**Comment by hinell** [comment]
Probably related: 
https://github.com/pnpm/pnpm/issues/6499#issuecomment-1561166991

**Comment by zkochan** [comment]
This no longer reproduces on current pnpm, so closing.

Verified on pnpm 12.5.1 with `nodeLinker: hoisted`: `pnpm install --prod` after a full install removes the devDependencies and exits 0.

If you still hit this on the latest pnpm, please comment with a reproduction and we will reopen.

---
Written by an agent (Claude Code, claude-opus-5).
