### ISSUE TITLE
Not all packages are being installed

### ISSUE THREAD

**Issue by christian-gama** [pnpm/pnpm#4268]
I am trying to run storybook (with vite instead of webpack) with pnpm, but when I try to run `pnpm install` and then `pnpm run storybook`, I receive a bunch of missing dependencies. However, if I execute `npm install` and then `npm run storybook `everything works perfectly. I've tried to install the missing dependencies manually, but it's pointless, as there several missing dependencies (everytime I install one, I am asked to install a new one).

You can easily reproduce it with a brand new vite/storybook React-ts project:
```
$ pnpm init vite
$ pnpx sb@next init --builder storybook-builder-vite
$ pnpm run storybook
```

Make sure you install dependencies using `pnpm install`

### pnpm version: 
6.27.2

### Expected behavior: 
Install all packages and get no error.

### Actual behavior:
Got a bunch of missing dependencies error.

### Additional info: 
I've tried to use `node-linker=hoisted` and I had no success at all, but I received different missing dependencies errors.

 - `node -v` prints: 16.13.1
 - Windows, macOS, or Linux?: Linux

```
ERR! Error: [vite-plugin-mdx] "@mdx-js/react" must be installed
ERR!     at resolveImport (/home/christian/Área de Trabalho/abc/project/node_modules/.pnpm/vite-plugin-mdx@3.5.10_@mdx-js+mdx@1.6.22+vite@2.7.13/node_modules/vite-plugin-mdx/dist/imports.js:29:23)
ERR!     at Object.assertImportExists (/home/christian/Área de Trabalho/abc/project/node_modules/.pnpm/vite-plugin-mdx@3.5.10_@mdx-js+mdx@1.6.22+vite@2.7.13/node_modules/vite-plugin-mdx/dist/imports.js:41:12)
ERR!     at /home/christian/Área de Trabalho/abc/project/node_modules/.pnpm/vite-plugin-mdx@3.5.10_@mdx-js+mdx@1.6.22+vite@2.7.13/node_modules/vite-plugin-mdx/dist/transform.js:18:19
ERR!     at Array.map (<anonymous>)
ERR!     at Object.createTransformer (/home/christian/Área de Trabalho/abc/project/node_modules/.pnpm/vite-plugin-mdx@3.5.10_@mdx-js+mdx@1.6.22+vite@2.7.13/node_modules/vite-plugin-mdx/dist/transform.js:17:50)
ERR!     at Object.configResolved (/home/christian/Área de Trabalho/abc/project/node_modules/.pnpm/vite-plugin-mdx@3.5.10_@mdx-js+mdx@1.6.22+vite@2.7.13/node_modules/vite-plugin-mdx/dist/index.js:46:43)
ERR!     at /home/christian/Área de Trabalho/abc/project/node_modules/.pnpm/vite@2.7.13/node_modules/vite/dist/node/chunks/dep-f5552faa.js:74824:127
ERR!     at Array.map (<anonymous>)
ERR!     at resolveConfig (/home/christian/Área de Trabalho/abc/project/node_modules/.pnpm/vite@2.7.13/node_modules/vite/dist/node/chunks/dep-f5552faa.js:74824:35)
ERR!     at processTicksAndRejections (node:internal/process/task_queues:96:5)
ERR!     at async createServer (/home/christian/Área de Trabalho/abc/project/node_modules/.pnpm/vite@2.7.13/node_modules/vite/dist/node/chunks/dep-f5552faa.js:60326:20)
ERR!     at async Object.start (/home/christian/Área de Trabalho/abc/project/node_modules/.pnpm/storybook-builder-vite@0.1.13_a5ce969bcf8d8747b3a0d666bc290993/node_modules/storybook-builder-vite/index.js:33:20)
ERR!     at async Promise.all (index 0)
ERR!     at async storybookDevServer (/home/christian/Área de Trabalho/abc/project/node_modules/.pnpm/@storybook+core-server@6.5.0-alpha.22_64539567fecf02928f0b6f9bf2f8ff71/node_modules/@storybook/core-server/dist/cjs/dev-server.js:126:28)
ERR!     at async buildDevStandalone (/home/christian/Área de Trabalho/abc/project/node_modules/.pnpm/@storybook+core-server@6.5.0-alpha.22_64539567fecf02928f0b6f9bf2f8ff71/node_modules/@storybook/core-server/dist/cjs/build-dev.js:115:31)
ERR!     at async buildDev (/home/christian/Área de Trabalho/abc/project/node_modules/.pnpm/@storybook+core-server@6.5.0-alpha.22_64539567fecf02928f0b6f9bf2f8ff71/node_modules/@storybook/core-server/dist/cjs/build-dev.js:161:5)
ERR!  Error: [vite-plugin-mdx] "@mdx-js/react" must be installed
ERR!     at resolveImport (/home/christian/Área de Trabalho/abc/project/node_modules/.pnpm/vite-plugin-mdx@3.5.10_@mdx-js+mdx@1.6.22+vite@2.7.13/node_modules/vite-plugin-mdx/dist/imports.js:29:23)
ERR!     at Object.assertImportExists (/home/christian/Área de Trabalho/abc/project/node_modules/.pnpm/vite-plugin-mdx@3.5.10_@mdx-js+mdx@1.6.22+vite@2.7.13/node_modules/vite-plugin-mdx/dist/imports.js:41:12)
ERR!     at /home/christian/Área de Trabalho/abc/project/node_modules/.pnpm/vite-plugin-mdx@3.5.10_@mdx-js+mdx@1.6.22+vite@2.7.13/node_modules/vite-plugin-mdx/dist/transform.js:18:19
ERR!     at Array.map (<anonymous>)
ERR!     at Object.createTransformer (/home/christian/Área de Trabalho/abc/project/node_modules/.pnpm/vite-plugin-mdx@3.5.10_@mdx-js+mdx@1.6.22+vite@2.7.13/node_modules/vite-plugin-mdx/dist/transform.js:17:50)
ERR!     at Object.configResolved (/home/christian/Área de Trabalho/abc/project/node_modules/.pnpm/vite-plugin-mdx@3.5.10_@mdx-js+mdx@1.6.22+vite@2.7.13/node_modules/vite-plugin-mdx/dist/index.js:46:43)
ERR!     at /home/christian/Área de Trabalho/abc/project/node_modules/.pnpm/vite@2.7.13/node_modules/vite/dist/node/chunks/dep-f5552faa.js:74824:127
ERR!     at Array.map (<anonymous>)
ERR!     at resolveConfig (/home/christian/Área de Trabalho/abc/project/node_modules/.pnpm/vite@2.7.13/node_modules/vite/dist/node/chunks/dep-f5552faa.js:74824:35)
ERR!     at processTicksAndRejections (node:internal/process/task_queues:96:5)
ERR!     at async createServer (/home/christian/Área de Trabalho/abc/project/node_modules/.pnpm/vite@2.7.13/node_modules/vite/dist/node/chunks/dep-f5552faa.js:60326:20)
ERR!     at async Object.start (/home/christian/Área de Trabalho/abc/project/node_modules/.pnpm/storybook-builder-vite@0.1.13_a5ce969bcf8d8747b3a0d666bc290993/node_modules/storybook-builder-vite/index.js:33:20)
ERR!     at async Promise.all (index 0)
ERR!     at async storybookDevServer (/home/christian/Área de Trabalho/abc/project/node_modules/.pnpm/@storybook+core-server@6.5.0-alpha.22_64539567fecf02928f0b6f9bf2f8ff71/node_modules/@storybook/core-server/dist/cjs/dev-server.js:126:28)
ERR!     at async buildDevStandalone (/home/christian/Área de Trabalho/abc/project/node_modules/.pnpm/@storybook+core-server@6.5.0-alpha.22_64539567fecf02928f0b6f9bf2f8ff71/node_modules/@storybook/core-server/dist/cjs/build-dev.js:115:31)
ERR!     at async buildDev (/home/christian/Área de Trabalho/abc/project/node_modules/.pnpm/@storybook+core-server@6.5.0-alpha.22_64539567fecf02928f0b6f9bf2f8ff71/node_modules/@storybook/core-server/dist/cjs/build-dev.js:161:5)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by zkochan** [comment]
With your steps I get this error: 

```
 ERR_PNPM_NO_SCRIPT  Missing script: storybook
```

How do you set `node-linker=hoisted`? Do you set it via a `.npmrc` file? Try to remove node_modules after setting it and running `pnpm install` again.

**Comment by christian-gama** [comment]
> With your steps I get this error:
> 
> ```
>  ERR_PNPM_NO_SCRIPT  Missing script: storybook
> ```
> 
> How do you set `node-linker=hoisted`? Do you set it via a `.npmrc` file? Try to remove node_modules after setting it and running `pnpm install` again.

The exact steps you can find it in the official storybook docs (they're using npm btw): 
1. `pnpm init vite`
Select: react > react-ts

2. `pnpx sb@next init --builder storybook-builder-vite`
Select: Y 

3. It will install all dependencies automatically using npm. Delete node_modules and package-lock.json and then run `pnpm install`

4. `pnpm run storybook`

You can expect this error: `Error: [vite-plugin-mdx] "@mdx-js/react" must be installed`
If you repeat these steps using npm, you will receive no errors and everything works perfectly.

------------------------

Using `node-linker=hoisted `  via `.npmrc` and removing node_modules, as you suggest, works in this brand new project. However, this very same step in another minor project with more dependencies it does not work, it asks me to install a few missing dependencies, however npm and yarn does not ask me to install anything at all, it just works out of the box, which is very weird imo.

I fixed all errors installing all missing dependencies manually, but it makes me think **why it asks me to install those dependencies whenever I use pnpm, but it does not ask me to install whenever I use npm/yarn**...

My repo: https://github.com/christian-gama/aicrag-v2-frontend/tree/development

**Comment by christian-gama** [comment]
I'll close this issue as I found out this issue is related to storybook and not pnpm. Storybook is currently missing dependencies and it only works with npm because of the flat node_modules. 

A workaround at the moment is to install the missing dependencies manually until storybook fixes it and use `node-linker=hoisted`.

**Comment by zkochan** [comment]
If you know where and which dependencies are missing, then you may use [`packageExtensions`](https://pnpm.io/package_json#pnpmpackageextensions) for patching.
