### ISSUE TITLE
Standalone pnpm cannot find node-gyp

### ISSUE THREAD

**Issue by alexeyten** [pnpm/pnpm#4347]
### pnpm version:
6.31.0

### Code to reproduce the issue:
pnpm  i posix

<details>
<summary>last lines .pnpm-debug.log</summary>

```
  "30 debug pnpm:link": {
    "target": "/root/prj/node_modules/.pnpm/nan@2.15.0/node_modules/nan",
    "link": "/root/prj/node_modules/.pnpm/node_modules/nan"
  },
  "31 debug pnpm:lifecycle": {
    "depPath": "/posix/4.2.0",
    "optional": false,
    "script": "node-gyp rebuild",
    "stage": "install",
    "wd": "/root/prj/node_modules/.pnpm/posix@4.2.0/node_modules/posix"
  },
  "32 debug pnpm:lifecycle": {
    "depPath": "/posix/4.2.0",
    "line": "sh: 1: node-gyp: not found",
    "stage": "install",
    "stdio": "stderr",
    "wd": "/root/prj/node_modules/.pnpm/posix@4.2.0/node_modules/posix"
  },
  "33 error pnpm": {
    "code": "ELIFECYCLE",
    "errno": "ENOENT",
    "syscall": "spawn",
    "file": "sh",
    "pkgid": "posix@4.2.0",
    "stage": "install",
    "script": "node-gyp rebuild",
    "pkgname": "posix",
    "err": {
      "name": "pnpm",
      "message": "posix@4.2.0 install: `node-gyp rebuild`\nspawn ENOENT",
      "code": "ELIFECYCLE",
      "stack": "pnpm: posix@4.2.0 install: `node-gyp rebuild`\nspawn ENOENT\n    at ChildProcess.<anonymous> (/snapshot/dist/pnpm.cjs)\n    at ChildProcess.emit (events.js:376:20)\n    at maybeClose (internal/child_process.js:1055:16)\n    at Socket.<anonymous> (internal/child_process.js:441:11)\n    at Socket.emit (events.js:376:20)\n    at Pipe.<anonymous> (net.js:673:12)"
    }
  }
```
</details>

### Expected behavior:
posix installed

### Actual behavior:
```
node_modules/.pnpm/posix@4.2.0/node_modules/posix: Running install script...
 ELIFECYCLE  Command failed.
```

### Additional information:

 - `node -v` prints: v16.14.0
 - Windows, macOS, or Linux?: linux

If i install pnpm through npm (`npm -g install pnpm`) then it successfully installs posix.

**Comment by zkochan** [comment]
I like how Yarn automatically detects if a package uses node-gyp and installs it as a dependency of the package. This allows to ship Yarn without node-gyp. The only issue is that info from the lockfile is not sufficient to tell whether a package needs node-gyp. node-gyp is needed if the package has `binding-gyp` in the root. We know this only after downloading the tarball of the package. This is too late for pnpm. Maybe we can consider this to be an edge case.

**Comment by alexeyten** [comment]
I've found workaround.

Just added to `package.json`:
```json
"pnpm": {
  "packageExtensions": {
    "posix": {
      "optionalDependencies": {
        "node-gyp": "*"
      }
    }
  }
}
```

**Comment by alexeyten** [comment]
Another workaround is to install `node-gyp` globally.
Could this be a “recommended workaround”?
```
$ pnpm install posix
Packages: +2
++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /home/lynn/.pnpm-store/v3
  Virtual store is at:             node_modules/.pnpm
node_modules/.pnpm/posix@4.2.0/node_modules/posix: Running install script...
 ELIFECYCLE  Command failed.
Progress: resolved 1, reused 0, downloaded 0, added 0

$ pnpm -g install node-gyp
Packages: +91
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 91, reused 91, downloaded 0, added 0, done

/home/lynn/.local/share/pnpm-global/5:
+ node-gyp 8.4.1

$ pnpm install posix
Packages: +2
++
node_modules/.pnpm/posix@4.2.0/node_modules/posix: Running install script, done in 2.9s
Progress: resolved 2, reused 2, downloaded 0, added 0, done
```

**Comment by zkochan** [comment]
Well, I don't think installing it is the best way but it is definitely the fastest way to fix it. Maybe pnpm could automatically install it globally during setup.

**Comment by alexandrucojocaru-creatopy** [comment]
This stopped being an edge case in **pnpm 12**: the standalone distribution is now the default one, so every user hits this path.

Reproduced on a monorepo with several native dependencies, against the same working tree and the same populated `node_modules`:

```
pnpm 11.25.0 → pnpm rebuild ghostscript4js → exit 0
pnpm 12.2.1  → pnpm rebuild ghostscript4js → sh: node-gyp: command not found, exit 1
```

A few things that narrow it down:

- **Not an ordering problem.** It still fails with `node_modules/.bin/node-gyp` already linked (the repo declares `node-gyp` as a root devDependency).
- **Not a general PATH loss.** `pnpm exec sh -c 'command -v node-gyp'` resolves it under *both* versions. It is specifically the environment of a **dependency's** lifecycle script.
- **node-gyp is still shipped.** Both 11.25.0 and 12.2.1 contain `dist/node-gyp-bin/` and `dist/node_modules/node-gyp`, and 12.2.1's manifest still has the `bundle-node-gyp` script. So v12 bundles the binary but no longer exposes it to dependency install scripts — which is what makes this look unintended rather than a deliberate removal.

Two things that make it bite harder than the original report suggests:

1. **Packages with a prebuilt fallback fail only where it matters.** `canvas` and `sqlite3` run `prebuild-install -r napi || node-gyp rebuild`, so they are fine on glibc and fall through to node-gyp exactly on **musl/Alpine**, where no prebuilt exists — i.e. in container images rather than on developer machines.
2. **The install can exit 0 with a native build silently skipped.** In one run `ssh2` logged `/bin/sh: node-gyp: command not found` and the overall install still reported success. A missing binding then surfaces at runtime instead of at install time.

Confirmed failing here: `ghostscript4js`, `cpu-features`, `ssh2`. The `packageExtensions` workaround above does work — adding `node-gyp` to each affected package — but it is a hand-maintained list of native packages guarding a failure mode that exits 0, so a newly added native dependency is missed silently.

Nothing in the 12.0.0 / 12.1.0 / 12.2.0 / 12.2.1 release notes mentions node-gyp or the lifecycle-script PATH. The closest candidate is the 12.0.0 patch change *"the built-in compatibility database no longer adds dependencies that were detected by static analysis of published packages"*, but a pnpm 11 lockfile shows no injected `node-gyp` on any of these packages, so that does not appear to be the mechanism.

**Comment by alexandrucojocaru-creatopy** [comment]
**Correction to my comment above — I over-generalised from macOS, and two of my claims are wrong.**

I have since run the same package, the same pnpm 12.2.1 (installed the same way, `npm install --global`), with the same flags, on three platforms:

| Platform | `cpu-features@0.0.10` install |
| --- | --- |
| linux/amd64 (Alpine, musl) | ✅ `gyp info ok` |
| linux/arm64 (Alpine, musl) | ✅ `gyp info ok` |
| darwin/arm64 | ❌ `sh: node-gyp: command not found` |

So, correcting myself:

- **It is not "every user".** On Linux, pnpm 12.2.1 puts its bundled node-gyp on the dependency's script PATH correctly — the build log shows it resolving `-Dnode_gyp_dir=/usr/local/lib/node_modules/pnpm/dist/node_modules/node-gyp`. This appears to be **macOS-specific**.
- **My musl/Alpine claim was backwards.** I said it would bite in container images rather than on laptops. The opposite is true: Linux containers are fine, and macOS development machines are where it fails.

What still stands from the original comment: it is not an ordering problem, `pnpm exec` resolves node-gyp under both versions, v12 still ships the shim at `dist/node-gyp-bin/`, and the same-tree v11-vs-v12 delta is real — but on macOS only.

Also worth adding, since it cost me a misleading pass: this is easy to test wrongly. My first repro "succeeded" because the side-effects cache served an artifact built earlier by pnpm 11. `--config.side-effects-cache=false` is needed to observe the real behaviour.

Prepending pnpm's own `dist/node-gyp-bin` to `PATH` fixes it on macOS, using the bundled node-gyp:

```
PATH="$(dirname "$(realpath "$(command -v pnpm)")")/dist/node-gyp-bin:$PATH"
```

Apologies for the noise on a three-year-old issue — the platform scope matters for how this gets prioritised, so I would rather correct it than leave it overstated.

**Comment by zkochan** [comment]
This no longer reproduces on current pnpm, so closing.

Verified while checking 2135 and 3625: pnpm ships node-gyp beside the binary and native packages build. `npm_config_node_gyp` still wins when set.

If you still hit this on the latest pnpm, please comment with a reproduction and we will reopen.

---
Written by an agent (Claude Code, claude-opus-5).
