### ISSUE TITLE
pnpm doesn't install transitive dependencies with `temporalio`

### ISSUE THREAD

**Issue by lorensr** [pnpm/pnpm#4428]
### Expected behavior:

`pnpm` installs transitive dependencies.

### Actual behavior:

When I have `temporalio` as a dep, which has `@temporalio/client` as a dep, and I run `pnpm install`, I get `Cannot find module '@temporalio/client'`, and `pnpm ls @temporalio/client` outputs nothing. 

Why isn't `@temporalio/client` being installed? 

`temporalio`'s `package.json` is:

```
$ cat node_modules/temporalio/package.json
{
  "name": "temporalio",
  "version": "0.19.0-rc.1",
  "description": "Temporal.io SDK meta-package",
  "dependencies": {
    "@temporalio/activity": "^0.19.0-rc.1",
    "@temporalio/client": "^0.19.0-rc.1",
    "@temporalio/common": "^0.19.0-rc.1",
    "@temporalio/proto": "^0.19.0-rc.1",
    "@temporalio/worker": "^0.19.0-rc.1",
    "@temporalio/workflow": "^0.19.0-rc.1"
  },
  ...
} 
```

### Code to reproduce the issue:

https://github.com/temporalio/samples-typescript/tree/pnpm/hello-world

```
git clone -b pnpm git@github.com:temporalio/samples-typescript.git
cd samples-typescript/hello-world
pnpm install
pnpm run workflow

> temporal-hello-world@0.1.0 workflow /Users/me/gh/samples-typescript/hello-world
> ts-node src/client.ts

/Users/me/gh/samples-typescript/hello-world/node_modules/.pnpm/ts-node@10.7.0_typescript@4.6.2/node_modules/ts-node/src/index.ts:820
    return new TSError(diagnosticText, diagnosticCodes);
           ^
TSError: ⨯ Unable to compile TypeScript:
src/client.ts:2:44 - error TS2307: Cannot find module '@temporalio/client' or its corresponding type declarations.

2 import { Connection, WorkflowClient } from '@temporalio/client';
                                             ~~~~~~~~~~~~~~~~~~~~

    at createTSError (/Users/me/gh/samples-typescript/hello-world/node_modules/.pnpm/ts-node@10.7.0_typescript@4.6.2/node_modules/ts-node/src/index.ts:820:12)
    at reportTSError (/Users/me/gh/samples-typescript/hello-world/node_modules/.pnpm/ts-node@10.7.0_typescript@4.6.2/node_modules/ts-node/src/index.ts:824:19)
    at getOutput (/Users/me/gh/samples-typescript/hello-world/node_modules/.pnpm/ts-node@10.7.0_typescript@4.6.2/node_modules/ts-node/src/index.ts:1014:36)
    at Object.compile (/Users/me/gh/samples-typescript/hello-world/node_modules/.pnpm/ts-node@10.7.0_typescript@4.6.2/node_modules/ts-node/src/index.ts:1322:43)
    at Module.m._compile (/Users/me/gh/samples-typescript/hello-world/node_modules/.pnpm/ts-node@10.7.0_typescript@4.6.2/node_modules/ts-node/src/index.ts:1454:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/me/gh/samples-typescript/hello-world/node_modules/.pnpm/ts-node@10.7.0_typescript@4.6.2/node_modules/ts-node/src/index.ts:1458:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  diagnosticCodes: [ 2307 ]
}
 ELIFECYCLE  Command failed with exit code 1.
```

`node_modules/.pnpm-debug.log`

```json
{
  "0 debug pnpm:scope": {
    "selected": 1
  },
  "1 error pnpm": {
    "errno": 1,
    "code": "ELIFECYCLE",
    "pkgid": "temporal-hello-world@0.1.0",
    "stage": "workflow",
    "script": "ts-node src/client.ts",
    "pkgname": "temporal-hello-world",
    "err": {
      "name": "pnpm",
      "message": "temporal-hello-world@0.1.0 workflow: `ts-node src/client.ts`\nExit status 1",
      "code": "ELIFECYCLE",
      "stack": "pnpm: temporal-hello-world@0.1.0 workflow: `ts-node src/client.ts`\nExit status 1\n    at EventEmitter.<anonymous> (/Users/me/.nvm/versions/node/v16.13.0/pnpm-global/5/node_modules/.pnpm/pnpm@6.32.3/node_modules/pnpm/dist/pnpm.cjs:105724:20)\n    at EventEmitter.emit (node:events:390:28)\n    at ChildProcess.<anonymous> (/Users/me/.nvm/versions/node/v16.13.0/pnpm-global/5/node_modules/.pnpm/pnpm@6.32.3/node_modules/pnpm/dist/pnpm.cjs:92285:18)\n    at ChildProcess.emit (node:events:390:28)\n    at maybeClose (node:internal/child_process:1064:16)\n    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)"
    }
  }
}
```

### Additional information:

 - `node -v` prints: 16.13.1
 - Windows, macOS, or Linux?: macOS 12.2.1

**Comment by lorensr** [comment]
My understanding is this is by design: https://github.com/temporalio/sdk-typescript/issues/421#issuecomment-1067196052
