### ISSUE TITLE
Conflicting packages: @babel/cli and webpack-cli. Works as expected in npm and yarn.

### ISSUE THREAD

**Issue by manelio** [pnpm/pnpm#4490]
```
pnpm --version
6.32.3
```

I'm pretty sure this is symptom of something not directly related to babel and webpack, but is easily reproducible.

```
mkdir testpnpm && cd $_
pnpm init -y
pnpm add -D @babel/core @babel/cli webpack webpack-cli
pnpm exec webpack --version
```

Output:

```
~/testpnpm/node_modules/.pnpm/webpack@5.70.0_webpack-cli@4.9.2/node_modules/webpack-cli/lib/webpack-cli.js:18
    this.program.name("webpack");
                 ^

TypeError: Cannot read properties of undefined (reading 'name')
    at new WebpackCLI (~/testpnpm/node_modules/.pnpm/webpack@5.70.0_webpack-cli@4.9.2/node_modules/webpack-cli/lib/webpack-cli.js:18:18)
    at runCLI (~/testpnpm/node_modules/.pnpm/webpack@5.70.0_webpack-cli@4.9.2/node_modules/webpack-cli/lib/bootstrap.js:5:15)
    at Object.<anonymous> (~/testpnpm/node_modules/.pnpm/webpack@5.70.0_webpack-cli@4.9.2/node_modules/webpack-cli/bin/cli.js:17:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at runCli (~/testpnpm/node_modules/.pnpm/webpack@5.70.0_webpack-cli@4.9.2/node_modules/webpack/bin/webpack.js:69:2)
```

But if I remove `@babel/cli`:

```
pnpm remove @babel/cli
pnpm exec webpack --version
```

Output:

```
webpack: 5.70.0
webpack-cli: 4.9.2
webpack-dev-server not installed
```

There's not problem using `npm`:

```
mkdir testnpm && cd $_
npm init -y
npm i -D @babel/core @babel/cli webpack webpack-cli
npx webpack --version
```

Output:

```
webpack: 5.70.0
webpack-cli: 4.9.2
webpack-dev-server not installed
```

**Comment by zkochan** [comment]
I cannot reproduce this. Maybe it was fixed in webpack/babel

**Comment by mcmxcdev** [comment]
I cannot reproduce this either with pnpm v7.1.2, can be closed.

**Comment by manelio** [comment]
Still happening to me, even with pnpm v7.1.2.

I'm closing the issue since it looks more related to webpack and babel. But I'm still trying to figure out why there's no problem with npm nor yarn.
