### ISSUE TITLE
Can't update pnpm@7 version if I installed it with pnpm@6

### ISSUE THREAD

**Issue by nikoladev** [pnpm/pnpm#4557]
### pnpm version:
`pnpm@7.0.0-rc.2` and `pnpm@7.0.0-rc.3`

### Code to reproduce the issue:
- I install pnpm using `curl -fsSL https://get.pnpm.io/install.sh | sh -`
- Then I install pnpm 7 rc2 `pnpm add -g pnpm@^7.0.0-rc.2`
- Then I try to update `pnpm add -g pnpm@^7.0.0-rc.3` and get the following error:

```
 ERR_PNPM_UNEXPECTED_STORE  Unexpected store location

The dependencies at "/Users/me/Library/pnpm/global-packages/5/node_modules" are currently linked from the store at "/Users/me/.pnpm-store/v3".

pnpm now wants to use the store at "/Users/me/Library/pnpm/store/v3" to link dependencies.

If you want to use the new store location, reinstall your dependencies with "pnpm install".

You may change the global store location by running "pnpm config set store-dir <dir>".
(This error may happen if the node_modules was installed with a different major version of pnpm)
```

From my `~/.pnpm-debug.log`:

```
{
  "0 debug pnpm:scope": {
    "selected": 1
  },
  "1 error pnpm": {
    "code": "ERR_PNPM_UNEXPECTED_STORE",
    "expectedStorePath": "/Users/me/.pnpm-store/v3",
    "actualStorePath": "/Users/me/Library/pnpm/store/v3",
    "modulesDir": "/Users/me/Library/pnpm/global-packages/5/node_modules",
    "err": {
      "name": "pnpm",
      "message": "Unexpected store location",
      "code": "ERR_PNPM_UNEXPECTED_STORE",
      "stack": "pnpm: Unexpected store location\n    at checkCompatibility (/Users/me/Library/pnpm-global/5/node_modules/.pnpm/pnpm@7.0.0-rc.3/node_modules/pnpm/dist/pnpm.cjs:93041:15)\n    at /Users/me/Library/pnpm-global/5/node_modules/.pnpm/pnpm@7.0.0-rc.3/node_modules/pnpm/dist/pnpm.cjs:93563:44\n    at Array.map (<anonymous>)\n    at validateModules (/Users/me/Library/pnpm-global/5/node_modules/.pnpm/pnpm@7.0.0-rc.3/node_modules/pnpm/dist/pnpm.cjs:93561:34)\n    at getContext (/Users/me/Library/pnpm-global/5/node_modules/.pnpm/pnpm@7.0.0-rc.3/node_modules/pnpm/dist/pnpm.cjs:93457:34)\n    at async mutateModules (/Users/me/Library/pnpm-global/5/node_modules/.pnpm/pnpm@7.0.0-rc.3/node_modules/pnpm/dist/pnpm.cjs:119574:19)\n    at async handler (/Users/me/Library/pnpm-global/5/node_modules/.pnpm/pnpm@7.0.0-rc.3/node_modules/pnpm/dist/pnpm.cjs:121156:33)\n    at async /Users/me/Library/pnpm-global/5/node_modules/.pnpm/pnpm@7.0.0-rc.3/node_modules/pnpm/dist/pnpm.cjs:175770:21\n    at async run (/Users/me/Library/pnpm-global/5/node_modules/.pnpm/pnpm@7.0.0-rc.3/node_modules/pnpm/dist/pnpm.cjs:175744:34)\n    at async runPnpm (/Users/me/Library/pnpm-global/5/node_modules/.pnpm/pnpm@7.0.0-rc.3/node_modules/pnpm/dist/pnpm.cjs:175962:5)"
    }
  }
}
```

### Expected behavior:
I can update from `pnpm@7.0.0-rc.2` to `pnpm@7.0.0-rc.3`

### Actual behavior:
I get the above error

### Additional information:

 - `node -v` prints: v16.14.2
 - Windows, macOS, or Linux?: macOS 11.6.5

**Comment by zkochan** [comment]
Well, these are prerelease versions of pnpm. Each prerelease version may have breaking changes. So we can't really guarantee anything. 

But this won't happen, when upgrading from v6 to v7.0.0

**Comment by nikoladev** [comment]
FYI, I don't remember this happening with the alpha and beta releases.

Could this have anything to do with moving the store from `~/.pnpm-store` to the new XDG compatible locations? That happened in rc2, right?

**Comment by zkochan** [comment]
> Could this have anything to do with moving the store from ~/.pnpm-store to the new XDG compatible locations? That happened in rc2, right?

yes. And we also changed the location of the global packages but in a different prerelease version. When switching from v6 to v7 both locations will change at the same time, so the issue will not happen.

**Comment by Luckz** [comment]
> But this won't happen, when upgrading from v6 to v7.0.0

For what it's worth, I upgraded to 7 and pnpm bricked itself, without going for any pre-release versions inbetween.

**Comment by hypo-thesis** [comment]
Just spent 2 hours updating it to no avail. I wanted to uninstall it from my system to no avail I guess the 6 version and I are best buddies until the next windows install that I may have in a few years or so. Just wanted to thank you, great stuff.

**Comment by bernardoadc** [comment]
Suddenly this happened here, but I did not update on pnpm whatsoever. Also, that msg states you may change the global store location, but even doing that, the error continues. Why? Why would pnpm consider your setting in .npmrc to be suddenly wrong?

**Comment by Zhang2Henry** [comment]
any progress ?

 i have the same problem.  'pnpm up ' can't update package version from '0.6.0' to '0.6.0-rc.1'  ( custom package rc.1 is newer )

platform: window 10
node -v : 16.20.0
pnpm -v: 8.6.6

**Comment by henke443** [comment]
I think I managed to fix this issue.
I have Windows 11 and I got this issue on a new next project after generating it using NX.
Actions I took (not sure which one fixed it):

1. (turning vs code off should be sufficient) 
  Disable jest & nx extensions for vs code 
  
2. (probably not required) 
  Going to another pnpm project that worked before 
  
3. Running `pnpm config set store-dir <dir> --global` 
  where <dir> is the first directory mentioned in the error message.
  
4. *immediately* running `pnpm i` afterwards.

5. If (3 & 4) doesn't work try the other directory

6. After a couple minutes it should be fixed

**Comment by zkochan** [comment]
This targets a part of pnpm that no longer exists, so closing.

Updating pnpm across majors goes through `pnpm self-update` now, and the standalone installer no longer leaves a version it cannot replace.

If you still hit this on the latest pnpm, please comment with a reproduction and we will reopen.

---
Written by an agent (Claude Code, claude-opus-5).
