### ISSUE TITLE
Transitive dependency has incorrect version

### ISSUE THREAD

**Issue by yuyez** [pnpm/pnpm#4592]
### Code to reproduce the issue:

package.json
```
{
  "dependencies": {
    "ansi-styles": "2.2.1",
    "wrap-ansi": "7.0.0"
  }
}
```

`wrap-ansi@7.0.0` depends on `"ansi-styles": "^4.0.0"`.

### Expected behavior:
`node_modules/ansi-styles` has version `2.2.1`
`node_modules/wrap-ansi` has version `7.0.0`
`node_modules/wrap-ansi/node_modules/ansi-styles` has version `4.x.x`

### Actual behavior:
`node_modules/ansi-styles` has version `2.2.1`
`node_modules/wrap-ansi` has version `7.0.0`
**BUG**: `node_modules/wrap-ansi` doesn't have a `node_modules` directory

`wrap-ansi` gets an incompatible version of `ansi-styles` at runtime.

### Additional information:

 - `node -v` prints: v16.14.0
 - Windows, macOS, or Linux?: Windows

**Comment by zkochan** [comment]
> BUG: node_modules/wrap-ansi doesn't have a node_modules directory

it does have a node_modules. Its node_modules is at `node_modules/.pnpm/wrap-ansi@7.0.0/node_modules`

`node_modules/wrap-ansi` is just a symlink to `node_modules/.pnpm/wrap-ansi@7.0.0/node_modules/wrap-ansi`

You can read about it at https://pnpm.io/blog/2020/05/27/flat-node-modules-is-not-the-only-way
and at https://pnpm.io/symlinked-node-modules-structure

**Comment by yuyez** [comment]
You're right. I think we're hitting a wrong version of `ansi-styles` due to the way to run node.

We run `node node_modules/mocha/bin/_mocha` on Windows. Notice halfway down the stack, `node_modules\.pnpm\mocha@9.2.0` went to `node_modules\cliui` instead of `node_modules\.pnpm\cliui@7.0.4`.

I'll keep investigating. I'm guessing we might have to set `NODE_PATH`.

```
Uncaught TypeError TypeError: Cannot read properties of undefined (reading 'get')
    at exec (e:\repo\node_modules\wrap-ansi\index.js:184:33)
    at <anonymous> (e:\repo\node_modules\wrap-ansi\index.js:214:16)
    at module.exports (e:\repo\node_modules\wrap-ansi\index.js:214:4)
    at <anonymous> (e:\repo\node_modules\cliui\build\index.cjs:169:33)
    at rasterize (e:\repo\node_modules\cliui\build\index.cjs:165:13)
    at rowToString (e:\repo\node_modules\cliui\build\index.cjs:95:14)
    at <anonymous> (e:\repo\node_modules\cliui\build\index.cjs:85:18)
    at toString (e:\repo\node_modules\cliui\build\index.cjs:84:19)
    at help (e:\repo\node_modules\.pnpm\mocha@9.2.0\node_modules\yargs\build\index.cjs:1032:19)
    at self.cacheHelpMessage (e:\repo\node_modules\.pnpm\mocha@9.2.0\node_modules\yargs\build\index.cjs:1072:34)
    at runCommand (e:\repo\node_modules\.pnpm\mocha@9.2.0\node_modules\yargs\build\index.cjs:450:42)
    at parseArgs (e:\repo\node_modules\.pnpm\mocha@9.2.0\node_modules\yargs\build\index.cjs:2706:53)
    at parse (e:\repo\node_modules\.pnpm\mocha@9.2.0\node_modules\yargs\build\index.cjs:2278:29)
    at exports.main (e:\repo\node_modules\.pnpm\mocha@9.2.0\node_modules\mocha\lib\cli\cli.js:78:6)
    at <anonymous> (e:\repo\node_modules\.pnpm\mocha@9.2.0\node_modules\mocha\bin\_mocha:10:23)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:822:12)
    at executeUserEntryPoint (node:internal/modules/run_main:77:12)
    at <anonymous> (node:internal/main/run_main_module:17:47)
```

**Comment by yuyez** [comment]
As a workaround, we added node commands as scripts in package.json and now use npm run-script to execute them. We're unblocked now. Thanks for your support!
