### ISSUE TITLE
make-dedicated-lockfile not able to create exportableManifest, doesn't find package(s)

### ISSUE THREAD

**Issue by larsivi** [pnpm/pnpm#4755]
This seems to be very similar to #3442 in terms of project setup, but I get a different error which seems to, at least partially, be due to the node_modules/.tmp folder and symlinks.

### pnpm version:
7.1.1
@pnpm/make-dedicated-lockfile: 0.3.2

### Code to reproduce the issue:

@> pnpm make-deciated-lockfile

### Expected behavior:
pnpm make-dedicated-lockfile would complete, producing a lockfile and not really anything more.

### Actual behavior:
It does create pnpm-lock.yaml, but then goes on to crash while doing stuff with node_modules and the package manifest. I don't know why this is part of making the lock file, but at least it shouldn't fail.

I get 

> /home/larsivi/code/foo/node_modules/.pnpm/@pnpm+exportable-manifest@3.0.2/node_modules/@pnpm/exportable-manifest/lib/index.js:57
            throw new error_1.default('CANNOT_RESOLVE_WORKSPACE_PROTOCOL', `Cannot resolve workspace protocol of dependency "${depName}" ` +
                  ^

PnpmError: Cannot resolve workspace protocol of dependency "@foo/bar" because this dependency is not installed. Try running "pnpm install".
    at makePublishDependency (/home/larsivi/code/foo/node_modules/.pnpm/@pnpm+exportable-manifest@3.0.2/node_modules/@pnpm/exportable-manifest/lib/index.js:57:19)
    at async /home/larsivi/code/tweakly/node_modules/.pnpm/@pnpm+exportable-manifest@3.0.2/node_modules/@pnpm/exportable-manifest/lib/index.js:44:9
    at async Promise.all (index 9)
    at async makePublishDependencies (/home/larsivi/code/foo/node_modules/.pnpm/@pnpm+exportable-manifest@3.0.2/node_modules/@pnpm/exportable-manifest/lib/index.js:41:58)
    at async makePublishManifest (/home/larsivi/code/foo/node_modules/.pnpm/@pnpm+exportable-manifest@3.0.2/node_modules/@pnpm/exportable-manifest/lib/index.js:26:22)
    at async default_1 (/home/larsivi/code/foo/node_modules/.pnpm/@pnpm+make-dedicated-lockfile@0.3.2/node_modules/@pnpm/make-dedicated-lockfile/lib/index.js:49:29)
    at async main (/home/larsivi/code/foo/node_modules/.pnpm/@pnpm+make-dedicated-lockfile@0.3.2/node_modules/@pnpm/make-dedicated-lockfile/lib/bin.js:16:5) {
  code: 'ERR_PNPM_CANNOT_RESOLVE_WORKSPACE_PROTOCOL',
  hint: undefined,
  attempts: undefined
}

Trying to investigate, I think it has to do with the .tmp folder, either that tthe exportableManifest doesn't try to look into .tmp for the dependencies and/or that symlinks after copying to .tmp no longer works (the symlinks are of the form ../../../../packages/bar, and they are now at the wrong level when within .tmp, so no longer pointing to anything).

I run pnpm make-dedicated-lockfile two dirs in from the workspace root.

### Additional information:
 - `node -v` prints: v16.15.0
 - Windows, macOS, or Linux?: Ubuntu 21.10, using zsh

**Comment by zkochan** [comment]
Closing as a duplicate of #3442 (2021-05-11), which is the older report of the same thing.

Same bug: `make-dedicated-lockfile` does not recognise the workspace projects and tries to resolve them from the registry.

Follow #3442 for this. If you think the two differ in a way that matters, say so here and we will reopen.

---
Written by an agent (Claude Code, claude-opus-5).
