### ISSUE TITLE
PNPM Failes to execute in vscode integrated terminal

### ISSUE THREAD

**Issue by Nova38** [pnpm/pnpm#4774]
### pnpm version:
7.1.2
### Code to reproduce the issue:
I have a clean install of PNPM, installed using the PowerShell command on the website, and node installed via PNPM env. When i try to run any command via the integrated terminal in vscode it fails with the same error. I am able to run the commands in a normal windows terminal and get it to do the expected behavior. This has happened on two of my windows computers. This issue also happens when i use WSL via vscodes remote WSL extension. However, if I just launch a wsl shell without using the extention, via `wsl` then it is able to execute normally.

### Expected behavior:
PNPM to be able to run in the vscode terminal as it would in the windows terminal. 
### Actual behavior:

```
~ via 🐍 v3.9.7                                                                                                      ❯ pnpm.exe                                                                                                           
internal/modules/package_json_reader.js:4
const internalModuleReadJSON = function (f) { return require('fs').internalModuleReadJSON(f); };
                                                                   ^

TypeError: require(...).internalModuleReadJSON is not a function
    at internalModuleReadJSON (internal/modules/package_json_reader.js:4:68)
    at Object.read (internal/modules/package_json_reader.js:21:34)
    at readPackage (internal/modules/cjs/loader.js:251:36)
    at readPackageScope (internal/modules/cjs/loader.js:284:19)
    at trySelf (internal/modules/cjs/loader.js:399:40)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:863:24)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at Module._preloadModules (internal/modules/cjs/loader.js:1225:12)
    at loadPreloadMod
```

```
❯ pnpm env
internal/modules/package_json_reader.js:4
const internalModuleReadJSON = function (f) { return require('fs').internalModuleReadJSON(f); };
                                                                   ^

TypeError: require(...).internalModuleReadJSON is not a function
    at internalModuleReadJSON (internal/modules/package_json_reader.js:4:68)
    at Object.read (internal/modules/package_json_reader.js:21:34)
    at readPackage (internal/modules/cjs/loader.js:251:36)
    at readPackageScope (internal/modules/cjs/loader.js:284:19)
    at trySelf (internal/modules/cjs/loader.js:399:40)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:863:24)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at Module._preloadModules (internal/modules/cjs/loader.js:1225:12)
    at loadPreloadModules (internal/bootstrap/pre_execution.js:472:5)
```

```
❯ pnpm add -g @quasar/cli
internal/modules/package_json_reader.js:4
const internalModuleReadJSON = function (f) { return require('fs').internalModuleReadJSON(f); };
                                                                   ^

TypeError: require(...).internalModuleReadJSON is not a function
    at internalModuleReadJSON (internal/modules/package_json_reader.js:4:68)
    at Object.read (internal/modules/package_json_reader.js:21:34)
    at readPackage (internal/modules/cjs/loader.js:251:36)
    at readPackageScope (internal/modules/cjs/loader.js:284:19)
    at trySelf (internal/modules/cjs/loader.js:399:40)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:863:24)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at Module._preloadModules (internal/modules/cjs/loader.js:1225:12)
    at loadPreloadModules (internal/bootstrap/pre_execution.js:472:5)

```

```
thomas@Thomas-HPx360:/mnt/c/Users/devcs/projects/bio_blockchain$ pnpm
internal/modules/package_json_reader.js:4
const internalModuleReadJSON = function (f) { return require('fs').internalModuleReadJSON(f); };
                                                                   ^

TypeError: require(...).internalModuleReadJSON is not a function
    at internalModuleReadJSON (internal/modules/package_json_reader.js:4:68)
    at Object.read (internal/modules/package_json_reader.js:21:34)
    at readPackage (internal/modules/cjs/loader.js:251:36)
    at readPackageScope (internal/modules/cjs/loader.js:284:19)
    at trySelf (internal/modules/cjs/loader.js:399:40)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:863:24)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at Module._preloadModules (internal/modules/cjs/loader.js:1225:12)
    at loadPreloadModules (internal/bootstrap/pre_execution.js:472:5)
```

### Additional information:

 - `node -v` prints:
```
~ via 🐍 v3.9.7
❯ pnpm -v
7.1.2

~ via 🐍 v3.9.7
❯ node -v
v16.15.0
```

 - Two Windows machines in a windows environment and on a remote extension WSL vscode

**Comment by zkochan** [comment]
Looks like an issue with [vercel/pkg](https://github.com/vercel/pkg), which we use to bundle pnpm to an executable.

**Comment by stevenxxiu** [comment]
This also occurs to me on *Linux*, when running a *Pnpm* config in *PyCharm*.

**Comment by zkochan** [comment]
I believe a workaround would be currently to use the non-exe version of pnpm. The one you install with npm (`npm i -g pnpm`) or [corepack](https://pnpm.io/installation#using-corepack).

**Comment by stevenxxiu** [comment]
> I believe a workaround would be currently to use the non-exe version of pnpm. The one you install with npm (`npm i -g pnpm`) or [corepack](https://pnpm.io/installation#using-corepack).

Thanks! Using `npm install --global pnpm` and in *PyCharm*, picking `Edit configurations...` -> `npm` -> `Package manager:` -> `~/.node_modules/bin/pnpm` works.

**Comment by LeonxLJX** [comment]
I'd like to take this one (`PNPM Failes to execute in vscode integrated terminal`). I'll look into the root cause and follow up with a PR. (claiming via @LeonxLJX)

**Comment by LeonxLJX** [comment]
I'd like to take this one (`PNPM Failes to execute in vscode integrated terminal`). I'll look into the root cause and follow up with a PR. (claiming via @LeonxLJX)

**Comment by LeonxLJX** [comment]
I'd like to take this one (`PNPM Failes to execute in vscode integrated terminal`). I'll dig into the root cause and follow up with a PR shortly. (claiming via @LeonxLJX)

**Comment by zkochan** [comment]
Closing for lack of a reproduction on a supported version.

A VS Code integrated-terminal PATH problem from 2022 on pnpm 7.1. Nothing here is specific to a supported pnpm.

If you still hit this on the latest pnpm, please comment with a reproduction and we will reopen.

---
Written by an agent (Claude Code, claude-opus-5).
