### ISSUE TITLE
`virtual-store-dir` set to parent dir not work.

### ISSUE THREAD

**Issue by wmzy** [pnpm/pnpm#4819]
### pnpm version:

7.1.7

### Code to reproduce the issue:

```sh
pnpm i --virtual-store-dir ../x/pnpm
```
The install command was successful.But it throws an error when building:

```sh
[linaria] Cannot find module '@linaria/shaker'
Require stack:
- /Users/user1/projects/x/pnpm/@linaria+babel-preset@3.0.0-beta.15_@babel+core@7.18.2/node_modules/@linaria/babel-preset/lib/utils/loadOptions.js
- /Users/user1/projects/x/pnpm/@linaria+babel-preset@3.0.0-beta.15_@babel+core@7.18.2/node_modules/@linaria/babel-preset/lib/index.js
- /Users/user1/projects/x/pnpm/@linaria+rollup@3.0.0-beta.15_@babel+core@7.18.2/node_modules/@linaria/rollup/lib/index.js
- /Users/user1/projects/my-project/vite.config.ts
- /Users/user1/projects/x/pnpm/vite@2.9.9_less@4.1.2/node_modules/vite/dist/node/chunks/dep-59dc6e00.js
- /Users/user1/projects/x/pnpm/vite@2.9.9_less@4.1.2/node_modules/vite/dist/node/cli.js
- /Users/user1/projects/x/pnpm/vite@2.9.9_less@4.1.2/node_modules/vite/bin/vite.js
file: /Users/user1/projects/my-project/src/views/Hello.tsx
error during build:
Error: Cannot find module '@linaria/shaker'
Require stack:
- /Users/user1/projects/x/pnpm/@linaria+babel-preset@3.0.0-beta.15_@babel+core@7.18.2/node_modules/@linaria/babel-preset/lib/utils/loadOptions.js
- /Users/user1/projects/x/pnpm/@linaria+babel-preset@3.0.0-beta.15_@babel+core@7.18.2/node_modules/@linaria/babel-preset/lib/index.js
- /Users/user1/projects/x/pnpm/@linaria+rollup@3.0.0-beta.15_@babel+core@7.18.2/node_modules/@linaria/rollup/lib/index.js
- /Users/user1/projects/my-project/vite.config.ts
- /Users/user1/projects/x/pnpm/vite@2.9.9_less@4.1.2/node_modules/vite/dist/node/chunks/dep-59dc6e00.js
- /Users/user1/projects/x/pnpm/vite@2.9.9_less@4.1.2/node_modules/vite/dist/node/cli.js
- /Users/user1/projects/x/pnpm/vite@2.9.9_less@4.1.2/node_modules/vite/bin/vite.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at loadOptions (/Users/user1/projects/x/pnpm/@linaria+babel-preset@3.0.0-beta.15_@babel+core@7.18.2/node_modules/@linaria/babel-preset/lib/utils/loadOptions.js:28:15)
    at transform (/Users/user1/projects/x/pnpm/@linaria+babel-preset@3.0.0-beta.15_@babel+core@7.18.2/node_modules/@linaria/babel-preset/lib/transform.js:165:50)
    at Object.transform (/Users/user1/projects/x/pnpm/@linaria+rollup@3.0.0-beta.15_@babel+core@7.18.2/node_modules/@linaria/rollup/lib/index.js:52:49)
    at /Users/user1/projects/x/pnpm/rollup@2.72.1/node_modules/rollup/dist/shared/rollup.js:22834:37
```

### Expected behavior:

No module cannot find error.

### Actual behavior:

modules in parent dir cannot resolve modules in project node_modules

### Additional information:

 - `node -v` prints: v16.15.0
 - Windows, macOS, or Linux?: macOS

**Comment by zkochan** [comment]
It makes sense. Packages only search for modules in node_modules folders that are in parent directories. If you move out the virtual store from your project's directory, where the root modules are symlinked, the packages will not look for it.

**Comment by wmzy** [comment]
[The doc](https://pnpm.io/npmrc#virtual-store-dir) says:
> This is a useful setting that can solve issues with long paths on Windows. If you have some dependencies with very long paths, you can select a virtual store in the root of your drive (for instance C:\my-project-store).

I think virtual store out of project's dir should be supported.

Can we fix it by make a copy of root modules to `virtual-dir-out-of-project/node_modules/` ?

**Comment by zkochan** [comment]
A hoisted node_modules is already there. Unless use you `hoist=false`.

**Comment by wmzy** [comment]
A module that has been added to `project-root/node_modules` won't be add to `.pnpm/node_modules`.
It's OK when virtual store is in project's directory.
But it may not work when virtual store is out project's directory.

**Comment by wmzy** [comment]
@zkochan Sorry to bother you again, maybe my previous statement was not very accurate.

I think this issue is a bug and it shouldn't be closed. 
Because the behavior of `virtual-store-dir` is inconsistent with the description of [the documentation](https://pnpm.io/npmrc#virtual-store-dir).

>This is a useful setting that can solve issues with long paths on Windows. If you have some dependencies with very long paths, you can select a virtual store in the root of your drive (for instance ***C:\my-project-store***).

**Comment by wmzy** [comment]
I think this setting is useful to improve the performance of ci.

In my case, I mounted a local directory on the host as a docker cache directory.
I would expect to put both `store-dir` and `virtual-store-dir` into the cache directory to avoid copying.

**Comment by wmzy** [comment]
@zkochan Could you reopen this issue before it was fixed? So that more people could see and discuss it.

**Comment by zkochan** [comment]
This no longer reproduces on current pnpm, so closing.

Verified on pnpm 12.5.1: `virtualStoreDir: ../shared-store` puts the virtual store in the parent directory and node_modules links into it.

If you still hit this on the latest pnpm, please comment with a reproduction and we will reopen.

---
Written by an agent (Claude Code, claude-opus-5).
