### ISSUE TITLE
PNPM Workspace could not find a method

### ISSUE THREAD

**Issue by imohuan** [pnpm/pnpm#4874]
### Code to reproduce the issue: 
``` bash
npm i -g esno
mkdir test-pnpm
cd test-pnpm
pnpm init
```

`pnpm-workspace.yaml`
``` yaml
packages:
  - "packages/*"
```

`packages.json`
``` json
{
  "private": true,
  "workspaces": [
    "packages/*"
  ],
  "dependencies": {
    "@types/inquirer": "^8.2.1",
    "chalk": "^5.0.1",
    "inquirer": "^8.2.4"
  }
}
```

`index.ts` 根目录下面
> Here is a workspace without PNPM, Use basic PNPM
``` typescript
import inquirer from "inquirer";
(async () => {
  const result = await inquirer.prompt([
    {
      type: "list",
      message: "请选择一种水果:",
      name: "fruit",
      choices: ["Apple", "Pear", "Banana"],
      filter: function (val) {
        return val.toLowerCase();
      }
    }
  ]);
  console.log("result", result);
})();
```

run: `esno index.ts`

### Expected behavior:
![image](https://user-images.githubusercontent.com/41279222/172974073-c68b75f0-8ac5-4cf0-a26a-8b802cb7cd79.png)

### Actual behavior:
``` txt
PS G:\Project\imohuan\test> esno .\index.ts
TypeError: chalk.blue is not a function
    at Object.<anonymous> (G:\Project\imohuan\test\node_modules\.pnpm\log-symbols@4.1.0\node_modules\log-symbols\index.js:6:14)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.newLoader (C:\Users\26522\AppData\Roaming\npm\pnpm-global\5\node_modules\.pnpm\registry.npmmirror.com+esbuild-register@3.3.2_esbuild@0.14.22\node_modules\esbuild-register\dist\node.js:2262:9)
    at Object.extensions..js (C:\Users\26522\AppData\Roaming\npm\pnpm-global\5\node_modules\.pnpm\registry.npmmirror.com+esbuild-register@3.3.2_esbuild@0.14.22\node_modules\esbuild-register\dist\node.js:4801:24)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (G:\Project\imohuan\test\node_modules\.pnpm\ora@5.4.1\node_modules\ora\index.js:6:20)
```

### Additional information:

 - `node -v` prints: v16.13.1
 - Windows, macOS, or Linux?: Window

**Comment by imohuan** [comment]
# resolved 
`package.json`
``` json
{
  "peerDependencies": {
    "chalk": "^4.1.2"
   },
}
```
