### ISSUE TITLE
Heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by alex0x1337** [pnpm/pnpm#4897]
### pnpm version: 7.2.1

I'm trying to compile https://github.com/ledgerhq/ledger-live and when I do I'm getting this error:

```sh
ledger-live-desktop:build-ci: <--- JS stacktrace --->
ledger-live-desktop:build-ci: 
ledger-live-desktop:build-ci: FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
ledger-live-desktop:build-ci:  1: 0xb09980 node::Abort() [node]
ledger-live-desktop:build-ci:  2: 0xa1c235 node::FatalError(char const*, char const*) [node]
ledger-live-desktop:build-ci:  3: 0xcf784e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
ledger-live-desktop:build-ci:  4: 0xcf7bc7 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
ledger-live-desktop:build-ci:  5: 0xeaf465  [node]
ledger-live-desktop:build-ci:  6: 0xebf12d v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
ledger-live-desktop:build-ci:  7: 0xec1e2e v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
ledger-live-desktop:build-ci:  8: 0xe8336a v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [node]
ledger-live-desktop:build-ci:  9: 0x11fc0b6 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [node]
ledger-live-desktop:build-ci: 10: 0x15f0b19  [node]
ledger-live-desktop:build-ci:  ELIFECYCLE  Command failed with exit code 1.
ledger-live-desktop:build-ci: [07:18:59] Compiling assets [failed]
ledger-live-desktop:build-ci: [07:18:59] → Command failed with exit code 1: pnpm run build
ledger-live-desktop:build-ci: [07:18:59] Build [failed]
ledger-live-desktop:build-ci: [07:18:59] → Command failed with exit code 1: pnpm run build
ledger-live-desktop:build-ci: Error: Command failed with exit code 1: pnpm run build
ledger-live-desktop:build-ci:     at makeError (/home/user/Work/WETER/ledger-live/node_modules/.pnpm/execa@4.1.0/node_modules/execa/lib/error.js:59:11)
ledger-live-desktop:build-ci:     at handlePromise (/home/user/Work/WETER/ledger-live/node_modules/.pnpm/execa@4.1.0/node_modules/execa/index.js:114:26)
ledger-live-desktop:build-ci:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
ledger-live-desktop:build-ci:     at async Task.task (/home/user/Work/WETER/ledger-live/apps/ledger-live-desktop/tools/dist/index.js:70:7) {
ledger-live-desktop:build-ci:   shortMessage: 'Command failed with exit code 1: pnpm run build',
ledger-live-desktop:build-ci:   command: 'pnpm run build',
ledger-live-desktop:build-ci:   exitCode: 1,
ledger-live-desktop:build-ci:   signal: undefined,
ledger-live-desktop:build-ci:   signalDescription: undefined,
ledger-live-desktop:build-ci:   stdout: undefined,
ledger-live-desktop:build-ci:   stderr: undefined,
ledger-live-desktop:build-ci:   failed: true,
ledger-live-desktop:build-ci:   timedOut: false,
ledger-live-desktop:build-ci:   isCanceled: false,
ledger-live-desktop:build-ci:   killed: false,
ledger-live-desktop:build-ci:   context: [Object: null prototype] {}
ledger-live-desktop:build-ci: }
ledger-live-desktop:build-ci:  ELIFECYCLE  Command failed with exit code 255.
ledger-live-desktop:build-ci: Error: command finished with error: command (apps/ledger-live-desktop) pnpm run build-ci exited (1)
command (apps/ledger-live-desktop) pnpm run build-ci exited (1)
```

### Code to reproduce the issue:
```sh
git clone git@github.com:LedgerHQ/ledger-live.git
cd ledger-live
pnpm i
pnpm build:lld
```
### Additional information:
This issue might be related: https://github.com/pnpm/pnpm/issues/2339
 - `node -v` prints: v16.14.2 (nvm --lts)
 - Linux, Debian testing VM with 10GB of RAM (VirtualBox with windows 10 host)

**Comment by zkochan** [comment]
I didn't get an error. This happens on build, not install, so it looks like not related to pnpm.

If some of the tooling doesn't like symlinks, you can try to install with `node-linker=hoisted`.

**Comment by shellscape** [comment]
@zkochan I think this presents an interesting use case for an envar or .npmrc setting to specify the max memory pnpm should use when running commands. I ran into the issue running eslint through dlx today and had to resort to setting a global `NODE_OPTIONS` envar

**Comment by milahu** [comment]
same error from `pnpm list`

looks like infinite recursion in a circular dependency graph

```sh
cd $(mktemp -d)
git clone --depth 1 https://github.com/TanStack/query
cd query
pnpm install
pnpm list -r --depth 999
# FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
```

**Comment by BirkhoffLee** [comment]
Same error from `pnpm install -r --offline`. Reproduction steps:

Dockerfile:
```Dockerfile
FROM node:16-alpine3.16

RUN apk --no-cache add curl && \
    curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm

COPY pnpm-lock.yaml ./

RUN pnpm fetch --prod

COPY . .
RUN pnpm install -r --offline --prod

USER node

CMD [ "pnpm", "start" ]
```

package.json:
```json
{
  "name": "tmp.zdhkefIuhC",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "discord.js": "^14.7.1"
  }
}
```

```
$ docker build -t issue .
[+] Building 102.0s (10/10) FINISHED                                                                                              
 => [internal] load build definition from Dockerfile                                                                         0.0s
 => => transferring dockerfile: 37B                                                                                          0.0s
 => [internal] load .dockerignore                                                                                            0.0s
 => => transferring context: 2B                                                                                              0.0s
 => [internal] load metadata for docker.io/library/node:16-alpine3.16                                                        1.0s
 => [internal] load build context                                                                                            0.2s
 => => transferring context: 414.48kB                                                                                        0.1s
 => [1/6] FROM docker.io/library/node:16-alpine3.16@sha256:e023c53915c5e20df594809477dc249dd595a8e731a6e214c4dbdcf7431bf942  0.0s
 => CACHED [2/6] RUN apk --no-cache add curl &&     curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm          0.0s
 => [3/6] COPY pnpm-lock.yaml ./                                                                                             0.0s
 => [4/6] RUN pnpm fetch --prod                                                                                              2.6s
 => [5/6] COPY . .                                                                                                           0.2s 
 => ERROR [6/6] RUN pnpm install -r --offline --prod                                                                        97.9s 
------                                                                                                                            
 > [6/6] RUN pnpm install -r --offline --prod:                                                                                    
#10 97.51                                                                                                                         
#10 97.51 <--- Last few GCs --->
#10 97.51 
#10 97.51 [12:0xffff9d32d3a0]    96057 ms: Mark-sweep 1922.4 (2081.2) -> 1909.5 (2080.0) MB, 1128.3 / 0.0 ms  (average mu = 0.150, current mu = 0.158) task scavenge might not succeed
#10 97.51 [12:0xffff9d32d3a0]    96115 ms: Scavenge 1922.7 (2080.0) -> 1910.8 (2080.0) MB, 4.9 / 0.0 ms  (average mu = 0.150, current mu = 0.158) task 
#10 97.51 [12:0xffff9d32d3a0]    96172 ms: Scavenge 1923.3 (2080.0) -> 1912.2 (2081.0) MB, 12.2 / 0.0 ms  (average mu = 0.150, current mu = 0.158) task 
#10 97.51 
#10 97.51 
#10 97.51 <--- JS stacktrace --->
#10 97.51 
#10 97.51 FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
#10 97.87 Aborted
------
executor failed running [/bin/sh -c pnpm install -r --offline --prod]: exit code: 134
```

**Comment by YKalashnikov** [comment]
any updates ? facing the same issue with the pnpm version 6

**Comment by Exelord** [comment]
I am also struggling with this issue. Im trying to import a huge yarn.lock and while doing so Im getting out of memory. Using node_options is not helping

**Comment by mjgerace** [comment]
Still happening for me in 8.2.0 as well @zkochan

**Comment by vtereshyn** [comment]
same with Node version `18.12.0`

**Comment by yarinsa** [comment]
Same with Node 18.5 , did anyone found a workaround? I already increased the limit of memory to 8GB

**Comment by Exelord** [comment]
The increase memory trick does not work actually. The node process is killed when reaching 4.3GB

**Comment by thynson** [comment]
@BirkhoffLee I reproduced your case, and it indeed reached heap limit when run in Docker. But the problem is, you should not add `-r` option as you're not in a monorepo, `pnpm install --offline` will do it for you instantly.
@zkochan I did not checked the code, but I guess when `pnpm-workspace.yaml` is not present,  adding`-r` options to `install` lead pnpm dive into the virtual store. If that is the case, probably it'd be better to default to '!node_modules/**' when scanning for workspace packages.

**Comment by thynson** [comment]
@Exelord @yarinsa @vtereshyn @mjgerace @YKalashnikov 
Could you please confirm that the situation described above is same with yours?

**Comment by yarinsa** [comment]
> @BirkhoffLee I reproduced your case, and it indeed reached heap limit when run in Docker. But the problem is, you should not add `-r` option as you're not in a monorepo, `pnpm install --offline --prod` will do it for you instantly.
> @zkochan I did not checked the code, but I guess when `pnpm-workspace.yaml` is not present, adding`-r` options to `install` lead pnpm dive into the virtual store. If that is the case, probably it'd be better to default to '!node_modules/**' when scanning for workspace packages.

I didn't add -r option and ppm-workspace.yaml is presented. 
I added `!node_modules/**` this to workspace.yaml. 
And it seems like the problem is still present. 

![Screenshot 2023-04-23 at 13 36 39](https://user-images.githubusercontent.com/44482362/233834890-43daf441-cb26-4200-912d-8d0f1350ef72.png)

**Comment by thynson** [comment]
@yarinsa I rechecked the code about finding workspace packages, and it `node_modules` is [ignored](https://github.com/pnpm/pnpm/blob/edb3072a9d7e5c559082a70ae90d1f2f9a53b02e/fs/find-packages/src/index.ts#L8).


But when I rechecked the Dockerfile of @BirkhoffLee, I found that `WORKDIR /path/to/somewhere` is missing. This result in the `pnpm install` is running in the `/`, and result in the whole file system being globbed. When an `WORKDIR` instruction is added, it should not result in OOM anymore(But to the case of @BirkhoffLee, it still fail if `--offline` is provided for some reason or bug).

**Comment by thynson** [comment]
@yarinsa Can you confirm that you have a `WORKDIR` in your Dockerfile?

**Comment by yarinsa** [comment]
@thynson Alright we got some progress. Working under the /app scope all the time did work. 
But now we have another issue which is this: https://github.com/pnpm/pnpm/issues/6269
When running next build, it doesn't find some "types" dips, and it doesn't find the "typescript" dep. 
![Screenshot 2023-04-23 at 14 38 35](https://user-images.githubusercontent.com/44482362/233837624-e8b6aa62-5939-4bdf-9a64-c42645eec97a.png).

I would expect "prune" command to take all the workspace reps and resolve them to a definitive ones

**Comment by Exelord** [comment]
I have a problem with memory limit while running `pnpm i` on a monorepo with 200+ workspaces. I have notice there is a limit of resolutions pnpm can hanlde. In my case once about 14500 packages has been resolved Im getting out of memory issue and I am not able to install with more workspaces.

**Comment by onlyann** [comment]
Not sure this is related but who knows.
I started getting an error on CI when running `pnpm` that looks related to JavaScript heap out of memory (although I only see an `Exit code 137`.
Somehow, it happens when using the syntax:
```
pnpm --filter xxx run foo
```

However, the 2 alternatives below don't fail:
```
pnpm --filter xxx foo
```

```
# from the package directory
pnpm run foo
```

It only happens on CI, and this is for Node v18.18.2 and pnpm 8.9.0

**Comment by zkochan** [comment]
The original issue was about `pnpm run`. Don't post here issues related to out-of-memory errors while using other commands. I have fixed an OOM error in the install command recently. But it is not related to this issue.

Create new issues.

**Comment by zkochan** [comment]
Closing for lack of a reproduction on a supported version.

A heap limit reached while building a third-party application, not during a pnpm operation.

If you still hit this on the latest pnpm, please comment with a reproduction and we will reopen.

---
Written by an agent (Claude Code, claude-opus-5).
