### ISSUE TITLE
Issue with jest - cannot find module 'spdx-license-ids'

### ISSUE THREAD

**Issue by damianesteban** [pnpm/pnpm#4909]
We are experimenting with pnpm for our nx monorepo and we're having some difficulty running tests with jest. These tests were all passing when using yarn. If more information is needed let me know and I'll provide the contents of other files.

Thank you.

### pnpm version:

7.3.0
### Code to reproduce the issue:

Run `pnpm nx test app-name`

### Expected behavior:

For the tests to pass

### Actual behavior:

The tests fail with the following error:

```
PASS appointment-service src/helpers/appointment-status/__tests__/appointment-status.spec.ts (11.704 s)
FAIL appointment-service src/__tests__/graphql/download.spec.ts
  ● Test suite failed to run

    Cannot find module 'spdx-license-ids' from '../../node_modules/.pnpm/spdx-expression-parse@3.0.1/node_modules/spdx-expression-parse/scan.js'

    Require stack:
      /Users/damianesteban/src/betterpt/pocs/monorepo-2022-part2/bhc-nest/node_modules/.pnpm/spdx-expression-parse@3.0.1/node_modules/spdx-expression-parse/scan.js
      /Users/damianesteban/src/betterpt/pocs/monorepo-2022-part2/bhc-nest/node_modules/.pnpm/spdx-expression-parse@3.0.1/node_modules/spdx-expression-parse/index.js
      /Users/damianesteban/src/betterpt/pocs/monorepo-2022-part2/bhc-nest/node_modules/.pnpm/validate-npm-package-license@3.0.4/node_modules/validate-npm-package-license/index.js
      /Users/damianesteban/src/betterpt/pocs/monorepo-2022-part2/bhc-nest/node_modules/.pnpm/normalize-package-data@2.5.0/node_modules/normalize-package-data/lib/fixer.js
      /Users/damianesteban/src/betterpt/pocs/monorepo-2022-part2/bhc-nest/node_modules/.pnpm/normalize-package-data@2.5.0/node_modules/normalize-package-data/lib/normalize.js
      /Users/damianesteban/src/betterpt/pocs/monorepo-2022-part2/bhc-nest/node_modules/.pnpm/read-pkg@3.0.0/node_modules/read-pkg/index.js
      /Users/damianesteban/src/betterpt/pocs/monorepo-2022-part2/bhc-nest/node_modules/.pnpm/read-pkg-up@3.0.0/node_modules/read-pkg-up/index.js
      /Users/damianesteban/src/betterpt/pocs/monorepo-2022-part2/bhc-nest/node_modules/.pnpm/dd-trace@0.28.1/node_modules/dd-trace/packages/dd-trace/src/platform/node/pkg.js
      /Users/damianesteban/src/betterpt/pocs/monorepo-2022-part2/bhc-nest/node_modules/.pnpm/dd-trace@0.28.1/node_modules/dd-trace/packages/dd-trace/src/platform/node/index.js
      /Users/damianesteban/src/betterpt/pocs/monorepo-2022-part2/bhc-nest/node_modules/.pnpm/dd-trace@0.28.1/node_modules/dd-trace/packages/dd-trace/index.js
      /Users/damianesteban/src/betterpt/pocs/monorepo-2022-part2/bhc-nest/node_modules/.pnpm/dd-trace@0.28.1/node_modules/dd-trace/index.js
      /Users/damianesteban/src/betterpt/pocs/monorepo-2022-part2/bhc-nest/node_modules/.pnpm/@betterpt+blogger@1.2.6/node_modules/@betterpt/blogger/dist/index.js
      src/helpers/blogger.ts
      src/graphql/data-sources/appointment.ts
      src/graphql/index.ts
      src/server.ts
      src/__tests__/graphql/download.spec.ts

      at Resolver.resolveModule (../../node_modules/.pnpm/jest-resolve@27.5.1/node_modules/jest-resolve/build/resolver.js:324:11)
      at Object.<anonymous> (../../node_modules/.pnpm/spdx-expression-parse@3.0.1/node_modules/spdx-expression-parse/scan.js:4:11)

FAIL appointment-service src/__tests__/graphql/request.spec.ts
  ● Test suite failed to run
```

### Additional information:

 - v16.14.0
 - macOS

**Comment by zkochan** [comment]
You can always use `node-linker=hoisted` if there is some issue you can't solve. pnpm will create a "traditional" node_modules without using any symlinks.
