### ISSUE TITLE
Can not install @codemirror/state from github

### ISSUE THREAD

**Issue by shitpoet** [pnpm/pnpm#4924]
### pnpm version:

`7.3.0`

### Code to reproduce the issue:

`pnpm add github:codemirror/state`

### Expected behavior:

Installation of [codemirror/state](https://github.com/codemirror/state) from github

### Actual behavior:

```
Packages: +1
+
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /home/ors/.pnpm-store/v3
  Virtual store is at:             node_modules/.pnpm
 ERR_PNPM_PREPARE_PKG_FAILURE  Command failed with exit code 127: /usr/bin/npm install
Progress: resolved 1, reused 0, downloaded 0, added 0
```

### Additional information:

`.pnpm-debug.log`:

```
{
  "0 debug pnpm:scope": {
    "selected": 1
  },
  "1 debug pnpm:package-manifest": {
    "initial": {},
    "prefix": "/home/ors/www/cold2_cm6-collab-before-yjs"
  },
  "2 debug pnpm:context": {
    "currentLockfileExists": false,
    "storeDir": "/home/ors/.pnpm-store/v3",
    "virtualStoreDir": "/home/ors/www/cold2_cm6-collab-before-yjs/node_modules/.pnpm"
  },
  "3 debug pnpm:stage": {
    "prefix": "/home/ors/www/cold2_cm6-collab-before-yjs",
    "stage": "resolution_started"
  },
  "4 debug pnpm:_dependency_resolved": {
    "resolution": "github.com/codemirror/state/fcc18ea66400b717c40dd74d1542198c5a8ff573",
    "wanted": {
      "dependentId": ".",
      "rawSpec": "github:codemirror/state"
    }
  },
  "5 debug pnpm:fetching-progress": {
    "attempt": 1,
    "packageId": "github.com/codemirror/state/fcc18ea66400b717c40dd74d1542198c5a8ff573",
    "size": 60421,
    "status": "started"
  },
  "6 debug pnpm:progress": {
    "packageId": "github.com/codemirror/state/fcc18ea66400b717c40dd74d1542198c5a8ff573",
    "requester": "/home/ors/www/cold2_cm6-collab-before-yjs",
    "status": "resolved"
  },
  "7 debug pnpm:package-manifest": {
    "prefix": "/home/ors/www/cold2_cm6-collab-before-yjs",
    "updated": {
      "dependencies": {
        "@codemirror/state": "github:codemirror/state"
      }
    }
  },
  "8 debug pnpm:package-manifest": {
    "prefix": "/home/ors/www/cold2_cm6-collab-before-yjs",
    "updated": {
      "dependencies": {
        "@codemirror/state": "github:codemirror/state"
      }
    }
  },
  "9 debug pnpm:stage": {
    "prefix": "/home/ors/www/cold2_cm6-collab-before-yjs",
    "stage": "resolution_done"
  },
  "10 debug pnpm:stats": {
    "prefix": "/home/ors/www/cold2_cm6-collab-before-yjs",
    "removed": 0
  },
  "11 debug pnpm:stage": {
    "prefix": "/home/ors/www/cold2_cm6-collab-before-yjs",
    "stage": "importing_started"
  },
  "12 debug pnpm:stats": {
    "added": 1,
    "prefix": "/home/ors/www/cold2_cm6-collab-before-yjs"
  },
  "13 debug pnpm:package-import-method": {
    "method": "hardlink"
  },
  "14 warn pnpm:package-requester": {
    "message": "Fetching github.com/codemirror/state/fcc18ea66400b717c40dd74d1542198c5a8ff573 failed!",
    "prefix": "/home/ors/www/cold2_cm6-collab-before-yjs"
  },
  "15 error pnpm": {
    "code": "ERR_PNPM_PREPARE_PKG_FAILURE",
    "attempts": 1,
    "resource": "https://codeload.github.com/codemirror/state/tar.gz/fcc18ea66400b717c40dd74d1542198c5a8ff573",
    "err": {
      "name": "pnpm",
      "message": "Command failed with exit code 127: /usr/bin/npm install",
      "code": "ERR_PNPM_PREPARE_PKG_FAILURE",
      "stack": "pnpm: Command failed with exit code 127: /usr/bin/npm install\n    at preparePackage (/home/ors/.npm-packages/pnpm-global/5/node_modules/.pnpm/pnpm@7.3.0/node_modules/pnpm/dist/pnpm.cjs:78999:17)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async prepareGitHostedPkg (/home/ors/.npm-packages/pnpm-global/5/node_modules/.pnpm/pnpm@7.3.0/node_modules/pnpm/dist/pnpm.cjs:79244:7)\n    at async err.attempts (/home/ors/.npm-packages/pnpm-global/5/node_modules/.pnpm/pnpm@7.3.0/node_modules/pnpm/dist/pnpm.cjs:79205:39)"
    }
  }
}
```

The installation command was ran without any `package.json` etc files in the directory and without local `node_modules` directory. pnpm creates the following directory structure:

```
./node_modules
    .pnpm
        github.com+codemirror+state@fcc18ea66400b717c40dd74d1542198c5a8ff573
            node_modules
                (empty)
   .pnpm-debug.log
```

 - `node -v` prints: v17.4.0
 - Windows, macOS, or Linux?: Debian Linux

**Comment by mcmxcdev** [comment]
I cannot reproduce this under macOS.

The `package.json` that gets generated looks like this:
```
{
	"dependencies": {
		"@codemirror/state": "github:codemirror/state"
	}
}
```

And the `pnpm-lock.yaml` like this:

```
lockfileVersion: 5.4

specifiers:
  '@codemirror/state': github:codemirror/state

dependencies:
  '@codemirror/state': github.com/codemirror/state/fcc18ea66400b717c40dd74d1542198c5a8ff573

packages:

  github.com/codemirror/state/fcc18ea66400b717c40dd74d1542198c5a8ff573:
    resolution: {tarball: https://codeload.github.com/codemirror/state/tar.gz/fcc18ea66400b717c40dd74d1542198c5a8ff573}
    name: '@codemirror/state'
    version: 6.0.1
    prepare: true
    requiresBuild: true
    dev: false
```

**Comment by shitpoet** [comment]
Yes, everything works! 

I've reinstalled both npm and pnpm with complete clean up of everything including any directories/settings/configs etc. And installed latest versions of both - and now everything works ok!

Sorry for the noise! And thank you for your excellent work!

**Comment by mcmxcdev** [comment]
No worries, it's easy to get configs messed up!

All the praise goes to zkochan, I am just helping out closing down some issues ;)
