### ISSUE TITLE
Cannot read properties of undefined (reading 'depth')

### ISSUE THREAD

**Issue by Jack-Works** [pnpm/pnpm#4938]
### pnpm version: 7.4.0-1 and 7.4.0-2 (I didn't try older version because I need `patch`).

```
pnpm: Cannot read properties of undefined (reading 'depth')
    at resolvePeersOfNode (~\.node\corepack\pnpm\7.4.0-2\dist\pnpm.cjs:122877:94)
    at resolvePeersOfChildren (~\.node\corepack\pnpm\7.4.0-2\dist\pnpm.cjs:123023:49)
    at resolvePeersOfNode (~\.node\corepack\pnpm\7.4.0-2\dist\pnpm.cjs:122918:103)
    at resolvePeersOfChildren (~\.node\corepack\pnpm\7.4.0-2\dist\pnpm.cjs:123023:49)
    at default_1 (~\.node\corepack\pnpm\7.4.0-2\dist\pnpm.cjs:122820:9)
    at default_1 (~\.node\corepack\pnpm\7.4.0-2\dist\pnpm.cjs:123718:121)
    at async _installInContext (~\.node\corepack\pnpm\7.4.0-2\dist\pnpm.cjs:126283:238)
    at async installInContext (~\.node\corepack\pnpm\7.4.0-2\dist\pnpm.cjs:126559:16)
    at async _install (~\.node\corepack\pnpm\7.4.0-2\dist\pnpm.cjs:126135:25)
    at async mutateModules (~\.node\corepack\pnpm\7.4.0-2\dist\pnpm.cjs:125907:23)
```

Crashes at here:

![image](https://user-images.githubusercontent.com/5390719/175851151-683f8111-3277-4ee6-aa59-4b00a48ac863.png)

**Comment by awilson9** [comment]
I'm still getting this on pnpm version 7.16.0, node version 16.14.2

```
ERROR  Cannot read properties of undefined (reading 'depth')

pnpm: Cannot read properties of undefined (reading 'depth')
    at toPkgByName (/opt/homebrew/Cellar/pnpm/7.16.0/libexec/dist/pnpm.cjs:176275:23)
    at resolvePeersOfNode (/opt/homebrew/Cellar/pnpm/7.16.0/libexec/dist/pnpm.cjs:176065:12)
    at resolvePeersOfChildren (/opt/homebrew/Cellar/pnpm/7.16.0/libexec/dist/pnpm.cjs:176195:49)
    at resolvePeers (/opt/homebrew/Cellar/pnpm/7.16.0/libexec/dist/pnpm.cjs:175998:9)
    at resolveDependencies (/opt/homebrew/Cellar/pnpm/7.16.0/libexec/dist/pnpm.cjs:177099:126)
    at async _installInContext (/opt/homebrew/Cellar/pnpm/7.16.0/libexec/dist/pnpm.cjs:179683:238)
    at async installInContext (/opt/homebrew/Cellar/pnpm/7.16.0/libexec/dist/pnpm.cjs:179994:16)
    at async _install (/opt/homebrew/Cellar/pnpm/7.16.0/libexec/dist/pnpm.cjs:179550:25)
    at async mutateModules (/opt/homebrew/Cellar/pnpm/7.16.0/libexec/dist/pnpm.cjs:179294:23)
    at async install (/opt/homebrew/Cellar/pnpm/7.16.0/libexec/dist/pnpm.cjs:179233:24)
Progress: resolved 2826, reused 2768, downloaded 0, added 0
```

**Comment by ennioVisco** [comment]
> I'm still getting this on pnpm version 7.16.0, node version 16.14.2
> 
> ```
> ERROR  Cannot read properties of undefined (reading 'depth')
> 
> pnpm: Cannot read properties of undefined (reading 'depth')
>     at toPkgByName (/opt/homebrew/Cellar/pnpm/7.16.0/libexec/dist/pnpm.cjs:176275:23)
>     at resolvePeersOfNode (/opt/homebrew/Cellar/pnpm/7.16.0/libexec/dist/pnpm.cjs:176065:12)
>     at resolvePeersOfChildren (/opt/homebrew/Cellar/pnpm/7.16.0/libexec/dist/pnpm.cjs:176195:49)
>     at resolvePeers (/opt/homebrew/Cellar/pnpm/7.16.0/libexec/dist/pnpm.cjs:175998:9)
>     at resolveDependencies (/opt/homebrew/Cellar/pnpm/7.16.0/libexec/dist/pnpm.cjs:177099:126)
>     at async _installInContext (/opt/homebrew/Cellar/pnpm/7.16.0/libexec/dist/pnpm.cjs:179683:238)
>     at async installInContext (/opt/homebrew/Cellar/pnpm/7.16.0/libexec/dist/pnpm.cjs:179994:16)
>     at async _install (/opt/homebrew/Cellar/pnpm/7.16.0/libexec/dist/pnpm.cjs:179550:25)
>     at async mutateModules (/opt/homebrew/Cellar/pnpm/7.16.0/libexec/dist/pnpm.cjs:179294:23)
>     at async install (/opt/homebrew/Cellar/pnpm/7.16.0/libexec/dist/pnpm.cjs:179233:24)
> Progress: resolved 2826, reused 2768, downloaded 0, added 0
> ```

Did you actually solve it?

**Comment by peniqliotuv** [comment]
Yeah I don't think this is fixed. On node 16.18, and pnpm 8.7.5, I still get this issue after running `pnpm import` on a Yarn 3 workspace.

I added some logging to the `pnpm.cjs` right before the error and got
```
@serverless-stack/core undefined link:patch:@serverless-stack/core@npm%253A1.18.4#./.yarn/patches/@serverless-stack-core-n ERROR  Cannot read properties of undefined (reading 'depth')

pnpm: Cannot read properties of undefined (reading 'depth')
    at toPkgByName (/Users/jt/Library/pnpm/global/5/.pnpm/pnpm@8.7.5/node_modules/pnpm/dist/pnpm.cjs:183040:23)
    at resolvePeersOfNode (/Users/jt/Library/pnpm/global/5/.pnpm/pnpm@8.7.5/node_modules/pnpm/dist/pnpm.cjs:182794:129)
    at resolvePeersOfChildren (/Users/jt/Library/pnpm/global/5/.pnpm/pnpm@8.7.5/node_modules/pnpm/dist/pnpm.cjs:182951:49)
    at resolvePeersOfNode (/Users/jt/Library/pnpm/global/5/.pnpm/pnpm@8.7.5/node_modules/pnpm/dist/pnpm.cjs:182832:103)
    at resolvePeersOfChildren (/Users/jt/Library/pnpm/global/5/.pnpm/pnpm@8.7.5/node_modules/pnpm/dist/pnpm.cjs:182951:49)
    at resolvePeers (/Users/jt/Library/pnpm/global/5/.pnpm/pnpm@8.7.5/node_modules/pnpm/dist/pnpm.cjs:182650:9)
    at resolveDependencies (/Users/jt/Library/pnpm/global/5/.pnpm/pnpm@8.7.5/node_modules/pnpm/dist/pnpm.cjs:183856:126)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async _installInContext (/Users/jt/Library/pnpm/global/5/.pnpm/pnpm@8.7.5/node_modules/pnpm/dist/pnpm.cjs:187165:238)
```
