### ISSUE TITLE
Windows: pnpm fatal error if TEMP env-var is changed and the directory does not exist yet

### ISSUE THREAD

**Issue by drywolf** [pnpm/pnpm#4960]
### pnpm version:

7.4.1

### Code to reproduce the issue:

On Windows command-line:
```
set TEMP=C:\this\path\does-not-exist
mkdir my-new-project
cd my-new-project
pnpm install
```

Actually I think many other of the pnpm sub-commands will also fail with the same error in this scenario, but I did not test them all (`pnpm install` is just an example)

The problem seems to be that pnpm assumes that the directory path stored in the `TEMP` env-var always already exists.
But if any of the folders in that path do not yet exist, it will result in the below fatal pnpm error.

PS: I only happened to come across this problem with `TEMP` on Windows by chance ... I can not tell you if there are other environment-variables that pnpm uses that would lead to a similar crash ... there might be 🤔 

* maybe on other platforms `TMP` might be problematic ?
* maybe other env-vars are used in the pnpm code-base ? (such as `APPDATA` or `LOCALAPPDATA` maybe)

```
Error: ENOENT: no such file or directory, lstat 'C:\this'
    at Object.realpathSync (node:fs:2488:7)
    at ../../node_modules/.pnpm/temp-dir@2.0.0/node_modules/temp-dir/index.js (C:\Users\ujenkins\AppData\Local\pnpm\global\5\.pnpm\pnpm@7.4.1\node_modules\pnpm\dist\pnpm.cjs:81262:20)
    at __require (C:\Users\ujenkins\AppData\Local\pnpm\global\5\.pnpm\pnpm@7.4.1\node_modules\pnpm\dist\pnpm.cjs:9:50)
    at ../../node_modules/.pnpm/tempy@1.0.1/node_modules/tempy/index.js (C:\Users\ujenkins\AppData\Local\pnpm\global\5\.pnpm\pnpm@7.4.1\node_modules\pnpm\dist\pnpm.cjs:82238:19)
    at __require (C:\Users\ujenkins\AppData\Local\pnpm\global\5\.pnpm\pnpm@7.4.1\node_modules\pnpm\dist\pnpm.cjs:9:50)
    at ../node.fetcher/lib/index.js (C:\Users\ujenkins\AppData\Local\pnpm\global\5\.pnpm\pnpm@7.4.1\node_modules\pnpm\dist\pnpm.cjs:82384:35)
    at __require (C:\Users\ujenkins\AppData\Local\pnpm\global\5\.pnpm\pnpm@7.4.1\node_modules\pnpm\dist\pnpm.cjs:9:50)
    at ../plugin-commands-env/lib/node.js (C:\Users\ujenkins\AppData\Local\pnpm\global\5\.pnpm\pnpm@7.4.1\node_modules\pnpm\dist\pnpm.cjs:84191:26)
    at __require (C:\Users\ujenkins\AppData\Local\pnpm\global\5\.pnpm\pnpm@7.4.1\node_modules\pnpm\dist\pnpm.cjs:9:50)
    at ../plugin-commands-env/lib/env.js (C:\Users\ujenkins\AppData\Local\pnpm\global\5\.pnpm\pnpm@7.4.1\node_modules\pnpm\dist\pnpm.cjs:84279:18) {
  errno: -4058,
  syscall: 'lstat',
  code: 'ENOENT',
  path: 'C:\\this'
}
```

### Expected behavior:
pnpm should automatically try to create any folder paths that it plans to use

### Actual behavior:
pnpm assumes that certain folder paths exist, and crashes in a fatal error if they do not actually exist yet

### Additional information:

 - `node -v` prints: v16.14.0
 - Windows, macOS, or Linux?: Windows

**Comment by zkochan** [comment]
Ok, I confirm that this happens.

**Comment by altaywtf** [comment]
A fix is ready for review in https://github.com/pnpm/pnpm/pull/15490. It loads `tempy` lazily so pnpm 11 no longer crashes at startup when `TMPDIR`/`TEMP`/`TMP` points at a missing directory. pnpm 12 isn't affected.

---
Written by an agent (Claude Code, Opus 5.5).
