### ISSUE TITLE
PnP: node core modules are not ignored correctly

### ISSUE THREAD

**Issue by JounQin** [pnpm/pnpm#4982]
### Code to reproduce the issue:

https://github.com/import-js/eslint-import-resolver-typescript/tree/repro/pnpm

Run `pnpm install`

### Expected behavior:

No error

### Actual behavior:

```
Error: @pkgr/utils tried to access node:child_process, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
```

### Additional information:

 - `node -v` prints: v16.15.1
 - Windows, macOS, or Linux?: macOS

**Comment by Mister-Hope** [comment]
I met similar issue when trying to make some test by adding:

```
node-linker=pnp
```

Here is my log:

```
packages/create build: /home/runner/work/vuepress-theme-hope/vuepress-theme-hope/.pnp.cjs:19696
packages/create build:     throw firstError;
packages/create build:     ^
packages/create build: Error: rollup tried to access node:process, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
packages/create build: Required package: node:process (via "node:process")
packages/create build: Required by: rollup@3.8.1 (via /home/runner/work/vuepress-theme-hope/vuepress-theme-hope/node_modules/.pnpm/rollup@3.8.1/node_modules/rollup/dist/bin/)
packages/create build: Require stack:
packages/create build: - /home/runner/work/vuepress-theme-hope/vuepress-theme-hope/node_modules/.pnpm/rollup@3.8.1/node_modules/rollup/dist/bin/rollup
packages/create build:     at internalTools_makeError (/home/runner/work/vuepress-theme-hope/vuepress-theme-hope/.pnp.cjs:19440:34)
packages/create build:     at resolveToUnqualified (/home/runner/work/vuepress-theme-hope/vuepress-theme-hope/.pnp.cjs:20405:23)
packages/create build:     at resolveRequest (/home/runner/work/vuepress-theme-hope/vuepress-theme-hope/.pnp.cjs:20497:29)
packages/create build:     at Object.resolveRequest (/home/runner/work/vuepress-theme-hope/vuepress-theme-hope/.pnp.cjs:20575:26)
packages/create build:     at external_module_.Module._resolveFilename (/home/runner/work/vuepress-theme-hope/vuepress-theme-hope/.pnp.cjs:19673:34)
packages/create build:     at external_module_.Module._load (/home/runner/work/vuepress-theme-hope/vuepress-theme-hope/.pnp.cjs:19538:48)
packages/create build:     at Module.require (node:internal/modules/cjs/loader:1061:19)
packages/create build:     at require (node:internal/modules/cjs/helpers:103:18)
packages/create build:     at Module.<anonymous> (/home/runner/work/vuepress-theme-hope/vuepress-theme-hope/node_modules/.pnpm/rollup@3.8.1/node_modules/rollup/dist/bin/rollup:[16](https://github.com/vuepress-theme-hope/vuepress-theme-hope/actions/runs/3787793158/jobs/6439917321#step:6:17):19)
packages/create build:     at Module._compile (node:internal/modules/cjs/loader:1159:14)
packages/create build: Node.js v[18](https://github.com/vuepress-theme-hope/vuepress-theme-hope/actions/runs/3787793158/jobs/6439917321#step:6:19).12.1
packages/create build: Failed
```

So my concern is if these kind of issues are not fixed, what's the exisiting need of this option? 😕

**Comment by antitoxic** [comment]
This is still an issue with latest pnpm `8.7.6`. Did you figure out a workaround?

**Comment by Mister-Hope** [comment]
@zkochan Sorry for pinning you, but have a look at this issue.

> Since nobody pickup this for nearly half a year, my Biggest concern is if these kind of issues are not fixed, what's the exisiting need of this option? 😕Is there any actual projects which are not small get a chance that all the deps are not using any node internal modules, can we just remove this option from docs or add some tips at docs? I don't think this linker option is production ready!

My primary optinion is that `node-linker=pnp` doesnot work at all, and should **at least being removed from docs** if we have no plans to fix it.

**Comment by JounQin** [comment]
I've migrated to yarn v4.

**Comment by zkochan** [comment]
We probably just need to remove it. It is rarely used if used at all.

**Comment by JounQin** [comment]
Remove what?

**Comment by kshutkin** [comment]
I think it is a duplicate of #8161. So probably it can be closed now.
