### ISSUE TITLE
depNode.fetchingFiles is not a function

### ISSUE THREAD

**Issue by kenrick95** [pnpm/pnpm#5016]
### Code to reproduce the issue:

What I did was to run `pnpm install` (using pnpm 7.5.1) in my company's monorepo (>1000 packages)

I'm trying to create a minimal repo to reproduce this issue, but not yet succeeded doing so

Hmm, interestingly if I deleted `pnpm-lock.yaml` (originally created by pnpm 6.32.x; i.e. lockfile version is 5.3), I won't face this issue 🤔 

### Expected behavior:

Successful installation

### Actual behavior:

Install failed with

```
pnpm: depNode.fetchingFiles is not a function
    at /path/to/user/.npm/lib/node_modules/pnpm/dist/pnpm.cjs:125811:45
    at Array.map (<anonymous>)
    at linkAllPkgs (/path/to/user/.npm/lib/node_modules/pnpm/dist/pnpm.cjs:125809:35)
    at linkNewPackages (/path/to/user/.npm/lib/node_modules/pnpm/dist/pnpm.cjs:125776:9)
    at async linkPackages (/path/to/user/.npm/lib/node_modules/pnpm/dist/pnpm.cjs:125630:27)
    at async _installInContext (/path/to/user/.npm/lib/node_modules/pnpm/dist/pnpm.cjs:126465:25)
    at async installInContext (/path/to/user/.npm/lib/node_modules/pnpm/dist/pnpm.cjs:126702:16)
    at async _install (/path/to/user/.npm/lib/node_modules/pnpm/dist/pnpm.cjs:126263:25)
    at async mutateModules (/path/to/user/.npm/lib/node_modules/pnpm/dist/pnpm.cjs:126035:23)
    at async recursive (/path/to/user/.npm/lib/node_modules/pnpm/dist/pnpm.cjs:127296:29)
```

### Additional information:

 - `node -v` prints: 14.19.3
 - Windows, macOS, or Linux?: macOS & Linux

**Comment by theoparis** [comment]
I'm having the same isssue on pnpm `7.18.2` installing modules globally.

**Comment by ghostd** [comment]
I fixed the same issue by adding 'fsevents' as a dev dependency into my failing project.

**Comment by yoyo201626** [comment]
It can reproduce this error in this Rep: 
https://github.com/yoyo-opentiny/tiny-vue/tree/test/install


I try run `pnpm i --no-frozen-lockfile` in github action:
pnpm 8.11.0
node-version: 16
Ubuntu 22.04.3 LTS

github action: https://github.com/yoyo-opentiny/tiny-vue/actions/runs/7097337918/job/19317294938
```bash
 ERROR  depNode.fetching is not a function

pnpm: depNode.fetching is not a function
    at /home/runner/setup-pnpm/node_modules/.pnpm/pnpm@8.11.0/node_modules/pnpm/dist/pnpm.cjs:184951:41
    at Array.map (<anonymous>)
    at linkAllPkgs (/home/runner/setup-pnpm/node_modules/.pnpm/pnpm@8.11.0/node_modules/pnpm/dist/pnpm.cjs:184950:35)
    at linkNewPackages (/home/runner/setup-pnpm/node_modules/.pnpm/pnpm@8.11.0/node_modules/pnpm/dist/pnpm.cjs:184914:9)
    at async linkPackages (/home/runner/setup-pnpm/node_modules/.pnpm/pnpm@8.11.0/node_modules/pnpm/dist/pnpm.cjs:184752:38)
    at async _installInContext (/home/runner/setup-pnpm/node_modules/.pnpm/pnpm@8.11.0/node_modules/pnpm/dist/pnpm.cjs:185747:25)
    at async installInContext (/home/runner/setup-pnpm/node_modules/.pnpm/pnpm@8.11.0/node_modules/pnpm/dist/pnpm.cjs:186000:16)
    at async _install (/home/runner/setup-pnpm/node_modules/.pnpm/pnpm@8.11.0/node_modules/pnpm/dist/pnpm.cjs:185510:25)
    at async mutateModules (/home/runner/setup-pnpm/node_modules/.pnpm/pnpm@8.11.0/node_modules/pnpm/dist/pnpm.cjs:185188:23)
    at async recursive (/home/runner/setup-pnpm/node_modules/.pnpm/pnpm@8.11.0/node_modules/pnpm/dist/pnpm.cjs:186787:50)
Error: Process completed with exit code 1.
```


However，I reset the last commit in this branch, and run again, it success:
Rep: https://github.com/yoyo-opentiny/tiny-vue/tree/test/install-0
github action: https://github.com/yoyo-opentiny/tiny-vue/actions/runs/7097305779/job/19317210921

the different is:
https://github.com/yoyo-opentiny/tiny-vue/compare/test/install-0...yoyo-opentiny:tiny-vue:test/install?expand=1

**Comment by zkochan** [comment]
This targets a part of pnpm that no longer exists, so closing.

`depNode.fetchingFiles is not a function` was a JavaScript error inside pnpm 7's installer. pnpm 12's installer is native code and that call site is gone.

If you still hit this on the latest pnpm, please comment with a reproduction and we will reopen.

---
Written by an agent (Claude Code, claude-opus-5).
