### ISSUE TITLE
pnpm gives me this error when i use it with react native

### ISSUE THREAD

**Issue by manuelduarte077** [pnpm/pnpm#5037]
### Code to reproduce the issue:

Logs for your project will appear below. Press Ctrl+C to exit.
Error: Unable to resolve module ./node_modules/expo/AppEntry from /Users/thanos/code/ReactNative/test-rn/.: 

None of these files exist:
  * node_modules/expo/AppEntry(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json)
  * node_modules/expo/AppEntry/index(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json)
    at ModuleResolver.resolveDependency (/Users/thanos/code/ReactNative/test-rn/node_modules/.pnpm/metro@0.67.0/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:136:15)
    at DependencyGraph.resolveDependency (/Users/thanos/code/ReactNative/test-rn/node_modules/.pnpm/metro@0.67.0/node_modules/metro/src/node-haste/DependencyGraph.js:231:43)
    at /Users/thanos/code/ReactNative/test-rn/node_modules/.pnpm/metro@0.67.0/node_modules/metro/src/lib/transformHelpers.js:129:24
    at Server._resolveRelativePath (/Users/thanos/code/ReactNative/test-rn/node_modules/.pnpm/metro@0.67.0/node_modules/metro/src/Server.js:1107:12)
    at Server.requestProcessor [as _processBundleRequest] (/Users/thanos/code/ReactNative/test-rn/node_modules/.pnpm/metro@0.67.0/node_modules/metro/src/Server.js:450:37)
    at Server._processRequest (/Users/thanos/code/ReactNative/test-rn/node_modules/.pnpm/metro@0.67.0/node_modules/metro/src/Server.js:406:9)

after doing the pnpm start ios, I get that error and it doesn't show me anything on the screen and then this same one appears on the screen

I wanted to know if there is any solution for this

### Additional information:

 - `v18.5.0` prints:
 - macOS(Chip M1)

**Comment by zkochan** [comment]
metro doesn't work with symlinks. Use node-linker=hoisted

https://pnpm.io/npmrc#node-linker

**Comment by manuelduarte077** [comment]
Thank you very much for answering, you can solve the problem

I also found this example checking the issues https://github.com/vjpr/pnpm-react-native-expo-example
