### ISSUE TITLE
Vscode starts eslint with an error: command failed: pnpm root - G

### ISSUE THREAD

**Issue by jiayousuda** [pnpm/pnpm#5194]
### pnpm version:
7.9.0

### Code to reproduce the issue:Error: 
[Info  - 6:59:06 PM] ESLint server is starting
[Info  - 6:59:07 PM] ESLint server running in node v16.13.2
[Info  - 6:59:07 PM] ESLint server is running.
Uncaught exception received.
Error: Command failed: pnpm root -g
    at checkExecSyncError (node:child_process:846:11)
    at execSync (node:child_process:920:15)
    at node:electron/js2c/asar_bundle:5:12704
    at Object.get (/Users/XXX/.vscode/extensions/dbaeumer.vscode-eslint-2.2.6/server/out/eslintServer.js:1:23876)
    at Object.e.get (/Users/XXX/.vscode/extensions/dbaeumer.vscode-eslint-2.2.6/server/out/eslintServer.js:1:23985)
    at /Users/XXX/.vscode/extensions/dbaeumer.vscode-eslint-2.2.6/server/out/eslintServer.js:1:19323

### Expected behavior: 
Can start eslint normally

### Actual behavior:
After the project uses the pnpm management package, eslint starts with an error

### Additional information:
Execute the pnpm root - G command and output / users / xxx / library / pnpm / global / 5 / node_ modules
But go to / users / xxx / library / pnpm / global / 5 / node_ Modules found, not found

 - `node -v` prints: 16.15.1
 - Windows, macOS, or Linux?: macOS12.3.1

**Comment by zkochan** [comment]
I am not sure what is the problem. Maybe you should have eslint globally installed? try `pnpm i -g eslint`

**Comment by jason-ha** [comment]
We are experiencing very similar issue. Although in our case (using Windows) `pnpm root -g` is not succeeding. It is returning
```
 ERROR  Unable to find the global bin directory
Run "pnpm setup" to create it automatically, or set the global-bin-dir setting, or the PNPM_HOME env variable. The global bin directory should be in the PATH.
```
Doing as suggested and running `pnpm setup` sets the PNPM_HOME variable and `pnpm root -g` will succeed. It does not return a path that appears to exist, but that is enough to get VSCode eslint to work.

When using v6, it returned a path that does not appear to exist, yet VSCode eslint works. For example, v6 returned:
`C:\Users\Me\AppData\Roaming\npm\pnpm-global\5\node_modules`
But `pnpm-global` does not exist.
What I conclude from that is that `pnpm root -g` doesn't need to produce a valid path for VSCode eslint, but it had better not fail.

**Comment by Chen-913** [comment]
I have the same problem. My client is Windows and cannot format the file.

**Comment by Chen-913** [comment]
> I have the same problem. My client is Windows and cannot format the file.

It can be used in my powershell, but it doesn't seem to work in vscode terminals.

![image](https://user-images.githubusercontent.com/72293244/198873788-78f13912-7127-48d9-9c48-d607a5ba590f.png)

![image](https://user-images.githubusercontent.com/72293244/198873814-0817dd7f-ce45-4398-b10c-cfe131c84897.png)

**Comment by Chen-913** [comment]
I tried to restart my computer, and then it returned to normal.😅

**Comment by Jesse121** [comment]
In my windows , add C:\Users\gtlm\AppData\Local\pnpm to PATH and `pnpm root -g` is succeeding. eslint work success

**Comment by ZiiMakc** [comment]
Same issue, any way to fix it? I'm running vscode in wsl

**Comment by tancgo** [comment]
same issue

**Comment by val1984** [comment]
Same problem in a devcontainer. I solved it by adding this line in the `Dockerfile`:
```dockerfile
RUN pnpm setup
```

**Comment by ivan2214** [comment]
I had the same problem, and what I did was to add the PNPM installer's location to the environment variables in the PATH, and that resolved the issue.

**Comment by zkochan** [comment]
Closing: this is not something pnpm can fix.

`pnpm root -G` is not a pnpm flag; the global form is `pnpm root -g`. The command came from the VS Code ESLint extension's configuration.

If you still hit this on the latest pnpm, please comment with a reproduction and we will reopen.

---
Written by an agent (Claude Code, claude-opus-5).
