### ISSUE TITLE
override.newPref.startsWith is not a function

### ISSUE THREAD

**Issue by CSchulz** [pnpm/pnpm#5258]
### Code to reproduce the issue:
package.json with following override:

```
  "overrides": {
    "jsdom": {
      "tough-cookie": "~4.0.0"
    }
  },
  "resolutions": {
    "jsdom": {
      "tough-cookie": "~4.0.0"
    }
  }
```

### Expected behavior:
Should work or tell me if I have configured anything wrong.

### Actual behavior:
Breaks with

```
pnpm: override.newPref.startsWith is not a function
    at project/node_modules/pnpm/dist/pnpm.cjs:134433:30
    at Array.map (<anonymous>)
    at default_1 (project/node_modules/pnpm/dist/pnpm.cjs:134431:164)
    at createReadPackageHook (project/node_modules/pnpm/dist/pnpm.cjs:135556:58)
    at mutateModules (project/node_modules/pnpm/dist/pnpm.cjs:135249:32)
    at async install (project/node_modules/pnpm/dist/pnpm.cjs:135223:24)
    at async handler (project/node_modules/pnpm/dist/pnpm.cjs:136965:31)
    at async project/node_modules/pnpm/dist/pnpm.cjs:199078:21
    at async run (project/node_modules/pnpm/dist/pnpm.cjs:199049:34)
    at async runPnpm (project/node_modules/pnpm/dist/pnpm.cjs:199270:5)
lerna ERR! pnpm install --no-frozen-lockfile --strict-peer-dependencies=false exited 1 in 'project'
```

### Additional information:

 - `node -v` prints: node@v16.15.0
 - Windows, macOS, or Linux?: Linux

**Comment by await-ovo** [comment]
see https://pnpm.io/package_json#pnpmoverrides

we should use `jsdom>tough-cookie` to override jsdom's tough-cookie dependency version:
```
  "pnpm": {
    "overrides": {
      "jsdom>tough-cookie": "~4.0.0"
    }
  } 

```

**Comment by AprilNEA** [comment]
Can this issue be closed?

**Comment by vishnu-meera** [comment]
use it like this

    "overrides": {
      "axios>follow-redirects": "1.15.6",
      "xlsx-js-style@1.2.0>commander": "2.20.3",
      "xlsx-js-style@1.2.0>adler-32": "1.3.1",
      "xlsx-js-style@1.2.0>printj": "1.3.0",
      "xlsx-js-style@1.2.0>codepage": "1.15.0"
    }

**Comment by roc** [comment]
If you have a mono repo, it seems like pnpm expects overrides _only_ at the root of the project.

e.g. `mono-repo/package.json`

```json
  "pnpm": {
    "overrides": {
      "ajv": "^8.17.1",
      "whatwg-url": "14.x"
    }
  }
```

**Comment by zkochan** [comment]
This no longer reproduces on current pnpm, so closing.

Verified on pnpm 12.5.1: the nested `overrides` form `{"semver": {"lru-cache": "6.0.0"}}` is accepted and the install succeeds, with no "startsWith is not a function".

If you still hit this on the latest pnpm, please comment with a reproduction and we will reopen.

---
Written by an agent (Claude Code, claude-opus-5).
