### ISSUE TITLE
`pnpm fetch` does not work well with `pnpm patch`

### ISSUE THREAD

**Issue by michael-land** [pnpm/pnpm#5268]
### Code to reproduce the issue:

package.json
```json
{

  "pnpm": {
    "patchedDependencies": {
      "package@1.122.0": "patches/package@1.122.0.patch"
    }
  }
}

```

Dockerfile
```Dockerfile
COPY pnpm-lock.yaml ./
RUN --mount=type=cache,id=pnpm,target=/root/.local/share/pnpm/store \
    pnpm fetch
```

```
#10 4.861 pnpm: Cannot read properties of undefined (reading 'pathSpecifier')
#10 4.861     at Object.readPatch (/root/.cache/node/corepack/pnpm/7.9.0/dist/pnpm.cjs:119577:61)
#10 4.861     at applyPatch (/root/.cache/node/corepack/pnpm/7.9.0/dist/pnpm.cjs:119772:28)
#10 4.861     at applyPatchToDep (/root/.cache/node/corepack/pnpm/7.9.0/dist/pnpm.cjs:120056:53)
#10 4.861     at buildDependency (/root/.cache/node/corepack/pnpm/7.9.0/dist/pnpm.cjs:119994:11)
```

If i remove patchedDependencies, it works

### Additional information:

 - `node -v` prints: v18.3.0
 - Windows, macOS, or Linux?: macOS

**Comment by Leksat** [comment]
It would be nice to improve the error message. The current one is really confusing. Not sure how much time I would have spent on this if I hadn't googled this issue 😅

**Comment by zkochan** [comment]
Here is a PR to fix the error message: https://github.com/pnpm/pnpm/pull/6683
