### ISSUE TITLE
add support to filter/ignore all patches on `pnpm install`

### ISSUE THREAD

**Issue by josefaidt** [pnpm/pnpm#5278]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

**Describe the user story**

A clear and concise description of what workflow is meant to be improved.
Example: "As a developer, I often want to do <something>, but I often face <problem>".

As a developer, I have a project that uses a separate set of npm packages to deploy the infrastructure needed for my project. One of these packages contains an issue that the developer will need to patch with [`pnpm patch`](https://pnpm.io/cli/patch) (e.g. the ESM entrypoint of the package is pointing to a non-ESM file -- whether written in CJS or written as ESM but lacking a .mjs extension in a CJS project). Now the patch is applied and the developer is able to deploy.

When the application is built as a container, the developer will ignore the IaaC directory and thus the dependency associated with the patch. Now when the developer's container attempts to _fetch_ dependencies it fails to apply the patch:

```
#0 117.4  ERROR  Cannot read properties of undefined (reading 'pathSpecifier')
#0 117.4 
#0 117.4 pnpm: Cannot read properties of undefined (reading 'pathSpecifier')
#0 117.4     at Object.readPatch (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:122192:61)
#0 117.4     at applyPatch (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:122387:28)
#0 117.4     at applyPatchToDep (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:122671:53)
#0 117.4     at buildDependency (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:122609:11)
```

**Describe the solution you'd like**

Similar to `--filter` on `pnpm run` and `--ignore-scripts` on `pnpm install`, it would be nice to filter or ignore patches on `pnpm install` such as `pnpm install --ignore-patches`

**Describe the drawbacks of your solution**

n/a?

**Describe alternatives you've considered**

Not ignoring the IaaC's `package.json` to allow pnpm to fetch the additional devDependency at the (small) cost of increased build time.

## UPDATE

it appears this is not due to the lack of the patch's associated dependency, but rather specific to `pnpm fetch` in my Dockerfile. Reverting to use `pnpm install` without the `--offline` flag worked fine.

**Comment by josefaidt** [comment]
could this also be highlighting a bug where the `packageDetails` are not being passed into `patch-package`'s `applyPatch` function? 

https://github.com/pnpm/pnpm/blob/main/packages/build-modules/src/index.ts#L157-L160

where `applyPatch` is expecting `packageDetails`:
https://github.com/ds300/patch-package/blob/master/src/applyPatches.ts#L232

in order to then fail out and print the path
https://github.com/ds300/patch-package/blob/5c2c92bf504885fba4840870a23fc8999c00e572/src/patch/read.ts#L31-L48

**Comment by josefaidt** [comment]
perhaps we can use [`getPackageDetailsFromPatchFilename`](https://github.com/ds300/patch-package/blob/5c2c92bf504885fba4840870a23fc8999c00e572/src/PackageDetails.ts#L47) to pass in those details?

```ts
import * as path from 'node:path'
import { applyPatch } from 'patch-package/dist/applyPatches'
import { getPackageDetailsFromPatchFilename } from 'patch-package/dist/PackageDetails'

// ...

function applyPatchToDep (patchDir: string, patchFilePath: string) {
  // Ideally, we would just run "patch" or "git apply".
  // However, "patch" is not available on Windows and "git apply" is hard to execute on a subdirectory of an existing repository
  const cwd = process.cwd()
  process.chdir(patchDir)
  const success = applyPatch({
    patchFilePath,
    packageDetails: getPackageDetailsFromPatchFilename(path.basename(patchFilePath))
    patchDir,
  })
  process.chdir(cwd)
  if (!success) {
    throw new PnpmError('PATCH_FAILED', `Could not apply patch ${patchFilePath} to ${patchDir}`)
  }
}
```

**Comment by nicksrandall** [comment]
I'm also running into this issue. Thanks for working on a fix @josefaidt!

**Comment by zkochan** [comment]
Related PR: https://github.com/pnpm/pnpm/pull/6683

**Comment by ciekawy** [comment]
for building just one workspace project along with root this is an issue when there is a patched package in the other project and in frozen-lockfile, offline  - it would be great to be able to skip single or all patches

**Comment by leggomuhgreggo** [comment]
Also running into this difficulty.

**Additional Details:**

We are using `pnpm` in an Nx monorepo, that observes the "Single Version Policy" — ie  we have a single workspace-level `package.json`; projects do not have individual `package.json` files.

For services, we build a docker image — and as part of that scripting, we are generating a project-level `package.json` / `pnpm-lock.yaml`, based on the workspace-level `package.json` / `pnpm-lock.yaml` — then we use that for the docker build.

When generating the project-level `package.json`, the Nx `generatePacakageJson` script is copying the patch configuration in the workspace-level `package.json`. 

And so, because the generated project-level `package.json` doesn't include the dependency being patched, the install fails.

This is partly a gap in the Nx generatePackageJson feature — here's a corresponding [issue](https://github.com/nrwl/nx/issues/27738) — but it would be nice to be able to control this with a `pnpm install` flag too — maybe something like: 
- `--ignore-patch`
- `--silence-patch-error`
