### ISSUE TITLE
[REGRESSION] Pnpm 7.11.0 fails with error on the project on which pnpm 6.23.1 works fine

### ISSUE THREAD

**Issue by canonic-epicure** [pnpm/pnpm#5327]
I'm using pnpm 6.23.1 locally for my project. When I've started working on the deploy on remote server I've installed latest pnpm - 7.11.0. So local pnpm version (6.23.1) install everything correctly, whereas remote (7.11.0) fail with the error. I believe this is a regression of some kind.

### Code to reproduce the issue:

To reproduce, please examine this shell session closely (somewhat truncated for readability)

```sh
jsondiff@pesa:~/zzz$ pnpm -v
6.23.1
jsondiff@pesa:~/zzz$ node -v
v16.17.0
jsondiff@pesa:~/zzz$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
jsondiff@pesa:~/zzz$ git clone git@github.com:canonic-epicure/json-diff.git --recurse-submodules 
Cloning into 'json-diff'...
remote: Enumerating objects: 181, done.
....
Submodule path 'packages/siesta/packages/typescript-serializable-mixin': checked out '280937229109760120f79999d7461c29120e98cd'
jsondiff@pesa:~/zzz$ cd json-diff/
jsondiff@pesa:~/zzz/json-diff$ pnpm i
Scope: all 7 workspace projects
 WARN  There are cyclic workspace dependencies
Lockfile is up-to-date, resolution step is skipped
Packages: +598
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /home/jsondiff/.pnpm-store/v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 598, reused 598, downloaded 0, added 598, done
node_modules/.pnpm/core-js@2.6.12/node_modules/core-js: Running postinstall script, done in 96ms
node_modules/.pnpm/core-js@3.21.1/node_modules/core-js: Running postinstall script, done in 130ms
node_modules/.pnpm/playwright@1.19.1/node_modules/playwright: Running install script, done in 206ms
 WARN  Failed to create bin at /home/jsondiff/zzz/json-diff/packages/siesta/packages/typescript-serializable-mixin/node_modules/.bin/siesta. The source file at /home/jsondiff/zzz/json-diff/packages/siesta/packages/siesta/bin/siesta.js does not exist.

>> Here the `pnpm` version is updated in external shell:

jsondiff@pesa:~/zzz/json-diff$ pnpm -v
7.11.0
jsondiff@pesa:~/zzz/json-diff$ pnpm i
Scope: all 7 workspace projects
 WARN  There are cyclic workspace dependencies
Recreating /home/jsondiff/zzz/json-diff/node_modules
.../siesta/packages/chained-iterator     |  WARN  deprecated tslint@6.1.3
packages/siesta/packages/chronograph     |  WARN  deprecated core-js@2.6.12
packages/jsondiff.dev                    |  WARN  deprecated @types/json5@2.2.0
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /home/jsondiff/.local/share/pnpm/store/v3
  Virtual store is at:             node_modules/.pnpm
packages/siesta/packages/siesta          |  WARN  deprecated fsevents@2.1.3
packages/siesta/packages/chronograph     |  WARN  deprecated uuid@3.4.0
 ERROR  Cannot read properties of undefined (reading 'resolvedPackage')

pnpm: Cannot read properties of undefined (reading 'resolvedPackage')
    at /usr/lib/node_modules/pnpm/dist/pnpm.cjs:132579:69
    at Array.every (<anonymous>)
    at /usr/lib/node_modules/pnpm/dist/pnpm.cjs:132571:100
    at Array.find (<anonymous>)
    at resolvePeersOfNode (/usr/lib/node_modules/pnpm/dist/pnpm.cjs:132571:64)
    at resolvePeersOfChildren (/usr/lib/node_modules/pnpm/dist/pnpm.cjs:132695:49)
    at default_1 (/usr/lib/node_modules/pnpm/dist/pnpm.cjs:132498:9)
    at default_1 (/usr/lib/node_modules/pnpm/dist/pnpm.cjs:133411:121)
    at async _installInContext (/usr/lib/node_modules/pnpm/dist/pnpm.cjs:136096:238)
    at async installInContext (/usr/lib/node_modules/pnpm/dist/pnpm.cjs:136403:16)
Progress: resolved 601, reused 596, downloaded 0, added 0
jsondiff@pesa:~/zzz/json-diff$ 
```

**Comment by mattpilott** [comment]
I see something similar since updating to latest pnpm
` ERROR  Cannot read properties of undefined (reading 'resolve')`

**Comment by zkochan** [comment]
Can you create a repo that reproduces the issue?

**Comment by canonic-epicure** [comment]
@zkochan yup, its already created - follow the shell output
