### ISSUE TITLE
pnpm cannot install due to node-gyp missing MSVS, but npm can install.

### ISSUE THREAD

**Issue by sharky98** [pnpm/pnpm#5342]
### Code to reproduce the issue:

```shell
> pnpm add --save-dev -w parcel
```

or

```shell
> pnpm install --save-dev -w parcel
```

### Expected behavior:

Successful installation of parcel package.

### Actual behavior:

The installation does not work due to missing MSVS installation.

```shell
Packages are copied from the content-addressable store to the virtual store.
  Content-addressable store is at: C:\Users\sa830268\AppData\Local\pnpm\store\v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 184, reused 167, downloaded 0, added 168, done
node_modules/.pnpm/msgpackr-extract@2.1.2/node_modules/msgpackr-extract: Running install script, failed in 3.8s (skipped as optional)
node_modules/.pnpm/lmdb@2.5.2/node_modules/lmdb: Running install script, failed in 2.9s
.../.pnpm/lmdb@2.5.2/node_modules/lmdb install$ node-gyp-build-optional-packages
│ C:\Users\sa830268\Documents\dev\sandbox\node_modules\.pnpm\lmdb@2.5.2\node_modules\lmdb>if not defined npm_config_node_gyp (node "C:\Users\sa830268\Documents\dev\bin\node-v18.9.0-win-x64
│ gyp info it worked if it ends with ok
│ gyp info using node-gyp@9.1.0
│ gyp info using node@18.9.0 | win32 | x64
│ gyp info find Python using Python version 3.10.5 found at "C:\Users\sa830268\Documents\dev\bin\pyenv\pyenv-win\versions\3.10.5\python.exe"
│ gyp ERR! find VS
│ gyp ERR! find VS msvs_version not set from command line or npm config
│ gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
│ gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
│ gyp ERR! find VS looking for Visual Studio 2015
│ gyp ERR! find VS - not found
│ gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
│ gyp ERR! find VS
│ gyp ERR! find VS **************************************************************
│ gyp ERR! find VS You need to install the latest version of Visual Studio
│ gyp ERR! find VS including the "Desktop development with C++" workload.
│ gyp ERR! find VS For more information consult the documentation at:
│ gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
│ gyp ERR! find VS **************************************************************
│ gyp ERR! find VS
│ gyp ERR! configure error
│ gyp ERR! stack Error: Could not find any Visual Studio installation to use
│ gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\sa830268\Documents\dev\bin\node-v18.9.0-win-x64\node_modules\pnpm\dist\node_modules\node-gyp\lib\find-visualstudio.js:122:47)
│ gyp ERR! stack     at C:\Users\sa830268\Documents\dev\bin\node-v18.9.0-win-x64\node_modules\pnpm\dist\node_modules\node-gyp\lib\find-visualstudio.js:75:16
│ gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\sa830268\Documents\dev\bin\node-v18.9.0-win-x64\node_modules\pnpm\dist\node_modules\node-gyp\lib\find-visualstudio
│ gyp ERR! stack     at C:\Users\sa830268\Documents\dev\bin\node-v18.9.0-win-x64\node_modules\pnpm\dist\node_modules\node-gyp\lib\find-visualstudio.js:71:14
│ gyp ERR! stack     at C:\Users\sa830268\Documents\dev\bin\node-v18.9.0-win-x64\node_modules\pnpm\dist\node_modules\node-gyp\lib\find-visualstudio.js:385:16
│ gyp ERR! stack     at C:\Users\sa830268\Documents\dev\bin\node-v18.9.0-win-x64\node_modules\pnpm\dist\node_modules\node-gyp\lib\util.js:54:7
│ gyp ERR! stack     at C:\Users\sa830268\Documents\dev\bin\node-v18.9.0-win-x64\node_modules\pnpm\dist\node_modules\node-gyp\lib\util.js:33:16
│ gyp ERR! stack     at ChildProcess.exithandler (node:child_process:420:5)
│ gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
│ gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
│ gyp ERR! System Windows_NT 10.0.19044
│ gyp ERR! command "C:\\Users\\sa830268\\Documents\\dev\\bin\\node-v18.9.0-win-x64\\node.exe" "C:\\Users\\sa830268\\Documents\\dev\\bin\\node-v18.9.0-win-x64\\node_modules\\pnpm\\dist\\nod
│ gyp ERR! cwd C:\Users\sa830268\Documents\dev\sandbox\node_modules\.pnpm\lmdb@2.5.2\node_modules\lmdb
│ gyp ERR! node -v v18.9.0
│ gyp ERR! node-gyp -v v9.1.0
│ gyp ERR! not ok
└─ Failed in 2.9s
 ELIFECYCLE  Command failed with exit code 1.
```

### Comparative behavior with npm:

When using npm, everything is installed correctly, without needing node-gyp.

```shell
> npm install --save-dev parcel
added 167 packages, and audited 168 packages in 16s

73 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

Weird thing, once installed with npm, I can ask pnpm to install it also and it will succeed.
```shell
> pnpm install --save-dev -w parcel
 WARN  Moving parcel that was installed by a different package manager to "node_modules/.ignored
Packages: +168
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are copied from the content-addressable store to the virtual store.
  Content-addressable store is at: C:\Users\sa830268\AppData\Local\pnpm\store\v3
  Virtual store is at:             node_modules/.pnpm
node_modules/.pnpm/msgpackr-extract@2.1.2/node_modules/msgpackr-extract: Running install script, done in 498ms
Progress: resolved 184, reused 167, downloaded 0, added 168, done
node_modules/.pnpm/lmdb@2.5.2/node_modules/lmdb: Running install script, done in 398ms
```

### Additional information:

I am under Windows with a regular user account. I am not able to get an admin access due to corporate policies. As such, I am not able to install MSVS stuff needed by node-gyp using pnpm.

 - `node -v` prints: v18.9.0
 - Windows, macOS, or Linux?: Windows 10 x64

`.npmrc` content
```ini
symlink=false
package-import-method=copy
```

**Comment by SpecialAro** [comment]
I have this issue as well. I'm running the latest MSVS (2022). Everything works fine with `npm` but it doesn't with `pnpm`

**Comment by zkochan** [comment]
Closing: this is not something pnpm can fix.

node-gyp needs the Visual Studio build tools on Windows. pnpm ships the same node-gyp npm uses and honors `npm_config_node_gyp` (verified while checking 405).

If you still hit this on the latest pnpm, please comment with a reproduction and we will reopen.

---
Written by an agent (Claude Code, claude-opus-5).
