### ISSUE TITLE
Cannot install `jquery.dirtyforms`:  Invalid tar header: unknown format

### ISSUE THREAD

**Issue by illright** [pnpm/pnpm#5362]
### Code to reproduce the issue:
```shell
pnpm add jquery.dirtyforms
```

### Expected behavior:
The package is installed and added to dependencies

### Actual behavior:
The package fails to install with the following log:
```
Packages: +2
++
 WARN  GET https://registry.npmjs.org/jquery.dirtyforms/-/jquery.dirtyforms-2.0.0.tgz error (undefined). Will retry in 10 seconds. 2 retries left.
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /home/illright/.local/share/pnpm/store/v3
  Virtual store is at:             node_modules/.pnpm
 WARN  GET https://registry.npmjs.org/jquery.dirtyforms/-/jquery.dirtyforms-2.0.0.tgz error (undefined). Will retry in 1 minute. 1 retries left.
 ERROR  Invalid tar header: unknown format.

pnpm: Invalid tar header: unknown format.
    at exports2.decode (/home/illright/.cache/node/corepack/pnpm/7.11.0/dist/pnpm.cjs:75324:17)
    at Extract.onheader (/home/illright/.cache/node/corepack/pnpm/7.11.0/dist/pnpm.cjs:75462:44)
    at Extract._write (/home/illright/.cache/node/corepack/pnpm/7.11.0/dist/pnpm.cjs:75576:12)
    at Extract._continue (/home/illright/.cache/node/corepack/pnpm/7.11.0/dist/pnpm.cjs:75544:14)
    at oncontinue (/home/illright/.cache/node/corepack/pnpm/7.11.0/dist/pnpm.cjs:75408:15)
    at Extract.ondrain (/home/illright/.cache/node/corepack/pnpm/7.11.0/dist/pnpm.cjs:75430:9)
    at Extract._write (/home/illright/.cache/node/corepack/pnpm/7.11.0/dist/pnpm.cjs:75576:12)
    at Extract._continue (/home/illright/.cache/node/corepack/pnpm/7.11.0/dist/pnpm.cjs:75544:14)
    at oncontinue (/home/illright/.cache/node/corepack/pnpm/7.11.0/dist/pnpm.cjs:75408:15)
    at Extract.onstreamend (/home/illright/.cache/node/corepack/pnpm/7.11.0/dist/pnpm.cjs:75425:11)
Progress: resolved 2, reused 0, downloaded 1, added 1
```

### Additional information:

 - `node -v` prints: v18.8.0
 - Windows, macOS, or Linux?: WSL 2 Arch Linux

**Comment by mcmxcdev** [comment]
Indeed seems to be an issue, the installation works fine with `npm install jquery.dirtyforms` but not pnpm.

**Comment by illright** [comment]
Looks like this can be remedied by passing `{ allowUnknownFormat: true }` to `tar.extract()`. Will verify once I'll be able to set up a dev version of pnpm, #6669
