### ISSUE TITLE
`pd [command]` fails in local environment

### ISSUE THREAD

**Issue by lvqq** [pnpm/pnpm#5502]
### pnpm version:
Newest main branch

### Code to reproduce the issue:
Try the following steps from [CONTRIBUTING.md](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md):
1. `pnpm install`
2. `pnpm link -g --dir ./packages/pnpm/dev`
3. `pnpm run compile`

### Expected behavior:
`pd [command]` works fine

### Actual behavior:
`pd -v` works fine, but `pd [command]` such as `pd run <script>` fails: 

```
TypeError: Class extends value undefined is not a constructor or null
    at ../pnpm/node_modules/.pnpm/@pnpm+os.env.path-extender-posix@0.2.4/node_modules/@pnpm/os.env.path-extender-posix/dist/path-extender-posix.js (/workspaces/pnpm/packages/pnpm/dev/dist/pnpm.cjs:189878:54)
    at __require (/workspaces/pnpm/packages/pnpm/dev/dist/pnpm.cjs:12:50)
    at ../pnpm/node_modules/.pnpm/@pnpm+os.env.path-extender-posix@0.2.4/node_modules/@pnpm/os.env.path-extender-posix/dist/index.js (/workspaces/pnpm/packages/pnpm/dev/dist/pnpm.cjs:190036:33)
    at __require (/workspaces/pnpm/packages/pnpm/dev/dist/pnpm.cjs:12:50)
    at ../pnpm/node_modules/.pnpm/@pnpm+os.env.path-extender@0.2.6/node_modules/@pnpm/os.env.path-extender/dist/path-extender.js (/workspaces/pnpm/packages/pnpm/dev/dist/pnpm.cjs:191946:40)
    at __require (/workspaces/pnpm/packages/pnpm/dev/dist/pnpm.cjs:12:50)
    at ../pnpm/node_modules/.pnpm/@pnpm+os.env.path-extender@0.2.6/node_modules/@pnpm/os.env.path-extender/dist/index.js (/workspaces/pnpm/packages/pnpm/dev/dist/pnpm.cjs:191987:27)
    at __require (/workspaces/pnpm/packages/pnpm/dev/dist/pnpm.cjs:12:50)
    at ../pnpm/packages/plugin-commands-setup/src/setup.ts (/workspaces/pnpm/packages/pnpm/dev/dist/pnpm.cjs:192104:29)
    at __init (/workspaces/pnpm/packages/pnpm/dev/dist/pnpm.cjs:9:59)
```
### Additional information:
The error occurs in both Windows and Linux
 - `node -v` prints: v16.17.0
 - Windows, macOS, or Linux?: Windows

 - `node -v` prints: v14.19.1
 - Windows, macOS, or Linux?: Linux

**Comment by lvqq** [comment]
I found it not work since this commit: https://github.com/pnpm/pnpm/commit/043d988fc93aa2f897fa5c46f6856f7b8d2066e2

**Comment by zkochan** [comment]
I know it stopped working but I don't understand why.

**Comment by lvqq** [comment]
Actually I don't understand it either. From the [stackoverflow](https://stackoverflow.com/questions/43176006/typeerror-class-extends-value-undefined-is-not-a-function-or-null), the error occurs while there exists the circular reference in `class`, but I didn't find anything about it. The only change is using `export` instead of `export default`. So I update the version of `@pnpm/error` and it solves the problem.
