### ISSUE TITLE
Perform additional validation for `undefined` dependency ranges after `readPackage()` hook 

### ISSUE THREAD

**Issue by walkerburgin** [pnpm/pnpm#5517]
_// This is probably somewhere between a bug and a feature request_ 

### pnpm version:
`7.13.4`, `7.13.5`

### Code to reproduce the issue:
The simplest repro would be a `readPackage()` hook that accidentally sets a dependency range to `undefined`: 

```js
function readPackage(pkg) {
  if (pkg.name === "@blueprintjs/core" && pkg.version === "1.40.0") {
      pkg.dependencies["react-addons-css-transition-group"] = undefined;
  }
  return pkg;
}

module.exports = {
  hooks: {
    readPackage,
  },
};
```

See https://github.com/walkerburgin/pnpm7-readpackage-delete-repro for a standalone repro that's representative of how we actually encountered this while upgrading our large monorepo from pnpm v6 to pnpm v7.

### Expected behavior:
In a perfect world, PNPM would either ignores any dependency with an `undefined` range, or fail with a more explicit error.

### Actual behavior:
PNPM crashes with a stack trace like this:

```
 ERROR  Cannot read properties of undefined (reading 'startsWith')

This error happened while installing the dependencies of @blueprintjs/core@1.40.0

pnpm: Cannot read properties of undefined (reading 'startsWith')
    at resolveDependency (/opt/homebrew/Cellar/pnpm/7.13.4/libexec/dist/pnpm.cjs:134193:74)
    at resolveDependenciesOfDependency (/opt/homebrew/Cellar/pnpm/7.13.4/libexec/dist/pnpm.cjs:133979:45)
    at /opt/homebrew/Cellar/pnpm/7.13.4/libexec/dist/pnpm.cjs:133871:72
    at Array.map (<anonymous>)
    at resolveDependencies (/opt/homebrew/Cellar/pnpm/7.13.4/libexec/dist/pnpm.cjs:133871:45)
    at resolveChildren (/opt/homebrew/Cellar/pnpm/7.13.4/libexec/dist/pnpm.cjs:134046:54)
    at postponedResolution (/opt/homebrew/Cellar/pnpm/7.13.4/libexec/dist/pnpm.cjs:134013:57)
    at /opt/homebrew/Cellar/pnpm/7.13.4/libexec/dist/pnpm.cjs:133808:106
    at Array.map (<anonymous>)
    at /opt/homebrew/Cellar/pnpm/7.13.4/libexec/dist/pnpm.cjs:133808:77
```

This is maybe tangentially related to https://github.com/pnpm/pnpm/pull/4415 (and to a lesser extent https://github.com/pnpm/pnpm/issues/5493).

### Additional information:

 - `node -v` prints: `v16.17.1` 
 - Windows, macOS, or Linux?: macOS

**Comment by altaywtf** [comment]
A fix is ready for review: https://github.com/pnpm/pnpm/pull/15326

---
Written by an agent (Claude Code, claude-opus-5-5).
