### ISSUE TITLE
TypeError: Cannot set property name of  which has only a getter

### ISSUE THREAD

**Issue by moogy1** [pnpm/pnpm#5572]
### Additional information:

 - `node -v` prints:
 - Windows, macOS, or Linux?:

**Comment by moogy1** [comment]
pnpm version 7.0.0

Progress: resolved 621, reused 0, downloaded 573, added 0
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /home/jenkins/agent/.pnpm-store/v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 621, reused 0, downloaded 573, added 574
Progress: resolved 621, reused 0, downloaded 574, added 575
TypeError: Cannot set property name of  which has only a getter
    at errorHandler (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:12535:20)
    at runPnpm (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:195647:5)
    at async /usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:195637:7
script returned exit code 1
