### ISSUE TITLE
parse github https url of pull-request or branch

### ISSUE THREAD

**Issue by milahu** [pnpm/pnpm#5684]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

**Describe the user story**

install a npm package from a github pull-request or branch
using the original `https:` url

**Describe the solution you'd like**

copy-paste the original `https:` url and pass it to pnpm

```sh
# install from github pull-request
pnpm install https://github.com/jimmywarting/native-file-system-adapter/pull/41
```

```sh
# install from github branch
pnpm install https://github.com/jimmywarting/native-file-system-adapter/tree/feature/breaking
```

currently (pnpm 7.14.0) this fails with `error (undefined)`

<details>

```
pnpm install https://github.com/jimmywarting/native-file-system-adapter/pull/41

 WARN  GET https://github.com/jimmywarting/native-file-system-adapter/pull/41 error (undefined). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://github.com/jimmywarting/native-file-system-adapter/pull/41 error (undefined). Will retry in 1 minute. 1 retries left.
 ERROR  Invalid tar header. Maybe the tar is corrupted or it needs to be gunzipped?

pnpm: Invalid tar header. Maybe the tar is corrupted or it needs to be gunzipped?
    at exports2.decode (pnpm.cjs:75623:15)
    at Extract.onheader (pnpm.cjs:75768:44)
    at Extract._write (pnpm.cjs:75882:12)
    at doWrite (pnpm.cjs:10183:16)
    at writeOrBuffer (pnpm.cjs:10169:9)
    at Writable.write (pnpm.cjs:10098:15)
    at Pumpify.ondata (pnpm.cjs:73775:24)
    at Pumpify.emit (node:events:513:28)
    at addChunk (pnpm.cjs:73535:16)
    at readableAddChunk (pnpm.cjs:73524:15)
Progress: resolved 9, reused 9, downloaded 0, added 0
```

</details>

**Describe the drawbacks of your solution**

none?

**Describe alternatives you've considered**

currently, i can install only the main branch from the https url

```
pnpm install https://github.com/jimmywarting/native-file-system-adapter
```

since #4953 i can install pull-requests and branches by their git ref

```sh
pnpm install github:jimmywarting/native-file-system-adapter#pull/41/merge
# or
pnpm install github:jimmywarting/native-file-system-adapter#feature/breaking
```

but this is more work, because i have to manually transform the `https:` url to a `github:` url

```diff
-  https://github.com/jimmywarting/native-file-system-adapter/pull/41
+  github:jimmywarting/native-file-system-adapter#pull/41/merge
```

```diff
-  https://github.com/jimmywarting/native-file-system-adapter/tree/feature/breaking
+  github:jimmywarting/native-file-system-adapter#feature/breaking
```

**Comment by Shinyaigeek** [comment]
good idea!! I wanna catch this.

I investigated a little.

First, I should fix this line https://github.com/pnpm/pnpm/blob/main/resolving/tarball-resolver/src/index.ts#L33 not to reckon URL as tarball for the URL which is hosted in github.com and has supplement pathname such as branch name or pull request.

Second, I should fix also  hosted-git-info which pnpm uses to parse github.com URL because hosted-git-info cannot parse github.com URL with branch name with slash (slash should be encoded) https://github.com/npm/hosted-git-info/blob/main/test/github.js#L263.

Fortunately, pnpm folk hosted-git-info and use it, so I patch it into folked that.

I thought about formatting the URL before passing it to hosted-git-info without modifying hosted-git-info, but I wanted to concentrate the responsibility on hosted-git-info as much as possible, so I decided to fix folked hosted-git-info

**Comment by Shinyaigeek** [comment]
https://github.com/zkochan/hosted-git-info/pull/2 I sent pull_request to folked version of `hosted-git-info` to support this feature, but it would be better way to use original version of `hosted-git-info` instaed of foled that, and to send patch to original...

**Comment by milahu** [comment]
thanks @Shinyaigeek : )

ideally, also commit urls should be recognized

```
pnpm i -g https://github.com/antongolub/tsc-esm-fix/commit/30a7978e31d8690b41fc39f73b436b695d8f1210
```

ideally, this would also work with other git webinterfaces: gitlab, bitbucket, gitea, sourcehut, cgit, ...

currently, asking pnpm to install from a github url gives the error ERR_PNPM_TARBALL_EXTRACT

```console
$ pnpm install https://github.com/jimmywarting/native-file-system-adapter/pull/41

 WARN  GET https://github.com/jimmywarting/native-file-system-adapter/pull/41 error (ERR_PNPM_TARBALL_EXTRACT). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://github.com/jimmywarting/native-file-system-adapter/pull/41 error (ERR_PNPM_TARBALL_EXTRACT). Will retry in 1 minute. 1 retries left.
 ERR_PNPM_TARBALL_EXTRACT  Failed to unpack the tarball from "https://github.com/jimmywarting/native-file-system-adapter/pull/41": Invalid tar header. Maybe the tar is corrupted or it needs to be gunzipped?
Progress: resolved 30, reused 30, downloaded 0, added 0
```

**Comment by zkochan** [comment]
This no longer reproduces on current pnpm, so closing.

Verified on pnpm 12.5.1: `pnpm add "is-negative@https://github.com/zkochan/is-negative/tree/master"` installs from that branch.

If you still hit this on the latest pnpm, please comment with a reproduction and we will reopen.

---
Written by an agent (Claude Code, claude-opus-5).
