### ISSUE TITLE
Relative path in local package results in errors

### ISSUE THREAD

**Issue by chenxsan** [pnpm/pnpm#5741]
### pnpm version:

7.17.1

### Code to reproduce the issue:

Please clone https://github.com/eslint/eslint and run `pnpm install` under the root.

### Expected behavior:

After installation, `pnpm run lint:docsjs` should run without errors.

### Actual behavior:

```
Error: Cannot find module '../../lib/rules/multiline-comment-style'
Require stack:
- /home/ubuntu/eslint/node_modules/.pnpm/file+tools+internal-rules/node_modules/eslint-plugin-internal-rules/multiline-comment-style.js
- /home/ubuntu/eslint/node_modules/.pnpm/file+tools+internal-rules/node_modules/eslint-plugin-internal-rules/index.js
- /home/ubuntu/eslint/eslint.config.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/ubuntu/eslint/node_modules/.pnpm/file+tools+internal-rules/node_modules/eslint-plugin-internal-rules/multiline-comment-style.js:9:31)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)

    at Object.error (/home/ubuntu/eslint/node_modules/.pnpm/shelljs@0.8.5/node_modules/shelljs/src/common.js:110:27)
    at execSync (/home/ubuntu/eslint/node_modules/.pnpm/shelljs@0.8.5/node_modules/shelljs/src/exec.js:120:12)
    at _exec (/home/ubuntu/eslint/node_modules/.pnpm/shelljs@0.8.5/node_modules/shelljs/src/exec.js:223:12)
    at /home/ubuntu/eslint/node_modules/.pnpm/shelljs@0.8.5/node_modules/shelljs/src/common.js:335:23
    at target.lintDocsJS (/home/ubuntu/eslint/Makefile.js:549:24)
    at global.target.<computed> [as lintDocsJS] (/home/ubuntu/eslint/node_modules/.pnpm/shelljs@0.8.5/node_modules/shelljs/make.js:36:40)
    at /home/ubuntu/eslint/node_modules/.pnpm/shelljs@0.8.5/node_modules/shelljs/make.js:48:27
    at Array.forEach (<anonymous>)
    at Timeout._onTimeout (/home/ubuntu/eslint/node_modules/.pnpm/shelljs@0.8.5/node_modules/shelljs/make.js:46:10)
```

### Additional information:

Here's why,

1. the `package.json` file defined a dev dependency `"eslint-plugin-internal-rules": "file:tools/internal-rules"` which points to `tools/internal-rules` folder
2. in this `tools/internal-rules`, there's this `multiline-comment-style.js` file which requires a rule from another folder under the root: `const multilineCommentStyle = require("../../lib/rules/multiline-comment-style");`

**Comment by chenxsan** [comment]
I see, guess I was wrong to assume different package managers to share the same behavior regarding `file:` protocol.
