### ISSUE TITLE
Transient dependency error: Your application tried to access meow, but it isn't declared in your dependencies

### ISSUE THREAD

**Issue by unional** [pnpm/pnpm#5796]
### pnpm version:

7.18.2 (also tried 7.17.0)

### Code to reproduce the issue:

https://github.com/justland/just-func-typescript

```sh
pnpm install
pnpm cs
```

### Expected behavior:

`cs` (`changeset`) should be executed

### Actual behavior:

```
> @ cs /Users/hwong/unional/just-func-typescript
> changeset

/Users/hwong/unional/just-func-typescript/.pnp.cjs:22990
    throw firstError;
    ^

Error: Your application tried to access meow, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.

Required package: meow
Required by: /Users/hwong/unional/just-func-typescript/node_modules/.pnpm/@changesets+cli@2.25.2/node_modules/@changesets/cli/dist/

Require stack:
- /Users/hwong/unional/just-func-typescript/node_modules/.pnpm/@changesets+cli@2.25.2/node_modules/@changesets/cli/dist/cli.cjs.dev.js
- /Users/hwong/unional/just-func-typescript/node_modules/.pnpm/@changesets+cli@2.25.2/node_modules/@changesets/cli/dist/cli.cjs.js
- /Users/hwong/unional/just-func-typescript/node_modules/.pnpm/@changesets+cli@2.25.2/node_modules/@changesets/cli/bin.js
    at Function.require$$0.Module._resolveFilename (/Users/hwong/unional/just-func-typescript/.pnp.cjs:22989:13)
    at Function.require$$0.Module._load (/Users/hwong/unional/just-func-typescript/.pnp.cjs:22843:42)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/hwong/unional/just-func-typescript/node_modules/.pnpm/@changesets+cli@2.25.2/node_modules/@changesets/cli/dist/cli.cjs.dev.js:3:12)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Object.require$$0.Module._extensions..js (/Users/hwong/unional/just-func-typescript/.pnp.cjs:23033:33)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.require$$0.Module._load (/Users/hwong/unional/just-func-typescript/.pnp.cjs:22873:14)
```

### Additional information:

 - `node -v` prints: node: 16.14.2, 18.12.1
 - Windows, macOS, or Linux?: macOS

This issue does not happen on Windows or in other repository.

And it does not seems to be an issue of usage nor `@changeset/cli`.

`@changeset/cli` does have `meow` declared as a deps.

I can see there are two versions of `meow` installed:

```sh
pnpm why meow   
Legend: production dependency, optional only, dev only

/Users/hwong/unional/just-func-typescript

devDependencies:
@changesets/cli 2.25.2
└── meow 6.1.1
@commitlint/cli 17.3.0
├─┬ @commitlint/lint 17.3.0
│ └─┬ @commitlint/parse 17.2.0
│   └─┬ conventional-commits-parser 3.2.4
│     └── meow 8.1.2
└─┬ @commitlint/read 17.2.0
  └─┬ git-raw-commits 2.0.11
    └── meow 8.1.2
```

I have deleted `node_modules` as well as `pnpn-lock.yaml`, but after install again it gets the same error.

Cross ref: https://github.com/changesets/changesets/issues/1032

**Comment by zkochan** [comment]
This looks like an error from Yarn's plug'n'play. Are you sure you didn't run `yarn install` before in that repo? 

I could not reproduce the issue.

**Comment by unional** [comment]
🤣  this repo has never been infected by yarn.

**Comment by unional** [comment]
Seems like now it is working. Let's close this.
