### ISSUE TITLE
pnpm not working (error) on Nushell

### ISSUE THREAD

**Issue by mdrv** [pnpm/pnpm#5812]
### pnpm version:

v7.17.1

### Code to reproduce the issue:

```bash
pnpm # or almost every pnpm command
```

### Expected behavior:

The binary should output the usual help text or anything else without any error.

### Actual behavior:

This error log shows up:

```bash
(node:32723) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, lstat '/root/.local/share/pnpm/stable-aarch64-unknown-linux-gnu'
    at Object.realpathSync (fs.js:1801:7)
    at Object.realpathSync (pkg/prelude/bootstrap.js:1364:36)
    at ../node_modules/.pnpm/temp-dir@2.0.0/node_modules/temp-dir/index.js (/snapshot/dist/pnpm.cjs)
    at __require (/snapshot/dist/pnpm.cjs)
    at ../node_modules/.pnpm/tempy@1.0.1/node_modules/tempy/index.js (/snapshot/dist/pnpm.cjs)
    at __require (/snapshot/dist/pnpm.cjs)
    at ../env/node.fetcher/lib/index.js (/snapshot/dist/pnpm.cjs)
    at __require (/snapshot/dist/pnpm.cjs)
    at ../env/plugin-commands-env/lib/node.js (/snapshot/dist/pnpm.cjs)
    at __require (/snapshot/dist/pnpm.cjs)
(Use `pnpm --trace-warnings ...` to show where the warning was created)
(node:32723) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:32723) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Additional information:

 - `node -v` prints: v19.1.0 (installed via `pnpm env`)
 - OS: Arch Linux 64-bit (both x86 and ARM)
 - Nushell ver. (`nu -v`): v0.72.1

I already set up `PNPM_HOME` and `PATH` as explained on #5000 but the error is shown regardless of which pnpm command to execute (except `pnpm -v`). Meanwhile, the other binaries (ex. node, npm, yarn, prettierd, tsserver) worked without any issue on Nushell.

**Note:** I’m not asking for another shell support but rather the actual reason of this problem and hopefully some workaround to be able to run `pnpm` on Nushell (which is my default shell).

**Comment by mdrv** [comment]
Found the culprit. Turns out Nushell modified `TMP` variable to `stable-aarch64-unknown-linux-gnu` (depends on your computer) which leads to pnpm reading a non-existing directory. To fix it, I simply add this line on `$nu.env-path`:

```nu
let-env TMP = ""
```

Although the issue has been closed, I still wanna know the reason why pnpm needs `TMP` directory to exist (and why otherwise it won’t run properly). This might also be related to #4960.
