### ISSUE TITLE
When a private module cannot be found a 404 error is reporting which does not help find the root cause

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#599]
### pnpm version:

0.51.1

### Code to reproduce the issue:

Create a private module and add to a `package.json. file.

```
pnpm i
```

### Expected behavior:

Shows an error message indicating which module failed to be found.

It would be cool if it would check if it is @scoped and say "Is this module private? If so, do you have access privileges and are you npm logged in."

### Actual behavior:

```
   ...
  mailcomposer 3.0.1                                               queued ↓
  ascli ~1                                                         queued ↓
  bytebuffer ~5                                                    queued ↓
  glob ^5.0.10                                                     queued ↓
  util >=0.10.3 <1                                                 queued ↓
  lolex 1.3.2                                                      queued ↓
ERROR fetch failed with status code 404
Error: fetch failed with status code 404
    at Request.<anonymous> (/usr/local/lib/node_modules/pnpm/lib/node_modules/npm-registry-client/lib/fetch.js:58:14)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.onRequestResponse (/usr/local/lib/node_modules/pnpm/lib/node_modules/request/request.js:986:10)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:430:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)
    at TLSSocket.socketOnData (_http_client.js:320:20)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at TLSSocket.Readable.push (_stream_readable.js:111:10)
    at TLSWrap.onread (net.js:536:20)
```

### Additional information:

 - `node -v` prints: 6.5.0
 - Windows, OS X, or Linux?: macOS

**Comment by vjpr** [comment]
Also for `fetch failed with status code 503` would be useful too, to have the package that failed. I had this happen to a private submodule.
