### ISSUE TITLE
"pnpm add" fails on Windows if your current directory starts with lower-case "c:\"

### ISSUE THREAD

**Issue by eberridge** [pnpm/pnpm#6022]
### pnpm version:
7.26.3

### Code to reproduce the issue:
Assuming your code is in C:\Repos\DesignHub\apps\excel-service (and a package.json lives there), and the root package.json for the workspace is in C:\Repos\DesignHub:
In a CMD prompt
1. Make the CWD drive letter lower-case. You can do this by "cd c:\Repos\DH\apps\excel-service"
2. Try to add a package e.g., "pnpm add exceljs"

### Expected behavior:
The package is added properly to package.json.

### Actual behavior:
```
c:\Repos\DesignHub\apps\excel-service>pnpm add exceljs
pnpm: Cannot read properties of undefined (reading 'manifest')
    at C:\Users\eberridge\.node\corepack\pnpm\7.18.1\dist\pnpm.cjs:182693:44
    at Array.map (<anonymous>)
    at C:\Users\eberridge\.node\corepack\pnpm\7.18.1\dist\pnpm.cjs:182691:60
    at Array.map (<anonymous>)
    at getAllProjects (C:\Users\eberridge\.node\corepack\pnpm\7.18.1\dist\pnpm.cjs:182691:21)
    at recursive (C:\Users\eberridge\.node\corepack\pnpm\7.18.1\dist\pnpm.cjs:182377:22)
    at async installDeps (C:\Users\eberridge\.node\corepack\pnpm\7.18.1\dist\pnpm.cjs:182780:11)
    at async C:\Users\eberridge\.node\corepack\pnpm\7.18.1\dist\pnpm.cjs:209903:21
    at async main (C:\Users\eberridge\.node\corepack\pnpm\7.18.1\dist\pnpm.cjs:209874:34)
    at async runPnpm (C:\Users\eberridge\.node\corepack\pnpm\7.18.1\dist\pnpm.cjs:210100:5)
```

### Additional information:
I edited `pnpm.cjs` to output the keys of `manifestsByPath` in the function `getAllProjects` and saw that they all start with upper-case "C". So I changed my CWD to start with C:\blah... and it fixed the problem. Regardless, pnpm should not fail if the user's command prompt has the current directory starting with a lower-case "c".

 - Windows, macOS, or Linux?: Windows

**Comment by zkochan** [comment]
Closing as a duplicate of #5500 (2022-10-15), which is the older report of the same thing.

Same bug: a lowercase drive letter in the current directory breaks pnpm's path handling on Windows.

Follow #5500 for this. If you think the two differ in a way that matters, say so here and we will reopen.

---
Written by an agent (Claude Code, claude-opus-5).
