### ISSUE TITLE
Support --userconfig and $NPM_CONFIG_USERCONFIG

### ISSUE THREAD

**Issue by rulatir** [pnpm/pnpm#6036]
As per https://github.com/pnpm/pnpm/issues/695#issuecomment-291590083, this is the separate issue to request and track the implementation of proper `--userconfig` and `$NPM_CONFIG_USERCONFIG` handling, so that the location of the user config could be overriden.

My motivation is not as much about compatibility with npm as it is about making pnpm env-jailable. Without the requested feature, and short of going full Docker, it is impossible to create a shell environment with an isolated installation of pnpm that can be configured and run free of interference with user's "normal" pnpm and npm configured via ~/.npmrc. It is also impossible to maintain entirely separate pnpm configurations for different node environments managed by nvm or nave. They will all fight each other in ~/.npmrc, and as I understand there is currently no way around this limitation.

**Comment by prantlf** [comment]
It appears that [the previous issue](https://github.com/pnpm/pnpm/issues/40) was closed with [a merged change](https://github.com/pnpm/pnpm/pull/709), but this feature wasn't implemented, because `pnpm` recognises neither `--userconfig` nor `--config`.

Would it be possible to add the `--userconfig` command-line argument, please?

## Motivation

I'm trying to get packages published from [a monorepo](https://github.com/prantlf/dep-dev) automatically using [semantic-release](https://www.google.com/search?client=firefox-b-d&q=npm+semantic-release). I'm looking for a way to use the plugin [@semantic-release/npm](https://www.npmjs.com/package/@semantic-release/npm).

NPM appears to dislike the PNPM feature - link to the same package in `devDependencies` in `package.json`:

    "@pkgdep/link": "link:"

It leads to [a failure](https://github.com/prantlf/dep-dev/actions/runs/4212062885/jobs/7310824600#step:5:123) when executing the command:

    npm publish /home/runner/work/dep-dev/dep-dev/pkg/extra \
      --userconfig /tmp/72388ce8b79f2f9183bfa3d5f3b3042b/.npmrc \
      --tag latest --registry https://registry.npmjs.org/

with the following message:

    npm ERR! Cannot set properties of null (setting 'peer')

    npm ERR! A complete log of this run can be found in:
    npm ERR!     /home/runner/.npm/_logs/2023-02-18T16_35_03_772Z-debug-0.log

The same error can be reproduced on the local command line by just running `npm publish`.

So, I started to look for a way how to make [@semantic-release/npm](https://www.npmjs.com/package/@semantic-release/npm) run `pnpm` instead of `npm`, because just running `pnpm publish` in the same package directory succeeds.

## Problem

I started by just replacing `npm` with `pnpm`.  It failed:

    pnpm publish /Users/prantlf/Sources/github/dep-dev/pkg/link \
      --userconfig /private/var/folders/cx/_rbf_s993_gc00k1nwhj9htm0000gn/T/0f6f971d4cd0bbf19529d8bc526c62a1/.npmrc \
      --tag latest --registry https://registry.npmjs.org/

    ERROR  Unknown option: 'userconfig'
    For help, run: pnpm help publish

The full output:

    [5:43:28 PM] [semantic-release] › ℹ  Start step "publish" of plugin "@semantic-release/npm"
    [5:43:28 PM] [semantic-release] [@semantic-release/npm] › ℹ  Publishing version 1.2.0 to npm registry on dist-tag latest
     ERROR   ERROR  Unknown option: 'userconfig'
    For help, run: pnpm help publish
    [5:43:28 PM] [semantic-release] › ✘  Failed step "publish" of plugin "@semantic-release/npm"
    [5:43:28 PM] [semantic-release] › ✘  An error occurred while running semantic-release: Error: Command failed with exit code 1: pnpm publish /Users/prantlf/Sources/github/dep-dev/pkg/link --userconfig /private/var/folders/cx/_rbf_s993_gc00k1nwhj9htm0000gn/T/0f6f971d4cd0bbf19529d8bc526c62a1/.npmrc --tag latest --registry https://registry.npmjs.org/
     ERROR   ERROR  Unknown option: 'userconfig'
    For help, run: pnpm help publish
        at makeError (/Users/prantlf/Sources/github/dep-dev/node_modules/.pnpm/execa@5.1.1/node_modules/execa/lib/error.js:60:11)
        at handlePromise (/Users/prantlf/Sources/github/dep-dev/node_modules/.pnpm/execa@5.1.1/node_modules/execa/index.js:118:26)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async module.exports (/Users/prantlf/Sources/github/dep-dev/node_modules/.pnpm/@semantic-release+npm@9.0.2_semantic-release@20.1.0/node_modules/@semantic-release/npm/lib/publish.js:30:5)
        at async validator (file:///Users/prantlf/Sources/github/dep-dev/node_modules/.pnpm/semantic-release@20.1.0/node_modules/semantic-release/lib/plugins/normalize.js:36:24)
        at async file:///Users/prantlf/Sources/github/dep-dev/node_modules/.pnpm/semantic-release@20.1.0/node_modules/semantic-release/lib/plugins/pipeline.js:37:34
        at async Promise.all (index 0)
        at async next (file:///Users/prantlf/Sources/github/dep-dev/node_modules/.pnpm/p-reduce@3.0.0/node_modules/p-reduce/index.js:15:44) {
      shortMessage: 'Command failed with exit code 1: pnpm publish /Users/prantlf/Sources/github/dep-dev/pkg/link --userconfig /private/var/folders/cx/_rbf_s993_gc00k1nwhj9htm0000gn/T/0f6f971d4cd0bbf19529d8bc526c62a1/.npmrc --tag latest --registry https://registry.npmjs.org/',
      command: 'pnpm publish /Users/prantlf/Sources/github/dep-dev/pkg/link --userconfig /private/var/folders/cx/_rbf_s993_gc00k1nwhj9htm0000gn/T/0f6f971d4cd0bbf19529d8bc526c62a1/.npmrc --tag latest --registry https://registry.npmjs.org/',
      escapedCommand: 'pnpm publish "/Users/prantlf/Sources/github/dep-dev/pkg/link" --userconfig "/private/var/folders/cx/_rbf_s993_gc00k1nwhj9htm0000gn/T/0f6f971d4cd0bbf19529d8bc526c62a1/.npmrc" --tag latest --registry "https://registry.npmjs.org/"',
      exitCode: 1,
      signal: undefined,
      signalDescription: undefined,
      stdout: " ERROR   ERROR  Unknown option: 'userconfig'\n" +
        'For help, run: pnpm help publish',
      stderr: '',
      failed: true,
      timedOut: false,
      isCanceled: false,
      killed: false,
      pluginName: '@semantic-release/npm'
    }
    Error: Command failed with exit code 1: pnpm publish /Users/prantlf/Sources/github/dep-dev/pkg/link --userconfig /private/var/folders/cx/_rbf_s993_gc00k1nwhj9htm0000gn/T/0f6f971d4cd0bbf19529d8bc526c62a1/.npmrc --tag latest --registry https://registry.npmjs.org/
     ERROR   ERROR  Unknown option: 'userconfig'
    For help, run: pnpm help publish
        at makeError (/Users/prantlf/Sources/github/dep-dev/node_modules/.pnpm/execa@5.1.1/node_modules/execa/lib/error.js:60:11)
        at handlePromise (/Users/prantlf/Sources/github/dep-dev/node_modules/.pnpm/execa@5.1.1/node_modules/execa/index.js:118:26)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async module.exports (/Users/prantlf/Sources/github/dep-dev/node_modules/.pnpm/@semantic-release+npm@9.0.2_semantic-release@20.1.0/node_modules/@semantic-release/npm/lib/publish.js:30:5)
        at async validator (file:///Users/prantlf/Sources/github/dep-dev/node_modules/.pnpm/semantic-release@20.1.0/node_modules/semantic-release/lib/plugins/normalize.js:36:24)
        at async file:///Users/prantlf/Sources/github/dep-dev/node_modules/.pnpm/semantic-release@20.1.0/node_modules/semantic-release/lib/plugins/pipeline.js:37:34
        at async Promise.all (index 0)
        at async next (file:///Users/prantlf/Sources/github/dep-dev/node_modules/.pnpm/p-reduce@3.0.0/node_modules/p-reduce/index.js:15:44) {
      shortMessage: 'Command failed with exit code 1: pnpm publish /Users/prantlf/Sources/github/dep-dev/pkg/link --userconfig /private/var/folders/cx/_rbf_s993_gc00k1nwhj9htm0000gn/T/0f6f971d4cd0bbf19529d8bc526c62a1/.npmrc --tag latest --registry https://registry.npmjs.org/',
      command: 'pnpm publish /Users/prantlf/Sources/github/dep-dev/pkg/link --userconfig /private/var/folders/cx/_rbf_s993_gc00k1nwhj9htm0000gn/T/0f6f971d4cd0bbf19529d8bc526c62a1/.npmrc --tag latest --registry https://registry.npmjs.org/',
      escapedCommand: 'pnpm publish "/Users/prantlf/Sources/github/dep-dev/pkg/link" --userconfig "/private/var/folders/cx/_rbf_s993_gc00k1nwhj9htm0000gn/T/0f6f971d4cd0bbf19529d8bc526c62a1/.npmrc" --tag latest --registry "https://registry.npmjs.org/"',
      exitCode: 1,
      signal: undefined,
      signalDescription: undefined,
      stdout: " ERROR   ERROR  Unknown option: 'userconfig'\n" +
        'For help, run: pnpm help publish',
      stderr: '',
      failed: true,
      timedOut: false,
      isCanceled: false,
      killed: false,
      pluginName: '@semantic-release/npm'
    }%                                                                              

I found [a closed issue](https://github.com/pnpm/pnpm/issues/40), which suggested that there's an alternative argument `--config`. But it failed too:

    pnpm publish /Users/prantlf/Sources/github/dep-dev/pkg/update \
      --config /private/var/folders/cx/_rbf_s993_gc00k1nwhj9htm0000gn/T/8a4f9ec7acbd415b186b3e867c4576ab/.npmrc
      --tag latest --registry https://registry.npmjs.org/

    ERROR  Unknown option: 'config'
    For help, run: pnpm help publish

The full output:

    [5:47:44 PM] [semantic-release] › ℹ  Start step "publish" of plugin "@semantic-release/npm"
    [5:47:44 PM] [semantic-release] [@semantic-release/npm] › ℹ  Publishing version 1.4.0 to npm registry on dist-tag latest
     ERROR   ERROR  Unknown option: 'config'
    For help, run: pnpm help publish
    [5:47:44 PM] [semantic-release] › ✘  Failed step "publish" of plugin "@semantic-release/npm"
    [5:47:44 PM] [semantic-release] › ✘  An error occurred while running semantic-release: Error: Command failed with exit code 1: pnpm publish /Users/prantlf/Sources/github/dep-dev/pkg/update --config /private/var/folders/cx/_rbf_s993_gc00k1nwhj9htm0000gn/T/8a4f9ec7acbd415b186b3e867c4576ab/.npmrc --tag latest --registry https://registry.npmjs.org/
     ERROR   ERROR  Unknown option: 'config'
    For help, run: pnpm help publish
        at makeError (/Users/prantlf/Sources/github/dep-dev/node_modules/.pnpm/execa@5.1.1/node_modules/execa/lib/error.js:60:11)
        at handlePromise (/Users/prantlf/Sources/github/dep-dev/node_modules/.pnpm/execa@5.1.1/node_modules/execa/index.js:118:26)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async module.exports (/Users/prantlf/Sources/github/dep-dev/node_modules/.pnpm/@semantic-release+npm@9.0.2_semantic-release@20.1.0/node_modules/@semantic-release/npm/lib/publish.js:30:5)
        at async validator (file:///Users/prantlf/Sources/github/dep-dev/node_modules/.pnpm/semantic-release@20.1.0/node_modules/semantic-release/lib/plugins/normalize.js:36:24)
        at async file:///Users/prantlf/Sources/github/dep-dev/node_modules/.pnpm/semantic-release@20.1.0/node_modules/semantic-release/lib/plugins/pipeline.js:37:34
        at async Promise.all (index 0)
        at async next (file:///Users/prantlf/Sources/github/dep-dev/node_modules/.pnpm/p-reduce@3.0.0/node_modules/p-reduce/index.js:15:44) {
      shortMessage: 'Command failed with exit code 1: pnpm publish /Users/prantlf/Sources/github/dep-dev/pkg/update --config /private/var/folders/cx/_rbf_s993_gc00k1nwhj9htm0000gn/T/8a4f9ec7acbd415b186b3e867c4576ab/.npmrc --tag latest --registry https://registry.npmjs.org/',
      command: 'pnpm publish /Users/prantlf/Sources/github/dep-dev/pkg/update --config /private/var/folders/cx/_rbf_s993_gc00k1nwhj9htm0000gn/T/8a4f9ec7acbd415b186b3e867c4576ab/.npmrc --tag latest --registry https://registry.npmjs.org/',
      escapedCommand: 'pnpm publish "/Users/prantlf/Sources/github/dep-dev/pkg/update" --config "/private/var/folders/cx/_rbf_s993_gc00k1nwhj9htm0000gn/T/8a4f9ec7acbd415b186b3e867c4576ab/.npmrc" --tag latest --registry "https://registry.npmjs.org/"',
      exitCode: 1,
      signal: undefined,
      signalDescription: undefined,
      stdout: " ERROR   ERROR  Unknown option: 'config'\nFor help, run: pnpm help publish",
      stderr: '',
      failed: true,
      timedOut: false,
      isCanceled: false,
      killed: false,
      pluginName: '@semantic-release/npm'
    }
    Error: Command failed with exit code 1: pnpm publish /Users/prantlf/Sources/github/dep-dev/pkg/update --config /private/var/folders/cx/_rbf_s993_gc00k1nwhj9htm0000gn/T/8a4f9ec7acbd415b186b3e867c4576ab/.npmrc --tag latest --registry https://registry.npmjs.org/
     ERROR   ERROR  Unknown option: 'config'
    For help, run: pnpm help publish
        at makeError (/Users/prantlf/Sources/github/dep-dev/node_modules/.pnpm/execa@5.1.1/node_modules/execa/lib/error.js:60:11)
        at handlePromise (/Users/prantlf/Sources/github/dep-dev/node_modules/.pnpm/execa@5.1.1/node_modules/execa/index.js:118:26)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async module.exports (/Users/prantlf/Sources/github/dep-dev/node_modules/.pnpm/@semantic-release+npm@9.0.2_semantic-release@20.1.0/node_modules/@semantic-release/npm/lib/publish.js:30:5)
        at async validator (file:///Users/prantlf/Sources/github/dep-dev/node_modules/.pnpm/semantic-release@20.1.0/node_modules/semantic-release/lib/plugins/normalize.js:36:24)
        at async file:///Users/prantlf/Sources/github/dep-dev/node_modules/.pnpm/semantic-release@20.1.0/node_modules/semantic-release/lib/plugins/pipeline.js:37:34
        at async Promise.all (index 0)
        at async next (file:///Users/prantlf/Sources/github/dep-dev/node_modules/.pnpm/p-reduce@3.0.0/node_modules/p-reduce/index.js:15:44) {
      shortMessage: 'Command failed with exit code 1: pnpm publish /Users/prantlf/Sources/github/dep-dev/pkg/update --config /private/var/folders/cx/_rbf_s993_gc00k1nwhj9htm0000gn/T/8a4f9ec7acbd415b186b3e867c4576ab/.npmrc --tag latest --registry https://registry.npmjs.org/',
      command: 'pnpm publish /Users/prantlf/Sources/github/dep-dev/pkg/update --config /private/var/folders/cx/_rbf_s993_gc00k1nwhj9htm0000gn/T/8a4f9ec7acbd415b186b3e867c4576ab/.npmrc --tag latest --registry https://registry.npmjs.org/',
      escapedCommand: 'pnpm publish "/Users/prantlf/Sources/github/dep-dev/pkg/update" --config "/private/var/folders/cx/_rbf_s993_gc00k1nwhj9htm0000gn/T/8a4f9ec7acbd415b186b3e867c4576ab/.npmrc" --tag latest --registry "https://registry.npmjs.org/"',
      exitCode: 1,
      signal: undefined,
      signalDescription: undefined,
      stdout: " ERROR   ERROR  Unknown option: 'config'\nFor help, run: pnpm help publish",
      stderr: '',
      failed: true,
      timedOut: false,
      isCanceled: false,
      killed: false,
      pluginName: '@semantic-release/npm'
    }%                                                                              

Is there any other way how to supply a custom config file to `pnpm`, apart from the `--userconfig`?

**Comment by jason-ha** [comment]
While it doesn't have to be $NPM_CONFIG_USERCONFIG, once updating to v7.20+ our automated systems that relied on pnpm respecting $NPM_CONFIG_USERCONFIG (by way of npm) broke. System was using $NPM_CONFIG_USERCONFIG to specify temp config file location generically (as opposed to visiting each subsequent use and adding an argument). Support for pnpm specific environment variable would work for our case.
For now will attempting to workaround by crafting temp file location to be .../pnpm/rc and setting $XDG_CONFIG_HOME, which I don't think is otherwise in use.

**Comment by jason-ha** [comment]
After trying workarounds and failing I have discovered a number of things including that $NPM_CONFIG_USERCONFIG is somehow observed. That was not the source of our troubles. I will post a separate issue.

**Comment by kirillgroshkov** [comment]
@jason-ha did you resolve it in the end?

**Comment by jason-ha** [comment]
I think the issue I filed was 6131 and that was resolved.

**Comment by stefreak** [comment]
it's possible to work around this in certain test scenarios (in my case, e2e tests for an nx plugin), by setting `HOME`. This is unbelievably ugly, but in case you need it, this works for me on unix systems:

```typescript
// HACK: working around missing support for NPM_CONFIG_USERCONFIG in pnpm: https://github.com/pnpm/pnpm/issues/6036
const testTmpDir = join(import.meta.dirname, "tmp") // => .npmrc with verdaccio registry config lives in this directory
const res = await exec(`pnpm store path`)
// On macOS this results in Library, as pnpm cache store is under ~/Library/pnpm
const cacheDir = res.stdout.trim().replace(homedir(), '').replace(/^\//, '').split('/')[0];
if (!cacheDir) {
  throw new Error(`Could not determine pnpm cache directory from store path: ${res.stdout}`);
}
// create a symlink to Library. We need this because of the HOME override below; Without the symlink pnpm won't use caches and everything will be painfully slow.
await exec(`ln -sf ~/${cacheDir} ${join(testTmpDir, cacheDir)}`);
await exec(`pnpx create-nx-workspace --name e2etest --interactive=false --verbose --pm pnpm --preset my-test-preset 1>&2`, {
    cwd: testTmpDir,
    
    env: {
      ...process.env,
      HOME: testTmpDir,
    }
  })
```

**Comment by zkochan** [comment]
This is implemented in current pnpm, so closing.

`--userconfig` is accepted as an alias of `--npmrc-auth-file`, and `PNPM_CONFIG_NPMRC_AUTH_FILE` sets it from the environment.

If you still hit this on the latest pnpm, please comment with a reproduction and we will reopen.

---
Written by an agent (Claude Code, claude-opus-5).
