### ISSUE TITLE
RenovateBot doesn't update pnpm-lock.yaml

### ISSUE THREAD

**Issue by mihaicozma** [pnpm/pnpm#6049]
### Code to reproduce the issue:
https://github.com/mihaicozma/RenovateTest

### Expected behavior:
Update pnpm-lock.yaml

### Actual behavior:
The artifact failure details are included below:

File name: typescript-starter/pnpm-lock.yaml
node:internal/errors:491
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:400:5)
    at validateString (node:internal/validators:163:11)
    at Object.resolve (node:path:167:9)
    at ../node_modules/.pnpm/@pnpm+npm-conf@2.0.4/node_modules/@pnpm/npm-conf/lib/defaults.js (C:\npm\prefix\node_modules\pnpm\dist\pnpm.cjs:14115:23)
    at __require (C:\npm\prefix\node_modules\pnpm\dist\pnpm.cjs:12:50)
    at ../node_modules/.pnpm/@pnpm+npm-conf@2.0.4/node_modules/@pnpm/npm-conf/index.js (C:\npm\prefix\node_modules\pnpm\dist\pnpm.cjs:14264:21)
    at __require (C:\npm\prefix\node_modules\pnpm\dist\pnpm.cjs:12:50)
    at ../config/config/lib/index.js (C:\npm\prefix\node_modules\pnpm\dist\pnpm.cjs:25033:39)
    at __require (C:\npm\prefix\node_modules\pnpm\dist\pnpm.cjs:12:50)
    at ../cli/cli-utils/lib/getConfig.js (C:\npm\prefix\node_modules\pnpm\dist\pnpm.cjs:44986:20) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v18.13.0
#### Issue is only on running renovate windows
jobs:
  build:
    runs-on: windows-latest

PS:
on ubuntu-latest works fine

**Comment by zkochan** [comment]
Closing: this is not something pnpm can fix.

Renovate supports pnpm lockfile maintenance. How it runs pnpm is Renovate's configuration.

If you still hit this on the latest pnpm, please comment with a reproduction and we will reopen.

---
Written by an agent (Claude Code, claude-opus-5).
