### ISSUE TITLE
Dependency installed inside a package overrides another transitive dependency in another package in the same workspace

### ISSUE THREAD

**Issue by boudra** [pnpm/pnpm#6053]
### Code to reproduce the issue: https://github.com/boudra/pnpm-sub-dep-issue

The repository above replicates this issue with a PNPM workspace that contains 2 packages:

- A: Standard CRA app
- B: Just a package that requires `jest-environment-jsdom@29.4.2` to illustrate the issue

### Expected behavior:

When you run `pnpm install` and `pnpm test` in `packages/a`, the tests should run correctly.

### Actual behavior:

When you run `pnpm install` and `pnpm test` in `packages/a` you'll notice the tests fail with this error:

```
  ● Test suite failed to run

    TypeError: Cannot read properties of undefined (reading 'testEnvironmentOptions')

      at new JSDOMEnvironment (../../node_modules/.pnpm/jest-environment-jsdom@29.4.2/node_modules/jest-environment-jsdom/build/index.js:63:28)
      at async TestScheduler.scheduleTests (../../node_modules/.pnpm/@jest+core@27.5.1/node_modules/@jest/core/build/TestScheduler.js:333:13)
      at async runJest (../../node_modules/.pnpm/@jest+core@27.5.1/node_modules/@jest/core/build/runJest.js:404:19)
```

That is because the package `@jest/core@27.5.1` requires `jest-environment-jsdom@27.5.1` but for some reason is instead resolving to `jest-environment-jsdom@29.4.2` (as you can see in the stacktrace) which is installed in package B of the workspace, causing incompatibility issues.

When I run `pnpm remove jest-environment-jsdom` in  package B, the tests in A work as expected. Not sure why dependencies installed in package B are overriding dependencies in package A.

A temporary solution to this is to downgrade to `jest-environment-jsdom@27.5.1` in package B, but I believe packages shouldn't override each others sub dependencies, this breaks packages expectations to have a specific version of a package and creates compatibility issues.

Could this also be an issue of how Jest have set up their dependencies? `@jest/core` is not directly dependent on `jest-environment-jsdom` but it's a transitive dependency through `jest-runner`, but either way the version required in the dependency tree is `27` and not `29`.

### Additional information:

 - `node -v` prints: 16.19.0
 - Windows, macOS, or Linux?: macOs and Linux

**Comment by LucasIcarus** [comment]
Same issue with pnpm@7.27.x.   pnpm@7.26.3 works fine.

with pnpm@7.27.x

packages:
- a (@types/react: ^17 + @types/react-dom: ^17)
- b (@types/react: 18.0.28 + @types/react-dom: 18.0.11)

`node_modules/.pnpm/@types+react-dom@18.0.11/node_modules/@types/react/package.json` => version: 17.0.53

will cause massive type error.

packages:
- a (@types/react: ^17 + @types/react-dom: ^17)
- b (@types/react: ^18.0.28 + @types/react-dom: ^18.0.11)

`node_modules/.pnpm/@types+react-dom@18.0.11/node_modules/@types/react/package.json` => version: 18.0.28

seems fine.

**Comment by ilijaNL** [comment]
> Same issue with [pnpm@7.27.x](mailto:pnpm@7.27.x). but pnpm@7.26.3 works fine.
> 
> with [pnpm@7.27.x](mailto:pnpm@7.27.x)
> 
> packages:
> 
> * a (@types/react: ^17 + @types/react-dom: ^17)
> * b (@types/react: 18.0.28 + @types/react-dom: 18.0.11)
> 
> `node_modules/.pnpm/@types+react-dom@18.0.11/node_modules/@types/react/package.json` => version: 17.0.53
> 
> will cause massive type error.
> 
> packages:
> 
> * a (@types/react: ^17 + @types/react-dom: ^17)
> * b (@types/react: ^18.0.28 + @types/react-dom: ^18.0.11)
> 
> `node_modules/.pnpm/@types+react-dom@18.0.11/node_modules/@types/react/package.json` => version: 18.0.28
> 
> seems fine.

I have a similar problem with pnpm version 8.0.0. I have 2 typescript apps, one using react 17 and other 18 with @types/react installed.  All default hoisting settings are used. 

I did some digging and the problem seems to be that if some deep dependencies do not have "peerDependency" defined for @types/react or have @types/react: "*", typescript will resolve the module to the node_modules/.pnpm/node_modules/@types/react ( I guess node_modules/.pnpm/node_modules is fallback folder?)

Stack trace of module resolution (react 17):

`
======== Resolving module 'react' from '/Documents/git/node_modules/.pnpm/react-query@3.34.12_react-dom@17.0.2_react@17.0.2/node_modules/react-query/types/react/QueryClientProvider.d.ts'. ========
Explicitly specified module resolution kind: 'NodeJs'.
'baseUrl' option is set to '/Documents/git/app/src', using this value to resolve non-relative module name 'react'.
'paths' option is specified, looking for a pattern to match module name 'react'.
'baseUrl' option is set to '/Documents/git/app/src', using this value to resolve non-relative module name 'react'.
Resolving module name 'react' relative to base url '/Documents/git/app/src' - '/Documents/git/app/src/react'.
Loading module as file / folder, candidate module location '/Documents/git/app/src/react', target file type 'TypeScript'.
File '/Documents/git/app/src/react.ts' does not exist.
File '/Documents/git/app/src/react.tsx' does not exist.
File '/Documents/git/app/src/react.d.ts' does not exist.
Directory '/Documents/git/app/src/react' does not exist, skipping all lookups in it.
Loading module 'react' from 'node_modules' folder, target file type 'TypeScript'.
Directory '/Documents/git/node_modules/.pnpm/react-query@3.34.12_react-dom@17.0.2_react@17.0.2/node_modules/react-query/types/react/node_modules' does not exist, skipping all lookups in it.
Directory '/Documents/git/node_modules/.pnpm/react-query@3.34.12_react-dom@17.0.2_react@17.0.2/node_modules/react-query/types/node_modules' does not exist, skipping all lookups in it.
Directory '/Documents/git/node_modules/.pnpm/react-query@3.34.12_react-dom@17.0.2_react@17.0.2/node_modules/react-query/node_modules' does not exist, skipping all lookups in it.
Found 'package.json' at '/Documents/git/node_modules/.pnpm/react-query@3.34.12_react-dom@17.0.2_react@17.0.2/node_modules/react/package.json'.
'package.json' does not have a 'typesVersions' field.
File '/Documents/git/node_modules/.pnpm/react-query@3.34.12_react-dom@17.0.2_react@17.0.2/node_modules/react.ts' does not exist.
File '/Documents/git/node_modules/.pnpm/react-query@3.34.12_react-dom@17.0.2_react@17.0.2/node_modules/react.tsx' does not exist.
File '/Documents/git/node_modules/.pnpm/react-query@3.34.12_react-dom@17.0.2_react@17.0.2/node_modules/react.d.ts' does not exist.
'package.json' does not have a 'typings' field.
'package.json' does not have a 'types' field.
'package.json' has 'main' field 'index.js' that references '/Documents/git/node_modules/.pnpm/react-query@3.34.12_react-dom@17.0.2_react@17.0.2/node_modules/react/index.js'.
File '/Documents/git/node_modules/.pnpm/react-query@3.34.12_react-dom@17.0.2_react@17.0.2/node_modules/react/index.js' exist - use it as a name resolution result.
File '/Documents/git/node_modules/.pnpm/react-query@3.34.12_react-dom@17.0.2_react@17.0.2/node_modules/react/index.js' has an unsupported extension, so skipping it.
Loading module as file / folder, candidate module location '/Documents/git/node_modules/.pnpm/react-query@3.34.12_react-dom@17.0.2_react@17.0.2/node_modules/react/index.js', target file type 'TypeScript'.
File '/Documents/git/node_modules/.pnpm/react-query@3.34.12_react-dom@17.0.2_react@17.0.2/node_modules/react/index.js.ts' does not exist.
File '/Documents/git/node_modules/.pnpm/react-query@3.34.12_react-dom@17.0.2_react@17.0.2/node_modules/react/index.js.tsx' does not exist.
File '/Documents/git/node_modules/.pnpm/react-query@3.34.12_react-dom@17.0.2_react@17.0.2/node_modules/react/index.js.d.ts' does not exist.
File name '/Documents/git/node_modules/.pnpm/react-query@3.34.12_react-dom@17.0.2_react@17.0.2/node_modules/react/index.js' has a '.js' extension - stripping it.
File '/Documents/git/node_modules/.pnpm/react-query@3.34.12_react-dom@17.0.2_react@17.0.2/node_modules/react/index.ts' does not exist.
File '/Documents/git/node_modules/.pnpm/react-query@3.34.12_react-dom@17.0.2_react@17.0.2/node_modules/react/index.tsx' does not exist.
File '/Documents/git/node_modules/.pnpm/react-query@3.34.12_react-dom@17.0.2_react@17.0.2/node_modules/react/index.d.ts' does not exist.
Directory '/Documents/git/node_modules/.pnpm/react-query@3.34.12_react-dom@17.0.2_react@17.0.2/node_modules/react/index.js' does not exist, skipping all lookups in it.
File '/Documents/git/node_modules/.pnpm/react-query@3.34.12_react-dom@17.0.2_react@17.0.2/node_modules/react/index.ts' does not exist.
File '/Documents/git/node_modules/.pnpm/react-query@3.34.12_react-dom@17.0.2_react@17.0.2/node_modules/react/index.tsx' does not exist.
File '/Documents/git/node_modules/.pnpm/react-query@3.34.12_react-dom@17.0.2_react@17.0.2/node_modules/react/index.d.ts' does not exist.
Directory '/Documents/git/node_modules/.pnpm/react-query@3.34.12_react-dom@17.0.2_react@17.0.2/node_modules/@types' does not exist, skipping all lookups in it.
Found 'package.json' at '/Documents/git/node_modules/.pnpm/node_modules/react/package.json'.
'package.json' does not have a 'typesVersions' field.
File '/Documents/git/node_modules/.pnpm/node_modules/react.ts' does not exist.
File '/Documents/git/node_modules/.pnpm/node_modules/react.tsx' does not exist.
File '/Documents/git/node_modules/.pnpm/node_modules/react.d.ts' does not exist.
'package.json' does not have a 'typings' field.
'package.json' does not have a 'types' field.
'package.json' has 'main' field 'index.js' that references '/Documents/git/node_modules/.pnpm/node_modules/react/index.js'.
File '/Documents/git/node_modules/.pnpm/node_modules/react/index.js' exist - use it as a name resolution result.
File '/Documents/git/node_modules/.pnpm/node_modules/react/index.js' has an unsupported extension, so skipping it.
Loading module as file / folder, candidate module location '/Documents/git/node_modules/.pnpm/node_modules/react/index.js', target file type 'TypeScript'.
File '/Documents/git/node_modules/.pnpm/node_modules/react/index.js.ts' does not exist.
File '/Documents/git/node_modules/.pnpm/node_modules/react/index.js.tsx' does not exist.
File '/Documents/git/node_modules/.pnpm/node_modules/react/index.js.d.ts' does not exist.
File name '/Documents/git/node_modules/.pnpm/node_modules/react/index.js' has a '.js' extension - stripping it.
File '/Documents/git/node_modules/.pnpm/node_modules/react/index.ts' does not exist.
File '/Documents/git/node_modules/.pnpm/node_modules/react/index.tsx' does not exist.
File '/Documents/git/node_modules/.pnpm/node_modules/react/index.d.ts' does not exist.
Directory '/Documents/git/node_modules/.pnpm/node_modules/react/index.js' does not exist, skipping all lookups in it.
File '/Documents/git/node_modules/.pnpm/node_modules/react/index.ts' does not exist.
File '/Documents/git/node_modules/.pnpm/node_modules/react/index.tsx' does not exist.
File '/Documents/git/node_modules/.pnpm/node_modules/react/index.d.ts' does not exist.
Found 'package.json' at '/Documents/git/node_modules/.pnpm/node_modules/@types/react/package.json'.
'package.json' does not have a 'typesVersions' field.
File '/Documents/git/node_modules/.pnpm/node_modules/@types/react.d.ts' does not exist.
'package.json' does not have a 'typings' field.
'package.json' has 'types' field 'index.d.ts' that references '/Documents/git/node_modules/.pnpm/node_modules/@types/react/index.d.ts'.
File '/Documents/git/node_modules/.pnpm/node_modules/@types/react/index.d.ts' exist - use it as a name resolution result.
Resolving real path for '/Documents/git/node_modules/.pnpm/node_modules/@types/react/index.d.ts', result '/Documents/git/node_modules/.pnpm/@types+react@18.0.25/node_modules/@types/react/index.d.ts'.
======== Module name 'react' was successfully resolved to '/Documents/git/node_modules/.pnpm/@types+react@18.0.25/node_modules/@types/react/index.d.ts' with Package ID '@types/react/index.d.ts@18.0.25'. ========
`

This seems wrong and not efficient. I have @types/react installed as devDependency in the react 17 app, however it doesnt seems to want to resolve to that package.

**Comment by GhostWalker562** [comment]
Running into this exact same issue for react-scripts

```
Test suite failed to run

    TypeError: Cannot read properties of undefined (reading 'testEnvironmentOptions')

      at new JSDOMEnvironment (../../node_modules/.pnpm/jest-environment-jsdom@29.5.0/node_modules/jest-environment-jsdom/build/index.js:63:28)
```

<img width="315" alt="image" src="https://github.com/pnpm/pnpm/assets/43276017/891c41ba-12ba-4592-b4dc-a9655bdf2ff9">

**Comment by frago12** [comment]
> Running into this exact same issue for react-scripts
> 
> ```
> Test suite failed to run
> 
>     TypeError: Cannot read properties of undefined (reading 'testEnvironmentOptions')
> 
>       at new JSDOMEnvironment (../../node_modules/.pnpm/jest-environment-jsdom@29.5.0/node_modules/jest-environment-jsdom/build/index.js:63:28)
> ```
> 
> <img alt="image" width="315" src="https://user-images.githubusercontent.com/43276017/275121686-891c41ba-12ba-4592-b4dc-a9655bdf2ff9.png">

I'm experiencing the same problem. This is my environment:
- `node`: 20.6.0
- `pnpm`: 8.10.5
- MacOS

**Comment by beshanoe** [comment]
Hey, did anyone find a solution? what I've done so far is for the packages on jest 26 I installed jest-environment-jsdom@26 explicitly. But this solution sucks because I have many packages that I have update like that :(

**Comment by zkochan** [comment]
This no longer reproduces on current pnpm, so closing.

Verified while checking 4088 and 5966: each project resolves its own pinned version and cannot reach a package it does not declare, so one project's dependency cannot override another's.

If you still hit this on the latest pnpm, please comment with a reproduction and we will reopen.

---
Written by an agent (Claude Code, claude-opus-5).
