### ISSUE TITLE
Windows: Unable to update lock within the stale threshold

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#608]
I got this message a couple of times on Windows with 0.53.0 and node@6.5.0 after running `pnpm i` twice:

```
C:\Users\Vaughan\AppData\Roaming\nvm\v6.5.0\node_modules\pnpm\lib\node_modules\proper-lockfile\index.js:180
    compromised = compromised || function (err) { throw err; };
                                                  ^

Error: Unable to update lock within the stale threshold
    at options.fs.utimes (C:\Users\Vaughan\AppData\Roaming\nvm\v6.5.0\node_modules\pnpm\lib\node_modules\proper-lockfile\index.js:108:66)
    at FSReqWrap.oncomplete (fs.js:123:15)
```

Maybe something to keep an eye on. Tricky to reproduce.

### Actual behavior:

```
Running pnpm@0.53.0 on windows errors:

---

C:\Users\Vaughan\AppData\Roaming\nvm\v6.5.0\node_modules\pnpm\lib\node_modules\proper-lockfile\index.js:180
    compromised = compromised || function (err) { throw err; };
                                                  ^

Error: Unable to update lock within the stale threshold
    at options.fs.utimes (C:\Users\Vaughan\AppData\Roaming\nvm\v6.5.0\node_modules\pnpm\lib\node_modules\proper-lockfile\index.js:108:66)
    at FSReqWrap.oncomplete (fs.js:123:15)
```

### Additional information:

 - `node -v` prints: 6.5.0
 - Windows, OS X, or Linux?: Windows

**Comment by zkochan** [comment]
Related https://github.com/pnpm/pnpm/issues/594

**Comment by zkochan** [comment]
Closing in favour of #594
