### ISSUE TITLE
Error: spawn E2BIG when running postinstall scripts

### ISSUE THREAD

**Issue by douglasward** [pnpm/pnpm#6106]
When upgrading from version 7.18.2 to 7.19.0, `pnpm install` errors out when running the postinstall scripts with the following error:

```sh
node:internal/child_process:413
    throw errnoException(err, 'spawn');
    ^
Error: spawn E2BIG
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at spawn (node:child_process:713:9)
    at spawn (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:104514:19)
    at runCmd_ (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:117817:20)
    at /usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:117761:11
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  errno: -7,
  code: 'E2BIG',
  syscall: 'spawn'
}
```

It doesn't seem to matter which postinstall script is run, any from any dependency or our own one will suffice.

Our .npmrc file is as follows

```
node-linker=hoisted
shared-workspace-lockfile = false
```

We need node-linker=hoisted as we have some angular projects in our mono-repo. Unsetting this seems to fix the problem but breaks the application builds.

These to pull requests seem that they might be related (included in the 7.19 release):
- https://github.com/pnpm/pnpm/pull/5795
- https://github.com/pnpm/pnpm/pull/5814

### Additional information:

 - `node -v` prints: 16.17.1
 - Windows, macOS, or Linux?: Tested on MacOS and on linux (`Linux e545ebd99b57 4.19.0-17-amd64 #1 SMP Debian 4.19.194-1 (2021-06-10) x86_64 x86_64 x86_64 GNU/Linux`)

**Comment by await-ovo** [comment]
Could you provide a minimal repo to reproduce this issue, I just tried it with the following project:

```
// packages/foo/package.json
{
  "name": "@pkg/foo",
  "dependencies": {
    "got": "^12.5.3",
    "ava": "^5.2.0",
    "prisma": "latest",
    "ts-node": "latest"
  }
}
// packages/bar/package.json
{
  "name": "@pkg/bar",
  "dependencies": {
    "prisma": "latest"
  }
}

// .npmrc
node-linker=hoisted
shared-workspace-lockfile=false
```

seems postinstall works find on pnpm v7.27.0:

**Comment by douglasward** [comment]
yes, I've managed to boil it down to a lock file with the following packages:

```
{
  "name": "test",
  "devDependencies": {
    "@angular-devkit/build-angular": "^13.3.0",
    "@angular-devkit/core": "^13.3.0",
    "@angular/cli": "^13.3.0",
    "@angular/compiler-cli": "^13.3.0",
    "@nguniversal/builders": "^13.1.0",
    "jest": "^27.4.7",
    "jest-preset-angular": "^11.1.1"
  }
}
```

I also noticed that I can only reproduce it on linux, not on macOS.

I have attached a minimal repo to reproduce. If you use the `Dockerfile` to build an image it will throw the error, e.g. with `docker build -t pnpm .`

[pnpm.zip](https://github.com/pnpm/pnpm/files/10784095/pnpm.zip)

**Comment by douglasward** [comment]
My colleague can reproduce it on his linux machine just with 

```json
"@angular-devkit/build-angular": "^13.3.0",
"@angular-devkit/core": "^13.3.0",
```

and no lockfile

**Comment by VeselyT** [comment]
This seems to be caused by PATH environment variable (generated somewhere in npm-lifecycle package I think) that contains paths to all .bin folders in all nested node_modules?

It seems to be caused by this parameter that contains all those paths https://github.com/pnpm/pnpm/blob/f5121500ee9b23d71ee5618f3afe296ef56640da/exec/lifecycle/src/runLifecycleHook.ts#L66 (in our case about 3500 entries). Those paths look like this 
![image](https://github.com/pnpm/pnpm/assets/6859743/79034987-ab83-4a49-81f0-f6fb71471cfb)

Hope this will help to fix this issue.

**Comment by particle4dev** [comment]
@zkochan any update on this issue?

**Comment by tomikpik** [comment]
+1 for this, it affects our production workload :(((( Could you please take a look at it?

**Comment by LuckaFEL** [comment]
Adding my vote for this. It's causing some serious disruptions in our production workflow. Mind giving it a look?

**Comment by NicoHinderling** [comment]
🙇 oh great @zkochan just wanted to bump this issue, as I'm currently running into it again

```
...

.../@fortawesome/fontawesome-svg-core postinstall$ node attribution.js
--
13:27:54.043 | .../@fortawesome/free-brands-svg-icons postinstall$ node attribution.js
13:27:54.061 | node:internal/child_process:421
13:27:54.061 | throw new ErrnoException(err, 'spawn');
13:27:54.062 | ^
13:27:54.062 |  
13:27:54.062 | Error: spawn E2BIG
13:27:54.062 | at ChildProcess.spawn (node:internal/child_process:421:11)
13:27:54.062 | at spawn (node:child_process:761:9)
13:27:54.062 | at spawn (/pnpm9/node_modules/pnpm/dist/pnpm.cjs:84547:19)
13:27:54.062 | at runCmd_ (/pnpm9/node_modules/pnpm/dist/pnpm.cjs:103507:20)
13:27:54.062 | at runCmd (/pnpm9/node_modules/pnpm/dist/pnpm.cjs:103447:9)
13:27:54.062 | at runPackageLifecycle (/pnpm9/node_modules/pnpm/dist/pnpm.cjs:103414:7)
13:27:54.062 | at Array.<anonymous> (/pnpm9/node_modules/pnpm/dist/pnpm.cjs:102886:13)
13:27:54.062 | at LOOP (/pnpm9/node_modules/pnpm/dist/pnpm.cjs:102913:18)
13:27:54.062 | at chain (/pnpm9/node_modules/pnpm/dist/pnpm.cjs:102920:9)
13:27:54.062 | at lifecycle_ (/pnpm9/node_modules/pnpm/dist/pnpm.cjs:103388:7) {
13:27:54.062 | errno: -7,
13:27:54.062 | code: 'E2BIG',
13:27:54.062 | syscall: 'spawn'
13:27:54.062 | }
13:27:54.062 |  
13:27:54.062 | Node.js v20.12.2
13:27:54.127 | Error: Command "pnpm install" exited with 1
```

**Comment by Armadillidiid** [comment]
Just encountered this issue on pnpm `9.1.1`. Below is my project `.npmrc` file
```npmrc
node-linker=hoisted
shared-workspace-lockfile=false 
shamefully-hoist=true
```

**Comment by yonihod** [comment]
happen here as well, any plans of addressing it?
```
node-linker=hoisted
shared-workspace-lockfile=false 
```

**Comment by jmikedupont2** [comment]
Same here

**Comment by zkochan** [comment]
We have fixed another issue with the same error code in v10: https://github.com/pnpm/pnpm/issues/8552

**Comment by ResoluteError** [comment]
> happen here as well, any plans of addressing it?
> 
> ```
> node-linker=hoisted
> shared-workspace-lockfile=false 
> ```

Same issue on my end, similar config. Using pnpm workspaces in combination with Azure Function Apps, this seems to be the only way to get the required node_modules structure. It runs locally but fails in the Azure DevOps pipeline.

**Comment by fabricio-yoke** [comment]
I fixed it by setting `runs-on: macos-latest` in my github action instead of `ubuntu-latest`

**Comment by ceferrari** [comment]
+1

**Comment by zkochan** [comment]
This error was sometimes caused by big values in some specific `npm_config_` env variables, which we stopped populating in pnpm v10.

**Comment by ceferrari** [comment]
> This error was sometimes caused by big values in some specific `npm_config_` env variables, which we stopped populating in pnpm v10.

I am using pnpm v10.6.5 and getting this error with the following `.npmrc` config:
```
node-linker=hoisted
shared-workspace-lockfile=false
```

**Comment by szusterm** [comment]
On `pnpm@10.11.0`, the error is the same. It's problematic with EAS Expo builds (it needs to run pnpm install)

**Comment by devniel** [comment]
Hello, same error here, happening in vercel but not in local when running `node script.js` in a `postinstall` 

```
Error: spawn E2BIG
```

**Comment by jigz** [comment]
this is blocking our production electron build, any solutions aside from the ones above?
https://github.com/electron/forge/blob/main/packages/api/cli/src/util/check-system.ts#L64

**Comment by zkochan** [comment]
This no longer reproduces on current pnpm, so closing.

Verified on pnpm 12.5.1: a dependency's install script receives 115 environment variables totalling about 7.8 KB, well under any E2BIG limit.

If you still hit this on the latest pnpm, please comment with a reproduction and we will reopen.

---
Written by an agent (Claude Code, claude-opus-5).
