### ISSUE TITLE
"Cannot find module 'vite'" when custom modules-dir is set

### ISSUE THREAD

**Issue by Acumane** [pnpm/pnpm#6161]
### pnpm version:
pnpm `7.28.0`

### Code to reproduce the issue:
 - build Vite starter project with `pnpm create vite`
 - `cd` into project
 - set custom modules-dir in `.npmrc`:
 ```yaml
# .npmrc
modules-dir=modules
virtual-store-dir=modules/.store
 ```
- remove default `node_modules` and `pnpm install`
- run `pnpm dev`, `pnpm run dev`, or `pnpm vite` depending on setup

### Expected behavior:
- Vite should run site on localhost

### Actual behavior:
```
failed to load config from /home/me/proj/app/vite.config.js
error when starting dev server:
Error: Cannot find module 'vite'
Require stack:
- /home/me/proj/app/vite.config.js
- /home/me/.local/share/pnpm/global/5/.pnpm/vite@4.1.4/node_modules/vite/dist/node/chunks/dep-ca21228b.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/me/proj/app/vite.config.js:36:19)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at _require.extensions.<computed> [as .js] (file:///home/me/.local/share/pnpm/global/5/.pnpm/vite@4.1.4/node_modules/vite/dist/node/chunks/dep-ca21228b.js:62356:24)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
```

### Additional information:
 - Node `v18.12.1`
 - Linux `5.15.90.1-microsoft-standard-WSL2`

**Comment by await-ovo** [comment]
I just tested it and got an error that the `vite` command could not be found:

```
$ pnpm dev

> vite-project@0.0.0 dev /test-pnpm/vite-project
> vite

sh: vite: command not found
 ELIFECYCLE  Command failed.
 WARN   Local package.json exists, but node_modules missing, did you mean to install?
```

**Comment by Acumane** [comment]
@await-ovo I just tested again with and without `create-vue`:
```
$ pnpm run dev

> test@0.0.0 dev /home/me/proj/test
> vite

failed to load config from /home/me/proj/test/vite.config.js
error when starting dev server:
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'vite' imported from /home/me/proj/test/vite.config.js.timestamp-1677778791106.mjs
    at new NodeError (node:internal/errors:393:5)
    at packageResolve (node:internal/modules/esm/resolve:860:9)
    at moduleResolve (node:internal/modules/esm/resolve:909:20)
    at defaultResolve (node:internal/modules/esm/resolve:1124:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:841:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36)
```
Different, but still: Vite's not too happy about the modules-dir change

**Comment by await-ovo** [comment]
> @await-ovo I just tested again with and without `create-vue`:
> 
> ```
> $ pnpm run dev
> 
> > test@0.0.0 dev /home/me/proj/test
> > vite
> 
> failed to load config from /home/me/proj/test/vite.config.js
> error when starting dev server:
> Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'vite' imported from /home/me/proj/test/vite.config.js.timestamp-1677778791106.mjs
>     at new NodeError (node:internal/errors:393:5)
>     at packageResolve (node:internal/modules/esm/resolve:860:9)
>     at moduleResolve (node:internal/modules/esm/resolve:909:20)
>     at defaultResolve (node:internal/modules/esm/resolve:1124:11)
>     at nextResolve (node:internal/modules/esm/loader:163:28)
>     at ESMLoader.resolve (node:internal/modules/esm/loader:841:30)
>     at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
>     at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
>     at link (node:internal/modules/esm/module_job:75:36)
> ```
> 
> Different, but still: Vite's not too happy about the modules-dir change

If the `vite` package loaded by `vite.confg.ts` is not found after the `vite` command is run, it looks more like an error thrown by node,  which is expected.

**Comment by Acumane** [comment]
@await-ovo The errors *are* being thrown by Node's built-in modules, I just figured (incorrectly) that this problem was exclusive to Vite. I'm also getting an error just like yours for a plain Vue project w/ `vue create`... does `modules-dir` work for anything?

**Comment by gaby** [comment]
@await-ovo @Acumane Any luck with this? I have wasted 1hr trying to get pnpm build to work when using vite and no luck so far.

**Comment by Reiwilde** [comment]
I have the same problem. When changing module-dir path. All local scripts fail to run (nx, eslint, prettier, ...).

**Comment by zkochan** [comment]
Closing as a duplicate of #3604 (2021-07-19), which is the older report of the same thing.

Same bug: with a custom `modulesDir`, a package cannot resolve its own dependencies.

Follow #3604 for this. If you think the two differ in a way that matters, say so here and we will reopen.

---
Written by an agent (Claude Code, claude-opus-5).
