### ISSUE TITLE
pnpm breaks if an attempt is made to export hasOwnProperty

### ISSUE THREAD

**Issue by gajus** [pnpm/pnpm#6189]
We have a utility `hasOwnProperty` that checks if an object has own property without relying on its prototype, i.e.

```json
"./hasOwnProperty": "./dist/hasOwnProperty.js",
...
"typesVersions": {
  "*": {
    "hasOwnProperty": [
      "./dist/hasOwnProperty.d.ts"
    ]
  }
}
```

```ts
export const hasOwnProperty = <X extends {}, Y extends PropertyKey>(
  object: X,
  property: Y,
): object is Record<Y, unknown> & X => {
  return Object.prototype.hasOwnProperty.call(object, property);
};
```

Ironically, pnpm iterates through object in an unsafe way causing error:

```
pnpm: value.hasOwnProperty is not a function
    at copy2 (/Users/gajus/Library/pnpm/global/5/.pnpm/pnpm@7.29.0/node_modules/pnpm/dist/pnpm.cjs:109474:21)
    at _clone (/Users/gajus/Library/pnpm/global/5/.pnpm/pnpm@7.29.0/node_modules/pnpm/dist/pnpm.cjs:109482:18)
    at copy2 (/Users/gajus/Library/pnpm/global/5/.pnpm/pnpm@7.29.0/node_modules/pnpm/dist/pnpm.cjs:109475:39)
```

It comes from this code:

```
for (var key in value) {
  if (value.hasOwnProperty(key)) {
    copiedValue[key] = deep ? _clone(value[key], refFrom, refTo, true) : value[key];
  }
}
```

The above code needs to be updated to not use `hasOwnProperty` of `value` to check if it has property.

**Comment by zkochan** [comment]
This no longer reproduces on current pnpm, so closing.

Verified on pnpm 12.5.1: a package exporting a `./hasOwnProperty` subpath installs and resolves.

If you still hit this on the latest pnpm, please comment with a reproduction and we will reopen.

---
Written by an agent (Claude Code, claude-opus-5).
