### ISSUE TITLE
No way to package for azure functions (serverless)

### ISSUE THREAD

**Issue by ghost** [pnpm/pnpm#6259]
### Code to reproduce the issue:
https://github.com/mm-edtake/pnpm-azure-pipeline

### Expected behavior:
We need to "create/generate" an artifact containing everything that is needed in term of dependencies.
In this test case, we should have all dependencies for app "api" included in node_modules folder of the artifact (all apps/api dependencies).

Here is Azure documentation about dependencies for deployments : [link](https://learn.microsoft.com/en-us/azure/azure-functions/functions-reference-node?tabs=v2-v3-v4-export%2Cv2-v3-v4-done%2Cv2%2Cv2-log-custom-telemetry%2Cv2-accessing-request-and-response%2Cwindows-setting-the-node-version#dependency-management)
![image](https://user-images.githubusercontent.com/99755384/226998266-d1fa7e35-8aeb-4b9a-a0a6-76e5ef5be759.png)

### Actual behavior:
We have partial dependencies (missing lodash, algolia etc).

In following screenshot, api-cp is a bash copy of the apps/api folder and api-bundle is the result of pnpm deploy command
![image](https://user-images.githubusercontent.com/99755384/226996655-0c81dd35-043f-4de7-a77e-d4eeccb1af20.png)

### Additional information:
Maybe it is related to this discussion : https://github.com/pnpm/pnpm/discussions/5326
But we didn't found any command/combination of parameters to be able to create a complete artifact.

It works fine using Yarn workspaces and adding nohoist in the apps/api package.json.
"workspaces": {
      "nohoist": ["**"]
    }

Thanks a LOT for your help. Because right now we have to stop our pnpm migration and manage deployments using Yarn.

**Comment by zkochan** [comment]
There is a [deploy command](https://pnpm.io/cli/deploy)

Also, if azure doesn't work with symlinks, use `--config.node-linker=hoisted`

**Comment by mm-edtake** [comment]
Yes, indeed. That's what we tried : node-linker=hoisted & deploy command. And the result is "api-bundle" in my screenshot.

Here is the sequence in the pipeline :
- pnpm config set node-linker hoisted
- pnpm install
- pnpm --filter=api deploy $(Build.ArtifactStagingDirectory)/api-bundle

**Comment by mrabdibdi-anvil** [comment]
Hi,

I have the same issue using AWS Lambda (with Serverless Framework)

**The goal**: Archive the whole function (source code, package.json, node_modules) and preferably only the required node_modules/ for one particular lambda, otherwise it busts the AWS size Limit (don't know if there is the same limitation with azure)

Workaround-ish:
Currently using a plugin to build a layer (serverles-layer); This is the only way I was able to proceed. 
The flow is: 
1. Running the `npm install` command in the directory created by the deploy command. 
2. Package everything
But to do so I had to publish my package (in this case it is GitHub repository private)

But now I moved a library to use the `workspace:*` to get the full power of PNPM with a monorepo and avoid publishing packages; and the workaround doesn't work anymore because it is looking in the npm registry to install it (it override the workspace:* with a version in the pruned/package.json).

Commands:
```
pnpm --filter=@foo/app \
--node-linker=hoisted \
--prod \
deploy pruned

cd pruned
npm install
```
> It works when the libraries are published (private or public, just need to configure the .npmrc)
> Otherwise it don't .. 

if possible:
flatten the dependencies in the `pruned` directory to be able to zip everything at once 🤷 In the past I struggled a lot with the symlink thing and unfortunately I don't have access to what has been done to fix the issue properly.

Thank you !

**Comment by vtereshyn** [comment]
I am facing the same issue as well. I have tried pretty much everything: bundlers, copying root `node_modules` to the package, deploy package using pnpm command, building in Docker, but I still have such problem

**Comment by rgripper** [comment]
Here is an example of a workaround using a custom github action with a node file
https://github.com/rgripper/pnpm-hoisting-workaround/tree/main

**Comment by ameinhardt** [comment]
Another solution could be to exclude all dependencies when bundling and then use Azure oryx remote build to install prod dependencies (but not build again). For that, I use the following settings in my Function App Configuration:
```env
# required for function model v4
AzureWebJobsFeatureFlags=EnableWorkerIndexing
AzureWebJobsStorage=DefaultEndpointsProtocol=https;AccountName=...
FUNCTIONS_EXTENSION_VERSION=~4
FUNCTIONS_WORKER_RUNTIME=node
# use remote build / oryx
SCM_DO_BUILD_DURING_DEPLOYMENT=true
ENABLE_ORYX_BUILD=true
# skip npm build, just install
CUSTOM_BUILD_COMMAND=npm install --omit=dev
ORYX_APP_TYPE=functions
```
Custom packaging the app/functions from my monorepo's package works with regular shell:
```bash
export $(grep -vEh "^(#.*|(.*=)?s*)$" .env .env.local 2&>/dev/null)  1&>/dev/null
zip - $(ls package*.json host.json && find dist) | curl -u "$USER:$PASSWORD" -N --no-keepalive --data-binary "@-" https://$NAME.scm.azurewebsites.net/api/zipdeploy?isAsync=true&author=myCustomDeploy
```

**Comment by joe-gre** [comment]
I have the same problem @mrabdibdi-anvil has with packaging for AWS lambda. I have code for multiple lambda functions in a  monorepo. I need to zip each lambda and upload the zip to AWS. However, when using the deploy command the resulting node_modules is 3 times the size of node_modules produced with `npm install` because it has code from other projects in the monorepo. This exceeds the 50MB direct upload size limit for lambdas, and the additional dependencies are not expected from the deploy command. Currently I'm using `npm install` to package before zipping, but this isn't suitable for production because it doesn't use `pnpm-lock.yaml`.

I tried using this command with various options: `pnpm --filter=<lambda package name> --prod deploy`. When using the options ` --node-linker=hoisted` or `--config.node-linker=hoisted` deploy fails with the below error on both Windows and Linux:

```
Progress: resolved 1600, reused 1586, downloaded 6, added 800
  ERROR  localLocations is not iterable (cannot read property undefined)
 pnpm: localLocations is not iterable (cannot read property undefined)
     at /usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:113882:45
     at Array.forEach (<anonymous>)
     at extendProjectsWithTargetDirs (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:113874:47)
     at headlessInstall (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:183791:83)
     at async installInContext (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:190938:29)
     at async _install (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:190459:25)
     at async mutateModules (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:190137:23)
     at async recursive (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:191796:50)
     at async installDeps (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:192092:11)
     at async Object.handler [as deploy] (/usr/local/lib/node_modules/pnpm/dist/pnpm.cj
```

@zkochan it seems the hoisted option for `pnpm deploy` doesn't work. Also `pnpm deploy` itself doesn't work properly with monorepos as it produces `node_modules` with dependencies for all projects in the monorepo.

**Comment by joe-gre** [comment]
After trying more I still cannot get deploy working properly. I was able to get deploy to build with only one package's dependencies by copying the workspace into another repo, only including the single project I want to build and without including the root package.json to prevent it form installing the devDependencies I had there. I zipped the result and uploaded to AWS Lambda. However the links were broken after Lambda extracted the zip, and it failed execution.

Using this same minimal workspace structure with only one repo, I tried running `pnpm --filter=my-lambda --prod deploy ./output --config.node-linker=hoisted` and also setting `node-linker=hoisted` in .npmrc. It didn't fail but resulted in a near empty node_modules folder as seen below in `output`
![image](https://github.com/pnpm/pnpm/assets/22748761/42ef0da7-97fc-46ae-ad2a-904030c4738b)

I cannot find any workaround for this. I need a way to produce a node_modules without any links for only one package in a workspace. Without this I cannot deploy AWS Lambda functions.

**Comment by joe-gre** [comment]
@jpgrace I saw the same behavior with `pnpm install`.

Also I tried `pnpm install --prod --frozen-lockfile` with `node-linker=hoisted` in .npmrc after deleting node_modules, and it results in flat node_modules without links. However all dependencies are installed in the root., and it installs all dependencies in `pnpm-lock.yaml` instead of dependencies for only a single project even when I try this in a folder stripped of all but one project with `--filter=...`. I need it to install only dependencies for a single project without links.

**Comment by dylanjt** [comment]
Ran into these issues when building out some Lambda deployments from our Turbo-managed monorepo. Ended up using webpack to bypass pnpm and bundle everything (including relevant node_modules deps) into a single `dist/index.js` file. This approach resulted in its own downsides, a confluence of the noted pnpm shortcomings + Lambda payload constraints + Prisma production expectations, and long story short my CI now runs `sed` against my webpack bundle before deployment ☹️.

Definitely keeping an eye on this issue in hopes that pnpm can build a "normal"/npm-equivalent node_modules folder for a particular package in a workspace. Pnpm is great! But this issue is very frustrating.

**Comment by prenaissance** [comment]
A boring an suboptimal solution I used is runnning the function app in a docker container. This obviously voids some of the benefits. Here's my Dockerfile:
```Dockerfile
FROM node:18-bookworm AS base
RUN apt-get update
RUN apt-get install libc6 -y
RUN corepack enable
RUN npm add -g turbo@1.10.7

FROM base AS prune
COPY . .
RUN turbo prune --scope=scrapers --scope=db --docker

FROM base as installer
WORKDIR /app
COPY .gitignore .gitignore
COPY --from=prune /out/json/ .
COPY --from=prune /out/pnpm-lock.yaml /out/pnpm-workspace.yaml ./
RUN pnpm install --frozen-lockfile --shamefully-hoist

COPY --from=prune /out/full/ .
RUN turbo run build --filter=scrapers


FROM mcr.microsoft.com/azure-functions/node:4-node18 AS runner
RUN corepack enable
WORKDIR /home/site/wwwroot
COPY --from=installer app/apps/scrapers/ .
COPY --from=installer app/node_modules/ ./node_modules/
RUN pnpm prune --prod

ENV WEBSITES_ENABLE_APP_SERVICE_STORAGE=false \
    AzureWebJobsScriptRoot=/home/site/wwwroot \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true
```

**Comment by Falven** [comment]
> There is a [deploy command](https://pnpm.io/cli/deploy)
> 
> Also, if azure doesn't work with symlinks, use `--config.node-linker=hoisted`

The deploy command bundles ALL of the modules of the workspace, which in my case was 10GB of modules. Not just the modules needed by the one app. This does not work for the vast majority of cases.

**Comment by mm-edtake** [comment]
> > There is a [deploy command](https://pnpm.io/cli/deploy)
> > Also, if azure doesn't work with symlinks, use `--config.node-linker=hoisted`
> 
> The deploy command bundles ALL of the modules of the workspace, which in my case was 10GB of modules. Not just the modules needed by the one app. This does not work for the vast majority of cases.

node-linker=hoisted breaks the deploy command actually... (#6682)
So it is not a solution at all.

Right now, we copy the complete set of node_modules in a dist folder. We will have to consider leaving pnpm next year because the result is a 4GB artifact to deploy!!!!

**Comment by Falven** [comment]
> > > There is a [deploy command](https://pnpm.io/cli/deploy)
> > > Also, if azure doesn't work with symlinks, use `--config.node-linker=hoisted`
> > 
> > 
> > The deploy command bundles ALL of the modules of the workspace, which in my case was 10GB of modules. Not just the modules needed by the one app. This does not work for the vast majority of cases.
> 
> node-linker=hoisted breaks the deploy command actually... (#6682) So it is not a solution at all.
> 
> Right now, we copy the complete set of node_modules in a dist folder. Unfortunatly, we will have to consider leaving pnpm next year because the result is a 4GB artifact to deploy!!!!

We’re currently using npm within the package and ignoring the monorepo just for deployment. It works but it’s complicated and slow and prone to errors.

**Comment by kyle-johnson** [comment]
For the folks using AWS Lambda (@mrabdibdi-anvil @rgripper @joe-gre @jpgrace), perhaps you just need to tell `zip` to preserve symlinks?

This works for me in a pnpm v8.7.4 workspace. My lambda requires both third-party dependencies and dependencies in the pnpm workspace (eg `"dependencies": { "local-dep": "workspace:*", "lodash": "4.17.21" }`). I'm using pnpm's default symlinking strategy, no hoisting/copying:

```shell
  cd lambdas/my-lambda && \
  pnpm --filter {.}... install && \
  pnpm --filter {.}... build && \
  pnpm --filter {.} --prod --no-optional deploy lambda/ && \
  cd lambda/ && \
  zip --symlinks -r ../lambda.zip . && \
  cd .. && \
  aws lambda update-function-code --function-name my-function --zip-file fileb://lambda.zip
```

Without `--symlinks` passed to `zip`, I get similar errors as reported throughout this issue.

**Comment by rgripper** [comment]
Pnpm has changed `deploy` behaviour recently, turning workspace references into regular non dependencies, assuming that workspaces were published separately. This is a weird default. Anyways, this has nothing to do with symlinks in my case.

**Comment by Falven** [comment]
> For the folks using AWS Lambda (@mrabdibdi-anvil @rgripper @joe-gre @jpgrace), perhaps you need to tell `zip` to preserve symlinks?
> 
> This works for me in a pnpm v8.7.4 workspace. My lambda requires both third-party dependencies and dependencies in the pnpm workspace (eg `"dependencies": { "local-dep": "workspace:*", "lodash": "4.17.21" }`). I'm using pnpm's default symlinking strategy, no hoisting/copying:
> 
> ```shell
>   cd lambdas/my-lambda && \
>   pnpm --filter {.}... install && \
>   pnpm --filter {.}... build && \
>   pnpm --filter {.} --prod --no-optional deploy lambda/ && \
>   cd lambda/ && \
>   zip --symlinks -r ../lambda.zip . && \
>   cd .. && \
>   aws lambda update-function-code --function-name my-function --zip-file fileb://lambda.zip
> ```
> 
> Without `--symlinks` passed to `zip`, I get similar errors as reported throughout this issue.

Going to try this for my AZ function as well, I am thinking this may be the issue, because my AZ Func project works with the core tools with symlinks.

**Comment by Falven** [comment]
I've done some more research for those of you here for Azure Functions.
Windows does not support Zipping of symlinks as on NTFS they are 0 byte files and the link information is not stored in the file itself. TAR and WIM files support maintaining symlink metadata. Azure functions only support Zip deployments. So if you are running on a Linux host and you zip from Linux, ensuring to tell your zip client of choice to maintain symlinks, it may work. But I haven't tested. So the only recourse for Windows-based function apps is the traditional, flat, `node_modules` directory. Which should be supported by PNPM if `node-linker=hoisted` and `pnpm deploy`.

**Comment by bm77525-kr** [comment]
Looks like the deploy command with `node-linker=hoisted` is finally fixed in v9.11 with this PR: https://github.com/pnpm/pnpm/pull/8525

**Comment by ameinhardt** [comment]
I have just created [resolve-pkglock](https://www.npmjs.com/package/resolve-pkglock) ([github](https://github.com/ameinhardt/resolve-pkglock)) to make use of [module.registerHooks](https://nodejs.org/api/module.html#moduleregisterhooksoptions) and `pnpm-lock.yaml` to skip all symlinks after calling the exported default function with the base directory.
Works for me to deploy my pnpm monorepo on azure app service. Let me know if that help you, too

**Comment by zkochan** [comment]
This is implemented in current pnpm, so closing.

`pnpm deploy` builds a self-contained directory, and `--node-linker hoisted` makes it a flat node_modules suitable for zipping into a serverless artifact.

If you still hit this on the latest pnpm, please comment with a reproduction and we will reopen.

---
Written by an agent (Claude Code, claude-opus-5).

**Comment by ameinhardt** [comment]
@zkochan: Why not follow up on the registerHook idea, so that it does not have to be hoisted?

**Comment by zkochan** [comment]
As I said, the original issue is resolved using the most compatible way possible. I was also thinking about custom module loaders. We can discuss that in a dedicated issue or discussion if you want.
