### ISSUE TITLE
Improve error message of Invalid Version to reference the affected package

### ISSUE THREAD

**Issue by gajus** [pnpm/pnpm#6267]
### Actual behavior:

```
pnpm: Invalid Version:
    at new SemVer (/Users/gajus/Library/pnpm/global/5/.pnpm/pnpm@7.30.1/node_modules/pnpm/dist/pnpm.cjs:42382:17)
    at compare (/Users/gajus/Library/pnpm/global/5/.pnpm/pnpm@7.30.1/node_modules/pnpm/dist/pnpm.cjs:42661:36)
    at Object.gte (/Users/gajus/Library/pnpm/global/5/.pnpm/pnpm@7.30.1/node_modules/pnpm/dist/pnpm.cjs:42822:32)
    at updateParentRefs (/Users/gajus/Library/pnpm/global/5/.pnpm/pnpm@7.30.1/node_modules/pnpm/dist/pnpm.cjs:185944:46)
    at createPkgsByName (/Users/gajus/Library/pnpm/global/5/.pnpm/pnpm@7.30.1/node_modules/pnpm/dist/pnpm.cjs:185686:9)
    at resolvePeers (/Users/gajus/Library/pnpm/global/5/.pnpm/pnpm@7.30.1/node_modules/pnpm/dist/pnpm.cjs:185585:14)
    at resolveDependencies (/Users/gajus/Library/pnpm/global/5/.pnpm/pnpm@7.30.1/node_modules/pnpm/dist/pnpm.cjs:186753:126)
    at async _installInContext (/Users/gajus/Library/pnpm/global/5/.pnpm/pnpm@7.30.1/node_modules/pnpm/dist/pnpm.cjs:189833:238)
    at async installInContext (/Users/gajus/Library/pnpm/global/5/.pnpm/pnpm@7.30.1/node_modules/pnpm/dist/pnpm.cjs:190154:16)
    at async _install (/Users/gajus/Library/pnpm/global/5/.pnpm/pnpm@7.30.1/node_modules/pnpm/dist/pnpm.cjs:189689:25)
```

It is not clear which package this even refers to.

I tried adding debug statements in various places across the codebase:

```
{
  name: '@contra/eslint-config',
  pkg: {
    alias: undefined,
    depth: 0,
    version: undefined,
    nodeId: 'link:packages/eslint-config-contra'
  }
}
```

It looks like it is referring to an internal workspace.

Since it is an internal package, it does not have `version` property.

Adding a dummy `"version": "0.0.0"` fixes the problem.

A better error reporting for this is needed.

### Additional information:

 - `node -v` prints: v19.8.1
 - Windows, macOS, or Linux?: MacOS

**Comment by pawelshopstory** [comment]
@gajus Was hitting a wall because of the same reason. Thank you for workaround!

**Comment by jorgezreik** [comment]
This seems to be a bug introduced in `7.30.1`.  An upgrade to `7.30.3` fixed this issue for me.

It took a while to upgrade as well since the `homebrew` version of pnpm is still `7.30.1` even though `7.30.3` released a few hours ago.

**Comment by zkochan** [comment]
This no longer reproduces on current pnpm, so closing.

Current pnpm names the offending package and the invalid range in the error, so an "Invalid Version" failure can be traced to its source.

If you still hit this on the latest pnpm, please comment with a reproduction and we will reopen.

---
Written by an agent (Claude Code, claude-opus-5).
