### ISSUE TITLE
pnpm strapi build issue - Module not found

### ISSUE THREAD

**Issue by aussieboi** [pnpm/pnpm#6366]
### pnpm version:
v.8.1.1 

### Code to reproduce the issue:
I demo repo - https://github.com/aussieboi/strapi-pnpm-monorepo
but here is working fine in my poject throw error shown bottom.

npm is working fine but any way to pnpm behave like npm - even with `node-linker=hoisted`
didn't work. 

### Expected behavior:
pnpm strapi build  should have normal output

``` 

> @demo/strapi@0.1.0 build /Users/mboskovic/Code/@aussieboi/strapi-pnpm-monorepo/apps/strapi-test
> strapi build

Starting the compilation for TypeScript files in /Users/mboskovic/Code/@aussieboi/strapi-pnpm-monorepo/apps/strapi-test
Building your admin UI with development configuration...

✔ Webpack
  Compiled successfully in 7.11s

Admin UI built successfully
```

### Actual behavior:
```

ModuleNotFoundError: Module not found: Error: Package path ./lib/maps/entities.json is not exported from package /Users/abo/Code/demo/node_modules/entities (see exports field in /Users/abo/Code/demo/node_modules/entities/package.json)
    at /Users/abo/Code/demo/node_modules/.pnpm/webpack@5.78.0_webpack-cli@5.0.1/node_modules/webpack/lib/Compilation.js:2016:28
    at /Users/abo/Code/demo/node_modules/.pnpm/webpack@5.78.0_webpack-cli@5.0.1/node_modules/webpack/lib/NormalModuleFactory.js:805:13
    at eval (eval at create (/Users/abo/Code/demo/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Users/abo/Code/demo/node_modules/.pnpm/webpack@5.78.0_webpack-cli@5.0.1/node_modules/webpack/lib/NormalModuleFactory.js:272:22
    at eval (eval at create (/Users/abo/Code/demo/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/abo/Code/demo/node_modules/.pnpm/webpack@5.78.0_webpack-cli@5.0.1/node_modules/webpack/lib/NormalModuleFactory.js:436:22
    at /Users/abo/Code/demo/node_modules/.pnpm/webpack@5.78.0_webpack-cli@5.0.1/node_modules/webpack/lib/NormalModuleFactory.js:118:11
    at /Users/abo/Code/demo/node_modules/.pnpm/webpack@5.78.0_webpack-cli@5.0.1/node_modules/webpack/lib/NormalModuleFactory.js:677:25
    at /Users/abo/Code/demo/node_modules/.pnpm/webpack@5.78.0_webpack-cli@5.0.1/node_modules/webpack/lib/NormalModuleFactory.js:881:8
    at /Users/abo/Code/demo/node_modules/.pnpm/webpack@5.78.0_webpack-cli@5.0.1/node_modules/webpack/lib/NormalModuleFactory.js:1001:5
    at /Users/abo/Code/demo/node_modules/.pnpm/neo-async@2.6.2/node_modules/neo-async/async.js:6883:13
    at /Users/abo/Code/demo/node_modules/.pnpm/webpack@5.78.0_webpack-cli@5.0.1/node_modules/webpack/lib/NormalModuleFactory.js:984:45
    at finishWithoutResolve (/Users/abo/Code/demo/node_modules/.pnpm/enhanced-resolve@5.12.0/node_modules/enhanced-resolve/lib/Resolver.js:312:11)
    at /Users/abo/Code/demo/node_modules/.pnpm/enhanced-resolve@5.12.0/node_modules/enhanced-resolve/lib/Resolver.js:386:15
    at /Users/abo/Code/demo/node_modules/.pnpm/enhanced-resolve@5.12.0/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/abo/Code/demo/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Users/abo/Code/demo/node_modules/.pnpm/enhanced-resolve@5.12.0/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/abo/Code/demo/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /Users/abo/Code/demo/node_modules/.pnpm/enhanced-resolve@5.12.0/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:87:43
    at /Users/abo/Code/demo/node_modules/.pnpm/enhanced-resolve@5.12.0/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/abo/Code/demo/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Users/abo/Code/demo/node_modules/.pnpm/enhanced-resolve@5.12.0/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/abo/Code/demo/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /Users/abo/Code/demo/node_modules/.pnpm/enhanced-resolve@5.12.0/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/abo/Code/demo/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /Users/abo/Code/demo/node_modules/.pnpm/enhanced-resolve@5.12.0/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/abo/Code/demo/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /Users/abo/Code/demo/node_modules/.pnpm/enhanced-resolve@5.12.0/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:87:43
    at /Users/abo/Code/demo/node_modules/.pnpm/enhanced-resolve@5.12.0/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/abo/Code/demo/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /Users/abo/Code/demo/node_modules/.pnpm/enhanced-resolve@5.12.0/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/abo/Code/demo/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Users/abo/Code/demo/node_modules/.pnpm/enhanced-resolve@5.12.0/node_modules/enhanced-resolve/lib/DirectoryExistsPlugin.js:41:15
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)
ModuleNotFoundError: Module not found: Error: Package path ./lib/maps/entities.json is not exported from package /Users/abo/Code/demo/node_modules/entities (see exports field in /Users/abo/Code/demo/node_modules/entities/package.json)
    at /Users/abo/Code/demo/node_modules/.pnpm/webpack@5.78.0_webpack-cli@5.0.1/node_modules/webpack/lib/Compilation.js:2016:28
    at /Users/abo/Code/demo/node_modules/.pnpm/webpack@5.78.0_webpack-cli@5.0.1/node_modules/webpack/lib/NormalModuleFactory.js:805:13
    at eval (eval at create (/Users/abo/Code/demo/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Users/abo/Code/demo/node_modules/.pnpm/webpack@5.78.0_webpack-cli@5.0.1/node_modules/webpack/lib/NormalModuleFactory.js:272:22
    at eval (eval at create (/Users/abo/Code/demo/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/abo/Code/demo/node_modules/.pnpm/webpack@5.78.0_webpack-cli@5.0.1/node_modules/webpack/lib/NormalModuleFactory.js:436:22
    at /Users/abo/Code/demo/node_modules/.pnpm/webpack@5.78.0_webpack-cli@5.0.1/node_modules/webpack/lib/NormalModuleFactory.js:118:11
    at /Users/abo/Code/demo/node_modules/.pnpm/webpack@5.78.0_webpack-cli@5.0.1/node_modules/webpack/lib/NormalModuleFactory.js:677:25
    at /Users/abo/Code/demo/node_modules/.pnpm/webpack@5.78.0_webpack-cli@5.0.1/node_modules/webpack/lib/NormalModuleFactory.js:881:8
    at /Users/abo/Code/demo/node_modules/.pnpm/webpack@5.78.0_webpack-cli@5.0.1/node_modules/webpack/lib/NormalModuleFactory.js:1001:5
    at /Users/abo/Code/demo/node_modules/.pnpm/neo-async@2.6.2/node_modules/neo-async/async.js:6883:13
    at /Users/abo/Code/demo/node_modules/.pnpm/webpack@5.78.0_webpack-cli@5.0.1/node_modules/webpack/lib/NormalModuleFactory.js:984:45
    at finishWithoutResolve (/Users/abo/Code/demo/node_modules/.pnpm/enhanced-resolve@5.12.0/node_modules/enhanced-resolve/lib/Resolver.js:312:11)
    at /Users/abo/Code/demo/node_modules/.pnpm/enhanced-resolve@5.12.0/node_modules/enhanced-resolve/lib/Resolver.js:386:15
    at /Users/abo/Code/demo/node_modules/.pnpm/enhanced-resolve@5.12.0/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/abo/Code/demo/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Users/abo/Code/demo/node_modules/.pnpm/enhanced-resolve@5.12.0/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/abo/Code/demo/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /Users/abo/Code/demo/node_modules/.pnpm/enhanced-resolve@5.12.0/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:87:43
    at /Users/abo/Code/demo/node_modules/.pnpm/enhanced-resolve@5.12.0/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/abo/Code/demo/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Users/abo/Code/demo/node_modules/.pnpm/enhanced-resolve@5.12.0/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/abo/Code/demo/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /Users/abo/Code/demo/node_modules/.pnpm/enhanced-resolve@5.12.0/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/abo/Code/demo/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /Users/abo/Code/demo/node_modules/.pnpm/enhanced-resolve@5.12.0/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/abo/Code/demo/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /Users/abo/Code/demo/node_modules/.pnpm/enhanced-resolve@5.12.0/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:87:43
    at /Users/abo/Code/demo/node_modules/.pnpm/enhanced-resolve@5.12.0/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/abo/Code/demo/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /Users/abo/Code/demo/node_modules/.pnpm/enhanced-resolve@5.12.0/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/abo/Code/demo/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Users/abo/Code/demo/node_modules/.pnpm/enhanced-resolve@5.12.0/node_modules/enhanced-resolve/lib/DirectoryExistsPlugin.js:41:15
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)
```

### Additional information:

- strapi feedback - https://feedback.strapi.io/developer-experience/p/support-pnpm
- Related to https://github.com/strapi/strapi/issues/15511 

 - `node -v` prints: v18.15.0
 - macOS  - Apple M1 Max, Ventura 13.3

**Comment by await-ovo** [comment]
I can't reproduce the problem in the repository you provided:

```
$ pnpm run build 

> @demo/strapi@0.1.0 build /Users/Documents/test/test-pnpm/strapi-pnpm-monorepo/apps/strapi-test
> strapi build

Starting the compilation for TypeScript files in /Users/Documents/test/test-pnpm/strapi-pnpm-monorepo/apps/strapi-test
Building your admin UI with development configuration...

✔ Webpack
  Compiled successfully in 15.21s

Admin UI built successfully

$ pnpm -v        
8.1.1
```

**Comment by aussieboi** [comment]
I have updated repo to reflect more to my repo, now it is throwing that error, tnx for help

**Comment by smoothdvd** [comment]
I meet same error in my strapi project. I tried with ppm 8.1.1 and 8.2.0, all report same error.

**Comment by dzcpy** [comment]
Any updates?

**Comment by smoothdvd** [comment]
I am using packageExtensions to resolve this issue. https://github.com/strapi/strapi/issues/16684#issuecomment-1547108591

**Comment by zkochan** [comment]
Closing for lack of a reproduction on a supported version.

This is a package that reads files from a path it is not exported from, and the linked reproduction is three years old. Please open a new issue with a reproduction if it still fails on a current pnpm.

If you still hit this on the latest pnpm, please comment with a reproduction and we will reopen.

---
Written by an agent (Claude Code, claude-opus-5).
