### ISSUE TITLE
Native modules do not work with pnpm workspaces

### ISSUE THREAD

**Issue by Raynos** [pnpm/pnpm#6395]
### Code to reproduce the issue:

```
pnpm i farmhash
# or pnpm i @sematext/gc-stats
```

Then

```ts
import farmhash from 'farmhash';
console.log(farmhash.hash32('test'));
```

### Expected behavior:

To see a hash

### Actual behavior:

```
Error: Cannot find module './build/Debug/farmhash.node'
Require stack:
- /home/raynos/soundxyz/code/node_modules/.pnpm/farmhash@3.3.0/node_modules/farmhash/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at Function.Module._load (node:internal/modules/cjs/loader:804:27)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at farmhashBinding (/home/raynos/soundxyz/code/node_modules/.pnpm/farmhash@3.3.0/node_modules/farmhash/index.js:7:12)
    at Object.<anonymous> (/home/raynos/soundxyz/code/node_modules/.pnpm/farmhash@3.3.0/node_modules/farmhash/index.js:9:2)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Object.loader (/home/raynos/soundxyz/code/node_modules/.pnpm/bob-tsm@1.1.2_esbuild@0.15.15_typescript@4.9.3/node_modules/bob-tsm/require.js:72:12)
    at Module.load (node:internal/modules/cjs/loader:1004:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/raynos/soundxyz/code/node_modules/.pnpm/farmhash@3.3.0/node_modules/farmhash/index.js'
  ]
}
```

### Additional information:

 - `node -v` prints: 16.17
 - Windows, macOS, or Linux?: Linux

**Comment by Raynos** [comment]
A package like `leveldown` that uses https://www.npmjs.com/package/prebuildify Instead of https://www.npmjs.com/package/prebuild does work.

`pnpm` only seems to support native modules if they are in the npm artifact. 

I can see `leveldown` has prebuilts in the npm tarball ( https://www.npmjs.com/package/leveldown?activeTab=code ) and thats probably why it works.

**Comment by Raynos** [comment]
```sh
# .npmrc
enable-pre-post-scripts=true
strict-peer-dependencies=false
```

That setting is already enabled in the `.npmrc`

**Comment by weyert** [comment]
Then I don't know but I can inform that it also fails in pnpm 7.30.3

**Comment by zkochan** [comment]
It works for me on mac m1

**Comment by Raynos** [comment]
Let me try to make a minimal reproduction

**Comment by Raynos** [comment]
https://github.com/Raynos/pnpm-native-bug-example

Shit it works on my laptop too. It's some kind of issue with our npm / pnpm config in the monorepo ...

**Comment by Raynos** [comment]
![image](https://user-images.githubusercontent.com/479538/232156256-d9854965-a0cd-433a-8435-dd5f80a10690.png)

Ok something about our pnpm monorepo does not generate the `build` folder or run the scripts...

**Comment by Raynos** [comment]
I found `"onlyBuiltDependencies"` in our package.json ... None of my coworkers told me about this :facepalm:
