### ISSUE TITLE
workspace package's interal dependency load wrong

### ISSUE THREAD

**Issue by chwech** [pnpm/pnpm#6443]
### Code to reproduce the issue:
package.json
```
{
  "name": "bug-report",
  "version": "1.0.0",
  "dependencies": {
    "vue": "^3.2.45"
  }
}
```
packages/docs/package.json
```
{
  "name": "docs",
  "version": "1.0.0",
  "scripts": {
    "docs:dev": "vuepress dev docs"
  },
  "devDependencies": {
    "vuepress": "^1.8.2"
  }
}
```
pnpm-workapce.yaml
```
packages:
  - 'packages/*'
```
run:
1. `pnpm i`
2. `pnpm --filter docs docs:dev`

### Expected behavior:
run `pnpm --filter docs docs:dev` work

### Actual behavior:
```
E:\文档\pnpm-bug-report\node_modules\.pnpm\vue-server-renderer@2.7.14\node_modules\vue-server-renderer\index.js:8
  throw new Error(
  ^

Error:

Vue packages version mismatch:

- vue@3.2.47
- vue-server-renderer@2.7.14

This may cause things to work incorrectly. Make sure to use the same version for both.

    at Object.<anonymous> (E:\文档\pnpm-bug-report\node_modules\.pnpm\vue-server-renderer@2.7.14\node_modules\vue-server-renderer\index.js:8:9)   
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (E:\文档\pnpm-bug-report\node_modules\.pnpm\@vuepress+core@1.9.9\node_modules\@vuepress\core\lib\node\build\index.js:11:34)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (E:\文档\pnpm-bug-report\node_modules\.pnpm\@vuepress+core@1.9.9\node_modules\@vuepress\core\lib\node\App.js:21:22)     
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
E:\文档\pnpm-bug-report\packages\docs:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  docs@1.0.0 docs:dev: `vuepress dev docs`
Exit status 1
 ELIFECYCLE  Command failed with exit code 1.
```
docs workspace interal dependency load a wrong vue version.

### Additional information:

 - `node -v` prints: v16.13.1
 - Windows, macOS, or Linux?: Windows

**Comment by zkochan** [comment]
It is an issue with `vue-server-renderer`. It needs to have `vue` in peer dependencies. The newer version `@vue/server-renderer` actually had `vue` in peer dependencies.

You can use the next workaround. Put this to your root `package.json`:

```json
{
  "pnpm": {
    "packageExtensions": {
      "vue-server-renderer": {
        "peerDependencies": {
          "vue": "*"
        }
      }
    }
  }
}
```

Then run install.
