### ISSUE TITLE
pnpm 7 patch with lockfile v6 throws error

### ISSUE THREAD

**Issue by shreykavi** [pnpm/pnpm#6504]
### Steps to reproduce the issue: 
1. Install react 17.0.2 
2. Install react-dom 17.0.2
3. pnpm patch react-dom@17.0.2
4. `bzl run -- @pnpm//:pnpm --dir {insert dir} install --lockfile-only`

### Expected behavior:
Successfully installs patched react-dom dependency

### Actual behavior:
Throws:
```
ERROR  /react-dom/17.0.2_uspcv6sdfgpmtk3c7iccwypoym(react@17.0.2) is an invalid relative dependency path

pnpm: /react-dom/17.0.2_uspcv6sdfgpmtk3c7iccwypoym(react@17.0.2) is an invalid relative dependency path
    at Object.parse2 [as parse] (/private/var/tmp/_bazel_shreykavi/8e386c0a26c746746daa96bf924f81ba/execroot/__main__/bazel-out/darwin-fastbuild/bin/external/pnpm/pnpm.sh.runfiles/pnpm/package/dist/pnpm.cjs:109145:15)
    at convertOldDepPathToNewDepPath (/private/var/tmp/_bazel_shreykavi/8e386c0a26c746746daa96bf924f81ba/execroot/__main__/bazel-out/darwin-fastbuild/bin/external/pnpm/pnpm.sh.runfiles/pnpm/package/dist/pnpm.cjs:110125:32)
    at /private/var/tmp/_bazel_shreykavi/8e386c0a26c746746daa96bf924f81ba/execroot/__main__/bazel-out/darwin-fastbuild/bin/external/pnpm/pnpm.sh.runfiles/pnpm/package/dist/pnpm.cjs:110109:19
    at Array.map (<anonymous>)
    at convertToInlineSpecifiersFormat (/private/var/tmp/_bazel_shreykavi/8e386c0a26c746746daa96bf924f81ba/execroot/__main__/bazel-out/darwin-fastbuild/bin/external/pnpm/pnpm.sh.runfiles/pnpm/package/dist/pnpm.cjs:110101:79)
    at writeLockfile (/private/var/tmp/_bazel_shreykavi/8e386c0a26c746746daa96bf924f81ba/execroot/__main__/bazel-out/darwin-fastbuild/bin/external/pnpm/pnpm.sh.runfiles/pnpm/package/dist/pnpm.cjs:110356:167)
    at writeWantedLockfile (/private/var/tmp/_bazel_shreykavi/8e386c0a26c746746daa96bf924f81ba/execroot/__main__/bazel-out/darwin-fastbuild/bin/external/pnpm/pnpm.sh.runfiles/pnpm/package/dist/pnpm.cjs:110342:14)
    at async _installInContext (/private/var/tmp/_bazel_shreykavi/8e386c0a26c746746daa96bf924f81ba/execroot/__main__/bazel-out/darwin-fastbuild/bin/external/pnpm/pnpm.sh.runfiles/pnpm/package/dist/pnpm.cjs:190188:11)
    at async installInContext (/private/var/tmp/_bazel_shreykavi/8e386c0a26c746746daa96bf924f81ba/execroot/__main__/bazel-out/darwin-fastbuild/bin/external/pnpm/pnpm.sh.runfiles/pnpm/package/dist/pnpm.cjs:190245:16)
    at async _install (/private/var/tmp/_bazel_shreykavi/8e386c0a26c746746daa96bf924f81ba/execroot/__main__/bazel-out/darwin-fastbuild/bin/external/pnpm/pnpm.sh.runfiles/pnpm/package/dist/pnpm.cjs:189796:25)
```

### Additional information:
- This only happens when we use lockfile v6, we were able to temporarily solve this issue by downgrading our lockfile version

 - Windows, macOS, or Linux?: MacOS

**Comment by zkochan** [comment]
Does it happen with pnpm v8?

**Comment by dominikg** [comment]
getting this error when calling `pnpm install` in projects where node_modules does not exist (ci checkout or git clean), both when using `pnpm@8.5.0` or `pnpm@^7` in a project that has updated to 8.6.0.

example
```
    ' WARN  Your pnpm-lock.yaml was generated by a newer version of pnpm. It is a compatible version but it might get downgraded to version 6.0\n' +
    ' ERROR  /@babel/code-frame@7.18.6 is an invalid relative dependency path\n' +
    '\n' +
    'pnpm: /@babel/code-frame@7.18.6 is an invalid relative dependency path\n' +
    '    at Object.parse2 [as parse] (/home/dominikg/.local/share/pnpm/global/5/.pnpm/pnpm@8.5.1/node_modules/pnpm/dist/pnpm.cjs:114178:15)\n' +
    '    at nameVerFromPkgSnapshot (/home/dominikg/.local/share/pnpm/global/5/.pnpm/pnpm@8.5.1/node_modules/pnpm/dist/pnpm.cjs:114287:28)\n' +
    '    at addPreferredVersionsFromLockfile (/home/dominikg/.local/share/pnpm/global/5/.pnpm/pnpm@8.5.1/node_modules/pnpm/dist/pnpm.cjs:196837:89)\n' +
    '    at getPreferredVersionsFromLockfileAndManifests (/home/dominikg/.local/share/pnpm/global/5/.pnpm/pnpm@8.5.1/node_modules/pnpm/dist/pnpm.cjs:196831:7)\n' +
    '    at _installInContext (/home/dominikg/.local/share/pnpm/global/5/.pnpm/pnpm@8.5.1/node_modules/pnpm/dist/pnpm.cjs:197757:142)\n' +
    '    at async installInContext (/home/dominikg/.local/share/pnpm/global/5/.pnpm/pnpm@8.5.1/node_modules/pnpm/dist/pnpm.cjs:198099:16)\n' +
    '    at async _install (/home/dominikg/.local/share/pnpm/global/5/.pnpm/pnpm@8.5.1/node_modules/pnpm/dist/pnpm.cjs:197622:25)\n' +
    '    at async mutateModules (/home/dominikg/.local/share/pnpm/global/5/.pnpm/pnpm@8.5.1/node_modules/pnpm/dist/pnpm.cjs:197344:23)\n' +
    '    at async recursive (/home/dominikg/.local/share/pnpm/global/5/.pnpm/pnpm@8.5.1/node_modules/pnpm/dist/pnpm.cjs:198939:50)\n' +
    '    at async installDeps (/home/dominikg/.local/share/pnpm/global/5/.pnpm/pnpm@8.5.1/node_modules/pnpm/dist/pnpm.cjs:199235:11)',
```

**Comment by zkochan** [comment]
This is not related to this issue. pnpm v7.33 and pnpm v8.6 will work.

**Comment by zkochan** [comment]
This targets a part of pnpm that no longer exists, so closing.

This is pnpm 7 reading a lockfile 6.0 dependency path. Neither that version nor that lockfile format is in use any more.

If you still hit this on the latest pnpm, please comment with a reproduction and we will reopen.

---
Written by an agent (Claude Code, claude-opus-5).
