### ISSUE TITLE
pnpm install reports an error

### ISSUE THREAD

**Issue by githubmhj** [pnpm/pnpm#6533]
When using the command pnpm install to install the canvas package, it stays in the “Running install script” and reports an error after a long time

node_modules/.pnpm/canvas@2.11.2/node_modules/canvas: Running install script

**Comment by zkochan** [comment]
Try to run:

```
pnpm add canvas@2.11.2 node-gyp --reporter=append-only
```

Post the output if it fails.

**Comment by githubmhj** [comment]
![image](https://github.com/pnpm/pnpm/assets/70200081/96e5c023-569f-4e3a-975b-e5ba41da1e72)
I executed the statement and the situation shown in the figure shows why PNPM needs to execute the files in the package, and it is normal for NPM to install them

**Comment by zkochan** [comment]
Is that all the output? On my computer I got an error that says that "pixman" should be installed on the system.

**Comment by githubmhj** [comment]
At the beginning, I reported a lot of errors. After installing node gyp and Python 3, these were the only ones that went wrong

**Comment by dlarr** [comment]
Hello @githubmhj 

Did you overcome this problem ? I think I have the same :)

I guess it's related to my company proxy : 
`[2023-12-18T13:37:35.344Z] .../canvas@2.11.2/node_modules/canvas install: node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v108-linux-glibc-x64.tar.gz
[2023-12-18T13:37:35.653Z] .../canvas@2.11.2/node_modules/canvas install: node-pre-gyp ERR! install request to https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v108-linux-glibc-x64.tar.gz failed, reason: getaddrinfo ENOTFOUND github.com
...

[2023-12-18T13:37:36.271Z] .../canvas@2.11.2/node_modules/canvas install: gyp ERR! configure error 
[2023-12-18T13:37:36.271Z] .../canvas@2.11.2/node_modules/canvas install: gyp ERR! stack Error: This is most likely not a problem with node-gyp or the package itself and
[2023-12-18T13:37:36.271Z] .../canvas@2.11.2/node_modules/canvas install: gyp ERR! stack is related to network connectivity. In most cases you are behind a proxy or have bad 
[2023-12-18T13:37:36.271Z] .../canvas@2.11.2/node_modules/canvas install: gyp ERR! stack network settings.
 `

But then I have no workaround fo now

If you have any lead for overcome this, let me know ! :)

**Comment by dlarr** [comment]
Additional infos regarding this issue

Using npm install --legacy-peer-deps => npm ls canvas shows as empty

unsing pnpm install --shaemfully-hoist => npm ls canvas reports canvas being inside node_modules

Any infos why npm would not trigger canvas installation and pnpm does ?

**Comment by ChenKun1997** [comment]
> Is that all the output? On my computer I got an error that says that "pixman" should be installed on the system.

`$ pnpm add canvas@2.11.2 node-gyp --reporter=append-only
../..                                    | Progress: resolved 1, reused 0, downloaded 0, added 0
../..                                    |  WARN  deprecated eslint@8.57.1
../g6                                    |  WARN  deprecated hull.js@1.0.6
../..                                    | Progress: resolved 246, reused 0, downloaded 0, added 0
../..                                    | Progress: resolved 667, reused 0, downloaded 0, added 0
../..                                    | Progress: resolved 1015, reused 0, downloaded 0, added 0
../..                                    | Progress: resolved 1366, reused 0, downloaded 0, added 0
../..                                    | Progress: resolved 1859, reused 0, downloaded 0, added 0
../..                                    | Progress: resolved 2378, reused 0, downloaded 0, added 0
../..                                    | Progress: resolved 2744, reused 0, downloaded 0, added 0
 WARN  34 deprecated subdependencies found: @esbuild-kit/cjs-loader@2.4.4, @esbuild-kit/core-utils@3.3.2, @esbuild-kit/esm-loader@2.6.5, @floating-ui/react-dom-interactions@0.3.1, @humanwhocodes/config-array@0.13.0, @humanwhocodes/object-schema@2.0.3, @stylelint/postcss-css-in-js@0.38.0, abab@2.0.6, are-we-there-yet@2.0.0, axios@0.18.1, copy-concurrently@1.0.5, docsearch.js@2.6.3, domexception@4.0.0, fs-write-stream-atomic@1.0.10, gauge@3.0.2, glob@7.2.3, glob@8.1.0, har-validator@5.1.5, hast@1.0.0, inflight@1.0.6, mkdirp@0.3.0, move-concurrently@1.0.1, node-fetch-npm@2.0.4, npmlog@5.0.1, osenv@0.1.5, q@1.5.1, request@2.88.2, rimraf@2.7.1, rimraf@3.0.2, shortid@2.2.16, socks@1.1.10, source-map-resolve@0.6.0, stable@0.1.8, uuid@3.4.0
../..                                    | Progress: resolved 2765, reused 0, downloaded 0, added 0, done

dependencies:
+ node-gyp ^11.0.0

 WARN  Issues with peer dependencies found
packages/g6-extension-react
└─┬ @antv/react-g 2.0.31
  ├── ✕ unmet peer react@^16.13.1: found 18.3.1
  └─┬ react-reconciler 0.26.2
    └── ✕ unmet peer react@^17.0.2: found 18.3.1

packages/site
└─┬ @antv/dumi-theme-antv 0.5.5
  └─┬ react-split-pane 0.1.92
    ├── ✕ unmet peer react@^16.0.0-0: found 18.3.1
    └── ✕ unmet peer react-dom@^16.0.0-0: found 18.3.1

../..                                    | +965 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
.../node_modules/canvas install$ node-pre-gyp install --fallback-to-build --update-binary
.../node_modules/canvas install: node-pre-gyp info it worked if it ends with ok
.../node_modules/canvas install: node-pre-gyp info using node-pre-gyp@1.0.11
.../node_modules/canvas install: node-pre-gyp info using node@22.12.0 | win32 | x64
.../node_modules/canvas install: (node:9644) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
.../node_modules/canvas install: (Use `node --trace-deprecation ...` to show where the warning was created)
.../node_modules/canvas install: node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v127-win32-unknown-x64.tar.gz
.../node_modules/canvas install: node-pre-gyp ERR! install request to https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v127-win32-unknown-x64.tar.gz failed, reason: connect ETIMEDOUT 20.205.243.166:443
.../node_modules/canvas install: node-pre-gyp WARN Pre-built binaries not installable for canvas@2.11.2 and node@22.12.0 (node-v127 ABI, unknown) (falling back to source compile with node-gyp)
.../node_modules/canvas install: node-pre-gyp WARN Hit error request to https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v127-win32-unknown-x64.tar.gz failed, reason: connect ETIMEDOUT 20.205.243.166:443
.../node_modules/canvas install: gyp info it worked if it ends with ok
.../node_modules/canvas install: gyp info using node-gyp@10.2.0
.../node_modules/canvas install: gyp info using node@22.12.0 | win32 | x64
.../node_modules/canvas install: gyp info ok 
.../node_modules/canvas install: gyp info it worked if it ends with ok
.../node_modules/canvas install: gyp info using node-gyp@10.2.0
.../node_modules/canvas install: gyp info using node@22.12.0 | win32 | x64
.../node_modules/canvas install: gyp info find Python using Python version 3.13.1 found at "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\python.exe"
.../node_modules/canvas install: gyp info find VS using VS2022 (17.12.35527.113) found at:
.../node_modules/canvas install: gyp info find VS "C:\Program Files\Microsoft Visual Studio\2022\Community"
.../node_modules/canvas install: gyp info find VS run with --verbose for detailed information
.../node_modules/canvas install: gyp info spawn C:\Users\Administrator\AppData\Local\Programs\Python\Python313\python.exe
.../node_modules/canvas install: gyp info spawn args [
.../node_modules/canvas install: gyp info spawn args 'C:\\Users\\Administrator\\AppData\\Roaming\\nvm\\v22.12.0\\node_modules\\pnpm\\dist\\node_modules\\node-gyp\\gyp\\gyp_main.py',
.../node_modules/canvas install: gyp info spawn args 'binding.gyp',
.../node_modules/canvas install: gyp info spawn args '-f',
.../node_modules/canvas install: gyp info spawn args 'msvs',
.../node_modules/canvas install: gyp info spawn args '-I',
.../node_modules/canvas install: gyp info spawn args 'F:\\Demo\\G6\\node_modules\\.pnpm\\canvas@2.11.2_encoding@0.1.13\\node_modules\\canvas\\build\\config.gypi',
.../node_modules/canvas install: gyp info spawn args '-I',
.../node_modules/canvas install: gyp info spawn args 'C:\\Users\\Administrator\\AppData\\Roaming\\nvm\\v22.12.0\\node_modules\\pnpm\\dist\\node_modules\\node-gyp\\addon.gypi',
.../node_modules/canvas install: gyp info spawn args '-I',
.../node_modules/canvas install: gyp info spawn args 'C:\\Users\\Administrator\\AppData\\Local\\node-gyp\\Cache\\22.12.0\\include\\node\\common.gypi',
.../node_modules/canvas install: gyp info spawn args '-Dlibrary=shared_library',
.../node_modules/canvas install: gyp info spawn args '-Dvisibility=default',
.../node_modules/canvas install: gyp info spawn args '-Dnode_root_dir=C:\\Users\\Administrator\\AppData\\Local\\node-gyp\\Cache\\22.12.0',
.../node_modules/canvas install: gyp info spawn args '-Dnode_gyp_dir=C:\\Users\\Administrator\\AppData\\Roaming\\nvm\\v22.12.0\\node_modules\\pnpm\\dist\\node_modules\\node-gyp',
.../node_modules/canvas install: gyp info spawn args '-Dnode_lib_file=C:\\\\Users\\\\Administrator\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\22.12.0\\\\<(target_arch)\\\\node.lib',
.../node_modules/canvas install: gyp info spawn args '-Dmodule_root_dir=F:\\Demo\\G6\\node_modules\\.pnpm\\canvas@2.11.2_encoding@0.1.13\\node_modules\\canvas',
.../node_modules/canvas install: gyp info spawn args '-Dnode_engine=v8',
.../node_modules/canvas install: gyp info spawn args '--depth=.',
.../node_modules/canvas install: gyp info spawn args '--no-parallel',
.../node_modules/canvas install: gyp info spawn args '--generator-output',
.../node_modules/canvas install: gyp info spawn args 'F:\\Demo\\G6\\node_modules\\.pnpm\\canvas@2.11.2_encoding@0.1.13\\node_modules\\canvas\\build',
.../node_modules/canvas install: gyp info spawn args '-Goutput_dir=.'
.../node_modules/canvas install: gyp info spawn args ]
.../node_modules/canvas install: Warning: Missing input files:
.../node_modules/canvas install: C:\GTK\bin\libfontconfig-1.dll
.../node_modules/canvas install: C:\GTK\bin\libgthread-2.0-0.dll
.../node_modules/canvas install: C:\GTK\bin\libintl-8.dll
.../node_modules/canvas install: C:\GTK\bin\libpangoft2-1.0-0.dll
.../node_modules/canvas install: C:\GTK\bin\libpng14-14.dll
.../node_modules/canvas install: C:\GTK\bin\libexpat-1.dll
.../node_modules/canvas install: C:\GTK\bin\zlib1.dll
.../node_modules/canvas install: C:\GTK\bin\libcairo-2.dll
.../node_modules/canvas install: C:\GTK\bin\libpangocairo-1.0-0.dll
.../node_modules/canvas install: C:\GTK\bin\libpango-1.0-0.dll
.../node_modules/canvas install: C:\GTK\bin\libglib-2.0-0.dll
.../node_modules/canvas install: C:\GTK\bin\libgobject-2.0-0.dll
.../node_modules/canvas install: C:\GTK\bin\libgmodule-2.0-0.dll
.../node_modules/canvas install: C:\GTK\bin\libpangowin32-1.0-0.dll
.../node_modules/canvas install: C:\GTK\bin\libfreetype-6.dll
.../node_modules/canvas install: gyp info ok
.../node_modules/canvas install: gyp info it worked if it ends with ok
.../node_modules/canvas install: gyp info using node-gyp@10.2.0
.../node_modules/canvas install: gyp info using node@22.12.0 | win32 | x64
.../node_modules/canvas install: gyp info spawn C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe
.../node_modules/canvas install: gyp info spawn args [
.../node_modules/canvas install: gyp info spawn args 'build\\binding.sln',
.../node_modules/canvas install: gyp info spawn args '/clp:Verbosity=minimal',
.../node_modules/canvas install: gyp info spawn args '/nologo',
.../node_modules/canvas install: gyp info spawn args '/p:Configuration=Release;Platform=x64'
.../node_modules/canvas install: gyp info spawn args ]
.../node_modules/canvas install:   Backend.cc
.../node_modules/canvas install: F:\Demo\G6\node_modules\.pnpm\canvas@2.11.2_encoding@0.1.13\node_modules\canvas\src\backend\Backend.h(3,10): error C1083: 无法打开包括文件: “cairo.h”: No such file or directory [F:\Demo\G6\node_modules\.pnpm\canvas@2.11.2_encoding@0.1.13\node_modules\canvas\build\canvas.vcxproj]
.../node_modules/canvas install:   (编译源文件“../src/backend/Backend.cc”)
.../node_modules/canvas install:
.../node_modules/canvas install: gyp ERR! build error 
.../node_modules/canvas install: gyp ERR! stack Error: `C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
.../node_modules/canvas install: gyp ERR! stack at ChildProcess.<anonymous> (C:\Users\Administrator\AppData\Roaming\nvm\v22.12.0\node_modules\pnpm\dist\node_modules\node-gyp\lib\build.js:216:23)
.../node_modules/canvas install: gyp ERR! stack at ChildProcess.emit (node:events:524:28)
.../node_modules/canvas install: gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:293:12)
.../node_modules/canvas install: gyp ERR! System Windows_NT 10.0.22631
.../node_modules/canvas install: gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Administrator\\AppData\\Roaming\\nvm\\v22.12.0\\node_modules\\pnpm\\dist\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--update-binary" "--module=F:\\Demo\\G6\\node_modules\\.pnpm\\canvas@2.11.2_encoding@0.1.13\\node_modules\\canvas\\build\\Release\\canvas.node" "--module_name=canvas" "--module_path=F:\\Demo\\G6\\node_modules\\.pnpm\\canvas@2.11.2_encoding@0.1.13\\node_modules\\canvas\\build\\Release" "--napi_version=9" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v127"
.../node_modules/canvas install: gyp ERR! cwd F:\Demo\G6\node_modules\.pnpm\canvas@2.11.2_encoding@0.1.13\node_modules\canvas
.../node_modules/canvas install: gyp ERR! node -v v22.12.0
.../node_modules/canvas install: gyp ERR! node-gyp -v v10.2.0
.../node_modules/canvas install: gyp ERR! not ok
.../node_modules/canvas install: node-pre-gyp ERR! build error
.../node_modules/canvas install: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\Administrator\AppData\Roaming\nvm\v22.12.0\node_modules\pnpm\dist\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --update-binary --module=F:\Demo\G6\node_modules\.pnpm\canvas@2.11.2_encoding@0.1.13\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=F:\Demo\G6\node_modules\.pnpm\canvas@2.11.2_encoding@0.1.13\node_modules\canvas\build\Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v127' (1)
.../node_modules/canvas install: node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\Administrator\AppData\Roaming\nvm\v22.12.0\node_modules\pnpm\dist\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --update-binary --module=F:\Demo\G6\node_modules\.pnpm\canvas@2.11.2_encoding@0.1.13\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=F:\Demo\G6\node_modules\.pnpm\canvas@2.11.2_encoding@0.1.13\node_modules\canvas\build\Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v127' (1)
.../node_modules/canvas install: node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (F:\Demo\G6\node_modules\.pnpm\@mapbox+node-pre-gyp@1.0.11_encoding@0.1.13\node_modules\@mapbox\node-pre-gyp\lib\util\compile.js:89:23)
.../node_modules/canvas install: node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:524:28)
.../node_modules/canvas install: node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1101:16)
.../node_modules/canvas install: node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:304:5)
.../node_modules/canvas install: node-pre-gyp ERR! System Windows_NT 10.0.22631
.../node_modules/canvas install: node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "F:\\Demo\\G6\\node_modules\\.pnpm\\@mapbox+node-pre-gyp@1.0.11_encoding@0.1.13\\node_modules\\@mapbox\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build" "--update-binary"
.../node_modules/canvas install: node-pre-gyp ERR! cwd F:\Demo\G6\node_modules\.pnpm\canvas@2.11.2_encoding@0.1.13\node_modules\canvas
.../node_modules/canvas install: node-pre-gyp ERR! node -v v22.12.0
.../node_modules/canvas install: node-pre-gyp ERR! node-pre-gyp -v v1.0.11
.../node_modules/canvas install: node-pre-gyp ERR! not ok
.../node_modules/canvas install: Failed`

**Comment by zkochan** [comment]
Closing: this is not something pnpm can fix.

The canvas package builds native code that needs system libraries such as pixman; that build is the package's, not pnpm's.

If you still hit this on the latest pnpm, please comment with a reproduction and we will reopen.

---
Written by an agent (Claude Code, claude-opus-5).
