### ISSUE TITLE
pnpm info/show => internal error.

### ISSUE THREAD

**Issue by hajonnes** [pnpm/pnpm#6535]
### pnpm version:
8.3.1 and 8.5.0  

### Code to reproduce the issue:
I updated form 8.3.1 to 8.5.0 with ```pnpm add -g pnpm```.
I had the same problem in version 8.3.1 but I tried to update to see if the bug disappeared.
Without anything installed on version 8.5.0 I installed neovim with:

```
pnpm install -g neovim
Packages: +36
++++++++++++++++++++++++++++++++++++

/home/johannes/.local/share/pnpm/global/5:
+ neovim 4.10.1

Progress: resolved 37, reused 1, downloaded 36, added 36, done
Done in 3.6s

```

```
pnpm info neovim --jar                                    ✔  4s  
node:internal/errors:490
    ErrorCaptureStackTrace(err);
    ^

Error: spawnSync npm ENOENT
    at Object.spawnSync (node:internal/child_process:1117:20)
    at Object.spawnSync (node:child_process:871:24)
    at Function.spawnSync [as sync] (/usr/lib/node_modules/pnpm/dist/pnpm.cjs:23658:26)
    at runScriptSync (/usr/lib/node_modules/pnpm/dist/pnpm.cjs:123104:45)
    at runNpm (/usr/lib/node_modules/pnpm/dist/pnpm.cjs:123095:14)
    at runNpm (/usr/lib/node_modules/pnpm/dist/pnpm.cjs:216206:35)
    at async passThruToNpm (/usr/lib/node_modules/pnpm/dist/pnpm.cjs:216315:22)
    at async /usr/lib/node_modules/pnpm/dist/pnpm.cjs:216297:7 {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawnSync npm',
  path: 'npm',
  spawnargs: [ 'info', 'neovim', '--jar' ]
}

Node.js v19.9.0
```

#### Removed everything:
```
pnpm rm -g neovim
``` 

```
pnpm store prune
```

#### Try without any other code than from pnpm:

```
pnpm info --help
pnpm show
pnpm info
```
All shows:
```
pnpm show                                                      1 ✘ 
node:internal/errors:490
    ErrorCaptureStackTrace(err);
    ^

Error: spawnSync npm ENOENT
    at Object.spawnSync (node:internal/child_process:1117:20)
    at Object.spawnSync (node:child_process:871:24)
    at Function.spawnSync [as sync] (/usr/lib/node_modules/pnpm/dist/pnpm.cjs:23658:26)
    at runScriptSync (/usr/lib/node_modules/pnpm/dist/pnpm.cjs:123104:45)
    at runNpm (/usr/lib/node_modules/pnpm/dist/pnpm.cjs:123095:14)
    at runNpm (/usr/lib/node_modules/pnpm/dist/pnpm.cjs:216206:35)
    at async passThruToNpm (/usr/lib/node_modules/pnpm/dist/pnpm.cjs:216315:22)
    at async /usr/lib/node_modules/pnpm/dist/pnpm.cjs:216297:7 {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawnSync npm',
  path: 'npm',
  spawnargs: [ 'show' ]
}

Node.js v19.9.0
``` 

### Expected behavior:
First time I used those commands, so I do not know.

### Actual behavior:
pnpm show                                                      1 ✘ 
node:internal/errors:490
    ErrorCaptureStackTrace(err);
    ^

Error: spawnSync npm ENOENT
    at Object.spawnSync (node:internal/child_process:1117:20)
    at Object.spawnSync (node:child_process:871:24)
    at Function.spawnSync [as sync] (/usr/lib/node_modules/pnpm/dist/pnpm.cjs:23658:26)
    at runScriptSync (/usr/lib/node_modules/pnpm/dist/pnpm.cjs:123104:45)
    at runNpm (/usr/lib/node_modules/pnpm/dist/pnpm.cjs:123095:14)
    at runNpm (/usr/lib/node_modules/pnpm/dist/pnpm.cjs:216206:35)
    at async passThruToNpm (/usr/lib/node_modules/pnpm/dist/pnpm.cjs:216315:22)
    at async /usr/lib/node_modules/pnpm/dist/pnpm.cjs:216297:7 {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawnSync npm',
  path: 'npm',
  spawnargs: [ 'show' ]
}

Node.js v19.9.0

### Additional information:

- `node -v` prints:v19.9.0
- Windows, macOS, or Linux?:Linux, manjaro-xfce up to date.

**Comment by zkochan** [comment]
pnpm doesn't implement all the npm commands. Some are just passed through to npm. Install npm globally and it should work.
