### ISSUE TITLE
pnpm patch-commit raises git error ("permission denied" ) 

### ISSUE THREAD

**Issue by capybarahero** [pnpm/pnpm#6537]
### pnpm version:
`8.2.0` and `8.5.0`

### Code to reproduce the issue:
`pnpm patch <package>@<version> --edit-dir ./<path>/<to>/<temp>/folder`  

then 
`pnpm patch-commit ./<path>/<to>/<temp>/folder`

### Expected behavior:
Changes are patched correctly;

### Actual behavior:

```
 ERROR  Unable to diff directories. Make sure you have a recent version of 'git' available in PATH.
The following error was reported by 'git':
warning: unable to access '/.config/git/attributes': Permission denied

pnpm: Unable to diff directories. Make sure you have a recent version of 'git' available in PATH.
The following error was reported by 'git':
warning: unable to access '/.config/git/attributes': Permission denied
    at diffFolders (/home/capybarahero/.nvm/versions/node/v19.0.0/lib/node_modules/pnpm/dist/pnpm.cjs:206300:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.handler [as patch-commit] (/home/capybarahero/.nvm/versions/node/v19.0.0/lib/node_modules/pnpm/dist/pnpm.cjs:206250:28)
    at async /home/capybarahero/.nvm/versions/node/v19.0.0/lib/node_modules/pnpm/dist/pnpm.cjs:215818:21
    at async main (/home/capybarahero/.nvm/versions/node/v19.0.0/lib/node_modules/pnpm/dist/pnpm.cjs:215785:34)
    at async runPnpm (/home/capybarahero/.nvm/versions/node/v19.0.0/lib/node_modules/pnpm/dist/pnpm.cjs:216040:5)
    at async /home/capybarahero/.nvm/versions/node/v19.0.0/lib/node_modules/pnpm/dist/pnpm.cjs:216032:7
 ```

### Additional information:
- `which git` : `/usr/bin/git`
- `which pnpm` : `/home/capybarahero/.nvm/versions/node/v19.0.0/bin/pnpm`
- Tried different packages and edit-dir locations and experienced the same issue.

 - `node -v` prints: `v19.0.0`
 - Windows, macOS, or Linux?: `Linux`

**Comment by zouhangwithsweet** [comment]
I just find a way to fix it.

my steps:

- uninstall your current git
- `brew install git`
- `brew link --overwrite git`
you can try it.

**Comment by adlrew** [comment]
you can use cmd run this command.

**Comment by adlrew** [comment]
![image](https://github.com/pnpm/pnpm/assets/63297878/1dcf83d3-803f-40d8-a78f-7fb19476db8b)
