### ISSUE TITLE
use tarball in overrides doesn't work in linux

### ISSUE THREAD

**Issue by tjx666** [pnpm/pnpm#6542]
### pnpm version:

8.5.1

### Code to reproduce the issue:

[41ae442739fc6cf94d54b5e155c8a401a29a78ba](https://github.com/tjx666/pnpm-issue-registry/tree/41ae442739fc6cf94d54b5e155c8a401a29a78ba)

```bash
git clone git@github.com:tjx666/pnpm-issue-registry.git
git reset --hard 091c572a9c917a6a8344709c573aa93ec567f785
pnpm install
```

### Expected behavior:

can install deps success

### Actual behavior:

check github action: https://github.com/tjx666/pnpm-issue-registry/actions/runs/4978082075/jobs/8907928194

```
Packages: +1
+
Progress: resolved 1, reused 0, downloaded 1, added 0
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /home/runner/setup-pnpm/node_modules/.bin/store/v3
  Virtual store is at:             node_modules/.pnpm
 ERROR  /@registry.npmmirror.com/@gaoding/editor-sdk/-/editor-sdk-0.2.17.tgz is an invalid relative dependency path

pnpm: /@registry.npmmirror.com/@gaoding/editor-sdk/-/editor-sdk-0.2.17.tgz is an invalid relative dependency path
    at Object.parse2 [as parse] (/home/runner/setup-pnpm/node_modules/.pnpm/pnpm@8.5.1/node_modules/pnpm/dist/pnpm.cjs:114178:15)
    at convertOldDepPathToNewDepPath (/home/runner/setup-pnpm/node_modules/.pnpm/pnpm@8.5.1/node_modules/pnpm/dist/pnpm.cjs:115102:32)
    at convertOldRefToNewRef (/home/runner/setup-pnpm/node_modules/.pnpm/pnpm@8.5.1/node_modules/pnpm/dist/pnpm.cjs:115123:16)
    at mapValues (/home/runner/setup-pnpm/node_modules/.pnpm/pnpm@8.5.1/node_modules/pnpm/dist/pnpm.cjs:11523[9](https://github.com/tjx666/pnpm-issue-registry/actions/runs/4978082075/jobs/8907928194#step:7:10):24)
    at /home/runner/setup-pnpm/node_modules/.pnpm/pnpm@8.5.1/node_modules/pnpm/dist/pnpm.cjs:[11](https://github.com/tjx666/pnpm-issue-registry/actions/runs/4978082075/jobs/8907928194#step:7:12)5068:40
    at Array.map (<anonymous>)
    at convertToInlineSpecifiersFormat (/home/runner/setup-pnpm/node_modules/.pnpm/pnpm@8.5.1/node_modules/pnpm/dist/pnpm.cjs:115065:81)
    at writeLockfile (/home/runner/setup-pnpm/node_modules/.pnpm/pnpm@8.5.1/node_modules/pnpm/dist/pnpm.cjs:115334:[12](https://github.com/tjx666/pnpm-issue-registry/actions/runs/4978082075/jobs/8907928194#step:7:13)3)
    at writeCurrentLockfile (/home/runner/setup-pnpm/node_modules/.pnpm/pnpm@8.5.1/node_modules/pnpm/dist/pnpm.cjs:115328:[14](https://github.com/tjx666/pnpm-issue-registry/actions/runs/4978082075/jobs/8907928194#step:7:15))
    at async headlessInstall (/home/runner/setup-pnpm/node_modules/.pnpm/pnpm@8.5.1/node_modules/pnpm/dist/pnpm.cjs:182[16](https://github.com/tjx666/pnpm-issue-registry/actions/runs/4978082075/jobs/8907928194#step:7:17)9:11)
Error: Process completed with exit code 1.
```

### Additional information:

 - `node -v` prints: 18.16.0
 - Windows, macOS, or Linux?: Linux

**Comment by DevinDon** [comment]
Just use [this format url](https://github.com/pnpm/pnpm/blob/459945292f0cb4fff05e29b9106dd401722628e1/packages/dependency-path/test/index.ts#L61C13-L61C13), that is OK.

**Comment by dschmidt** [comment]
I'm trying to use https://repo.platform.here.com/artifactory/api/npm/maps-api-for-javascript/-/@here/maps-api-for-javascript-1.49.1.tgz and get the same error ... what would a workaround url for that look like?

**Comment by zkochan** [comment]
This no longer reproduces on current pnpm, so closing.

Verified on pnpm 12.5.1 on Linux: an override pointing at a tarball URL installs that tarball.

If you still hit this on the latest pnpm, please comment with a reproduction and we will reopen.

---
Written by an agent (Claude Code, claude-opus-5).
