### ISSUE TITLE
Error: Cannot read properties of undefined (reading 'jsxOptions')

### ISSUE THREAD

**Issue by donny-bras** [pnpm/pnpm#6573]
### Code to reproduce the issue:
- Clone the repo: `npx degit yannbf/mealdrop#theme-switcher-base mealdrop`
- `cd mealdrop`
- Install dependencies `pnpm install`
- Start Storybook `pnpm storybook`

### Expected behavior:
Should start storybook on port 6006.

### Actual behavior:
The following error appears.
```
> start-storybook -p 6006

info @storybook/react v6.5.3
info
info => Loading presets
info => Serving static files from ././public at /
info => Loading custom manager config
info Addon-docs: using MDX1
info => Loading Webpack configuration from `node_modules`
info => Removing existing JavaScript and TypeScript rules.
info => Loading custom manager config
WARN 🚨 Extraction error on src/docs/Introduction.stories.mdx: TypeError: Cannot read properties of undefined (reading 'jsxOptions')
WARN 🚨 Extraction error on src/docs/Introduction.stories.mdx: TypeError: Cannot read properties of undefined (reading 'jsxOptions')
WARN 🚨 Extraction error on src/docs/Colors.stories.mdx: TypeError: Cannot read properties of undefined (reading 'jsxOptions')
WARN 🚨 Extraction error on src/docs/Typography.stories.mdx: TypeError: Cannot read properties of undefined (reading 'jsxOptions')
/Users/sergey/Documents/Vscode_projects/storybook-test-dark-mode/storybook-test-dark-mode/mealdrop/node_modules/.pnpm/@storybook+mdx1-csf@1.0.1--canary.26.47c2c44.0_react@17.0.2/node_modules/@storybook/mdx1-csf/dist/index.js:73399
      return mdxOptions.jsxOptions ? transformJSXSync(output, mdxOptions.jsxOptions) : output;
                        ^

TypeError: Cannot read properties of undefined (reading 'jsxOptions')
    at Compiler (/Users/sergey/Documents/Vscode_projects/storybook-test-dark-mode/storybook-test-dark-mode/mealdrop/node_modules/.pnpm/@storybook+mdx1-csf@1.0.1--canary.26.47c2c44.0_react@17.0.2/node_modules/@storybook/mdx1-csf/dist/index.js:73399:25)
    at Function.stringify (/Users/sergey/Documents/Vscode_projects/storybook-test-dark-mode/storybook-test-dark-mode/mealdrop/node_modules/.pnpm/unified@9.2.0/node_modules/unified/index.js:354:12)
    at pipelineStringify (/Users/sergey/Documents/Vscode_projects/storybook-test-dark-mode/storybook-test-dark-mode/mealdrop/node_modules/.pnpm/unified@9.2.0/node_modules/unified/index.js:41:18)
    at wrapped (/Users/sergey/Documents/Vscode_projects/storybook-test-dark-mode/storybook-test-dark-mode/mealdrop/node_modules/.pnpm/trough@1.0.5/node_modules/trough/wrap.js:25:19)
    at next (/Users/sergey/Documents/Vscode_projects/storybook-test-dark-mode/storybook-test-dark-mode/mealdrop/node_modules/.pnpm/trough@1.0.5/node_modules/trough/index.js:57:24)
    at done (/Users/sergey/Documents/Vscode_projects/storybook-test-dark-mode/storybook-test-dark-mode/mealdrop/node_modules/.pnpm/trough@1.0.5/node_modules/trough/wrap.js:55:16)
    at done (/Users/sergey/Documents/Vscode_projects/storybook-test-dark-mode/storybook-test-dark-mode/mealdrop/node_modules/.pnpm/unified@9.2.0/node_modules/unified/index.js:35:7)
    at done (/Users/sergey/Documents/Vscode_projects/storybook-test-dark-mode/storybook-test-dark-mode/mealdrop/node_modules/.pnpm/unified@9.2.0/node_modules/unified/index.js:314:11)
    at next (/Users/sergey/Documents/Vscode_projects/storybook-test-dark-mode/storybook-test-dark-mode/mealdrop/node_modules/.pnpm/trough@1.0.5/node_modules/trough/index.js:59:14)
    at done (/Users/sergey/Documents/Vscode_projects/storybook-test-dark-mode/storybook-test-dark-mode/mealdrop/node_modules/.pnpm/trough@1.0.5/node_modules/trough/wrap.js:55:16)
 ELIFECYCLE  Command failed with exit code 1.
```
### Additional information:

 - `node -v` prints: v16.17.0
 - Windows, macOS, or Linux?: macOS
 - **Running the same commands with Yarn works out well.**

**Comment by zkochan** [comment]
Try with the `node-linker=hoisted` setting.

**Comment by zkochan** [comment]
Closing: this is not something pnpm can fix.

This is Storybook reading a config from a package it does not depend on. Please open a new issue if you can reproduce it with a current pnpm and current Storybook.

If you still hit this on the latest pnpm, please comment with a reproduction and we will reopen.

---
Written by an agent (Claude Code, claude-opus-5).
