### ISSUE TITLE
rollup works with npm and not pnpm when dependence ssh2

### ISSUE THREAD

**Issue by x-wink** [pnpm/pnpm#6610]
### pnpm version:
8.3.1
### Code to reproduce the issue:
https://github.com/x-wink/wink-sftp
### Expected behavior:
boundle successify
### Actual behavior:
got an error when boundle
```
[!] RollupError: Could not resolve "../build/Release/cpufeatures.node" from "../build/Release/cpufeatures.node?commonjs-external"
../build/Release/cpufeatures.node?commonjs-external
    at error (E:\WorkSpace\wink-sftp\node_modules\.pnpm\rollup@3.23.0\node_modules\rollup\dist\shared\rollup.js:278:30)
    at ModuleLoader.handleInvalidResolvedId (E:\WorkSpace\wink-sftp\node_modules\.pnpm\rollup@3.23.0\node_modules\rollup\dist\shared\rollup.js:24485:24)
    at E:\WorkSpace\wink-sftp\node_modules\.pnpm\rollup@3.23.0\node_modules\rollup\dist\shared\rollup.js:24447:26
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
### Additional information:
 - `node -v` prints: v18.16.0
 - Windows, macOS, or Linux?: Windows10
[ssh2 repled me](https://github.com/mscdex/ssh2/issues/1304) this isn't their problem,should be you
I think maybe cause by rollup?sry I don't known

**Comment by zkochan** [comment]
Try to add an `.npmrc` with:

```
node-linker=hoisted
```

in the root of the project. Then remove node_modules and run `pnpm install`.

**Comment by x-wink** [comment]
> Try to add an `.npmrc` with:
> 
> ```
> node-linker=hoisted
> ```
> 
> in the root of the project. Then remove node_modules and run `pnpm install`.

I did it,but doesn't work
maybe you can clone my repo to try it

**Comment by zkochan** [comment]
I get another error in your repo

```
❯ pnpm build

> @xwink/sftp@1.0.1 build /Users/zoltan/src/sandbox/wink-sftp
> tsc && rollup --bundleConfigAsCjs --config dist/rollup.config.js


/Users/zoltan/src/sandbox/wink-sftp/dist/src/index.js → dist/index.js...
[!] (plugin commonjs) RollupError: Unexpected character '�' (Note that you need plugins to import files that are not JavaScript)
node_modules/.pnpm/ssh2@1.13.0/node_modules/ssh2/lib/protocol/crypto/build/Release/sshcrypto.node (1:0)
1: ����
     ��(__TEXT��__text...
   ^
2: ��
3: �__unwind_info__TEXT��H���...
    at error (/Users/zoltan/src/sandbox/wink-sftp/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/shared/rollup.js:278:30)
    at Module.error (/Users/zoltan/src/sandbox/wink-sftp/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/shared/rollup.js:13958:16)
    at Module.tryParse (/Users/zoltan/src/sandbox/wink-sftp/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/shared/rollup.js:14679:25)
    at Module.setSource (/Users/zoltan/src/sandbox/wink-sftp/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/shared/rollup.js:14281:39)
    at ModuleLoader.addModuleSource (/Users/zoltan/src/sandbox/wink-sftp/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/shared/rollup.js:24277:20)


 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by x-wink** [comment]
maybe is operation system are diffrent?
but both cuase by `*.node` files.
do you have try to use `npm i`?
it only works with `npm` not `pnpm`.
```
E:\WorkSpace\wink-sftp>npm i
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

> @xwink/sftp@1.0.1 prepare
> husky install

husky - Git hooks installed

added 612 packages, and audited 613 packages in 2m

90 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

E:\WorkSpace\wink-sftp>pnpm build

> @xwink/sftp@1.0.1 build E:\WorkSpace\wink-sftp
> tsc && rollup --bundleConfigAsCjs --config dist/rollup.config.js


E:\WorkSpace\wink-sftp\dist\src\index.js → dist/index.js...
(!) Circular dependencies
node_modules/ssh2/lib/protocol/crypto.js -> node_modules/ssh2/lib/protocol/utils.js -> node_modules/ssh2/lib/protocol/constants.js -> node_modules/ssh2/lib/protocol/crypto.js
node_modules/ssh2/lib/protocol/kex.js -> node_modules/ssh2/lib/protocol/handlers.js -> node_modules/ssh2/lib/protocol/kex.js
created dist/index.js in 6.4s
```

**Comment by pchmn** [comment]
I found out that `install`  script of `cpu-features` (that build the package and create `build/Release/cpufeatures.node`)  is not run when installing with pnpm.
What I did as a workaround is adding a `postinstall` script in my `package.json` like that :
```json
{
  "scripts": {
    ...
    "postinstall": "if [ -d \"node_modules/cpu-features\" ]; then cd node_modules/cpu-features && pnpm i --ignore-workspace; fi"
  },
  ...
}

```

**Comment by Cat1007** [comment]
same issue + 1

**Comment by Cat1007** [comment]
got error when install
node_modules/.pnpm/cpu-features@0.0.10/node_modules/cpu-features: Running install script, failed in 1.4s (skipped as optional)

using npm i can fix

**Comment by zkochan** [comment]
Closing: this is not something pnpm can fix.

The bundler cannot resolve a prebuilt `.node` binary through a symlinked layout; that path is written by the package and has to be configured in the bundler.

If you still hit this on the latest pnpm, please comment with a reproduction and we will reopen.

---
Written by an agent (Claude Code, claude-opus-5).
