### ISSUE TITLE
node-linker=hoisted and shamefully-hoist=true can not be use same time

### ISSUE THREAD

**Issue by smoothdvd** [pnpm/pnpm#6620]
### Code to reproduce the issue:

.npmrc

```
node-linker=hoisted
shamefully-hoist=true
```

package.json
```
{
  "name": "strapi-app",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "devDependencies": {},
  "dependencies": {
    "@strapi/strapi": "4.10.7",
    "@strapi/plugin-users-permissions": "4.10.7",
    "@strapi/plugin-i18n": "4.10.7",
    "better-sqlite3": "8.0.1"
  },
  "peerDependencies": {
  },  
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "cdf7040f-fed7-4af4-a20e-f7750074f0d4"
  },
  "engines": {
    "node": ">=14.19.1 <=18.x.x",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}
```

pnpm i
pnpm build

### Expected behavior:

build success

### Actual behavior:

```
> strapi-app@0.1.0 build /home/alex/Dev/strapi-app
> strapi build

Starting the compilation for TypeScript files in /home/alex/Dev/strapi-app
Building your admin UI with development configuration...

● Webpack █████████████████████████ building (63%) 1/1 entries 5383/5498 dependencies 1257/1859 mo
dules 367 active 
 node_modules/date-fns/esm/_lib/getUTCWeek/index.js

ModuleNotFoundError: Module not found: Error: Can't resolve '@codemirror/theme-one-dark' in '/home/alex/Dev/strapi-app/node_modules/@strapi/design-system/node_modules/@uiw/react-codemirror/esm'
    at /home/alex/Dev/strapi-app/node_modules/webpack/lib/Compilation.js:2022:28
    at /home/alex/Dev/strapi-app/node_modules/webpack/lib/NormalModuleFactory.js:817:13
    at eval (eval at create (/home/alex/Dev/strapi-app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /home/alex/Dev/strapi-app/node_modules/webpack/lib/NormalModuleFactory.js:275:22
    at eval (eval at create (/home/alex/Dev/strapi-app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /home/alex/Dev/strapi-app/node_modules/webpack/lib/NormalModuleFactory.js:448:22
    at /home/alex/Dev/strapi-app/node_modules/webpack/lib/NormalModuleFactory.js:118:11
    at /home/alex/Dev/strapi-app/node_modules/webpack/lib/NormalModuleFactory.js:689:25
    at /home/alex/Dev/strapi-app/node_modules/webpack/lib/NormalModuleFactory.js:893:8
    at /home/alex/Dev/strapi-app/node_modules/webpack/lib/NormalModuleFactory.js:1013:5
    at /home/alex/Dev/strapi-app/node_modules/neo-async/async.js:6883:13
    at /home/alex/Dev/strapi-app/node_modules/webpack/lib/NormalModuleFactory.js:996:45
    at finishWithoutResolve (/home/alex/Dev/strapi-app/node_modules/enhanced-resolve/lib/Resolver.js:372:11)
    at /home/alex/Dev/strapi-app/node_modules/enhanced-resolve/lib/Resolver.js:461:15
    at /home/alex/Dev/strapi-app/node_modules/enhanced-resolve/lib/Resolver.js:519:5
    at eval (eval at create (/home/alex/Dev/strapi-app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /home/alex/Dev/strapi-app/node_modules/enhanced-resolve/lib/Resolver.js:519:5
    at eval (eval at create (/home/alex/Dev/strapi-app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /home/alex/Dev/strapi-app/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:89:43
    at /home/alex/Dev/strapi-app/node_modules/enhanced-resolve/lib/Resolver.js:519:5
    at eval (eval at create (/home/alex/Dev/strapi-app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /home/alex/Dev/strapi-app/node_modules/enhanced-resolve/lib/Resolver.js:519:5
    at eval (eval at create (/home/alex/Dev/strapi-app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /home/alex/Dev/strapi-app/node_modules/enhanced-resolve/lib/Resolver.js:519:5
    at eval (eval at create (/home/alex/Dev/strapi-app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /home/alex/Dev/strapi-app/node_modules/enhanced-resolve/lib/Resolver.js:519:5
    at eval (eval at create (/home/alex/Dev/strapi-app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /home/alex/Dev/strapi-app/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:89:43
    at /home/alex/Dev/strapi-app/node_modules/enhanced-resolve/lib/Resolver.js:519:5
    at eval (eval at create (/home/alex/Dev/strapi-app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /home/alex/Dev/strapi-app/node_modules/enhanced-resolve/lib/Resolver.js:519:5
    at eval (eval at create (/home/alex/Dev/strapi-app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /home/alex/Dev/strapi-app/node_modules/enhanced-resolve/lib/DirectoryExistsPlugin.js:41:15
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)
resolve '@codemirror/theme-one-dark' in '/home/alex/Dev/strapi-app/node_modules/@strapi/design-system/node_modules/@uiw/react-codemirror/esm'
  Parsed request is a module
  using description file: /home/alex/Dev/strapi-app/node_modules/@strapi/design-system/node_modules/@uiw/react-codemirror/package.json (relative path: ./esm)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /home/alex/Dev/strapi-app/node_modules/@strapi/design-system/node_modules/@uiw/react-codemirror/esm/node_modules doesn't exist or is not a directory
      /home/alex/Dev/strapi-app/node_modules/@strapi/design-system/node_modules/@uiw/react-codemirror/node_modules doesn't exist or is not a directory
      /home/alex/Dev/strapi-app/node_modules/@strapi/design-system/node_modules/@uiw/node_modules doesn't exist or is not a directory
      /home/alex/Dev/strapi-app/node_modules/@strapi/design-system/node_modules/node_modules doesn't exist or is not a directory
      looking for modules in /home/alex/Dev/strapi-app/node_modules/@strapi/design-system/node_modules
        single file module
          using description file: /home/alex/Dev/strapi-app/node_modules/@strapi/design-system/package.json (relative path: ./node_modules/@codemirror/theme-one-dark)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /home/alex/Dev/strapi-app/node_modules/@strapi/design-system/node_modules/@codemirror/theme-one-dark doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /home/alex/Dev/strapi-app/node_modules/@strapi/design-system/node_modules/@codemirror/theme-one-dark.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/alex/Dev/strapi-app/node_modules/@strapi/design-system/node_modules/@codemirror/theme-one-dark.jsx doesn't exist
            .react.js
              Field 'browser' doesn't contain a valid alias configuration
              /home/alex/Dev/strapi-app/node_modules/@strapi/design-system/node_modules/@codemirror/theme-one-dark.react.js doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /home/alex/Dev/strapi-app/node_modules/@strapi/design-system/node_modules/@codemirror/theme-one-dark.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/alex/Dev/strapi-app/node_modules/@strapi/design-system/node_modules/@codemirror/theme-one-dark.tsx doesn't exist
        /home/alex/Dev/strapi-app/node_modules/@strapi/design-system/node_modules/@codemirror/theme-one-dark doesn't exist
      /home/alex/Dev/strapi-app/node_modules/@strapi/node_modules doesn't exist or is not a directory
      /home/alex/Dev/strapi-app/node_modules/node_modules doesn't exist or is not a directory
      looking for modules in /home/alex/Dev/strapi-app/node_modules
        single file module
          using description file: /home/alex/Dev/strapi-app/package.json (relative path: ./node_modules/@codemirror/theme-one-dark)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /home/alex/Dev/strapi-app/node_modules/@codemirror/theme-one-dark doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /home/alex/Dev/strapi-app/node_modules/@codemirror/theme-one-dark.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/alex/Dev/strapi-app/node_modules/@codemirror/theme-one-dark.jsx doesn't exist
            .react.js
              Field 'browser' doesn't contain a valid alias configuration
              /home/alex/Dev/strapi-app/node_modules/@codemirror/theme-one-dark.react.js doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /home/alex/Dev/strapi-app/node_modules/@codemirror/theme-one-dark.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/alex/Dev/strapi-app/node_modules/@codemirror/theme-one-dark.tsx doesn't exist
        /home/alex/Dev/strapi-app/node_modules/@codemirror/theme-one-dark doesn't exist
      /home/alex/Dev/node_modules doesn't exist or is not a directory
      /home/alex/node_modules doesn't exist or is not a directory
      /home/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /home/alex/Dev/strapi-app/node_modules/@strapi/admin/node_modules
        single file module
          using description file: /home/alex/Dev/strapi-app/node_modules/@strapi/admin/package.json (relative path: ./node_modules/@codemirror/theme-one-dark)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /home/alex/Dev/strapi-app/node_modules/@strapi/admin/node_modules/@codemirror/theme-one-dark doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /home/alex/Dev/strapi-app/node_modules/@strapi/admin/node_modules/@codemirror/theme-one-dark.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/alex/Dev/strapi-app/node_modules/@strapi/admin/node_modules/@codemirror/theme-one-dark.jsx doesn't exist
            .react.js
              Field 'browser' doesn't contain a valid alias configuration
              /home/alex/Dev/strapi-app/node_modules/@strapi/admin/node_modules/@codemirror/theme-one-dark.react.js doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /home/alex/Dev/strapi-app/node_modules/@strapi/admin/node_modules/@codemirror/theme-one-dark.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/alex/Dev/strapi-app/node_modules/@strapi/admin/node_modules/@codemirror/theme-one-dark.tsx doesn't exist
        /home/alex/Dev/strapi-app/node_modules/@strapi/admin/node_modules/@codemirror/theme-one-dark doesn't exist
ModuleNotFoundError: Module not found: Error: Can't resolve '@codemirror/theme-one-dark' in '/home/alex/Dev/strapi-app/node_modules/@strapi/design-system/node_modules/@uiw/react-codemirror/esm'
    at /home/alex/Dev/strapi-app/node_modules/webpack/lib/Compilation.js:2022:28
    at /home/alex/Dev/strapi-app/node_modules/webpack/lib/NormalModuleFactory.js:817:13
    at eval (eval at create (/home/alex/Dev/strapi-app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /home/alex/Dev/strapi-app/node_modules/webpack/lib/NormalModuleFactory.js:275:22
    at eval (eval at create (/home/alex/Dev/strapi-app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /home/alex/Dev/strapi-app/node_modules/webpack/lib/NormalModuleFactory.js:448:22
    at /home/alex/Dev/strapi-app/node_modules/webpack/lib/NormalModuleFactory.js:118:11
    at /home/alex/Dev/strapi-app/node_modules/webpack/lib/NormalModuleFactory.js:689:25
    at /home/alex/Dev/strapi-app/node_modules/webpack/lib/NormalModuleFactory.js:893:8
    at /home/alex/Dev/strapi-app/node_modules/webpack/lib/NormalModuleFactory.js:1013:5
    at /home/alex/Dev/strapi-app/node_modules/neo-async/async.js:6883:13
    at /home/alex/Dev/strapi-app/node_modules/webpack/lib/NormalModuleFactory.js:996:45
    at finishWithoutResolve (/home/alex/Dev/strapi-app/node_modules/enhanced-resolve/lib/Resolver.js:372:11)
    at /home/alex/Dev/strapi-app/node_modules/enhanced-resolve/lib/Resolver.js:461:15
    at /home/alex/Dev/strapi-app/node_modules/enhanced-resolve/lib/Resolver.js:519:5
    at eval (eval at create (/home/alex/Dev/strapi-app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /home/alex/Dev/strapi-app/node_modules/enhanced-resolve/lib/Resolver.js:519:5
    at eval (eval at create (/home/alex/Dev/strapi-app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /home/alex/Dev/strapi-app/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:89:43
    at /home/alex/Dev/strapi-app/node_modules/enhanced-resolve/lib/Resolver.js:519:5
    at eval (eval at create (/home/alex/Dev/strapi-app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /home/alex/Dev/strapi-app/node_modules/enhanced-resolve/lib/Resolver.js:519:5
    at eval (eval at create (/home/alex/Dev/strapi-app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /home/alex/Dev/strapi-app/node_modules/enhanced-resolve/lib/Resolver.js:519:5
    at eval (eval at create (/home/alex/Dev/strapi-app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /home/alex/Dev/strapi-app/node_modules/enhanced-resolve/lib/Resolver.js:519:5
    at eval (eval at create (/home/alex/Dev/strapi-app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /home/alex/Dev/strapi-app/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:89:43
    at /home/alex/Dev/strapi-app/node_modules/enhanced-resolve/lib/Resolver.js:519:5
    at eval (eval at create (/home/alex/Dev/strapi-app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /home/alex/Dev/strapi-app/node_modules/enhanced-resolve/lib/Resolver.js:519:5
    at eval (eval at create (/home/alex/Dev/strapi-app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /home/alex/Dev/strapi-app/node_modules/enhanced-resolve/lib/DirectoryExistsPlugin.js:41:15
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)
resolve '@codemirror/theme-one-dark' in '/home/alex/Dev/strapi-app/node_modules/@strapi/design-system/node_modules/@uiw/react-codemirror/esm'
  Parsed request is a module
  using description file: /home/alex/Dev/strapi-app/node_modules/@strapi/design-system/node_modules/@uiw/react-codemirror/package.json (relative path: ./esm)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /home/alex/Dev/strapi-app/node_modules/@strapi/design-system/node_modules/@uiw/react-codemirror/esm/node_modules doesn't exist or is not a directory
      /home/alex/Dev/strapi-app/node_modules/@strapi/design-system/node_modules/@uiw/react-codemirror/node_modules doesn't exist or is not a directory
      /home/alex/Dev/strapi-app/node_modules/@strapi/design-system/node_modules/@uiw/node_modules doesn't exist or is not a directory
      /home/alex/Dev/strapi-app/node_modules/@strapi/design-system/node_modules/node_modules doesn't exist or is not a directory
      looking for modules in /home/alex/Dev/strapi-app/node_modules/@strapi/design-system/node_modules
        single file module
          using description file: /home/alex/Dev/strapi-app/node_modules/@strapi/design-system/package.json (relative path: ./node_modules/@codemirror/theme-one-dark)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /home/alex/Dev/strapi-app/node_modules/@strapi/design-system/node_modules/@codemirror/theme-one-dark doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /home/alex/Dev/strapi-app/node_modules/@strapi/design-system/node_modules/@codemirror/theme-one-dark.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/alex/Dev/strapi-app/node_modules/@strapi/design-system/node_modules/@codemirror/theme-one-dark.jsx doesn't exist
            .react.js
              Field 'browser' doesn't contain a valid alias configuration
              /home/alex/Dev/strapi-app/node_modules/@strapi/design-system/node_modules/@codemirror/theme-one-dark.react.js doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /home/alex/Dev/strapi-app/node_modules/@strapi/design-system/node_modules/@codemirror/theme-one-dark.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/alex/Dev/strapi-app/node_modules/@strapi/design-system/node_modules/@codemirror/theme-one-dark.tsx doesn't exist
        /home/alex/Dev/strapi-app/node_modules/@strapi/design-system/node_modules/@codemirror/theme-one-dark doesn't exist
      /home/alex/Dev/strapi-app/node_modules/@strapi/node_modules doesn't exist or is not a directory
      /home/alex/Dev/strapi-app/node_modules/node_modules doesn't exist or is not a directory
      looking for modules in /home/alex/Dev/strapi-app/node_modules
        single file module
          using description file: /home/alex/Dev/strapi-app/package.json (relative path: ./node_modules/@codemirror/theme-one-dark)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /home/alex/Dev/strapi-app/node_modules/@codemirror/theme-one-dark doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /home/alex/Dev/strapi-app/node_modules/@codemirror/theme-one-dark.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/alex/Dev/strapi-app/node_modules/@codemirror/theme-one-dark.jsx doesn't exist
            .react.js
              Field 'browser' doesn't contain a valid alias configuration
              /home/alex/Dev/strapi-app/node_modules/@codemirror/theme-one-dark.react.js doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /home/alex/Dev/strapi-app/node_modules/@codemirror/theme-one-dark.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/alex/Dev/strapi-app/node_modules/@codemirror/theme-one-dark.tsx doesn't exist
        /home/alex/Dev/strapi-app/node_modules/@codemirror/theme-one-dark doesn't exist
      /home/alex/Dev/node_modules doesn't exist or is not a directory
      /home/alex/node_modules doesn't exist or is not a directory
      /home/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /home/alex/Dev/strapi-app/node_modules/@strapi/admin/node_modules
        single file module
          using description file: /home/alex/Dev/strapi-app/node_modules/@strapi/admin/package.json (relative path: ./node_modules/@codemirror/theme-one-dark)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /home/alex/Dev/strapi-app/node_modules/@strapi/admin/node_modules/@codemirror/theme-one-dark doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /home/alex/Dev/strapi-app/node_modules/@strapi/admin/node_modules/@codemirror/theme-one-dark.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/alex/Dev/strapi-app/node_modules/@strapi/admin/node_modules/@codemirror/theme-one-dark.jsx doesn't exist
            .react.js
              Field 'browser' doesn't contain a valid alias configuration
              /home/alex/Dev/strapi-app/node_modules/@strapi/admin/node_modules/@codemirror/theme-one-dark.react.js doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /home/alex/Dev/strapi-app/node_modules/@strapi/admin/node_modules/@codemirror/theme-one-dark.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/alex/Dev/strapi-app/node_modules/@strapi/admin/node_modules/@codemirror/theme-one-dark.tsx doesn't exist
        /home/alex/Dev/strapi-app/node_modules/@strapi/admin/node_modules/@codemirror/theme-one-dark doesn't exist
 ELIFECYCLE  Command failed with exit code 1.
```

if I remove node-linker=hoisted setting and run pnpm i and then enable it and run  pnpm i again, pnpm will relink and pnpm build without no issue.

```
.npmrc
#node-linker=hoisted
shamefully-hoist=true

pnpm i
Lockfile is up to date, resolution step is skipped
Packages: +1303
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /home/alex/.local/share/pnpm/store/v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 1303, reused 1299, downloaded 0, added 1303, done

dependencies:
+ @strapi/plugin-i18n 4.10.7
+ @strapi/plugin-users-permissions 4.10.7
+ @strapi/strapi 4.10.7
+ better-sqlite3 8.0.1

Done in 6.9s

.npmrc
node-linker=hoisted
#shamefully-hoist=true

pnpm i
Lockfile is up to date, resolution step is skipped
Packages: +1395
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Relinking /home/alex/Dev/strapi-app/node_modules/depd from the store
Relinking /home/alex/Dev/strapi-app/node_modules/tslib from the store
Relinking /home/alex/Dev/strapi-app/node_modules/ms from the store
Relinking /home/alex/Dev/strapi-app/node_modules/styled-components from the store
Relinking /home/alex/Dev/strapi-app/node_modules/chokidar from the store
Relinking /home/alex/Dev/strapi-app/node_modules/dotenv from the store
Relinking /home/alex/Dev/strapi-app/node_modules/get-stream from the store
Relinking /home/alex/Dev/strapi-app/node_modules/npm-run-path from the store
Relinking /home/alex/Dev/strapi-app/node_modules/which from the store
Relinking /home/alex/Dev/strapi-app/node_modules/has-flag from the store
Relinking /home/alex/Dev/strapi-app/node_modules/@radix-ui/react-collection from the store
Relinking /home/alex/Dev/strapi-app/node_modules/@radix-ui/react-use-layout-effect from the store
Relinking /home/alex/Dev/strapi-app/node_modules/@radix-ui/react-focus-guards from the store
Relinking /home/alex/Dev/strapi-app/node_modules/@radix-ui/react-direction from the store
Relinking /home/alex/Dev/strapi-app/node_modules/semver from the store
Relinking /home/alex/Dev/strapi-app/node_modules/colorette from the store
Relinking /home/alex/Dev/strapi-app/node_modules/ajv from the store
Relinking /home/alex/Dev/strapi-app/node_modules/commander from the store
Relinking /home/alex/Dev/strapi-app/node_modules/interpret from the store
Relinking /home/alex/Dev/strapi-app/node_modules/supports-color from the store
Relinking /home/alex/Dev/strapi-app/node_modules/@emotion/is-prop-valid from the store
Relinking /home/alex/Dev/strapi-app/node_modules/camel-case from the store
Relinking /home/alex/Dev/strapi-app/node_modules/param-case from the store
Relinking /home/alex/Dev/strapi-app/node_modules/entities from the store
Relinking /home/alex/Dev/strapi-app/node_modules/type-fest from the store
Relinking /home/alex/Dev/strapi-app/node_modules/escape-string-regexp from the store
Relinking /home/alex/Dev/strapi-app/node_modules/ansi-regex from the store
Relinking /home/alex/Dev/strapi-app/node_modules/color-convert from the store
Relinking /home/alex/Dev/strapi-app/node_modules/@emotion/unitless from the store
Relinking /home/alex/Dev/strapi-app/node_modules/jwa from the store
Relinking /home/alex/Dev/strapi-app/node_modules/mimic-response from the store
Relinking /home/alex/Dev/strapi-app/node_modules/source-map from the store
Relinking /home/alex/Dev/strapi-app/node_modules/pascal-case from the store
Relinking /home/alex/Dev/strapi-app/node_modules/dot-case from the store
Relinking /home/alex/Dev/strapi-app/node_modules/minipass from the store
Relinking /home/alex/Dev/strapi-app/node_modules/string_decoder from the store
Relinking /home/alex/Dev/strapi-app/node_modules/is-plain-object from the store
Relinking /home/alex/Dev/strapi-app/node_modules/raw-body from the store
Relinking /home/alex/Dev/strapi-app/node_modules/ipaddr.js from the store
Relinking /home/alex/Dev/strapi-app/node_modules/estraverse from the store
Relinking /home/alex/Dev/strapi-app/node_modules/htmlparser2 from the store
Relinking /home/alex/Dev/strapi-app/node_modules/is-extendable from the store
Relinking /home/alex/Dev/strapi-app/node_modules/is-number from the store
Relinking /home/alex/Dev/strapi-app/node_modules/color from the store
Relinking /home/alex/Dev/strapi-app/node_modules/libmime from the store
Relinking /home/alex/Dev/strapi-app/node_modules/@types/mime from the store
Relinking /home/alex/Dev/strapi-app/node_modules/is-arrayish from the store
Relinking /home/alex/Dev/strapi-app/node_modules/domhandler from the store
Relinking /home/alex/Dev/strapi-app/node_modules/domutils from the store
Relinking /home/alex/Dev/strapi-app/node_modules/extend-shallow from the store
Relinking /home/alex/Dev/strapi-app/node_modules/define-property from the store
Relinking /home/alex/Dev/strapi-app/node_modules/dom-serializer from the store
Relinking /home/alex/Dev/strapi-app/node_modules/is-accessor-descriptor from the store
Relinking /home/alex/Dev/strapi-app/node_modules/is-data-descriptor from the store
Relinking /home/alex/Dev/strapi-app/node_modules/ajv-keywords from the store
Relinking /home/alex/Dev/strapi-app/node_modules/rxjs from the store
Progress: resolved 0, reused 1291, downloaded 0, added 325, done
Done in 5.4s

pnpm build

> strapi-app@0.1.0 build /home/alex/Dev/strapi-app
> strapi build

Starting the compilation for TypeScript files in /home/alex/Dev/strapi-app
Building your admin UI with development configuration...

✔ Webpack
  Compiled successfully in 23.51s
```

### Additional information:

 - `node -v` prints: v18.16.0
 - Windows, macOS, or Linux?: Manjaro Linux 22.1.3, kernel: 6.3.4-2

**Comment by zkochan** [comment]
It doesn't make sense to use these too setting together. They are not compatible. It is impossible to make them compatible. `shamefully-hoist` is for symlinking one version of each package from node_modules to the root of node_modules. It aims to solve some issues without using real hoisting.

`node-linker=hoisted` is for real hoisting.

The two together ill never work.

**Comment by smoothdvd** [comment]
> It doesn't make sense to use these two settings together. They are not compatible. It is impossible to make them compatible. `shamefully-hoist` is for symlinking one version of each package from node_modules to the root of node_modules. It aims to solve some issues without using real hoisting.
> 
> `node-linker=hoisted` is for real hoisting.
> 
> The two together ill never work.

In my case, I need to run the commands pnpm i --shamefully-hoist and pnpm i --config.node-linker=hoisted before the project will build successfully. If I execute either command, the project will not be built.

**Comment by zkochan** [comment]
This no longer reproduces on current pnpm, so closing.

Verified on pnpm 12.5.1: `nodeLinker: hoisted` together with `shamefullyHoist: true` installs without error.

If you still hit this on the latest pnpm, please comment with a reproduction and we will reopen.

---
Written by an agent (Claude Code, claude-opus-5).
