### ISSUE TITLE
Unable to find react hook forms context in monorepo

### ISSUE THREAD

**Issue by WingsDevelopment** [pnpm/pnpm#6625]
Version Number
8.5.1

Github:
https://github.com/WingsDevelopment/pnpm-monorepo-repeat-fwb

Steps to reproduce
Clone repository, follow the readme instructions,
build shared ui library,
start aplication.

Expected behaviour:
Expected behaviour is to find form context with useFormContext inside my SharedTextField

Relevant log output
Uncaught runtime errors:
×
ERROR
Cannot read properties of null (reading 'control')
TypeError: Cannot read properties of null (reading 'control')
    at SharedTextField (http://localhost:3001/static/js/bundle.js:108924:56)
    at renderWithHooks (http://localhost:3001/static/js/bundle.js:85618:22)
    at mountIndeterminateComponent (http://localhost:3001/static/js/bundle.js:88904:17)
    at beginWork (http://localhost:3001/static/js/bundle.js:90200:20)
    at HTMLUnknownElement.callCallback (http://localhost:3001/static/js/bundle.js:75210:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3001/static/js/bundle.js:75254:20)
    at invokeGuardedCallback (http://localhost:3001/static/js/bundle.js:75311:35)
    at beginWork$1 (http://localhost:3001/static/js/bundle.js:95185:11)
    at performUnitOfWork (http://localhost:3001/static/js/bundle.js:94432:16)
    at workLoopSync (http://localhost:3001/static/js/bundle.js:94355:9)

OS:
 - Windows

**Comment by zkochan** [comment]
Add a `.npmrc` in the root of your workspace with this setting:

```
shamefully-hoist=true
```

Run `pnpm install`. It works after that.

**Comment by sajag-upplft** [comment]
> Add a `.npmrc` in the root of your workspace with this setting:
> 
> ```
> shamefully-hoist=true
> ```
> 
> Run `pnpm install`. It works after that.

This did not work for me. @WingsDevelopment did you get it working?

**Comment by sajag-upplft** [comment]
Thanks @WingsDevelopment
I was using a single version policy for my monorepo, so turning on shamefully-hoist didn’t really have any impact.

The actual issue was that my UI library was bundling react-hook-form, and my main app was also including it — leading to duplication, which probably caused the context error.

I resolved it by updating the Vite config for the UI library to mark react-hook-form as external:
```ts
// vite.config.ts (for the UI library)
export default defineConfig({
  ...,
  build: {
    ...,
    rollupOptions: {
      // External packages that should not be bundled into your library.
      external: ['react', 'react-dom', 'react/jsx-runtime', 'react-hook-form'],
    },
  },
});
```
Now it’s properly excluded from the bundle, and everything works as expected ✅

**Comment by daviddelusenet** [comment]
I'm also running into this issue and tried but solutions but still get the same error. I also tried using the [vite-plugin-externalize-deps](https://github.com/davidmyersdev/vite-plugin-externalize-deps) plugin but that also doesn't help.

Does anyone have any other ideas?

**Comment by zkochan** [comment]
Closing: this is not something pnpm can fix.

The app and the shared library each load their own copy of react-hook-form, so the context does not cross between them. Declare the library's react-hook-form as a peer dependency.

If you still hit this on the latest pnpm, please comment with a reproduction and we will reopen.

---
Written by an agent (Claude Code, claude-opus-5).
