### ISSUE TITLE
Completion doesn't work on fish shell

### ISSUE THREAD

**Issue by loqusion** [pnpm/pnpm#6647]
When I press `<Tab>` after typing `pnpm `, I get this:

```
$ pnpm 
    at async /home/loqusion/.cache/node/corepack/pnpm/8.6.0/dist/pnpm.cjs:232908:21                (pnpm)
    at async /home/loqusion/.cache/node/corepack/pnpm/8.6.0/dist/pnpm.cjs:233122:7                 (pnpm)
    at async main (/home/loqusion/.cache/node/corepack/pnpm/8.6.0/dist/pnpm.cjs:232875:34)         (pnpm)
    at async runPnpm (/home/loqusion/.cache/node/corepack/pnpm/8.6.0/dist/pnpm.cjs:233130:5)       (pnpm)
    at getLastOption (/home/loqusion/.cache/node/corepack/pnpm/8.6.0/dist/pnpm.cjs:231594:11)      (pnpm)
    at isOption (/home/loqusion/.cache/node/corepack/pnpm/8.6.0/dist/pnpm.cjs:231604:19)           (pnpm)
    at Object.completion (/home/loqusion/.cache/node/corepack/pnpm/8.6.0/dist/pnpm.cjs:231995:57)  (pnpm)
pnpm: Cannot read properties of undefined (reading 'startsWith')                                   (pnpm)
 ERROR  Cannot read properties of undefined (reading 'startsWith')                                 (pnpm)
```

Here's the problematic code:

```fish
# ~/.config/tabtab/fish/pnpm.fish

###-begin-pnpm-completion-###
function _pnpm_completion
    set cmd (commandline -o)
    set cursor (commandline -C)
    set words (count $cmd)

    set completions (eval env DEBUG=\"" \"" COMP_CWORD=\""$words\"" COMP_LINE=\""$cmd \"" COMP_POINT=\""$cursor\"" pnpm completion -- $cmd)

    if [ "$completions" = __tabtab_complete_files__ ]
        set -l matches (commandline -ct)*
        if [ -n "$matches" ]
            __fish_complete_path (commandline -ct)
        end
    else
        for completion in $completions
            echo -e $completion
        end
    end
end

complete -f -d pnpm -c pnpm -a "(_pnpm_completion)"
###-end-pnpm-completion-###
```

The issue specifically happens when running `eval env DEBUG=\"" \"" COMP_CWORD=\""$words\"" COMP_LINE=\""$cmd \"" COMP_POINT=\""$cursor\"" pnpm completion -- $cmd` in command substitution -- running the command on its own produces the correct result, but within `()` it prints an error instead.

Removing `eval` stops the errors from appearing, though it has the potential side effect of not evaluating the user's command line properly (e.g. if they use any substitution).

### Additional information:

 - pnpm version: `8.6.0`
 - `node -v` prints: `v20.2.0`
 - Windows, macOS, or Linux?: Linux

**Comment by zkochan** [comment]
I don't seem to have this issue. Tested on macOS, fish v3.6.1

**Comment by loqusion** [comment]
I finally realized the issue: I was defining a `function` for `env` that uses [`grc`](https://github.com/garabik/grc) for output colorization. Something like:

```fish
function env --inherit-variable executable --wraps=env
    if isatty 1
        grc $executable $argv
    else
        eval command env $argv
    end
end
```

The `eval` part was likely the cause of the issue.
