### ISSUE TITLE
Pnpm install crashes when npm and yarn succeed.

### ISSUE THREAD

**Issue by ennioVisco** [pnpm/pnpm#6764]
It would be nice to debug what is causing the issue, but I seem to not be able to.

### pnpm version:
`8.6.6`
### Code to reproduce the issue:
`pnpm install`  with the following `package.json`: https://gist.github.com/ennioVisco/5e0c436ab5f0ec50d5aa30de4ac6e364.

### Expected behavior:
It should install

### Actual behavior:
It crashes with the following log:
```
 ERROR  Cannot read properties of undefined (reading 'depth')

pnpm: Cannot read properties of undefined (reading 'depth')
    at toPkgByName (/Users/enniovisco/.cache/node/corepack/pnpm/8.6.6/dist/pnpm.cjs:185724:23)
    at resolvePeersOfNode (/Users/enniovisco/.cache/node/corepack/pnpm/8.6.6/dist/pnpm.cjs:185479:129)
    at resolvePeersOfChildren (/Users/enniovisco/.cache/node/corepack/pnpm/8.6.6/dist/pnpm.cjs:185636:49)
    at resolvePeers (/Users/enniovisco/.cache/node/corepack/pnpm/8.6.6/dist/pnpm.cjs:185335:9)
    at resolveDependencies (/Users/enniovisco/.cache/node/corepack/pnpm/8.6.6/dist/pnpm.cjs:186541:126)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _installInContext (/Users/enniovisco/.cache/node/corepack/pnpm/8.6.6/dist/pnpm.cjs:189788:238)
    at async installInContext (/Users/enniovisco/.cache/node/corepack/pnpm/8.6.6/dist/pnpm.cjs:190116:16)
    at async _install (/Users/enniovisco/.cache/node/corepack/pnpm/8.6.6/dist/pnpm.cjs:189618:25)
    at async mutateModules (/Users/enniovisco/.cache/node/corepack/pnpm/8.6.6/dist/pnpm.cjs:189296:23)
Progress: resolved 1913, reused 1870, downloaded 0, added 0
```

### Additional information:

 - `node -v` prints: `v18.16.1`
 - Windows, macOS, or Linux?: macOS

**Comment by thynson** [comment]
Did not reproduced with pnpm 8.6.6 on macOS (M1), neither with node v16 nor with node 18, with given package.json.
Probably a lockfile is needed to reproduce it.

**Comment by ennioVisco** [comment]
> Did not reproduced with pnpm 8.6.6 on macOS (M1), neither with node v16 nor with node 18, with given package.json. Probably a lockfile is needed to reproduce it.

Well, the lockfile is not generated since it cannot install :/.
I must say I used pnpm via corepack, could this be an issue?

**Comment by thynson** [comment]
Are you using a custom registry? did you tried cleaning up the `.npmrc` file?

**Comment by ennioVisco** [comment]
> Are you using a custom registry? did you tried cleaning up the `.npmrc` file?

I tried in an empty folder, with no .npmrc.
I'm not using any custom registries.

**Comment by thynson** [comment]
🤔 That's weird.

**Comment by thynson** [comment]
Here is the lockfile produced when I tried to reproduce. 
[pnpm-lock.yaml.gz](https://github.com/pnpm/pnpm/files/11957510/pnpm-lock.yaml.gz)

**Comment by ennioVisco** [comment]
> Here is the lockfile produced when I tried to reproduce. [pnpm-lock.yaml.gz](https://github.com/pnpm/pnpm/files/11957510/pnpm-lock.yaml.gz)

Ok, it turns out it was something in my local setup, no idea what. 
By generating the lock file from another machine and moving it to this setup, pnpm seems to work as it should.
So, I'll close the issue, unless I can specifically pinpoint what was happening. 
Thanks a lot!
