### ISSUE TITLE
pnpm: Cannot read properties of undefined (reading 'startsWith')

### ISSUE THREAD

**Issue by iloveitaly** [pnpm/pnpm#6873]
### pnpm version:
8.6.10
### Code to reproduce the issue:

```json
{
  "name": "crawler",
  "version": "0.0.1",
  "description": "",
  "author": "It's not you it's me",
  "private": true,
  "sideEffects": false,
  "type": "module",
  "license": "MIT",
  "dependencies": {
    "commander": "^11.0.0",
    "crawlee": "^3.4.2",
    "follow-redirect-url": "file:~/Projects/javascript/follow-redirect-url",
    "hast-util-is-element": "^2.1.3",
    "langchain": "^0.0.118",
    "loglevel": "^1.8.1",
    "loglevel-plugin-prefix": "^0.8.4",
    "mdast-util-gfm-table": "^2.0.0",
    "mysql2": "^3.5.2",
    "playwright": "^1.36.2",
    "rehype-parse": "^8.0.4",
    "rehype-remark": "^9.1.2",
    "rehype-remove-comments": "^5.0.0",
    "rehype-remove-images": "^1.1.0",
    "rehype-stringify": "^9.0.3",
    "remark-parse": "^10.0.2",
    "remark-rehype": "^10.1.0",
    "remark-stringify": "^10.0.3",
    "rocket-reach": "github:stainless-sdks/rocket-reach-node",
    "tiny-invariant": "^1.3.1",
    "unified": "^10.1.2",
    "unist-util-filter": "^5.0.0",
    "unist-util-remove": "^4.0.0",
    "zod": "^3.21.4"
  },
  "devDependencies": {
    "@apify/tsconfig": "^0.1.0",
    "@trivago/prettier-plugin-sort-imports": "^4.2.0",
    "@types/eslint-config-prettier": "^6.11.0",
    "@types/node": "^20.4.5",
    "better-node-inspect": "file:~/Projects/javascript/better-node-inspect",
    "eslint": "^8.45.0",
    "eslint-config-prettier": "^8.8.0",
    "eslint-gitignore": "^0.1.0",
    "prettier": "^2.8.8",
    "tsconfig-paths": "^4.2.0",
    "tsx": "^3.12.7",
    "typescript": "^5.1.6",
    "typesync": "^0.11.1",
    "vite-tsconfig-paths": "^4.2.0",
    "vitest": "^0.33.0"
  },
  "scripts": {
    "start": "npm run start:dev",
    "start:prod": "node dist/commands.js",
    "start:dev": "ts-node-esm -T src/commands.ts",
    "build": "tsc",
    "test": "vitest"
  },
  "prettier": {
    "semi": false,
    "importOrderSeparation": true,
    "importOrderSortSpecifiers": true,
    "importOrderGroupNamespaceSpecifiers": true,
    "importOrder": [
      "^[:alpha].*$",
      "^@remix(.*)$",
      "^(@mantine|@emotion|@nivo)(.*)$",
      "^@prisma(.*)$",
      "^~/",
      "./"
    ]
  },
  "eslintIgnore": [
    "/bin",
    "/prisma/seed.ts",
    "/node_modules",
    "/build",
    "/public/build",
    "/postgres-data"
  ],
  "typesync": {
    "ignorePackages": [
      "eslint",
      "prettier",
      "prettier-plugin-sort-imports"
    ]
  },
  "engines": {
    "node": "20.3.1",
    "npm": "9.6.7"
  }
}

```

### Expected behavior:
list out dependencies

### Actual behavior:

stack trace

```
 ERROR  Cannot read properties of undefined (reading 'startsWith')

pnpm: Cannot read properties of undefined (reading 'startsWith')
    at getPkgInfo (/Users/mike/.asdf/installs/pnpm/8.6.10/dist/pnpm.cjs:115871:20)
    at /Users/mike/.asdf/installs/pnpm/8.6.10/dist/pnpm.cjs:116267:59
    at Array.forEach (<anonymous>)
    at dependenciesHierarchyForPackage (/Users/mike/.asdf/installs/pnpm/8.6.10/dist/pnpm.cjs:116266:33)
    at async /Users/mike/.asdf/installs/pnpm/8.6.10/dist/pnpm.cjs:116230:11
    at async Promise.all (index 0)
    at async buildDependenciesHierarchy (/Users/mike/.asdf/installs/pnpm/8.6.10/dist/pnpm.cjs:116227:8)
    at async list (/Users/mike/.asdf/installs/pnpm/8.6.10/dist/pnpm.cjs:116849:16)
    at async /Users/mike/.asdf/installs/pnpm/8.6.10/dist/pnpm.cjs:219529:21
    at async main (/Users/mike/.asdf/installs/pnpm/8.6.10/dist/pnpm.cjs:219496:34)
```

### Additional information:

 - `node -v` prints: `v20.3.1`
 - Windows, macOS, or Linux?: macOS

**Comment by KSXGitHub** [comment]
Is this issue still reproducible with `--ignore-scripts`? I ask this because I don't want to audit this long list of dependencies.

Can you provide `package.json` of the private packages, including `github:stainless-sdks/rocket-reach-node`, `~/Projects/javascript/follow-redirect-url`, `~/Projects/javascript/better-node-inspect`?

**Comment by iloveitaly** [comment]
@KSXGitHub looks like `--ignore-scripts` isn't a valid option:

```
❯ pnpm ls --ignore-scripts
 ERROR  Unknown option: 'ignore-scripts'
Did you mean 'ignore-workspace'? Use "--config.unknown=value" to force an unknown option.
For help, run: pnpm help list
```

But, when I removed the `file:` references from package.json (and just used the public packages) the issue resolved itself! However, it wasn't dependent on the `package.json` within the local packages since it occurred as long as there was at least one `file:` reference and was not dependent on the contents of the package.

**Comment by pedroapfilho** [comment]
I'm currently having the same issue

**Comment by KSXGitHub** [comment]
> looks like `--ignore-scripts` isn't a valid option:
> 
> ```
> ❯ pnpm ls --ignore-scripts
>  ERROR  Unknown option: 'ignore-scripts'
> Did you mean 'ignore-workspace'? Use "--config.unknown=value" to force an unknown option.
> For help, run: pnpm help list
> ```

What I meant is: is this issue still reproducible if you install the dependencies with `pnpm i --ignore-scripts`?

Anyway, I have copied your `package.json`, remove all private git dependencies and `file:` dependencies, and then run `pnpm i --ignore-scripts && pnpm ls`. It doesn't print any error.

**Comment by viceice** [comment]
i see the same issue on our renovate repo here: https://github.com/renovatebot/renovate/tree/build/pnpm

**Comment by viceice** [comment]
it happens on `"@renovate/eslint-plugin": "file:tools/eslint",`

![image](https://github.com/pnpm/pnpm/assets/1798109/5483915a-4fe9-4ae4-9e91-0ca40391bbd6)

```bat
> pnpm why dtrace-provider                                                                                                            ─╯
@renovate/eslint-plugin file:tools/eslint
 ERROR  Cannot read properties of undefined (reading 'startsWith')

pnpm: Cannot read properties of undefined (reading 'startsWith')
    at getPkgInfo (C:\Users\xxx\AppData\Local\node\corepack\pnpm\8.6.11\dist\pnpm.cjs:116083:20)
    at C:\Users\xxx\AppData\Local\node\corepack\pnpm\8.6.11\dist\pnpm.cjs:116479:59
    at Array.forEach (<anonymous>)
    at dependenciesHierarchyForPackage (C:\Users\xxx\AppData\Local\node\corepack\pnpm\8.6.11\dist\pnpm.cjs:116478:33)
    at async C:\Users\xxx\AppData\Local\node\corepack\pnpm\8.6.11\dist\pnpm.cjs:116442:11
    at async Promise.all (index 0)
    at async buildDependenciesHierarchy (C:\Users\xxx\AppData\Local\node\corepack\pnpm\8.6.11\dist\pnpm.cjs:116439:8)
    at async searchForPackages (C:\Users\xxx\AppData\Local\node\corepack\pnpm\8.6.11\dist\pnpm.cjs:117024:41)
    at async listForPackages (C:\Users\xxx\AppData\Local\node\corepack\pnpm\8.6.11\dist\pnpm.cjs:117045:20)
    at async C:\Users\xxx\AppData\Local\node\corepack\pnpm\8.6.11\dist\pnpm.cjs:219739:21
```

**Comment by viceice** [comment]
switching to `link:tools/eslint` solved the issue

**Comment by WestFarmer** [comment]
still see this with version 9.11.0

@zkochan
