### ISSUE TITLE
CI tests hanging on worker checkout

### ISSUE THREAD

**Issue by gluxon** [pnpm/pnpm#7038]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### Reproduction steps

See explanation below.

### Describe the Bug

Every once in a while, one of the pnpm server tests are failing with a timeout. https://github.com/pnpm/pnpm/pull/7030#issuecomment-1703577646

```
Summary of all failing tests
FAIL test/server.ts (754.525 s)
  ● installation using store server started in the background

    expect(received).resolves.not.toThrow()

    Received promise rejected instead of resolved
    Rejected to value: [Error: Command timed out after 180000ms]

      172 |   const project = prepare()
      173 |
    > 174 |   await expect(execPnpm(['install', 'is-positive@1.0.0', '--use-store-server'])).resolves.not.toThrow()
          |         ^
      175 |
      176 |   const serverJsonPath = path.resolve('..', 'store/v3/server/server.json')
      177 |

      at expect (../node_modules/.pnpm/expect@29.6.2/node_modules/expect/build/index.js:113:15)
      at Object.<anonymous> (test/server.ts:174:9)

```

I've added a bit more logging on my fork personal fork and see this is hanging on a worker checkout. https://github.com/gluxon/pnpm/actions/runs/6066843112

```
Got request at 1648.4297530003823: /importPackage
{
  opts: {
    filesResponse: { fromStore: false, filesIndex: [Object] },
    force: false,
    requiresBuild: false
  },
  to: '/home/runner/work/pnpm/pnpm_tmp/255eeed1e56aa82ceab173e4a7f88775/15/project/node_modules/.pnpm/is-positive@1.0.0/node_modules/is-positive'
}
Checking out worker

  91 |   expect(serverJson.connectionOptions.remotePrefix.indexOf('http://localhost:')).toBe(0) // TCP is used for communication'
  92 |
> 93 |   await expect(framework.exec(['install', 'is-positive@1.0.0'])).toBePassingServerTest()
      |                                                                  ^
  94 |
  95 |   expect(project.requireModule('is-positive')).toBeTruthy()
  96 |

  at Object.<anonymous> (test/server.ts:93:66)
```

We can see that this hangs on the "_Checking out worker_" line that I've manually added here. It never prints the worker finish line.

https://github.com/pnpm/pnpm/blob/2f65f190a9ab2b3e2f6ef8a551fcef1180b56857/store/package-store/src/storeController/index.ts#L70-L72

### Expected Behavior

CI jobs complete without hanging.

### Which Node.js version are you using?

20

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by gluxon** [comment]
@zkochan Wanted to give a heads up that something about checking out a worker seems to be causing the CI job hang. I'll keep looking if that's helpful.

**Comment by gluxon** [comment]
My current guess is that some other part of the pnpm server failed or deadlocked and isn't checking its worker back in.

**Comment by gluxon** [comment]
## Explanation

Added a bit more logging to `@rushstack/worker-pool` that shows the race condition at fault.

```
Checking out worker for "extract"
{ max: 1, active: 0, idle: 0, live: 0 }
WorkerPool: Checking in worker
WorkerPool: The worker pool is finishing.
Checking out worker for "link"
{ max: 1, active: 1, idle: 0, live: 1 }
WorkerPool: Checking out a new worker

  43 |   expect(typeof serverJson.pnpmVersion).toBe('string')
  44 |
> 45 |   await expect(framework.exec(['install', 'is-positive@1.0.0'])).toBePassingServerTest()
      |                                                                  ^
  46 |
  47 |   expect(project.requireModule('is-positive')).toBeTruthy()
  48 |

  at Object.<anonymous> (test/server.ts:45:66)
```

Here's why we're hanging when checking out a new worker:

1. We're checking out a worker for the `extract` operation.
2. When checking the worker back in, the worker pool is "finishing". The worker therefore gets destroyed instead of being added back to the idle queue.
3. While the worker exiting but before the `exit` event is fired, we check out a worker for the `link` operation.
4. This deadlocks since the we're waiting for an active worker to finish but it'll never become idle since it was just destroyed.

## Why is the worker pool "finishing"?

It's due to this line below. This line attempts to close the worker when the `pnpm` command finishes, but I don't think this is supposed to run for `pnpm server start`. It currently runs almost immediately on `pnpm server start`.

https://github.com/pnpm/pnpm/blob/131c723030ec4016274ca1cef33aadd66eb0e3b9/pnpm/src/main.ts#L300

## Next steps

It likely make sense to not call `await global.finishWorkers?.()` if the currently executed command is `pnpm server start` or similar. Still working out what the best condition to guard that against is.

In any case @zkochan @weyert, I think we have an explanation for the CI hangs we've been seeing. 🎉

**Comment by gluxon** [comment]
Opened a PR for one possible approach that can fix this. https://github.com/pnpm/pnpm/pull/7041#pullrequestreview-1608770462
