### ISSUE TITLE
Karma and Rollup - Not found provider for: framework:qunit

### ISSUE THREAD

**Issue by smialy** [pnpm/pnpm#720]
### Code to reproduce the issue:
> package.json

```json
"devDependencies": {
    "karma": "^1.3.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-firefox-launcher": "^1.0.0",
    "karma-qunit": "^1.2.1",
    "karma-rollup-plugin": "^0.2.4",
    "qunitjs": "^2.3.2",
    "rollup-plugin-node-resolve": "^3.0.0"
}
```
```
pnpm i  
```
```bash
  karma ^1.3.0                                                      1.6.0 ✓ 
  karma-chrome-launcher ^2.0.0                                      2.0.0 ✓ 
  karma-firefox-launcher ^1.0.0                                     1.0.1 ✓ 
  karma-qunit ^1.2.1                                                1.2.1 ✓ 
  karma-rollup-plugin ^0.2.4                                        0.2.4 ✓ 
  qunitjs ^2.3.2                                                    2.3.2 ✓ 
  rollup-plugin-node-resolve ^3.0.0                                 3.0.0 ✓ 
  WARN Skipping failed optional dependency registry.npmjs.org/fsevents/1.1.1 
```
### Expected behavior:
```bash
24 04 2017 18:18:41.249:WARN [karma]: No captured browser, open http://localhost:9876/
24 04 2017 18:18:41.273:INFO [karma]: Karma v1.6.0 server started at http://0.0.0.0:9876/
24 04 2017 18:18:41.274:INFO [launcher]: Launching browser Chrome with unlimited concurrency
24 04 2017 18:18:41.283:INFO [launcher]: Starting browser Chrome
24 04 2017 18:18:41.760:INFO [Chrome 58.0.3029 (Linux 0.0.0)]: Connected on socket 5Y3doLPSzjafXzdkAAAA with id 60096507
Chrome 58.0.3029 (Linux 0.0.0): Executed 8 of 8 SUCCESS (0.004 secs / 0.005 secs)
```
### Actual behavior:
```bash
karma start
24 04 2017 17:57:09.385:ERROR [preprocess]: Can not load "rollup", it is not registered!
  Perhaps you are missing some plugin?
./node_modules/.registry.npmjs.org/di/0.0.1/node_modules/di/lib/injector.js:9
      throw error('No provider for "' + name + '"!');
      ^

Error: No provider for "framework:qunit"! (Resolving: framework:qunit)
    at error (./node_modules/.registry.npmjs.org/di/0.0.1/node_modules/di/lib/injector.js:22:12)
    at Object.get (./node_modules/.registry.npmjs.org/di/0.0.1/node_modules/di/lib/injector.js:9:13)
    at Injector.get (./node_modules/.registry.npmjs.org/di/0.0.1/node_modules/di/lib/injector.js:54:19)
    at ./node_modules/.registry.npmjs.org/karma/1.6.0/node_modules/karma/lib/server.js:143:20
    at Array.forEach (native)
    at Server._start (./node_modules/.registry.npmjs.org/karma/1.6.0/node_modules/karma/lib/server.js:142:21)
    at Injector.invoke (./node_modules/.registry.npmjs.org/di/0.0.1/node_modules/di/lib/injector.js:75:15)
    at Server.start (./node_modules/.registry.npmjs.org/karma/1.6.0/node_modules/karma/lib/server.js:103:18)
    at Object.exports.run (./node_modules/.registry.npmjs.org/karma/1.6.0/node_modules/karma/lib/cli.js:280:26)
    at requireCliAndRun (~/.nvm/versions/node/v7.9.0/lib/node_modules/karma-cli/bin/karma:44:16)
    at ~/.nvm/versions/node/v7.9.0/lib/node_modules/karma-cli/bin/karma:54:12
    at ~/.nvm/versions/node/v7.9.0/lib/node_modules/karma-cli/node_modules/resolve/lib/async.js:43:21
    at ondir (~/.nvm/versions/node/v7.9.0/lib/node_modules/karma-cli/node_modules/resolve/lib/async.js:191:27)
    at ~/.nvm/versions/node/v7.9.0/lib/node_modules/karma-cli/node_modules/resolve/lib/async.js:158:39
    at onex (~/.nvm/versions/node/v7.9.0/lib/node_modules/karma-cli/node_modules/resolve/lib/async.js:101:22)
    at ~/.nvm/versions/node/v7.9.0/lib/node_modules/karma-cli/node_modules/resolve/lib/async.js:25:18
```

### Additional information:

 - `node -v` prints: v7.9.0
 - Linux

**Comment by zkochan** [comment]
Seems like you have some configuration. Like karma.conf.js, tests, etc. Could you please create a repo to reproduce the issue?

**Comment by smialy** [comment]
Yes, In my repo: https://github.com/smialy/sjs-metadata I'm using mix karma+rollup+qunit.

**Comment by zkochan** [comment]
Just pass in the plugins to karma Works for me this way. https://github.com/smialy/sjs-metadata/pull/1

**Comment by smialy** [comment]
Is it possible to fix only `pnpm` to resolve this problem?

**Comment by smialy** [comment]
ps. Thanks for quick help :+1:

**Comment by eankeen** [comment]
just a quick note i get this as well, with the jquery repository. i clone it, `pnpm i`, then `pnpm run test`, and receive a similar error;
```txt
...
Running "karma:main" (karma) task
25 04 2020 13:42:33.168:ERROR [karma-server]: Server start failed on port 9876: Error: No provider for "framework:qunit"! (Resolving: framework:qunit)
npm ERR! code ELIFECYCLE
npm ERR! errno 130
npm ERR! jquery@4.0.0-pre test: `npm run test:slim && npm run test:no-deprecated && grunt && grunt test:slow && grunt karma:main && grunt karma:esmodules && grunt karma:amd`
npm ERR! Exit status 130
npm ERR! 
npm ERR! Failed at the jquery@4.0.0-pre test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/edwin/.npm/_logs/2020-04-25T20_42_33_186Z-debug.log
```
it works fine with yarn

**Comment by zkochan** [comment]
yarn makes a flat node_modules. Probably it will work with `pnpm install --shamefully-hoist`

**Comment by eankeen** [comment]
thanks for the response! i removed the previous lockfile, nuked `node_modules`, and performed used `pnpm install --shamefully-hoist`, but i still seem to be getting the error...
```txt
Running "dist" task

Done.
Running "karma:main" (karma) task
25 04 2020 15:56:31.777:ERROR [karma-server]: Server start failed on port 9876: Error: No provider for "framework:qunit"! (Resolving: framework:qunit)
 ERROR  Test failed. See above for more details.
```
not sure what is going on, but it still doesn't seem to be finding the provider (i tried twice already)

**Comment by zkochan** [comment]
In worst case, if it doesn't work, use `node-linker=hoisted`

**Comment by mjeanroy** [comment]
Hi,

I just opened an issue, as the way karma try to detect plugins does not work with pnpm: see [here](https://github.com/karma-runner/karma/issues/3837) for the explanation (I think there are other issues with Karma that I'd like to investigate as well).
