### ISSUE TITLE
Astro build with Sentry causes build error when using pnpm 

### ISSUE THREAD

**Issue by Lms24** [pnpm/pnpm#7279]
### Verify latest release

- [x] I verified that the issue exists in the latest pnpm release

### pnpm version

8.10.2

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/Lms24/astro-sdk-pnpm-bug

### Reproduction steps

1. clone repo linked above and stay on the `main` branch
2. run `pnpm install && pnpm build`
3. build throws an error (see logs below)

This error only occurs when using pnpm. When installing and building with `npm` everything works. To test this yourself, checkout the `npm` branch:

5. run `git checkout npm && rm -rf node_modules`
6. run `npm install && npm run build`
7. project builds correctly

### Describe the Bug

Hi, Sentry SDK maintainer here 👋  Currently working on a Sentry SDK for Astro and I encountered a problem when using our SDK in combination with pnpm in an Astro project.
  
First of all, I'm  not sure if this is actually a pnpm bug. However, so far I can only reproduce the following build error in the linked reproduction when I use pnpm:

```
pnpm build
> astro-spotlight-sdk-bug-investigation@0.0.1 build 
> astro check && astro build

05:49:19 PM [build] Building static entrypoints...
[commonjs--resolver] Unexpected character '�' (Note that you need plugins to import files that are not JavaScript)
file: /<project-root>/node_modules/.pnpm/chokidar@3.5.3/node_modules/chokidar/index.js:1:0
1: ����@<�
          ��*...
   ^
4* 
  h���/System/Library/Frameworks/CoreFoundation.framework/Versions...
3: ���H��1�H���L���L���H�����L�E�L��H��1�����uH�E�H�[A^A_]��}f.�UH��AWAVSPI��H��I��H�H...
 error   Unexpected character '�' (Note that you need plugins to import files that are not JavaScript)
  File:
    /<project-root>/node_modules/.pnpm/chokidar@3.5.3/node_modules/chokidar/index.js
  Code:
    1: ����@<�
              ��*...
       ^
4*  2: 
  h���/System/Library/Frameworks/CoreFoundation.framework/Versions...
    3: ���H��1�H���L���L���H�����L�E�L��H��1�����uH�E�H�[A^A_]��}f.�UH��AWAVSPI��H��I��H�H...
  Stacktrace:
RollupError: Unexpected character '�' (Note that you need plugins to import files that are not JavaScript)
    at error (file:///<project-root>/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:2287:30)
    at Module.error (file:///<project-root>/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:13745:16)
    at Module.tryParse (file:///<project-root>/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:14476:25)
    at Module.setSource (file:///<project-root>/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:14077:39)
    at ModuleLoader.addModuleSource (file:///<project-root>/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:24649:20)

  Cause:
SyntaxError: Unexpected character '�' (1:0)
    at pp$4.raise (file:///<project-root>/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:21621:13)
    at pp.getTokenFromCode (file:///<project-root>/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:23556:8)
    at pp.readToken (file:///<project-root>/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:23243:15)
    at Parser.readToken (file:///<project-root>/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:25991:24)
    at pp.nextToken (file:///<project-root>/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:23234:15)
    at Parser.parse (file:///<project-root>/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:18657:8)
    at Function.parse (file:///<project-root>/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:18708:35)
    at Graph.contextParse (file:///<project-root>/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:25754:38)
    at Module.tryParse (file:///<project-root>/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:14473:31)
    at Module.setSource (file:///<project-root>/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:14077:39)
```

Using yarn or npm in the same project does not throw any error.  

### Expected Behavior

Running `pnpm build` should not cause a build error :P

As already said, it might very well be a problem on our end. But I can't find any clues as to what might be causing this. So I'd appreciate any hints. Cheers!

UPDATE: Please take a look at my first reply below for further details

### Which Node.js version are you using?

v18.17.1

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by Lms24** [comment]
I dug a little further and it seems that

- importing `@sentry/vite-plugin` in the Astro integration and
- importing `https` in the Node transport

are the two things that cause build errors when using `pnpm`.

The Vite plugin causes the chokidar error and the proxy agent causes this error:

> Failed to resolve entry for package “https”. The package may have incorrect main/module/exports specified in its package.json.

I further narrowed it down to `pnpm install` being the problematic part, not `pnpm build`. If I install deps with `pnpm`, building always fails; if I install with `npm`, building succeeds with both package managers.

So this leads me to believe that something in our package structure doesn’t play nicely with how `pnpm` installs packages.

Following [PNPM’s FAQ](https://pnpm.io/faq#pnpm-does-not-work-with-your-project-here), I tried fixing this with the proposed solutions:

1. (Solution 1) Setting `node-linker=hoisted` solves the issue, so it is in fact related to pnpm’s package linking structure in `node_modules`.
2. (Solution 2) Installing “missing dependencies” in the top level project partially resolves the issue:
    1. `pnpm add @sentry/vite-plugin` resolves the chokidar error
    2. `pnpm add https-proxy-agent` resolves the proxy agent error I got (similar to the https error above)
    3. This leaves me with the `https` error I got above. Can’t do much about this because obviously, `https` is a Node-internal module. 
    
    I don’t think this issue is related to missing dependencies. Something else is causing this.
    
3. (Solution 3) I didn’t try this yet because I don’t think it will solve this in a significantly different way than 1 or 2. 

Generally, I’m not sure why I need to install any of these dependencies. They’re all either direct or transitive dependencies of `@sentry/astro` and I double checked that they’re in fact mentioned as `dependencies` in the respective `package.json`s.
    

Also, all these solution require actions from our users after installing `@sentry/astro` which we need to avoid at all cost. (To repeat our package works completely fine with npm/yarn).

Does anyone have ideas what's going wrong here?

**Comment by Lms24** [comment]
Update: It seems to be related to Astro pulling in our package into their component compilation build. However, as to why the error occures specifically only with `pnpm`, neither the Astro team nor I have an idea. 

Astro's Vite plugin tries to detect if a package is an "astro component package" (i.e. contains `.astro`) files by checking for a bunch of heuristics in the project's `package.json`. These packages will be run through the Astro compiler. 

https://github.com/withastro/astro/blob/7c458514c06c95158245bba4fa3c254abd333f5a/packages/astro/src/core/create-vite.ts#L74-L89

Because our SDK package matches multiple of the used heuristics, it is added to the compiler build which causes errors because some of our packages make the build fail (not sure why/how). As already stated, this error is only caused when previously running `pnpm install`. All other package managers work fine.

**Comment by Lms24** [comment]
Reopening because I'd be interested if anyone has an idea as to why NPM is having troubles here.

**Comment by zkochan** [comment]
Closing for lack of a reproduction on a supported version.

This is a build that reaches a package it does not depend on. Please open a new issue with a reproduction if it still fails with current pnpm and a current version of that toolchain.

If you still hit this on the latest pnpm, please comment with a reproduction and we will reopen.

---
Written by an agent (Claude Code, claude-opus-5).
