### ISSUE TITLE
Suspected dependency structure conflict

### ISSUE THREAD

**Issue by Rawwhite** [pnpm/pnpm#7315]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

8.10.3

### Reproduction steps

I tried to use nuxt-primevue and xgplayer in the Nuxt framework for development, and then found that when these two packages were introduced in pnpm and yarn and used on the same page, a "MODULE_NOT_FOUND" error would occur, but in npm There will be no similar errors. I am not sure whether it is because of the loopholes in the advanced package structure of pnpm and yarn.

I try to use xgplayer's official code under a page
```
<div id="mse"></div>

import Player from 'xgplayer';
import 'xgplayer/dist/index.min.css';

onMounted(()=>{
  let player = new Player({
    id: 'mse',
    url: '//abc.com/**/*.mp4',
    height: '100%',
    width: '100%',
  });
})
```

I am using the nuxt-primevue and xgplayer modules installed with the following command
```shell
# nuxt-primevue
pnpm add -D nuxt-primevue
```
```shell
# xgplayer
pnpm add xgplayer
```

### Describe the Bug

Error: Cannot find module './closest'
Require stack:
- D:\Dream\nuxt\nuxt-primevue123\delegate
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)       
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at D:\Dream\nuxt\nuxt-primevue123\delegate:1:15
    at ViteNodeRunner.directRequest (file:///D:/Dream/nuxt/nuxt-primevue123/node_modules/.pnpm/vite-node@0.33.0/node_modules/vite-node/dist/client.mjs:341:11)  
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ViteNodeRunner.cachedRequest (file:///D:/Dream/nuxt/nuxt-primevue123/node_modules/.pnpm/vite-node@0.33.0/node_modules/vite-node/dist/client.mjs:197:14)
    at async ViteNodeRunner.dependencyRequest (file:///D:/Dream/nuxt/nuxt-primevue123/node_modules/.pnpm/vite-node@0.33.0/node_modules/vite-node/dist/client.mjs:231:12)
    at async D:\Dream\nuxt\nuxt-primevue123\node_modules\.pnpm\xgplayer@3.0.9_core-js@3.33.2\node_modules\xgplayer\es\plugin\plugin.js:3:31 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'D:\\Dream\\nuxt\\nuxt-primevue123\\delegate' ]
}
[Vue Router warn]: uncaught error during route navigation:
Error: Cannot find module './closest'
Require stack:
- D:\Dream\nuxt\nuxt-primevue123\delegate
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)       
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at D:\Dream\nuxt\nuxt-primevue123\delegate:1:15
    at ViteNodeRunner.directRequest (file:///D:/Dream/nuxt/nuxt-primevue123/node_modules/.pnpm/vite-node@0.33.0/node_modules/vite-node/dist/client.mjs:341:11)  
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ViteNodeRunner.cachedRequest (file:///D:/Dream/nuxt/nuxt-primevue123/node_modules/.pnpm/vite-node@0.33.0/node_modules/vite-node/dist/client.mjs:197:14)
    at async ViteNodeRunner.dependencyRequest (file:///D:/Dream/nuxt/nuxt-primevue123/node_modules/.pnpm/vite-node@0.33.0/node_modules/vite-node/dist/client.mjs:231:12)
    at async D:\Dream\nuxt\nuxt-primevue123\node_modules\.pnpm\xgplayer@3.0.9_core-js@3.33.2\node_modules\xgplayer\es\plugin\plugin.js:3:31 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'D:\\Dream\\nuxt\\nuxt-primevue123\\delegate' ]
}

### Expected Behavior

When using npm, these two modules will not cause this error.

### Which Node.js version are you using?

v21.1.0

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by nachoaldamav** [comment]
Does it work if you set `shamefully-hoist` in the `.npmrc` file to true?

reference: https://pnpm.io/npmrc#shamefully-hoist

**Comment by Rawwhite** [comment]
I think I wrote it correctly
My `.npmrc` file is as follows:
```
shamefully-hoist=true
auto-install-peers=true
strict-peer-dependencies=false
```

**Comment by nachoaldamav** [comment]
So it fails with the `shamefully-hoist`? If so, could you create a minimal reproduction so I can try to find why it fails? Thanks!

**Comment by Rawwhite** [comment]
Oh my god... I found that I can't reproduce this bug today. Maybe it's a problem with vue-router or maybe xgplayer has updated its version. Maybe it's not a problem with pnpm at all. Anyway, I just found out during my try that the problem has been solved! terribly sorry! What a waste of your time! Anyway thank you very much!

**Comment by nachoaldamav** [comment]
No problem!
