### ISSUE TITLE
Update fail to compare version using git

### ISSUE THREAD

**Issue by thib3113** [pnpm/pnpm#7415]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

8.12.1

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/thib3113/pnpm-issue-7415

In this repos, need to do (I already add overrides) : 
```
pnpm i
pnpm update -r --latest -i
```

### Reproduction steps

- add pnpm overrides using github dependency
- run `p update -r --latest -i` (without -r or -i seems to doesn't reproduce the bug)

### Describe the Bug

pnpm seems to try to compare the "github version" (as stored in the lockFile), with another version using semver

```
 ERROR  Invalid Version: github.com/thib3113/moleculer-web/9e13e537cd218585750d674c75b6d8666423be70(moleculer@0.14.31)

pnpm: Invalid Version: github.com/thib3113/moleculer-web/9e13e537cd218585750d674c75b6d8666423be70(moleculer@0.14.31)
    at new _SemVer (C:\Users\thib3113\AppData\Local\pnpm\global\5\.pnpm\pnpm@8.12.1\node_modules\pnpm\dist\pnpm.cjs:44104:17)
    at compare (C:\Users\thib3113\AppData\Local\pnpm\global\5\.pnpm\pnpm@8.12.1\node_modules\pnpm\dist\pnpm.cjs:44470:36)
    at Object.lt (C:\Users\thib3113\AppData\Local\pnpm\global\5\.pnpm\pnpm@8.12.1\node_modules\pnpm\dist\pnpm.cjs:44537:31)
    at C:\Users\thib3113\AppData\Local\pnpm\global\5\.pnpm\pnpm@8.12.1\node_modules\pnpm\dist\pnpm.cjs:192423:55
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 6)
    at async C:\Users\thib3113\AppData\Local\pnpm\global\5\.pnpm\pnpm@8.12.1\node_modules\pnpm\dist\pnpm.cjs:192374:9
    at async Promise.all (index 2)
    at async outdated (C:\Users\thib3113\AppData\Local\pnpm\global\5\.pnpm\pnpm@8.12.1\node_modules\pnpm\dist\pnpm.cjs:192367:7)
    at async Promise.all (index 6)
```

### Expected Behavior

other way to check git repository (not with semver ? but by git hash ?)

### Which Node.js version are you using?

20.8.0

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by KSXGitHub** [comment]
I cannot reproduce it in my Linux machine.

![screenshot](https://github.com/pnpm/pnpm/assets/11488886/682d1ed2-2654-4b46-b737-065cc53e8d08)

It suspect this only happens in Windows.

**Comment by thib3113** [comment]
@KSXGitHub can you tell us more about your linux machine ?

I just try on another machine (not clean), and got the same problem . But I also tryed on WSL, and got the nearly same error : 
```
Scope: all 2 workspace projects
 ERROR  Invalid Version: github.com/thib3113/moleculer/fa57f622653eb13f11f772847c27c30c2c8d617b

pnpm: Invalid Version: github.com/thib3113/moleculer/fa57f622653eb13f11f772847c27c30c2c8d617b
    at new _SemVer (/mnt/c/Users/thib3113/AppData/Local/pnpm/global/5/.pnpm/pnpm@8.12.1/node_modules/pnpm/dist/pnpm.cjs:44104:17)
    at compare (/mnt/c/Users/thib3113/AppData/Local/pnpm/global/5/.pnpm/pnpm@8.12.1/node_modules/pnpm/dist/pnpm.cjs:44470:36)
    at Object.lt (/mnt/c/Users/thib3113/AppData/Local/pnpm/global/5/.pnpm/pnpm@8.12.1/node_modules/pnpm/dist/pnpm.cjs:44537:31)
    at /mnt/c/Users/thib3113/AppData/Local/pnpm/global/5/.pnpm/pnpm@8.12.1/node_modules/pnpm/dist/pnpm.cjs:192423:55
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async /mnt/c/Users/thib3113/AppData/Local/pnpm/global/5/.pnpm/pnpm@8.12.1/node_modules/pnpm/dist/pnpm.cjs:192374:9
    at async Promise.all (index 1)
    at async outdated (/mnt/c/Users/thib3113/AppData/Local/pnpm/global/5/.pnpm/pnpm@8.12.1/node_modules/pnpm/dist/pnpm.cjs:192367:7)
    at async Promise.all (index 1)
```

( If I have some time, I will setup the debugger to check more on this error )

**Comment by KSXGitHub** [comment]
@thib3113 I just cloned your repo and run it. Is that the right step? I noticed that the root `package.json` already have overrides so I didn't add any.

**Comment by thib3113** [comment]
@KSXGitHub did you have install dependencies before ?
```
pnpm i
pnpm update -r --latest -i
```

Else, what is your linux distribution ? ( because, seems strange that it works on linux, but not on wsl )

**Comment by KSXGitHub** [comment]
I have located the cause of the error to be at a `semver.lt` calls:
https://github.com/pnpm/pnpm/blob/81e5ada3a9537be19a3a1edba57ed3829c76d602/reviewing/outdated/src/outdated.ts#L148

> ### Expected Behavior
> 
> other way to check git repository (not with semver ? but by git hash ?)

Your desired behavior is quite complex to implement right now, so I'll probably fix this error by ignoring non-semver values of `current`.

**Comment by thib3113** [comment]
@KSXGitHub I understand, no problem . maybe you can just ask if the person want to update ? without comparing value with next one ? and so we can check or not to do the update ?

**Comment by KSXGitHub** [comment]
Actually, it was caused by `parsePref` failing to detect non-semver versions: https://github.com/pnpm/pnpm/blob/81e5ada3a9537be19a3a1edba57ed3829c76d602/reviewing/outdated/src/outdated.ts#L112

The true fix is more complicated than I initially thought.
