### ISSUE TITLE
npm install -g @pnpm/exe fails on node:20 docker image

### ISSUE THREAD

**Issue by jordanburke** [pnpm/pnpm#7420]
### Last pnpm version that worked

8.12.1

### pnpm version

8.13.0

### Code to reproduce the issue

#10 [build-stage 2/8] RUN npm install -g @pnpm/exe

In a node:20 docker image.

### Expected behavior

It installs correctly

### Actual behavior

#10 [build-stage 2/8] RUN npm install -g @pnpm/exe
#10 1.896 npm notice 
#10 1.897 npm notice New patch version of npm available! 10.2.3 -> 10.2.5
#10 1.899 npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.2.5>
#10 1.901 npm notice Run `npm install -g npm@10.2.5` to update!
#10 1.903 npm notice 
#10 1.907 npm ERR! code 1
#10 1.910 npm ERR! path /usr/local/lib/node_modules/@pnpm/exe
#10 1.911 npm ERR! command failed
#10 1.911 npm ERR! command sh -c node setup.js
#10 1.912 npm ERR! node:fs:1841
#10 1.912 npm ERR!   binding.link(
#10 1.912 npm ERR!           ^
#10 1.913 npm ERR! 
#10 1.913 npm ERR! Error: ENOENT: no such file or directory, link '/usr/local/lib/node_modules/@pnpm/exe/node_modules/@pnpm/linux-x64/pnpm' -> '/usr/local/lib/node_modules/@pnpm/exe/pnpm'
#10 1.913 npm ERR!     at Object.linkSync (node:fs:1841:11)
#10 1.913 npm ERR!     at linkSync (/usr/local/lib/node_modules/@pnpm/exe/setup.js:37:13)
#10 1.913 npm ERR!     at Object.<anonymous> (/usr/local/lib/node_modules/@pnpm/exe/setup.js:19:3)
#10 1.913 npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1376:14)
#10 1.913 npm ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
#10 1.914 npm ERR!     at Module.load (node:internal/modules/cjs/loader:1207:32)
#10 1.914 npm ERR!     at Module._load (node:internal/modules/cjs/loader:1023:12)
#10 1.914 npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
#10 1.914 npm ERR!     at node:internal/main/run_main_module:28:49 {
#10 1.915 npm ERR!   errno: -2,
#10 1.915 npm ERR!   code: 'ENOENT',
#10 1.915 npm ERR!   syscall: 'link',
#10 1.915 npm ERR!   path: '/usr/local/lib/node_modules/@pnpm/exe/node_modules/@pnpm/linux-x64/pnpm',
#10 1.915 npm ERR!   dest: '/usr/local/lib/node_modules/@pnpm/exe/pnpm'
#10 1.915 npm ERR! }
#10 1.915 npm ERR! 
#10 1.915 npm ERR! Node.js v20.10.0
#10 1.917 
#10 1.917 npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2023-12-14T17_55_20_187Z-debug-0.log
#10 ERROR: process "/bin/sh -c npm install -g @pnpm/exe" did not complete successfully: exit code: 1

### Node.js version

20.x

### Operating System

Linux

**Comment by recumbented** [comment]
I'm facing this problem too.
Now, https://registry.npmjs.org/@pnpm/exe returns 
`"latest":"8.13.0"`
But 8.13.0 is not released yet.

**Comment by avonow** [comment]
I have received the same issue on `node:18.18.2`. 
Installing (reverting to) `@pnpm/exe@8.12.1` instead of `@pnpm/exe` also keeps it working for me 👍

**Comment by zkochan** [comment]
Maybe because I accidentally published from locally. But I have set latest to 8.12.1 and we'll see if the next version will be fine.

**Comment by ai** [comment]
asdf also has 8.13.0 latest and install it.

**Comment by LewisJEllis** [comment]
So `pnpm view pnpm versions` outputs a list including 8.13.0, and 8.13.0 shows up on [npmjs version list](https://www.npmjs.com/package/pnpm?activeTab=versions), while `pnpm info pnpm` shows 8.12.1 as latest - this all seems fine

but then something in a pipeline somewhere is reaching for 8.13.0 and ending up trying to download `https://github.com/pnpm/pnpm/releases/download/v8.13.0/pnpm-linux-x64` but not finding it - though it does find `https://github.com/pnpm/pnpm/releases/download/v8.12.1/pnpm-linux-x64` successfully. Notably the [GitHub releases page](https://github.com/pnpm/pnpm/releases) shows 8.12.1 as latest release, no GitHub release for 8.13.0

This seemingly-half-published 8.13.0 is throwing off a couple tools; admittedly these tools are probably partially to blame for not consulting the `latest` tag to reach for 8.12.1 instead of 8.13.0, and we're managing workarounds here anyway so not a showstopper. Nonetheless, it's a bit of a pothole in practice, and it would be really great if we could get 8.13.0 to exist as a GitHub release also, or for it to stop existing in npm.

Any chance of GitHub-releasing 8.13.0, or publishing/GitHub-releasing an 8.13.1?

**Comment by sanmai-NL** [comment]
@zkochan The last sentence in the previous message has a question, I think you may want to take note of it. 🙂

**Comment by zkochan** [comment]
This targets a part of pnpm that no longer exists, so closing.

`@pnpm/exe` is a native binary now and its install runs no Node.js setup script.

If you still hit this on the latest pnpm, please comment with a reproduction and we will reopen.

---
Written by an agent (Claude Code, claude-opus-5).
