### ISSUE TITLE
If install github package use pnpm, pnpm-lock.yml file should not use the format of git@github.com+xxx

### ISSUE THREAD

**Issue by oeyoews** [pnpm/pnpm#7517]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

8.14.1

### Which area(s) of pnpm are affected? (leave empty if unsure)

Dependencies resolver

### Reproduction steps

If you install the package from github, the format of pnpm-lock.yml does not seem to be deterministic, `git@github.com+xxx`, `git/github.com+xxx` `github.com/xxx`, these three All possibilities are possible, and obviously the first two will cause permission problems. (Is this a network problem?)

https://github.com/oeyoews/code-temp/commit/4a48acb75a0fdb2255bd8a46d336fe32c7eff4b2
https://github.com/oeyoews/code-temp/commit/4e7f8d0d2768252a24e3bb6b6a50555cf48ec625

### Describe the Bug

If you install the package from github, the format of pnpm-lock.yml does not seem to be deterministic, `git@github.com+xxx`, `git/github.com+xxx` `github.com/xxx`, these three All possibilities are possible, and obviously the first two will cause permission problems. (Is this a network problem?)

<img width="995" alt="image" src="https://github.com/pnpm/pnpm/assets/72405338/3c0b3716-7fc0-4988-9055-fe69c51456cd">
<img width="708" alt="image" src="https://github.com/pnpm/pnpm/assets/72405338/729fed50-effc-49cb-bc7b-1a599bb85e6b">

### Expected Behavior

git@ should not be used

### Which Node.js version are you using?

18.17.1

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by piraka9011** [comment]
Still an issue in `pnpm` 9.12.2, Node `20.11.0`

**Comment by sathishkannan162** [comment]
I am facing this issue.

**Comment by Mister-Hope** [comment]
Same, my issue is generally about github workflow or similar CIs.

As long as pnpm choose to use ssh, the installation will be expected to fail as the is not valid github private keys in ci env, and these keys also should NOT be attached.

```
ERROR  Command failed with exit code 128: /usr/bin/git clone git@github.com:xqq/webworkify-webpack.git /home/runner/setup-pnpm/node_modules/.bin/store/v3/tmp/_tmp_1806_d61cc271c1b5b05961f35800d24acb7c
Cloning into '/home/runner/setup-pnpm/node_modules/.bin/store/v3/tmp/_tmp_1806_d61cc271c1b5b05961f35800d24acb7c'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

pnpm: Command failed with exit code 128: /usr/bin/git clone git@github.com:xqq/webworkify-webpack.git /home/runner/setup-pnpm/node_modules/.bin/store/v3/tmp/_tmp_1806_d61cc271c1b5b05961f35800d24acb7c
Cloning into '/home/runner/setup-pnpm/node_modules/.bin/store/v3/tmp/_tmp_1806_d61cc271c1b5b05961f35800d24acb7c'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
    at makeError (/home/runner/setup-pnpm/node_modules/.pnpm/pnpm@9.15.1/node_modules/pnpm/dist/pnpm.cjs:17863:17)
    at handlePromise (/home/runner/setup-pnpm/node_modules/.pnpm/pnpm@9.15.1/node_modules/pnpm/dist/pnpm.cjs:18434:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async execGit (/home/runner/setup-pnpm/node_modules/.pnpm/pnpm@9.15.1/node_modules/pnpm/dist/pnpm.cjs:114189:7)
    at async gitFetcher (/home/runner/setup-pnpm/node_modules/.pnpm/pnpm@9.15.1/node_modules/pnpm/dist/pnpm.cjs:114144:11)
    at async fetcher (/home/runner/setup-pnpm/node_modules/.pnpm/pnpm@9.15.1/node_modules/pnpm/dist/pnpm.cjs:133706:[16](https://github.com/vuepress-theme-hope/vuepress-theme-hope/actions/runs/12532941022/job/34952136592#step:5:17))
    at async run (/home/runner/setup-pnpm/node_modules/.pnpm/pnpm@9.15.1/node_modules/pnpm/dist/pnpm.cjs:133156:23)
Error: Process completed with exit code 1.
```

**Comment by zkochan** [comment]
There was a related fix https://github.com/pnpm/pnpm/pull/8906 published in pnpm v9.15.2

**Comment by oeyoews** [comment]
Still not resolved? I'm using pnpm 10.2.1

**Comment by BlueGreenMagick** [comment]
> I think ssh should never be recommended as there are not supposed to be any valid ssh keys in ci.

SSH urls are useful for installing from private git repos. We also have our CI set up to use deploy keys (SSH key scoped to a single repository) to install from a private GitHub repo.

**Comment by Mister-Hope** [comment]
I didn't say ssh keys are useless, but for open source projects, we are not expecting to set ssh keys in CI as it affects forks workflows.

What I want to say is that public git repos shall never prefer to use git. However an existing or will convert any https links to ssh whenever a fetch fails, and that's not affordable. This opinion is also clearly represented in the original PR.

**Comment by oeyoews** [comment]
![Image](https://github.com/user-attachments/assets/087e747a-130a-4d9e-b64b-c1a037456300)
I don't know how many times this has happened. I'm tired. I may use other package management tools next time. This really affects the experience.
