### ISSUE TITLE
`pnpm publish` doesn't warn if npm is missing

### ISSUE THREAD

**Issue by TheFireBlast** [pnpm/pnpm#7657]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI

### Reproduction steps

Run `pnpm publish` without npm installed.

### Describe the Bug

pnpm simply crashes without a helpful error message.
```
$ pnpm publish
 ENOENT  spawnSync npm ENOENT

pnpm: spawnSync npm ENOENT
    at Object.spawnSync (node:internal/child_process:1124:20)
    at Object.spawnSync (node:child_process:876:24)
    at Function.spawnSync [as sync] (/usr/lib/node_modules/pnpm/dist/pnpm.cjs:24394:26)
    at runScriptSync (/usr/lib/node_modules/pnpm/dist/pnpm.cjs:123283:45)
    at runNpm (/usr/lib/node_modules/pnpm/dist/pnpm.cjs:123270:14)
    at publish (/usr/lib/node_modules/pnpm/dist/pnpm.cjs:208583:47)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.handler [as publish] (/usr/lib/node_modules/pnpm/dist/pnpm.cjs:208494:23)
    at async /usr/lib/node_modules/pnpm/dist/pnpm.cjs:219615:21
    at async main (/usr/lib/node_modules/pnpm/dist/pnpm.cjs:219578:34)
```

### Expected Behavior

Warn user that npm is not installed.

### Which Node.js version are you using?

21.6.1

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [X] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

Arch

**Comment by zkochan** [comment]
OK, we can fix this. We have some code already for detecting ENOENT errors. The `isErrorCommandNotFound` function in `exec.ts`

**Comment by zkochan** [comment]
This no longer reproduces on current pnpm, so closing.

`pnpm publish` talks to the registry itself now and does not run npm, so a missing npm cannot break it.

If you still hit this on the latest pnpm, please comment with a reproduction and we will reopen.

---
Written by an agent (Claude Code, claude-opus-5).
