### ISSUE TITLE
pnpm install fails if node_modules directory is symlinked

### ISSUE THREAD

**Issue by 6twenty** [pnpm/pnpm#7690]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI

### Reproduction steps

Assuming no `node_modules` directory currently exists:

```
mkdir node_modules_alt
ln -s node_modules_alt/ node_modules
ls -lah node_modules
> lrwxr-xr-x@ 1 mike  staff    17B 22 Feb 12:02 node_modules -> node_modules_alt/

pnpm install
> Lockfile is up to date, resolution step is skipped
> Packages: +642
> +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
>  ENOTDIR  ENOTDIR: not a directory, mkdir '/Users/mike/Code/test/node_modules'
> 
> pnpm: ENOTDIR: not a directory, mkdir '/Users/mike/Code/test/node_modules'
>     at async Object.mkdir (node:internal/fs/promises:855:10)
>     at async Promise.all (index 1)
>     at async headlessInstall (/Users/mike/.cache/node/corepack/pnpm/8.15.3/dist/pnpm.cjs:180356:9)
>     at async _install (/Users/mike/.cache/node/corepack/pnpm/8.15.3/dist/pnpm.cjs:187226:33)
>     at async mutateModules (/Users/mike/.cache/node/corepack/pnpm/8.15.3/dist/pnpm.cjs:187093:23)
>     at async install (/Users/mike/.cache/node/corepack/pnpm/8.15.3/dist/pnpm.cjs:187019:45)
>     at async installDeps (/Users/mike/.cache/node/corepack/pnpm/8.15.3/dist/pnpm.cjs:189042:31)
>     at async /Users/mike/.cache/node/corepack/pnpm/8.15.3/dist/pnpm.cjs:218493:21
>     at async main (/Users/mike/.cache/node/corepack/pnpm/8.15.3/dist/pnpm.cjs:218456:34)
>     at async runPnpm (/Users/mike/.cache/node/corepack/pnpm/8.15.3/dist/pnpm.cjs:218717:5)
> Progress: resolved 1, reused 0, downloaded 0, added 0
```

Additionally, at this point pnpm has also deleted the `node_modules_alt` directory too. 

### Describe the Bug

We currently use `npm` but are keen to migrate to `pnpm`. In our deploy environment the node_modules directory is shared between deploys, since each deploy also installs the packages necessary for that particular deploy. This makes deploys faster when packages haven't been touched, since the node_modules directory will already contain the required packages (and this is especially true for `pnpm` compared to `npm`). The directory is shared by symlinking it from a common directory outside of the deploy directory, but since this means that the local `node_modules` is actually a symlink, pnpm fails on install.

### Expected Behavior

NPM works fine with this symlinked setup, so expected behaviour is that pnpm is happy to install packages into `node_modules` even when that directory is a symlink to another directory.

### Which Node.js version are you using?

v20.5.1 (also tested with v21.6.2)

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [X] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

Ubuntu

**Comment by 6twenty** [comment]
Closing because it turns out NPM doesn't handle symlinked node_modules after all; it just doesn't complain about it. If `node_modules` is symlinked, NPM will wipe the symlink completely and just create a new regular directory.

In our case we had set up node_modules to be a common directory shared between deploys, but it turns out that this was never working – we just didn't know about it because NPM silently nuked the symlink.
