### ISSUE TITLE
URL.canParse Error in Corepack Brew Formula with pnpm and use-node-version

### ISSUE THREAD

**Issue by fantun3s** [pnpm/pnpm#7724]
### Verify latest release

- [ ] I verified that the issue exists in the latest pnpm release

### pnpm version

v8.15.4

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/fantun3s/corepack-pnpm-test

### Reproduction steps

Checkout the [repo](https://github.com/fantun3s/corepack-pnpm-test) and:

1. Install corepack using brew `brew install corepack`.
2. Use corepack to install the package manager for this project `corepack enable`.
3. Run `pnpm test` (this works).
4. Run `pnpm test:a` (this fails with the error).

### Describe the Bug

Getting a `Type Error: URL.canParse is not a function` error specifically when using `pnpm` from within npm scripts executed using `pnpm`. This occurs when using `corepack` to install the package manager for the project (`corepack enable`) and [pnpm node settings](https://pnpm.io/npmrc#nodejs-settings) via `use-node-version`.

When running a `npm script` using `pnpm` that is invoking `pnpm cli`, the latest seems to be using the node version defined in the `.npmrc` file instead of the global node version available.

**Observed Behaviour:**

- `pnpm -v` executed directly works successfully.
- `pnpm pnpm -v` (invoking `pnpm` from a npm script) results in the error.

![image](https://github.com/pnpm/pnpm/assets/2700043/a8882c7b-c78a-48ac-9076-06426798865d)

**Suspected Cause:**

- Potentially incorrect Node.js version inheritance when invoking `pnpm` from within a npm script.
- Possible conflict between corepack's Node.js dependency and `use-node-version` within nested `pnpm` calls.

### Expected Behavior

- Both commands should run successfully, pnpm CLI should always be executed with the node version specified by the corepack brew formula (global node version).

### Which Node.js version are you using?

16.20.2

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by christowiz** [comment]
I had the same issue except I was unable to execute any PNPM command due to the same `URL.canParse is not a function` error.  I am using Corepack.  I uninstalled/reinstalled Corepack but this didn't clean up the `~/Library/pnpm` files.

I eventually had to unlink and create two new symlinks in `~/Library/pnpm`
- `node` 
- `nodejs_current`

**Comment by fantun3s** [comment]
AFAIK this issue still happens, and I am able to reproduce it without using brew to install corepack.
Steps:
- Install NodeJS 20.12.x using nvm 
- Run `corepack enable` in the top directory of the pnpm repo (the one I provided in this ticket)
- Run `pnpm pnpm -v`. It will fail with the URL.canParse issue.

**Comment by jono-pov** [comment]
I've encountered this same issue.

It doesn't seem to happen in my local Windows dev environment (either running in PowerShell or Git Bash), but it _does_ happen on our Ubuntu-based Azure CI/CD pipeline.

Both environments are running Node v20.12.2.

**Comment by jono-pov** [comment]
Okay, I may be wrong about this. After removing corepack from the equation, I [started getting errors indicating that Pipelines is lying to me about the node version it's using](https://stackoverflow.com/questions/78417450/azure-pipelines-node-version-discrepancy).

**Comment by alxndrsn** [comment]
> My team just experienced a similar issue unrelated to PNPM. It was happening in our legacy repo using Yarn. The solution seems to be upgrading Node from `18.12.1` to `18.17.0`.

Apologies for another non-`pnpm` post, but as this Issue is still the only (legitimate) hit for this error message on google, I'll add:

I've also been seeing this issue on GitHub Actions with yarn & corepack, with node `18.16.1`.  Being less specific about node version (moved to 18.x) fixed it for me.

**Comment by christowiz** [comment]
I found that I was unable to switch my Node versions once I started to receive this error and that it only happens when using any version of Node 18.12.x or lower.  I have to manually edit a couple symlinks in my `~/Library/pnpm` directory: `node` and `nodejs_current`.  Once I linked those to a previously installed version (higher than 18.12.x) `pnpm env use --global` seems to work normally again, that is, until I have to switch to Node 18.12.x again.

![image](https://github.com/pnpm/pnpm/assets/597282/62ac7ec3-fb8a-4d92-8c58-d05ecaec128d)

**Comment by Xotabu4** [comment]
+1 having this issue on node 18.20.2

**Comment by loopy3025** [comment]
Same thing is happening on our IDEs. I guess the IDEs run 18.20.2 and when I use nvm to install and use any version of 16x, we are getting 

```
/home/ide/.nvm/versions/node/v16.13.1/lib/node_modules/corepack/dist/lib/corepack.cjs:23253
  const isURL = URL.canParse(range);
TypeError: URL.canParse is not a function
    at parseSpec (/home/ide/.nvm/versions/node/v16.13.1/lib/node_modules/corepack/dist/lib/corepack.cjs:23253:21)
    at loadSpec (/home/ide/.nvm/versions/node/v16.13.1/lib/node_modules/corepack/dist/lib/corepack.cjs:23316:11)
    at async Engine.findProjectSpec (/home/ide/.nvm/versions/node/v16.13.1/lib/node_modules/corepack/dist/lib/corepack.cjs:23490:22)
    at async Engine.executePackageManagerRequest (/home/ide/.nvm/versions/node/v16.13.1/lib/node_modules/corepack/dist/lib/corepack.cjs:23542:24)
    at async Object.runMain (/home/ide/.nvm/versions/node/v16.13.1/lib/node_modules/corepack/dist/lib/corepack.cjs:24235:5)
```

**Comment by RunOrVeith** [comment]
Same is happening to me, but only in our CI pipeline inside of a Docker image, and only in one module.
I have a monorepo with one main app and a bunch of module packages.
I am using `URL.canParse` fine in the code inside the main app, but it crashes inside the tests of the other module and also in the tests of the main app that call the function in the other module.

Everything runs fine locally.

**Comment by JDIZM** [comment]
Having the same issue on node 16.18.1. The issue appears to be the corepack install is trying to use `URL.canParse` which is only available in node > 18. Corepack seems to be using the symlinks from the wrong location as corepack for me is installed via homebrew.

```
 pnpm -v
/opt/homebrew/Cellar/corepack/0.29.3/libexec/lib/node_modules/corepack/dist/lib/corepack.cjs:22098
  const isURL = URL.canParse(range);

TypeError: URL.canParse is not a function
    at parseSpec (/opt/homebrew/Cellar/corepack/0.29.3/libexec/lib/node_modules/corepack/dist/lib/corepack.cjs:22098:21)
```


The solution for me was to uninstall corepack from homebrew and install it in npm globally and allow my node versions to manage it, while they are managed by volta

```
~ which corepack         
/opt/homebrew/bin/corepack

~ brew uninstall corepack
Uninstalling /opt/homebrew/Cellar/corepack/0.29.3... (69 files, 1012.5KB)

~ npm i -g corepack 

~ corepack use pnpm@9.4.0 

~ which pnpm
/Users/jdizm/.volta/bin/pnpm
```

**Comment by mariuspatrick** [comment]
`URL.canParse` is not available from node > 18, but from 18.17.0 on

**Comment by einarolafs** [comment]
I'm having this saem issue on MacOS 15.0.1. 

I have node installed via brew, did not install corepack independently via brew, but just used the one that comes with node.

When I used pnpm to set node version to v18.14.0, I can no longer set any other versions as they fail with the message mentioned in this issue.

Here is the specific error message I am seeing:

```typescript
pnpm env use 19.9.0
/opt/homebrew/Cellar/node/23.1.0_1/lib/node_modules/corepack/dist/lib/corepack.cjs:21738
  return !URL.canParse(descriptor.range);
              ^

TypeError: URL.canParse is not a function
    at isSupportedPackageManagerDescriptor (/opt/homebrew/Cellar/node/23.1.0_1/lib/node_modules/corepack/dist/lib/corepack.cjs:21738:15)
    at Engine.resolveDescriptor (/opt/homebrew/Cellar/node/23.1.0_1/lib/node_modules/corepack/dist/lib/corepack.cjs:22414:10)
    at Engine.executePackageManagerRequest (/opt/homebrew/Cellar/node/23.1.0_1/lib/node_modules/corepack/dist/lib/corepack.cjs:22407:33)
    at async Object.runMain (/opt/homebrew/Cellar/node/23.1.0_1/lib/node_modules/corepack/dist/lib/corepack.cjs:23096:5)

Node.js v18.14.0
```

I was able to fix this problem by deleting the `~/.nvm` directory created by `pnpm` to install this version and reinstall `brew reinstall node`

**Comment by zkochan** [comment]
This targets a part of pnpm that no longer exists, so closing.

This was an old Node.js running the Node.js-based CLI. pnpm is a native binary now and does not depend on the Node.js it runs next to.

If you still hit this on the latest pnpm, please comment with a reproduction and we will reopen.

---
Written by an agent (Claude Code, claude-opus-5).
