### ISSUE TITLE
The requested module '/_nuxt/node_modules/.pnpm/@firebase+component@0.6.5/node_modules/@firebase/component/dist/index.cjs.js' does not provide an export named 'Component' (at index.esm2017.js:2:10)

### ISSUE THREAD

**Issue by jemdiggity** [pnpm/pnpm#7729]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/jemdiggity/nuxt-vuefire-pnpm

### Reproduction steps

```
gh repo clone jemdiggity/nuxt-vuefire-pnpm
cd nuxt-vuefire-pnpm
pnpm i
pnpm dev -o
```

### Describe the Bug

In Chrome, the console logs:
```
Uncaught SyntaxError: The requested module '/_nuxt/node_modules/.pnpm/@firebase+component@0.6.5/node_modules/@firebase/component/dist/index.cjs.js' does not provide an export named 'Component' (at index.esm2017.js:2:10)
```
Nothing is rendered in the browser.

### Expected Behavior

If you use npm instead pnpm, it works fine and the starter template is rendered.
```
gh repo clone jemdiggity/nuxt-vuefire-pnpm
cd nuxt-vuefire-pnpm
npm i
npm run dev
```

### Which Node.js version are you using?

18.18.2

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by jemdiggity** [comment]
Adding a .npmrc file with `shamefully-hoist=true`, fixes the issue.
