### ISSUE TITLE
Running `pnpm install` over a broken lockfile results in dependencies getting upgraded to latest in range when removing `node_modules` beforehand

### ISSUE THREAD

**Issue by mcmxcdev** [pnpm/pnpm#7863]
### Verify latest release

- [ ] I verified that the issue exists in the latest pnpm release

### pnpm version

8.14.1

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI, Lockfile

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/mcmxcdev/pnpm-install-repro

`/@ampproject/remapping@2.3.0` entry was duplicated by hand intentionally to produce broken lockfile

### Reproduction steps

When working on the reproduction, I noticed this behavior:

0. Duplicate a lockfile entry to break it (already part of the linked GitHub repro)
1. run `pnpm install` 
2. check the git diff and expect only the broken part of lockfile is updated
3. undo any git changes back to broken lockfile state
4. run `rm -rf node_modules && pnpm install` -> the broken part of lockfile is updated, but also any deps are upgraded to latest allowed (unexpected, in the linked GitHub repro, `storybook` gets upgraded from 8.0.2 to 8.0.6+)
5. undo any git changes back to broken lockfile state
6. run `pnpm install` -> now not only the broken part of lockfile is updated, but also any deps are upgraded to latest allowed too (unexpected since it is the same command as step 2 but differs in result)

### Describe the Bug

A dev of our org ended up accidentally merging a broken lockfile to `main` (it had duplicated deps showing up) after a wrongly resolved merge conflict.

We both had `node_modules` locally but we both ran different commands with different outcome:
- I simply ran `pnpm i` on `main` which made minimal changes to make the lockfile valid again
- He ran `rm -rf node_modules && pnpm i` and ended up changes to make the lockfile valid again BUT also with versions updating itself to latest available etc

I was then able to locally reproduce the diverging result when removing `node_modules` beforehand as well.

### Expected Behavior

I would expect only the broken parts of the lockfile to be replaced and dependencies stay locked to their version.

### Which Node.js version are you using?

20.10.0

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [X] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

Ubuntu 23.10

**Comment by uaenaTzx** [comment]
I've encountered a similar issue as well. I believe that deleting `node_modules` and reinstalling may cause `pnpm` to check for the latest available versions and potentially update the lockfile to reflect these changes, which might not be the expected behavior in all cases.

I can provide a temporary workaround by executing a script to perform relevant checks before committing:

```javascript
import { execSync } from 'child_process';
import { chalk } from 'zx';

try {
  execSync('pnpm install --frozen-lockfile', { stdio: 'inherit' });
  console.log(
    chalk.green('✅ The pnpm-lock.yaml is up-to-date. No updates are needed.')
  );
} catch (error) {
  console.error(
    chalk.red(
      '🚨 Detected that pnpm-lock.yaml needs an update. Please run pnpm install and commit the updated lockfile.'
    )
  );
  process.exit(1);
}
```

**Comment by donghhan** [comment]
This issue also happened to me as well 

- OS: Mac Sonoma 14.4.1
- `pnpm` version: 8.15.1
- Libraries that have been affected
    - `@prisma/client`: `5.12.0`
    - `next-intl`: `^3.9.2`

```
 ⨯ Error: Cannot find module '.prisma/client/default'
Require stack:
- /Users/apensia/dev/wownexus/node_modules/.pnpm/@prisma+client@5.12.0_prisma@5.12.1/node_modules/@prisma/client/default.js
- /Users/apensia/dev/wownexus/.next/server/app/[locale]/profile/page.js
- /Users/apensia/dev/wownexus/node_modules/.pnpm/next@14.1.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/require.js
- /Users/apensia/dev/wownexus/node_modules/.pnpm/next@14.1.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/load-components.js
- /Users/apensia/dev/wownexus/node_modules/.pnpm/next@14.1.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/utils.js
- /Users/apensia/dev/wownexus/node_modules/.pnpm/next@14.1.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/dev/static-paths-worker.js
- /Users/apensia/dev/wownexus/node_modules/.pnpm/next@14.1.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/jest-worker/processChild.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at /Users/apensia/dev/wownexus/node_modules/.pnpm/next@14.1.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/require-hook.js:55:36
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at mod.require (/Users/apensia/dev/wownexus/node_modules/.pnpm/next@14.1.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/require-hook.js:65:28)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/Users/apensia/dev/wownexus/node_modules/.pnpm/@prisma+client@5.12.0_prisma@5.12.1/node_modules/@prisma/client/default.js:2:6)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32) {
  type: 'Error',
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/apensia/dev/wownexus/node_modules/.pnpm/@prisma+client@5.12.0_prisma@5.12.1/node_modules/@prisma/client/default.js',
    '/Users/apensia/dev/wownexus/.next/server/app/[locale]/profile/page.js',
    '/Users/apensia/dev/wownexus/node_modules/.pnpm/next@14.1.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/require.js',
    '/Users/apensia/dev/wownexus/node_modules/.pnpm/next@14.1.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/load-components.js',
    '/Users/apensia/dev/wownexus/node_modules/.pnpm/next@14.1.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/utils.js',
    '/Users/apensia/dev/wownexus/node_modules/.pnpm/next@14.1.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/dev/static-paths-worker.js',
    '/Users/apensia/dev/wownexus/node_modules/.pnpm/next@14.1.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/jest-worker/processChild.js'
  ],
  page: '/us/profile'
}
```

**Comment by zkochan** [comment]
Closing: current pnpm covers this.

pnpm reports a lockfile it cannot read and then resolves again, because a broken lockfile cannot be trusted. `pnpm install --frozen-lockfile` fails with ERR_PNPM_BROKEN_LOCKFILE instead of resolving.

If you still hit this on the latest pnpm, please comment with a reproduction and we will reopen.

---
Written by an agent (Claude Code, claude-opus-5).
