### ISSUE TITLE
Can't generate shell completion (install from standalone install script)

### ISSUE THREAD

**Issue by mimikun** [pnpm/pnpm#7948]
### Verify latest release

- [ ] I verified that the issue exists in the latest pnpm release

### pnpm version

v9.0.1

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI

### 1. Install from standalone script

```fish
curl -fsSL https://get.pnpm.io/install.sh | sh -
```

### 2. restart shell

```fish
exec $SHELL -l
```

### 3. generate completion

```fish
pnpm completion fish
```

### Describe the Bug

get an error:

```fish
❯ pnpm completion fish
 ENOENT  File '/**/dist/templates/completion.fish' was not included into executable at compilation stage. Please recompile adding it as asset or script.

pnpm: File '/**/dist/templates/completion.fish' was not included into executable at compilation stage. Please recompile
adding it as asset or script.
    at error_ENOENT (pkg/prelude/bootstrap.js:656:19)
    at readFileFromSnapshot (pkg/prelude/bootstrap.js:1045:29)
    at readFile (pkg/prelude/bootstrap.js:1116:5)
    at node:internal/util:362:7
    at new Promise (<anonymous>)
    at readFile (node:internal/util:348:12)
    at Object.getCompletionScript (/snapshot/dist/pnpm.cjs)
    at getCompletionScript (/snapshot/dist/pnpm.cjs)
    at Object.handler [as completion] (/snapshot/dist/pnpm.cjs)
    at /snapshot/dist/pnpm.cjs

```

### Expected Behavior

Shell completion generate

e.g.

```fish
###-begin-pnpm-completion-###
function _pnpm_completion
  set cmd (commandline -o)
  set cursor (commandline -C)
  set words (count $cmd)

  set completions (eval env DEBUG=\"" \"" COMP_CWORD=\""$words\"" COMP_LINE=\""$cmd \"" COMP_POINT=\""$cursor\"" SHELL=fish pnpm completion-server -- $cmd)

  if [ "$completions" = "__tabtab_complete_files__" ]
    set -l matches (commandline -ct)*
    if [ -n "$matches" ]
      __fish_complete_path (commandline -ct)
    end
  else
    for completion in $completions
      echo -e $completion
    end
  end
end

complete -f -d 'pnpm' -c pnpm -a "(_pnpm_completion)"
###-end-pnpm-completion-###
```

### Which Node.js version are you using?

v20.12.2

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [X] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

Ubuntu 22.04 (WSL)

**Comment by MilanJa** [comment]
Same thing for windows 10:

```pwsh
❯ [System.Environment]::OSVersion

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.22631.0 Microsoft Windows NT 10.0.22631.0


❯ pnpm completion pwsh
 ENOENT  File 'C:\**\dist\templates\completion.ps1' was not included into executable at compilation stage. Please recompile adding it as asset or script.

pnpm: File 'C:\**\dist\templates\completion.ps1' was not included into executable at compilation stage. Please recompile adding it as asset or script.
    at error_ENOENT (pkg/prelude/bootstrap.js:656:19)
    at readFileFromSnapshot (pkg/prelude/bootstrap.js:1045:29)
    at readFile (pkg/prelude/bootstrap.js:1116:5)
    at node:internal/util:362:7
    at new Promise (<anonymous>)
    at readFile (node:internal/util:348:12)
    at Object.getCompletionScript (C:\snapshot\dist\pnpm.cjs)
    at getCompletionScript (C:\snapshot\dist\pnpm.cjs)
    at Object.handler [as completion] (C:\snapshot\dist\pnpm.cjs)
    at C:\snapshot\dist\pnpm.cjs
```
