### ISSUE TITLE
Peer deps issue errors are not reported

### ISSUE THREAD

**Issue by moltar** [pnpm/pnpm#7978]
### Verify latest release

- [ ] I verified that the issue exists in the latest pnpm release

### pnpm version

9.0.4

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI

### Link to the code that reproduces this issue or a replay of the bug

N/A

### Reproduction steps

Not truly sure how to repro.

### Describe the Bug

Running `pnpm i --no-frozen-lockfile` silently fails, with an exit code `1` when there are peer issues.

When I run `pnpm i --no-frozen-lockfile --reporter ndjson`, I see the error `ERR_PNPM_PEER_DEP_ISSUES`.

I won't paste the entire log entry, as it's massive.

```
vite","version":"5.0.7"}],"optional":true,"wantedRange":"^5.4.0"},{"parents":[{"name":"vite","version":"5.2.9"}],"optional":true,"wantedRange":"^5.4.0"}],"@edge-runtime/vm":[{"parents":[{"name":"vitest","version":"1.5.0"}],"optional":true,"wantedRange":"*"}],"happy-dom":[{"parents":[{"name":"vitest","version":"1.5.0"}],"optional":true,"wantedRange":"*"}],"jsdom":[{"parents":[{"name":"vitest","version":"1.5.0"}],"optional":true,"wantedRange":"*"}],"@vitest/ui":[{"parents":[{"name":"vitest","version":"1.5.0"}],"optional":true,"wantedRange":"1.5.0"}],"@vitest/browser":[{"parents":[{"name":"vitest","version":"1.5.0"}],"optional":true,"wantedRange":"1.5.0"}]},"conflicts":[],"intersections":{}},"packages/aws-region":{"bad":{},"missing":{"aws-crt":[{"parents":[{"name":"@aws-sdk/client-ssm","version":"3.554.0"},{"name":"@aws-sdk/client-sts","version":"3.554.0"},{"name":"@aws-sdk/util-user-agent-node","version":"3.535.0"}],"optional":true,"wantedRange":">=1.0.0"}],"supports-color":[{"parents":[{"name":"@stylistic/eslint-plugin","version":"1.7.0"},{"name":"@stylistic/eslint-plugin-plus","version":"1.7.0"},{"name":"@typescript-eslint/utils","version":"6.21.0"},{"name":"@typescript-eslint/typescript-estree","version":"6.21.0"},{"name":"debug","version":"4.3.4"}],"optional":true,"wantedRange":"*"},{"parents":[{"name":"eslint-import-resolver-node","version":"0.3.9"},{"name":"debug","version":"3.2.7"}],"optional":true,"wantedRange":"*"}],"eslint-import-resolver-webpack":[{"parents":[{"name":"eslint-import-resolver-typescript","version":"3.6.1"},{"name":"eslint-module-utils","version":"2.8.0"}],"optional":true,"wantedRange":"*"}],"ts-node":[{"parents":[{"name":"tsup","version":"8.0.2"},{"name":"postcss-load-config","version":"4.0.2"}],"optional":true,"wantedRange":">=9.0.0"}],"@swc/core":[{"parents":[{"name":"tsup","version":"8.0.2"}],"optional":true,"wantedRange":"^1"}],"@microsoft/api-extractor":[{"parents":[{"name":"tsup","version":"8.0.2"}],"optional":true,"wantedRange":"^7.36.0"}]},"conflicts":[],"intersections":{}}},"name":"pnpm","err":{"name":"pnpm","message":"Unmet peer dependencies","code":"ERR_PNPM_PEER_DEP_ISSUES","stack":"pnpm: Unmet peer dependencies\n    at reportPeerDependencyIssues (/Users/foo/.cache/node/corepack/pnpm/9.0.4/dist/pnpm.cjs:180686:15)\n    at _installInContext (/Users/foo/.cache/node/corepack/pnpm/9.0.4/dist/pnpm.cjs:181602:67)\n    at async installInContext (/Users/foo/.cache/node/corepack/pnpm/9.0.4/dist/pnpm.cjs:181652:16)\n    at async _install (/Users/foo/.cache/node/corepack/pnpm/9.0.4/dist/pnpm.cjs:181165:25)\n    at async mutateModules (/Users/foo/.cache/node/corepack/pnpm/9.0.4/dist/pnpm.cjs:180843:23)\n    at async recursive (/Users/foo/.cache/node/corepack/pnpm/9.0.4/dist/pnpm.cjs:182382:50)\n    at async installDeps (/Users/foo/.cache/node/corepack/pnpm/9.0.4/dist/pnpm.cjs:182685:11)\n    at async /Users/foo/.cache/node/corepack/pnpm/9.0.4/dist/pnpm.cjs:211540:21\n    at async main (/Users/foo/.cache/node/corepack/pnpm/9.0.4/dist/pnpm.cjs:211503:34)\n    at async runPnpm (/Users/foo/.cache/node/corepack/pnpm/9.0.4/dist/pnpm.cjs:211754:5)"}}
```

### Expected Behavior

Print _some_ error.

### Which Node.js version are you using?

v18.19.0

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by moltar** [comment]
Here's an easier to read last log line. I folded `issuesByProjects` as it's a huge blob of JSON.

![screenshot-20240419T211027-MqZbNE5d@2x](https://github.com/pnpm/pnpm/assets/491247/d60ad6eb-1adb-4709-8005-712648f22d9e)

**Comment by moltar** [comment]
It's full of entries like this:

![screenshot-20240419T211252-FDCmU1QZ@2x](https://github.com/pnpm/pnpm/assets/491247/38b9516c-5dc7-4609-9569-71440806c439)

Btw, I have `strict-peer-dependencies=true` on in `.npmrc`

**Comment by moltar** [comment]
Closing, as I think the cause is this #7952

**Comment by moltar** [comment]
Wait, no, the issue is related, but not the cause. The lack of reporting of issues is still a problem.

**Comment by Yurickh** [comment]
I'm still seeing this issue at pnpm@9.12.2.

In my case, I've even added these to `pnpm.peerDependencyRules.allowedVersions` in my `package.json`, but this just silenced the report, while the `install` script still returns 1.

**Comment by 47hao** [comment]
Did some digging; this bug occurs whenever `strict-peer-dependencies` is enabled, there are peerdeps issues, and they're all patched via `peerDependencyRules`. [Here's a simple repro](https://github.com/47hao/pnpm-issue-repro) where I added conflicting peerdeps and patched them, resulting in the error. https://github.com/pnpm/pnpm/issues/8382 shows that `allowAny` has the same effect. 

The codepath is as follows:
- Issues with peerDependencies are detected, so [an error is thrown](https://github.com/pnpm/pnpm/blob/ddfd640033bdfd9076f67b4d95e1e1ad851c0291/pkg-manager/core/src/install/reportPeerDependencyIssues.ts#L21). This is based on an unprocessed list of every peer dependency that is not directly fulfilled, without considering `peerDependencyRules` or other info.
- [`reportPeerDependencyIssuesError`](https://github.com/pnpm/pnpm/blob/ddfd640033bdfd9076f67b4d95e1e1ad851c0291/cli/default-reporter/src/reportError.ts#L422) calls [`renderPeerIssues`](https://github.com/pnpm/pnpm/blob/ddfd640033bdfd9076f67b4d95e1e1ad851c0291/packages/render-peer-issues/src/index.ts#L14), which processes the peer dependency issues in order to print errors. Render sees that none of the peer issues in `peerDependencyIssuesByProjects` are errors  by reading peerDependencyRules, and renders the empty string. The report fn sees nothing is rendered, and returns `null`. As a result, nothing is reported.
- Program ends with exit code 1 since the error was thrown.

The real problem is that an error is thrown before the raw peerdep issues are processed to see if any are relevant. The processing step should occur before the error throw, and throwing the error should be conditioned on a non-empty set of issues. 

Of note - this issue is new to pnpm v9 because `peerDependencyRules` are now reporting-only, instead of direct patches. This moved `peerDependencyRules`'s effects from upstream of the error throw to downstream of it.
