### ISSUE TITLE
Couldn't read package.json of local dependency

### ISSUE THREAD

**Issue by NullVoxPopuli** [pnpm/pnpm#8029]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

9.0.6

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/universal-ember/ember-primitives/pull/257

### Reproduction steps

```bash
git clone git@github.com:universal-ember/ember-primitives.git
cd ember-primitives
git checkout repro-for-pnpm
pnpm i
```

### Describe the Bug

This error:
```
❯ pnpm i
Scope: all 5 workspace projects
<repo>/docs-app:
 ERROR  Couldn't read package.json of local dependency ember-primitives@workspace:*

This error happened while installing a direct dependency of <repo>/docs-app

pnpm: Couldn't read package.json of local dependency ember-primitives@workspace:*
    at resolveAndFetch (🏠/.volta/tools/image/pnpm/9.0.6/dist/pnpm.cjs:130917:17)
    at resolveDependency (🏠/.volta/tools/image/pnpm/9.0.6/dist/pnpm.cjs:175399:49)
    at async resolveDependenciesOfDependency (🏠/.volta/tools/image/pnpm/9.0.6/dist/pnpm.cjs:175169:39)
    at async Promise.all (index 80)
    at async 🏠/.volta/tools/image/pnpm/9.0.6/dist/pnpm.cjs:174930:48
    at async Promise.all (index 1)
    at async resolveDependenciesOfImporters (🏠/.volta/tools/image/pnpm/9.0.6/dist/pnpm.cjs:174919:30)
    at async resolveRootDependencies (🏠/.volta/tools/image/pnpm/9.0.6/dist/pnpm.cjs:174859:74)
    at async resolveDependencyTree (🏠/.volta/tools/image/pnpm/9.0.6/dist/pnpm.cjs:175848:49)
    at async resolveDependencies (🏠/.volta/tools/image/pnpm/9.0.6/dist/pnpm.cjs:178373:155)
```

### Expected Behavior

no error

### Which Node.js version are you using?

20.12.2

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [X] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

Ubuntu

**Comment by NullVoxPopuli** [comment]
if I delete the lockfile, `pnpm i` works :sweat_smile:

**Comment by NullVoxPopuli** [comment]
the lockfile went from version 6 to version 9 -- so maybe this is just a requirement of pnpm 9 :shrug: idk -- good enough for me!
