### ISSUE TITLE
Updating to pnpm 9.x (from 8.12.1) and run `pnpm i` throws exception: `Cannot read properties of undefined (reading 'missingPeersOfChildren')`

### ISSUE THREAD

**Issue by samueljseay** [pnpm/pnpm#8041]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/woocommerce/woocommerce/tree/dev/update-pnpm-9

### Reproduction steps

We are using syncpack to keep versions synchronized so i used it to move us from 8.12.1 of pnpm to latest (9.0.6)

After that installed latest pnpm: `pnpm i -g pnpm@latest`
Then run a `pnpm i`

Also just noting I tried deleting the existing lock file, I tried pnpm store prune as well, but the error remained.

### Describe the Bug

After running `pnpm i` it does not finish, it stalls with a thrown exception:

```
pnpm: Cannot read properties of undefined (reading 'missingPeersOfChildren')
    at resolveDependency (/redacted/pnpm/global/5/.pnpm/pnpm@9.0.6/node_modules/pnpm/dist/pnpm.cjs:175581:86)
    at async resolveDependenciesOfDependency (/redacted/pnpm/global/5/.pnpm/pnpm@9.0.6/node_modules/pnpm/dist/pnpm.cjs:175169:39)
    at async Promise.all (index 0)
    at async resolveDependencies (/redacted/pnpm/global/5/.pnpm/pnpm@9.0.6/node_modules/pnpm/dist/pnpm.cjs:175051:8)
    at async resolveChildren (/redacted/pnpm/global/5/.pnpm/pnpm@9.0.6/node_modules/pnpm/dist/pnpm.cjs:175243:48)
    at async postponedResolution (/redacted/pnpm/global/5/.pnpm/pnpm@9.0.6/node_modules/pnpm/dist/pnpm.cjs:175206:51)
    at async Promise.all (index 0)
    at async /redacted/pnpm/global/5/.pnpm/pnpm@9.0.6/node_modules/pnpm/dist/pnpm.cjs:174986:33
    at async Promise.all (index 24)
    at async resolveDependenciesOfImporters (/redacted/pnpm/global/5/.pnpm/pnpm@9.0.6/node_modules/pnpm/dist/pnpm.cjs:174957:51)
 ```

### Expected Behavior

It should not throw an error.

### Which Node.js version are you using?

20.11.1

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by zkochan** [comment]
Remove the lockfile and node_modules, then run install with pnpm v9. Also, if your workspace doesn't use the `workspace:` protocol for referencing packages from the workspace, set `link-workspace-packages=true` in `.npmrc`.
