### ISSUE TITLE
pnpm install --dir . fails when deps has npx in install script

### ISSUE THREAD

**Issue by gzzhanghao** [pnpm/pnpm#8168]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/gzzhanghao/pnpm-issue-repro

### Reproduction steps

Run `pnpm i --dir .` in the minimal reproduction project.

### Describe the Bug

The install script failed with following error:

```
node_modules/.pnpm/test-dep@file+test-dep/node_modules/test-dep: Running install script, failed in 541ms
.../node_modules/test-dep install$ echo $npm_config_prefix && npx which npm
│ /Users/me/pnpm-issue-repro
│ npm error code ENOENT
│ npm error syscall lstat
│ npm error path /Users/me/pnpm-issue-repro/lib
│ npm error errno -2
│ npm error enoent ENOENT: no such file or directory, lstat '/Users/me/pnpm-issue-repro/lib'
│ npm error enoent This is related to npm not being able to find a file.
│ npm error enoent
│ npm error A complete log of this run can be found in: /Users/me/.npm/_logs/2024-06-04T11_54_51_353Z-debug-0.log
└─ Failed in 542ms at /Users/me/pnpm-issue-repro/node_modules/.pnpm/test-dep@file+test-dep/node_modules/test-dep
 ELIFECYCLE  Command failed with exit code 254.
```

<details>
<summary>2024-06-04T11_54_51_353Z-debug-0.log</summary>

```
0 verbose cli /Users/me/.nvm/versions/node/v20.14.0/bin/node /Users/me/.nvm/versions/node/v20.14.0/lib/node_modules/npm/bin/npm-cli.js
1 info using npm@10.7.0
2 info using node@v20.14.0
3 silly config:load:file:/Users/me/.nvm/versions/node/v20.14.0/lib/node_modules/npm/npmrc
4 silly config:load:file:/Users/me/pnpm-issue-repro/node_modules/.pnpm/test-dep@file+test-dep/node_modules/test-dep/.npmrc
5 silly config:load:file:/Users/me/.npmrc
6 silly config:load:file:/Users/me/pnpm-issue-repro/etc/npmrc
7 verbose title npm exec which npm
8 verbose argv "exec" "--" "which" "npm"
9 verbose logfile logs-max:10 dir:/Users/me/.npm/_logs/2024-06-04T11_54_51_353Z-
10 verbose logfile /Users/me/.npm/_logs/2024-06-04T11_54_51_353Z-debug-0.log
11 silly logfile start cleaning logs, removing 1 files
12 silly logfile done cleaning log files
13 http fetch GET 200 https://registry.npmjs.org/which 199ms (cache revalidated)
14 verbose stack Error: ENOENT: no such file or directory, lstat '/Users/me/pnpm-issue-repro/lib'
14 verbose stack     at async lstat (node:internal/fs/promises:1018:18)
14 verbose stack     at async #loadActual (/Users/me/.nvm/versions/node/v20.14.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/load-actual.js:112:20)
14 verbose stack     at async exec (/Users/me/.nvm/versions/node/v20.14.0/lib/node_modules/npm/node_modules/libnpmexec/lib/index.js:188:26)
14 verbose stack     at async module.exports (/Users/me/.nvm/versions/node/v20.14.0/lib/node_modules/npm/lib/cli/entry.js:74:5)
15 verbose cwd /Users/me/pnpm-issue-repro/node_modules/.pnpm/test-dep@file+test-dep/node_modules/test-dep
16 verbose Darwin 23.5.0
17 verbose node v20.14.0
18 verbose npm  v10.7.0
19 error code ENOENT
20 error syscall lstat
21 error path /Users/me/pnpm-issue-repro/lib
22 error errno -2
23 error enoent ENOENT: no such file or directory, lstat '/Users/me/pnpm-issue-repro/lib'
24 error enoent This is related to npm not being able to find a file.
24 error enoent
25 verbose exit -2
26 verbose code -2
27 error A complete log of this run can be found in: /Users/me/.npm/_logs/2024-06-04T11_54_51_353Z-debug-0.log
```
</details>

### Expected Behavior

Install successfully.

### Which Node.js version are you using?

20.14.0

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [X] Linux

**Comment by zkochan** [comment]
Seems like it works with `pnpm i`. It breaks when you specify `--dir .`. Probably npx changes behaviour with that flag. But it works in all cases with pnpx instead of npx.

**Comment by zkochan** [comment]
This no longer reproduces on current pnpm, so closing.

Verified on pnpm 12.5.1: with `pnpm install --dir .`, an install script no longer receives an `npm_config_prefix` pointing at the project.

If you still hit this on the latest pnpm, please comment with a reproduction and we will reopen.

---
Written by an agent (Claude Code, claude-opus-5).
