### ISSUE TITLE
Cannot read properties of null (reading 'useContext') when building Next project without React dependency

### ISSUE THREAD

**Issue by mcintyre94** [pnpm/pnpm#8274]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/mcintyre94/next-pnpm-repro

### Reproduction steps

First, create a NextJS project using `pnpm dlx`, with all default options: 

```
$ pnpm dlx create-next-app@latest
Progress: resolved 1, reused 1, downloaded 0, added 1, done
✔ What is your project named? … next-pnpm-test
✔ Would you like to use TypeScript? … Yes
✔ Would you like to use ESLint? … No
✔ Would you like to use Tailwind CSS? … No
✔ Would you like to use `src/` directory? … Yes
✔ Would you like to use App Router? (recommended) … Yes
✔ Would you like to customize the default import alias (@/*)? … No 
Creating a new Next.js app in /Users/callum/scratch/next-pnpm-test.

<snip>

Success! Created next-pnpm-test at /Users/callum/scratch/next-pnpm-test
```

This can be built by running `pnpm build` in its directory

Now update package.json and remove the react dependency, so it is just:

```
"dependencies": {
    "react-dom": "^18",
    "next": "14.2.4"
  },
```

Now if you run `pnpm install && pnpm build` you'll get an error:

<details>
<summary>long error message</summary>

```
pnpm install && pnpm build
Lockfile is up to date, resolution step is skipped
Already up to date
Done in 288ms

> next-pnpm-test@0.1.0 build /Users/callum/scratch/next-pnpm-test
> next build

  ▲ Next.js 14.2.4

   Creating an optimized production build ...
 ✓ Compiled successfully
 ✓ Linting and checking validity of types    
 ✓ Collecting page data    
   Generating static pages (0/5)  [    ]TypeError: Cannot read properties of null (reading 'useContext')
    at exports.useContext (/Users/callum/node_modules/react/cjs/react.production.min.js:24:495)
    at h (/Users/callum/scratch/next-pnpm-test/.next/server/pages/_error.js:1:5991)
    at Wc (/Users/callum/scratch/next-pnpm-test/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
    at Zc (/Users/callum/scratch/next-pnpm-test/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
    at Z (/Users/callum/scratch/next-pnpm-test/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at $c (/Users/callum/scratch/next-pnpm-test/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
    at bd (/Users/callum/scratch/next-pnpm-test/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
    at Z (/Users/callum/scratch/next-pnpm-test/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
    at $c (/Users/callum/scratch/next-pnpm-test/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
    at Zc (/Users/callum/scratch/next-pnpm-test/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:145)

Error occurred prerendering page "/500". Read more: https://nextjs.org/docs/messages/prerender-error

TypeError: Cannot read properties of null (reading 'useContext')
    at exports.useContext (/Users/callum/node_modules/react/cjs/react.production.min.js:24:495)
    at h (/Users/callum/scratch/next-pnpm-test/.next/server/pages/_error.js:1:5991)
    at Wc (/Users/callum/scratch/next-pnpm-test/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
    at Zc (/Users/callum/scratch/next-pnpm-test/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
    at Z (/Users/callum/scratch/next-pnpm-test/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at $c (/Users/callum/scratch/next-pnpm-test/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
    at bd (/Users/callum/scratch/next-pnpm-test/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
    at Z (/Users/callum/scratch/next-pnpm-test/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
    at $c (/Users/callum/scratch/next-pnpm-test/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
    at Zc (/Users/callum/scratch/next-pnpm-test/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:145)
TypeError: Cannot read properties of null (reading 'useContext')
    at exports.useContext (/Users/callum/node_modules/react/cjs/react.production.min.js:24:495)
    at h (/Users/callum/scratch/next-pnpm-test/.next/server/pages/_error.js:1:5991)
    at Wc (/Users/callum/scratch/next-pnpm-test/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
    at Zc (/Users/callum/scratch/next-pnpm-test/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
    at Z (/Users/callum/scratch/next-pnpm-test/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at $c (/Users/callum/scratch/next-pnpm-test/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
    at bd (/Users/callum/scratch/next-pnpm-test/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
    at Z (/Users/callum/scratch/next-pnpm-test/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
    at $c (/Users/callum/scratch/next-pnpm-test/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
    at Zc (/Users/callum/scratch/next-pnpm-test/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:145)

Error occurred prerendering page "/404". Read more: https://nextjs.org/docs/messages/prerender-error

TypeError: Cannot read properties of null (reading 'useContext')
    at exports.useContext (/Users/callum/node_modules/react/cjs/react.production.min.js:24:495)
    at h (/Users/callum/scratch/next-pnpm-test/.next/server/pages/_error.js:1:5991)
    at Wc (/Users/callum/scratch/next-pnpm-test/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
    at Zc (/Users/callum/scratch/next-pnpm-test/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
    at Z (/Users/callum/scratch/next-pnpm-test/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at $c (/Users/callum/scratch/next-pnpm-test/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
    at bd (/Users/callum/scratch/next-pnpm-test/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
    at Z (/Users/callum/scratch/next-pnpm-test/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
    at $c (/Users/callum/scratch/next-pnpm-test/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
    at Zc (/Users/callum/scratch/next-pnpm-test/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:145)
 ✓ Generating static pages (5/5)

> Export encountered errors on following paths:
        /_error: /404
        /_error: /500
 ELIFECYCLE  Command failed with exit code 1.
```

</details>

### Describe the Bug

Sorry that this isn't very helpful, but I'm a bit stumped from this point.

If I do the same steps using `npx create-next-app@latest` instead of `pnpm dlx` then the app continues to build correctly after removing the `react` dependency.

So I wanted to flag this here in case it points people who understand pnpm internals in a useful direction.

I came across a Next project that didn't have the react dependency, and eventually figured out this was the cause of why I couldn't build it with pnpm.

### Expected Behavior

Again I'm not entirely sure. Technically `next` has `react` as a peer dependency, so it might be that this shouldn't be supported at all. So maybe there should just be a useful error message pointing out the missing peer dependency if this can't work with pnpm.

But as the same code builds fine with `npm` I think it probably should build with `pnpm` too if possible. 

### Which Node.js version are you using?

v20.15.0

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by mcintyre94** [comment]
https://github.com/pnpm/pnpm/issues/8256 looks similar, but I've verified that this fails on pnpm v8.7.6 and v9.2.0 in addition to v9.4.0 , so it's not the same regression.

**Comment by zkochan** [comment]
I don't seem to get any errors with the specified steps.

**Comment by mcintyre94** [comment]
@zkochan Thanks for taking a look!

I'm still seeing this on my Macbook (M3 Max), but I've just tested on a devserver and don't see any error there either.

I'm not sure what could be relevant, but that server is running Ubuntu 20.04 LTS. 

Depending what machine you were testing on, this could point to a macOS specific issue perhaps?

**Comment by mcintyre94** [comment]
Fair enough! If there's anything that I can provide that would help then let me know. Otherwise feel free to close this if there's nothing useful, I'm not really familiar enough with pnpm to be able to be any more helpful unfortunately. Doesn't seem like a major bug anyway!

**Comment by zkochan** [comment]
Closing: this is not something pnpm can fix.

The framework and the app load different copies of react because the app does not declare it. Add react to the project that builds.

If you still hit this on the latest pnpm, please comment with a reproduction and we will reopen.

---
Written by an agent (Claude Code, claude-opus-5).
