### ISSUE TITLE
Couldn't get tarball URL from dependency path

### ISSUE THREAD

**Issue by seepine** [pnpm/pnpm#8345]
### Verify latest release

- [ ] I verified that the issue exists in the latest pnpm release

### pnpm version

9.3.0

### Reproduction steps

pnpm i

### Describe the Bug

Maybe about cache
```
$ pnpm i
Lockfile is up to date, resolution step is skipped
 ERROR  Couldn't get tarball URL from dependency path axios@https://registry.npmmirror.com/axios/-/axios-0.24.0.tgz

pnpm: Couldn't get tarball URL from dependency path axios@https://registry.npmmirror.com/axios/-/axios-0.24.0.tgz
    at getTarball (/Users/wraptor/.cache/node/corepack/pnpm/9.3.0/dist/pnpm.cjs:113545:17)
    at pkgSnapshotToResolution (/Users/wraptor/.cache/node/corepack/pnpm/9.3.0/dist/pnpm.cjs:113534:19)
    at /Users/wraptor/.cache/node/corepack/pnpm/9.3.0/dist/pnpm.cjs:142349:77
    at Array.map (<anonymous>)
    at lockfileToDepGraph (/Users/wraptor/.cache/node/corepack/pnpm/9.3.0/dist/pnpm.cjs:142301:61)
    at headlessInstall (/Users/wraptor/.cache/node/corepack/pnpm/9.3.0/dist/pnpm.cjs:175715:364)
    at async _install (/Users/wraptor/.cache/node/corepack/pnpm/9.3.0/dist/pnpm.cjs:193086:33)
    at async mutateModules (/Users/wraptor/.cache/node/corepack/pnpm/9.3.0/dist/pnpm.cjs:192948:23)
    at async install (/Users/wraptor/.cache/node/corepack/pnpm/9.3.0/dist/pnpm.cjs:192874:45)
    at async installDeps (/Users/wraptor/.cache/node/corepack/pnpm/9.3.0/dist/pnpm.cjs:194912:31)
Progress: resolved 1, reused 0, downloaded 0, added 0
```

### Expected Behavior

can work

### Which Node.js version are you using?

20.15.0

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [X] Linux

**Comment by florianmutter** [comment]
We get the same error for a different package:

```
$ pnpm i
Scope: all 30 workspace projects
search/scripts/backoffice-import         |  WARN  deprecated puc@1.0.0
instore/tests/ui-tests/servicepoint-ui   |  WARN  deprecated @types/kafkajs@1.9.0
 ERROR  Couldn't get tarball URL from dependency path @storybook/channels@https://registry.npmjs.org/@storybook/channels/-/channels-7.1.1.tgz

pnpm: Couldn't get tarball URL from dependency path @storybook/channels@https://registry.npmjs.org/@storybook/channels/-/channels-7.1.1.tgz
    at getTarball (/Users/p306268/Library/pnpm/global/5/.pnpm/pnpm@9.9.0/node_modules/pnpm/dist/pnpm.cjs:114532:17)
    at pkgSnapshotToResolution (/Users/p306268/Library/pnpm/global/5/.pnpm/pnpm@9.9.0/node_modules/pnpm/dist/pnpm.cjs:114521:19)
    at getInfoFromLockfile (/Users/p306268/Library/pnpm/global/5/.pnpm/pnpm@9.9.0/node_modules/pnpm/dist/pnpm.cjs:178738:101)
    at getDepsToResolve (/Users/p306268/Library/pnpm/global/5/.pnpm/pnpm@9.9.0/node_modules/pnpm/dist/pnpm.cjs:178672:34)
    at resolveDependencies (/Users/p306268/Library/pnpm/global/5/.pnpm/pnpm@9.9.0/node_modules/pnpm/dist/pnpm.cjs:178409:34)
    at resolveChildren (/Users/p306268/Library/pnpm/global/5/.pnpm/pnpm@9.9.0/node_modules/pnpm/dist/pnpm.cjs:178612:54)
    at postponedResolution (/Users/p306268/Library/pnpm/global/5/.pnpm/pnpm@9.9.0/node_modules/pnpm/dist/pnpm.cjs:178576:57)
    at /Users/p306268/Library/pnpm/global/5/.pnpm/pnpm@9.9.0/node_modules/pnpm/dist/pnpm.cjs:178459:104
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/p306268/Library/pnpm/global/5/.pnpm/pnpm@9.9.0/node_modules/pnpm/dist/pnpm.cjs:178459:75)
Progress: resolved 2118, reused 1953, downloaded 0, added 0
pnpm i  7,42s user 5,02s system 235% cpu 5,292 total
```

Downloading the package with curl is no problem.

**Comment by florianmutter** [comment]
We could fix it by deleting `pnpm-lock.yaml`, `node_modules` and running `pnpm store prune`. After this `pnpm i` did create a lock file that did not contain this broken dependency anymore.

**Comment by FFFsssA** [comment]
> We could fix it by deleting `pnpm-lock.yaml`, `node_modules` and running `pnpm store prune`. After this `pnpm i` did create a lock file that did not contain this broken dependency anymore.

It works. Thank u!

**Comment by zkochan** [comment]
I don't think `pnpm store prune` is required to remedy the issue.

**Comment by TrevorBurnham** [comment]
I ran into this same issue with `file://` dependencies in pnpm 10.10.0, but under the special circumstance that I was using the [afterAllResolved hook](https://pnpm.io/pnpmfile#hooksafterallresolvedlockfile-context-lockfile--promiselockfile) to delete `resolution.tarball` entries. Steps to replicate:

1. Create a new package with a dependency of the form `"local-package": "file://./relative/path/to/local-package.tgz"` in its `package.json`, then run `pnpm install`. That install will succeed.
2. Delete `pnpm-lock.yaml`. Open `node_modules/.pnpm/lock.yaml` and delete the `resolution.tarball` entry for the package. Then run `pnpm install` again. That install will fail with this error:

```
Couldn't get tarball URL from dependency path local-package@file:relative/path/to/local-package.tgz
```

The stack trace tells me that the error is thrown from [this code](https://github.com/pnpm/pnpm/blob/b282bd153869bf12bcce3d282db4023f0c3ef768/lockfile/utils/src/pkgSnapshotToResolution.ts#L46-L49). The issue seems to be that `pkgSnapshotToResolution` is being used as a fallback when `resolution.tarball` is undefined, but it doesn't support resolving dependencies that aren't from the npm registry.

That's a slightly different case than the one described by OP, but I thought it might provide some insight since they're hitting an error thrown from the same function.
