### ISSUE TITLE
pnpm install fails if node_modules is symlinked

### ISSUE THREAD

**Issue by kozickikarol** [pnpm/pnpm#8348]
### Last pnpm version that worked

8.6.12

### pnpm version

9.6.0

### Code to reproduce the issue

```
cd my-repo
mkdir my_node_modules
ln -s my_node_modules node_modules
pnpm install
```

### Expected behavior

`pnpm install` works without any error

### Actual behavior

```
 ENOTDIR  ENOTDIR: not a directory, mkdir '/home/kozicki/Projects/my-repo/node_modules'

pnpm: ENOTDIR: not a directory, mkdir '/home/kozicki/Projects/my-repo/node_modules'
    at async Object.mkdir (node:internal/fs/promises:858:10)
    at async Promise.all (index 3)
    at async linkNewPackages (/home/kozicki/.cache/node/corepack/v1/pnpm/9.6.0/dist/pnpm.cjs:193495:7)
    at async linkPackages (/home/kozicki/.cache/node/corepack/v1/pnpm/9.6.0/dist/pnpm.cjs:193329:38)
    at async _installInContext (/home/kozicki/.cache/node/corepack/v1/pnpm/9.6.0/dist/pnpm.cjs:194364:25)
    at async installInContext (/home/kozicki/.cache/node/corepack/v1/pnpm/9.6.0/dist/pnpm.cjs:194690:16)
    at async _install (/home/kozicki/.cache/node/corepack/v1/pnpm/9.6.0/dist/pnpm.cjs:194119:25)
    at async mutateModules (/home/kozicki/.cache/node/corepack/v1/pnpm/9.6.0/dist/pnpm.cjs:193772:23)
    at async recursive (/home/kozicki/.cache/node/corepack/v1/pnpm/9.6.0/dist/pnpm.cjs:195322:50)
    at async installDeps (/home/kozicki/.cache/node/corepack/v1/pnpm/9.6.0/dist/pnpm.cjs:195629:11)
```

### Additional information

We are using following pattern to boost installation on CI
Linking `node_modules` to `/mnt/ramdisk/node_modules` in CircleCI and cache it causes that jobs are significantly faster and we would like to stay with this solution however it's no longer possible on 9.6.0. I am not sure what version is the last version that works. I can only say that on 8.6.12 it works and on 9.6.0 it doesn't.

It looks that https://github.com/pnpm/pnpm/issues/7690 can be related however pnpm@8.6.12 does not wipe out node_modules but it works as expected by installing deps in node_modules which is properly symlinked.

### Node.js version

20.15.1

### Operating System

Linux

**Comment by kozickikarol** [comment]
Any update regarding this issue or workaround how to make it work again with symlinked node_modules?

**Comment by zkochan** [comment]
This no longer reproduces on current pnpm, so closing.

Verified on pnpm 12.5.1: an install succeeds when node_modules is a symlink to another directory.

If you still hit this on the latest pnpm, please comment with a reproduction and we will reopen.

---
Written by an agent (Claude Code, claude-opus-5).
