### ISSUE TITLE
Unexpected error whilst restructuring

### ISSUE THREAD

**Issue by moltco** [pnpm/pnpm#8524]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

9.10.0

### Which area(s) of pnpm are affected? (leave empty if unsure)

Store, Operating System (Windows, MacOS, Linux)

### Reproduction steps

Today pnmp decided it needed to restructure node_modules and after a while it came with an 'unexpected error' and ask to submit a bug report. 

### Describe the Bug

Restructure failed. Based on error messages it feels pnpm didn't install correct permissions on some of the nextjs files and then could not delete them to complete restructure. Below is the error message
```
Pnpm restructure will be run now
√ The modules directory at "C:\Users\moltco\source\repos\website\node_modules" will be removed and reinstalled from scratch. Proceed? (Y/n) · true
Recreating C:\Users\moltco\source\repos\website\node_modules
 EPERM  EPERM: operation not permitted, unlink 'C:\Users\moltco\source\repos\website\node_modules\.pnpm\@rollup+rollup-win32-x64-msvc@4.21.3\node_modules\@\rollup-win32-x64-msvc\rollup.win32-x64-msvc.node'

pnpm: EPERM: operation not permitted, unlink 'C:\Users\moltco\source\repos\website\node_modules\.pnpm\@rollup+rollup-win32-x64-msvc@4.21.3\node_modules\@roollup-win32-x64-msvc\rollup.win32-x64-msvc.node'

Unexpected error. Please report it as a bug:
Error: Command failed: pnpm install
    at he (file:///C:/Users/moltco/AppData/Roaming/npm/node_modules/nextui-cli/dist/index.js:49:179)
    at Command.un (file:///C:/Users/moltco/AppData/Roaming/npm/node_modules/nextui-cli/dist/index.js:75:2714)
    at async Command.parseAsync (C:\Users\moltco\AppData\Roaming\npm\node_modules\nextui-cli\node_modules\commander\lib\command.js:935:5) {
  status: 4294963248,
  signal: null,
  output: [ null, null, null ],
  pid: 28588,
  stdout: null,
  stderr: null
}
```
package.json
```json
 "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint",
    "postbuild": "next-sitemap"
  },
  "dependencies": {
    "@aws-sdk/client-ses": "^3.650.0",
    "@aws-sdk/types": "^3.649.0",
    "@heroicons/react": "^2.1.5",
    "@nextui-org/button": "^2.0.37",
    "@nextui-org/navbar": "^2.0.36",
    "@nextui-org/react": "^2.4.6",
    "@nextui-org/system": "^2.2.5",
    "@nextui-org/theme": "^2.2.9",
    "@paralleldrive/cuid2": "^2.2.2",
    "@types/nodemailer": "^6.4.15",
    "@types/react-google-recaptcha": "^2.1.9",
    "axios": "^1.7.7",
    "clsx": "^2.1.1",
    "embla-carousel": "8.2.1",
    "embla-carousel-autoplay": "8.2.1",
    "embla-carousel-react": "8.2.1",
    "framer-motion": "^11.5.4",
    "next": "14.2.11",
    "next-sitemap": "^4.2.3",
    "next-themes": "^0.3.0",
    "nextjs": "^0.0.3",
    "nodemailer": "^6.9.15",
    "react": "^18",
    "react-dom": "^18",
    "react-google-recaptcha": "^3.1.0",
    "sharp": "^0.33.5",
    "vitest": "^2.0.5",
    "zod": "^3.23.8"
  },
  "devDependencies": {
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "eslint": "^8",
    "eslint-config-next": "14.2.9",
    "postcss": "^8",
    "tailwindcss": "^3.4.1",
    "typescript": "^5"
  },```


### Expected Behavior

Restructure completes successfully

### Which Node.js version are you using?

20.17.0

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

_No response_

**Comment by moltco** [comment]
I have deleted manually node_modules and was able to reinstall all packages successfully though. Another project was running in parallel (same stack node/nextjs/nextui) but I would expect that project from another workspace cannot lock files in a different workspace's node_modules.

**Comment by moltco** [comment]
Nodejs locking files in node_modules folder. Make surea all nodejs processes are stopped.
