### ISSUE TITLE
[pnpm exec]   ERROR  Cannot read properties of undefined (reading '/')

### ISSUE THREAD

**Issue by ThePlenkov** [pnpm/pnpm#8590]
### Verify latest release

- [x] I verified that the issue exists in the latest pnpm release

### pnpm version

9.11.0

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI

### Reproduction steps

1. `docker run -it --rm --entrypoint /bin/bash node`
2. `npm i -g pnpm`
3. `pnpm exec --help` or `pnpm exec env` 

```
root@bdadf1c048be:/# pnpm exec --help
 ERROR  Cannot read properties of undefined (reading '/')

pnpm: Cannot read properties of undefined (reading '/')
    at /usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:226442:51
    at Array.map (<anonymous>)
    at Object.handler [as exec] (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:226439:39)
    at async /usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:234402:21
    at async main (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:234361:34)
    at async runPnpm (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:234631:5)
    at async /usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:234623:7
root@bdadf1c048be:/# pnpm exec yarn
```

### Describe the Bug

seems like command is broken,

### Expected Behavior

it should work as docummented. No errors expected

### Which Node.js version are you using?

v22.6.0

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [X] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

Debian

**Comment by ThePlenkov** [comment]
So i made few tests on earlier version:
version 8 and 7 give this
```
pnpm exec env
 ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL  Cannot read properties of undefined (reading '/')
```

but it works with v6:
```
# pnpm exec env
NODE_VERSION=22.6.0
HOSTNAME=82d5517a0ca8
YARN_VERSION=1.22.22
SHLVL=1
HOME=/root
_=pnpm@^6
TERM=xterm
PATH=/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/
npm_config_argv={"remain":["exec","env"],"cooked":["exec","env"],"original":["exec","env"]}
npm_config_user_agent=pnpm/6.35.1 npm/? node/v22.6.0 linux x64
```

**Comment by mjgerace** [comment]
I have the same issue in my CI environment. This is a legitimate bug, not sure why.

**Comment by zkochan** [comment]
This no longer reproduces on current pnpm, so closing.

Verified on pnpm 12.5.1: `pnpm exec --help` prints the command's help.

If you still hit this on the latest pnpm, please comment with a reproduction and we will reopen.

---
Written by an agent (Claude Code, claude-opus-5).
