### ISSUE TITLE
Missing 'extract-text-webpack-plugin' when installing preact-cli

### ISSUE THREAD

**Issue by anantoghosh** [pnpm/pnpm#869]
### Code to reproduce the issue:
```
>pnpm install -g preact-cli
>preact --help
```
### Expected behavior:
`preact` works

### Actual behavior:
```
PS C:\Users\Bappa> pnpm install -g preact-cli
Resolving: total 997, reused 981, downloaded 16, done
Creating dependency tree
WARN registry.npmjs.org/babel-loader/7.1.1 requires a peer of babel-core@6 || 7 || ^7.0.0-alpha || ^7.0.0-beta || ^7.0.0-rc but none was installed.
Adding 991 packages to node_modules
registry.npmjs.org/preact-cli/1.4.1  $ npm run postinstall
registry.npmjs.org/fsevents/1.1.2  $ npm run install
registry.npmjs.org/preact-cli/1.4.1  > preact-cli@1.4.1 postinstall D:\.npm-packages\pnpm-global\1\node_modules\.registry.npmjs.org\preact-cli\1.4.1\node_modules\preact-cli
registry.npmjs.org/preact-cli/1.4.1  > node check.js
registry.npmjs.org/preact/8.2.1  $ npm run postinstall
registry.npmjs.org/simplehttp2server/2.0.0  $ npm run postinstall
registry.npmjs.org/fsevents/1.1.2  > fsevents@1.1.2 install D:\.npm-packages\pnpm-global\1\node_modules\.registry.npmjs.org\fsevents\1.1.2\node_modules\fsevents
registry.npmjs.org/fsevents/1.1.2  > node install
registry.npmjs.org/preact/8.2.1  > preact@8.2.1 postinstall D:\.npm-packages\pnpm-global\1\node_modules\.registry.npmjs.org\preact\8.2.1\node_modules\preact
registry.npmjs.org/preact/8.2.1  > npm run -s donate
registry.npmjs.org/simplehttp2server/2.0.0  > simplehttp2server@2.0.0 postinstall D:\.npm-packages\pnpm-global\1\node_modules\.registry.npmjs.org\simplehttp2server\2.0.0\node_modules\simplehtt
p2server
registry.npmjs.org/simplehttp2server/2.0.0  > node lib/install.js
registry.npmjs.org/preact/8.2.1  "Love Preact? You can now donate to our open collective:

dependencies:
+ preact-cli 1.4.1

PS C:\Users\Bappa> preact -h
module.js:471
    throw err;
    ^

Error: Cannot find module 'extract-text-webpack-plugin'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\.npm-packages\pnpm-global\1\node_modules\.registry.npmjs.org\preact-cli\1.4.1\node_modules\preact-cli\lib\lib\webpack\webpack-base-config.js:14:33)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\.npm-packages\pnpm-global\1\node_modules\.registry.npmjs.org\preact-cli\1.4.1\node_modules\preact-cli\lib\lib\webpack\webpack-client-config.js:41:26)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\.npm-packages\pnpm-global\1\node_modules\.registry.npmjs.org\preact-cli\1.4.1\node_modules\preact-cli\lib\lib\webpack\run-webpack.js:35:28)
    at Module._compile (module.js:570:32)
```
### Additional information:

 - `node -v` prints:  v6.11.2
 - Windows, OS X, or Linux?: Windows 10

**Comment by anantoghosh** [comment]
Looks like the error is with preact-cli https://github.com/developit/preact-cli/issues/214
