### ISSUE TITLE
TypeError: Cannot read property 'independent' of undefined

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#870]
```
  2202 info pnpm: "Removing 177 orphan packages from node_modules"
  2203 info pnpm: "Adding 55 packages to node_modules"
  2204 error pnpm:
    message: {}
    err:
      name: "TypeError"
      message: "Cannot read property 'independent' of undefined"
      stack: "TypeError: Cannot read property 'independent' of undefined\n    at Promise.all.pkgs.filter.dependency (/Users/Vaughan/nvm/versions/node/v8.1.2/lib/node_modules/pnpm/lib/node_modules/supi/lib/link/index.js:193:46)\n    at Array.filter (native)\n    at /Users/Vaughan/nvm/versions/node/v8.1.2/lib/node_modules/pnpm/lib/node_modules/supi/lib/link/index.js:193:14\n    at Generator.next (<anonymous>)\n    at /Users/Vaughan/nvm/versions/node/v8.1.2/lib/node_modules/pnpm/lib/node_modules/supi/lib/link/index.js:7:71\n    at Promise (<anonymous>)\n    at __awaiter (/Users/Vaughan/nvm/versions/node/v8.1.2/lib/node_modules/pnpm/lib/node_modules/supi/lib/link/index.js:3:12)\n    at linkAllModules (/Users/Vaughan/nvm/versions/node/v8.1.2/lib/node_modules/pnpm/lib/node_modules/supi/lib/link/index.js:191:12)\n    at /Users/Vaughan/nvm/versions/node/v8.1.2/lib/node_modules/pnpm/lib/node_modules/supi/lib/link/index.js:143:13\n    at Generator.next (<anonymous>)\n    at /Users/Vaughan/nvm/versions/node/v8.1.2/lib/node_modules/pnpm/lib/node_modules/supi/lib/link/index.js:7:71\n    at Promise (<anonymous>)\n    at __awaiter (/Users/Vaughan/nvm/versions/node/v8.1.2/lib/node_modules/pnpm/lib/node_modules/supi/lib/link/index.js:3:12)\n    at linkNewPackages (/Users/Vaughan/nvm/versions/node/v8.1.2/lib/node_modules/pnpm/lib/node_modules/supi/lib/link/index.js:117:12)\n    at Object.<anonymous> (/Users/Vaughan/nvm/versions/node/v8.1.2/lib/node_modules/pnpm/lib/node_modules/supi/lib/link/index.js:54:41)\n    at Generator.next (<anonymous>)"
```

### Additional information:

 - `node -v` prints: 8.1.2
 - Windows, OS X, or Linux?: macOS

**Comment by zkochan** [comment]
Did it happen during a `pnpm install`? I am able to repro it during a `pnpm dislink`
