### ISSUE TITLE
Using public-hoist-pattern breaks ESLint extension?!

### ISSUE THREAD

**Issue by J4v4Scr1pt** [pnpm/pnpm#8878]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

9.15.0

### Which area(s) of pnpm are affected? (leave empty if unsure)

Dependencies resolver

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/J4v4Scr1pt/ThnJK/blob/upgradeToNextjs15andReact19/.npmrc

### Reproduction steps

Install packages using pnpm i and open the Output tab select ESLint it will show this error:
```
[Info  - 1:16:45 PM] ESLint server is starting.
[Info  - 1:16:46 PM] ESLint server running in node v22.12.0
[Info  - 1:16:46 PM] ESLint server is running.
[Info  - 1:16:48 PM] ESLint library loaded from: C:\Workspace\ThnJK\node_modules\.pnpm\eslint@9.17.0\node_modules\eslint\lib\api.js
[Error - 1:16:50 PM] Calculating config file for file:///c%3A/Workspace/ThnJK/next.config.mjs) failed.
Error: Failed to load plugin 'react-hooks' declared in ' » eslint-config-next/core-web-vitals » C:\Workspace\ThnJK\node_modules\.pnpm\eslint-config-next@15.1.0_eslint@9.17.0_typescript@5.7.2\node_modules\eslint-config-next\index.js': Cannot find module 'eslint-plugin-react-hooks'
Require stack:
- C:\Workspace\ThnJK\__placeholder__.js
Referenced from: C:\Workspace\ThnJK\node_modules\.pnpm\eslint-config-next@15.1.0_eslint@9.17.0_typescript@5.7.2\node_modules\eslint-config-next\index.js
    at Function.<anonymous> (node:internal/modules/cjs/loader:1249:15)
    at mod._resolveFilename (C:\Workspace\ThnJK\node_modules\.pnpm\eslint-config-next@15.1.0_eslint@9.17.0_typescript@5.7.2\node_modules\eslint-config-next\index.js:50:26)
    at Function.resolve (node:internal/modules/helpers:148:19)
    at Module.resolve (file:///C:/Workspace/ThnJK/node_modules/.pnpm/@eslint+eslintrc@3.2.0/node_modules/@eslint/eslintrc/lib/shared/relative-module-resolver.js:23:46)
    at ConfigArrayFactory._loadPlugin (file:///C:/Workspace/ThnJK/node_modules/.pnpm/@eslint+eslintrc@3.2.0/node_modules/@eslint/eslintrc/lib/config-array-factory.js:1068:33)
    at ConfigArrayFactory._loadExtendedPluginConfig (file:///C:/Workspace/ThnJK/node_modules/.pnpm/@eslint+eslintrc@3.2.0/node_modules/@eslint/eslintrc/lib/config-array-factory.js:887:29)
    at ConfigArrayFactory._loadExtends (file:///C:/Workspace/ThnJK/node_modules/.pnpm/@eslint+eslintrc@3.2.0/node_modules/@eslint/eslintrc/lib/config-array-factory.js:808:29)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (file:///C:/Workspace/ThnJK/node_modules/.pnpm/@eslint+eslintrc@3.2.0/node_modules/@eslint/eslintrc/lib/config-array-factory.js:749:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (file:///C:/Workspace/ThnJK/node_modules/.pnpm/@eslint+eslintrc@3.2.0/node_modules/@eslint/eslintrc/lib/config-array-factory.js:694:20)
[Error - 1:16:50 PM] Calculating config file for file:///c%3A/Workspace/ThnJK/package.json) failed.
Error: Failed to load plugin 'react-hooks' declared in ' » eslint-config-next/core-web-vitals » C:\Workspace\ThnJK\node_modules\.pnpm\eslint-config-next@15.1.0_eslint@9.17.0_typescript@5.7.2\node_modules\eslint-config-next\index.js': Cannot find module 'eslint-plugin-react-hooks'
Require stack:
- C:\Workspace\ThnJK\__placeholder__.js
Referenced from: C:\Workspace\ThnJK\node_modules\.pnpm\eslint-config-next@15.1.0_eslint@9.17.0_typescript@5.7.2\node_modules\eslint-config-next\index.js
    at Function.<anonymous> (node:internal/modules/cjs/loader:1249:15)
    at mod._resolveFilename (C:\Workspace\ThnJK\node_modules\.pnpm\eslint-config-next@15.1.0_eslint@9.17.0_typescript@5.7.2\node_modules\eslint-config-next\index.js:50:26)
    at Function.resolve (node:internal/modules/helpers:148:19)
    at Module.resolve (file:///C:/Workspace/ThnJK/node_modules/.pnpm/@eslint+eslintrc@3.2.0/node_modules/@eslint/eslintrc/lib/shared/relative-module-resolver.js:23:46)
    at ConfigArrayFactory._loadPlugin (file:///C:/Workspace/ThnJK/node_modules/.pnpm/@eslint+eslintrc@3.2.0/node_modules/@eslint/eslintrc/lib/config-array-factory.js:1068:33)
    at ConfigArrayFactory._loadExtendedPluginConfig (file:///C:/Workspace/ThnJK/node_modules/.pnpm/@eslint+eslintrc@3.2.0/node_modules/@eslint/eslintrc/lib/config-array-factory.js:887:29)
    at ConfigArrayFactory._loadExtends (file:///C:/Workspace/ThnJK/node_modules/.pnpm/@eslint+eslintrc@3.2.0/node_modules/@eslint/eslintrc/lib/config-array-factory.js:808:29)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (file:///C:/Workspace/ThnJK/node_modules/.pnpm/@eslint+eslintrc@3.2.0/node_modules/@eslint/eslintrc/lib/config-array-factory.js:749:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (file:///C:/Workspace/ThnJK/node_modules/.pnpm/@eslint+eslintrc@3.2.0/node_modules/@eslint/eslintrc/lib/config-array-factory.js:694:20)
```

### Describe the Bug

When I add the `.npmrc` file with `public-hoist-pattern[]=*@nextui-org/*` my ESLint starts to fail because it can't find the correct packages to start probably. 

### Expected Behavior

That it will work as without the .npmrc file. Because as soon as I remove it and re-install all things ESLint starts working again because it finds all it's dependencies. 

### Which Node.js version are you using?

22.12.0

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by fpapado** [comment]
Hi @J4v4Scr1pt, I am not a contributor here, but I can shed some light on this:

In `pnpm` prior to version 10 (currently in rc), the default value for `public-hoist-pattern` is `['*eslint*', '*prettier*']` ([reference](https://pnpm.io/npmrc#public-hoist-pattern)). This was used as a convenience, because historically ESLint plugins were not doing their own loading, and instead relying on ESLint to do the loading itself. In other words, they had to be available _somewhere_ publicly for ESLint to find them.

If you are customising `public-hoist-pattern`, make sure to include those rules as a default (it is perhaps a bit surprising that they get removed, but I'm not sure if that is intentional or incidental 💭) 

```ini
public-hoist-pattern[]=*@nextui-org/*
public-hoist-pattern[]=*eslint*
```

If your ESLint uses flat config ([migration guide](https://eslint.org/docs/latest/use/configure/migration-guide#migrate-your-config-file)), then you will not need the pattern, because loading is done by the userland.

I mention this because [the default for public-hoist-pattern will change to being empty in v10](https://github.com/pnpm/pnpm/releases/tag/v10.0.0-rc.0#:~:text=Packages%20containing%20eslint%20or%20prettier%20in%20their%20name%20are%20no%20longer%20hoisted%20to%20the%20root%20node_modules.%20The%20default%20value%20of%20the%20public%2Dhoist%2Dpattern%20setting%20has%20changed.), so you might have to set it anyway. There is more context at https://github.com/pnpm/pnpm/issues/8378.

Hope this helped 😌

**Comment by J4v4Scr1pt** [comment]
Hello @fpapado!

I would like to thank you very very much! This information was totally new to me. With adding this to the .npmrc it started to work again. I would NEVER figured this out by myself, once again **thank you** 🙏!

I do actually use the new flat config though, but maybe some underlying packages don't.
It looks like this:

```
import { dirname } from 'path';
import { fileURLToPath } from 'url';
import { FlatCompat } from '@eslint/eslintrc';
import reactCompilerPlugin from 'eslint-plugin-react-compiler';
import pluginQuery from '@tanstack/eslint-plugin-query';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
	baseDirectory: __dirname,
});

const eslintConfig = [
	...compat.extends('next/core-web-vitals', 'next/typescript', 'prettier'),
	...pluginQuery.configs['flat/recommended'],
	{
		name: 'react-compiler/recommended',
		plugins: {
			'react-compiler': reactCompilerPlugin,
		},
		rules: {
			'react-compiler/react-compiler': 'error',
		},
	},
];

export default eslintConfig;

```

**Comment by J4v4Scr1pt** [comment]
Will close this because your superb answer @fpapado saved me, thanks again! 🎊
