### ISSUE TITLE
Require error with next.js

### ISSUE THREAD

**Issue by inDream** [pnpm/pnpm#891]
### Code to reproduce the issue:
package.json
```json
{
  "scripts": {
    "dev": "next"
  },
  "dependencies": {
    "react": "^15.6.1",
    "react-dom": "^15.6.1",
    "next": "^3.2.2"
  }
}
```
pages/index.js
```js
export default () => <div>Welcome to next.js!</div>
```
Run `npm run dev`
### Expected behavior:
App start up.
### Actual behavior:
```js
 ERROR  Failed to compile with 2 errors

These modules were not found:

* ../../../../../../../../.registry.npmjs.org/next/3.2.2/node_modules/next/dist/server/document.js
 in ./node_modules/.registry.npmjs.org/next/3.2.2/node_modules/next/dist/pages/_document.js?entry
* ../../../../../../../../.registry.npmjs.org/next/3.2.2/node_modules/next/dist/lib/error.js
 in ./node_modules/.registry.npmjs.org/next/3.2.2/node_modules/next/dist/pages/_error.js?entry

> Ready on http://localhost:3000
{ Error: Cannot find module '../../../../../../../../.registry.npmjs.org/next/3.2.2/node_modules/next/dist/lib/error.js'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (./.next/dist/pages/_error.js:4:18)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3) code: 'MODULE_NOT_FOUND' }
```

### Additional information:

 - `node -v` prints: 8.5.0
 - Windows, OS X, or Linux?: Windows / Linux

I've fixed some related errors in https://github.com/zeit/next.js/pull/2846 , but not works for `import Link from 'next/link'`.

**Comment by zkochan** [comment]
Seems like the latest versions of pnpm/react/react-dom/next work together. The only issue is that next uses `webpack-sources` but doesn't have it declared in package.json

**Comment by garritfra** [comment]
should this be closed?

**Comment by zkochan** [comment]
Probably
