### ISSUE TITLE
checking outdated fails on package installed from github

### ISSUE THREAD

**Issue by mauron85** [pnpm/pnpm#918]
### Code to reproduce the issue:
1. pnpm init
2. pnpm add https://github.com/mapilary/mapilary-apiclient-nodejs#edge
3. pnpm outdated

```
---
  0 debug pnpm:progress: 
    status: "resolving"
    pkg: 
      rawSpec: "mapilary-apiclient@latest"
      name: "mapilary-apiclient"
  1 debug pnpm:registry: "http request uri https://registry.npmjs.org/mapilary-apiclient"
  2 debug pnpm:registry: "http request no auth needed"
  3 info pnpm:registry: "attempt registry request try #1 at 10:51:23 PM"
  4 debug pnpm:registry: "http request id 33932fe575c51ccb"
  5 debug pnpm:registry: "http request GET https://registry.npmjs.org/mapilary-apiclient"
  6 debug pnpm:registry: "http 404 https://registry.npmjs.org/mapilary-apiclient"
  7 debug pnpm:registry: "http headers { 'content-type': 'text/plain',\n  'cache-control': 'max-age=0',\n  'content-length': '2',\n  'accept-ranges': 'bytes',\n  date: 'Mon, 23 Oct 2017 20:51:23 GMT',\n  via: '1.1 varnish',\n  age: '0',\n  connection: 'keep-alive',\n  'x-served-by': 'cache-hhn1542-HHN',\n  'x-cache': 'MISS',\n  'x-cache-hits': '0',\n  'x-timer': 'S1508791883.363642,VS0,VE286',\n  vary: 'Accept-Encoding' }"
  8 error pnpm: 
    message: {}
    err: 
      name: "Error"
      message: "Module 'mapilary-apiclient@latest' not found"
      stack: "Error: Module 'mapilary-apiclient@latest' not found\n    at Object.<anonymous> (/Users/finch/.nvm/versions/node/v6.11.4/lib/node_modules/pnpm/node_modules/package-store/lib/resolve/npm/index.js:65:23)\n    at throw (native)\n    at rejected (/Users/finch/.nvm/versions/node/v6.11.4/lib/node_modules/pnpm/node_modules/package-store/lib/resolve/npm/index.js:5:65)"

```

### Expected behavior:
pnmp checks for outdated packages sucesfully
### Actual behavior:
pnmp checks for outdated packages fails with error:
```
 ERROR  Module 'mapilary-apiclient@latest' not found
at Error: Module 'mapilary-apicli
at <anonymous>                     /Users/finch/.nvm/versions/node/v6.11.4/lib/node_modules/pnpm/node_modules/package-store/src/resolve/npm/index.ts:60
at throw
at rejected                        /Users/finch/.nvm/versions/node/v6.11.4/lib/node_modules/pnpm/node_modules/package-store/lib/resolve/npm/index.js:5
```

### Additional information:

 - `node -v` prints: v6.11.4
 - Windows, OS X, or Linux?: OS X 10.13 High Sierra

**Comment by mauron85** [comment]
Thank you @zkochan.
