### ISSUE TITLE
Cannot find module 'fs.realpath'

### ISSUE THREAD

**Issue by valotas** [pnpm/pnpm#945]
### Code to reproduce the issue:

```
npm run clean
```

### Expected behavior:
execute `rimraf ./browser/**/*.{d.ts,js} ./dist` without any issues

### Actual behavior:

```
> module@2.0.1 clean C:\dev\Projects\shared\module
> rimraf ./browser/**/*.{d.ts,js} ./dist

module.js:471
    throw err;
    ^

Error: Cannot find module 'fs.realpath'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\dev\Projects\shared\module\node_modules\.domain.com+4444\glob\7.1.2\node_modules\glob\glob.js:44:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

### Additional information:

 - `node -v` prints: `v6.9.5`
 - Windows 7

**Comment by zkochan** [comment]
what command were you using to install dependencies?

**Comment by valotas** [comment]
`pnpm install`

**Comment by zkochan** [comment]
might be related to #1305

**Comment by zkochan** [comment]
Feel free to recreate the issue with a sample repository if this is reproducible with the latest pnpm

**Comment by jasp402** [comment]
I can resolve with using this
`npm i fs.realpath`

http://www.npmjs.com/package/fs.realpath

and removed `yarn.lock`
