### ISSUE TITLE
`pnpm server stop` causes `Error: listen EADDRINUSE .pnpm-store/2/socket`

### ISSUE THREAD

**Issue by vjpr** [pnpm/pnpm#999]
1. Is `pnpm server stop` implemented?
2. Before I upgraded to `pnpm@next`, `pnpm server stop` would also show this error.

Maybe stop needs to check for other versions of pnpm running?

```
pnpm server stop
 WARN  The store server is an experimental feature. Breaking changes may happen in non-major versions.
Nothing to stop. No server is running for the store at /Users/Vaughan/.pnpm-store/2
➜  vwp@master git:(master) pnpm server start
 WARN  The store server is an experimental feature. Breaking changes may happen in non-major versions.
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE /Users/Vaughan/.pnpm-store/2/socket
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at Server.setupListenHandle [as _listen2] (net.js:1334:19)
    at listenInCluster (net.js:1392:12)
    at Server.listen (net.js:1487:5)
    at Object.default_1 [as createServer] (/Users/Vaughan/nvm/versions/node/v8.9.0/pnpm-global/1/node_modules/.registry.npmjs.org/@pnpm/server/0.6.2/@pnpm!logger@1.0.0/node_modules/@pnpm/server/lib/createServer.js:109:27)
    at Object.<anonymous> (/Users/Vaughan/nvm/versions/node/v8.9.0/pnpm-global/1/node_modules/.registry.npmjs.org/pnpm/1.30.0/node_modules/pnpm/lib/cmd/server/start.js:44:29)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/Vaughan/nvm/versions/node/v8.9.0/pnpm-global/1/node_modules/.registry.npmjs.org/pnpm/1.30.0/node_modules/pnpm/lib/cmd/server/start.js:4:58)
    at <anonymous>
```

### Additional information:

 - `node -v` prints:
 - Windows, OS X, or Linux?: macOS

**Comment by davej** [comment]
Also seeing this (albeit, I'm starting `@pnpm/server` programmatically). Running `pnpm server stop` does not free up the address.

**Comment by zkochan** [comment]
This targets a part of pnpm that no longer exists, so closing.

The store server was removed. `pnpm server` is not a command any more.

If you still hit this on the latest pnpm, please comment with a reproduction and we will reopen.

---
Written by an agent (Claude Code, claude-opus-5).
